### ISSUE TITLE
Should Tabulator continue to support IE?

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#1019]
Hi Oli and everyone
IE11 usage has dropped below 3%.
With regard to the presumably still lot of work You planned for tabulator and the maintenance the very broad feature set usually creates, I wonder, if dropping tabulator IE11 support would mean considerable work savings and make developement really easier for You. Also in respect to its ES>=6 incompatibilty.

If this is the case, I am interested in Your and everybodys take on if it would be a good idea to drop IE11 support to make development and support easier.

Cheers Michael

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

That is an interesting question, and one I would love to hear feedback from the community on.

At the moment it is not too much of an issue, I have built a fallback system into Tabulator that lets it offer reduced functionality if IE cant handle something.

But it does rather hold back what I can do when it comes to some of the latest coding features. In version 4.0 which I will be releasing later in the year, I am hoping to pull in some of the latest features from ES6 - ES8, which IE definitely dosn't support, so not having to make fallback for these would be great.

I am happy to continue supporting IE for the time being, but if the community feels it no longer needs the support it would be nice to be able to drop it.

Please leave any feedback you have below, all opinions welcome!

Cheers

Oli :)

**Comment by Nyut0n** [comment]
Hi,
in my opinion, IE11 support shouln't be dropped before Windows 7 is EOL (or close to). And let me tell you very precisely why.

Win7 is still widely used in corporate networks and intranets all over the globe. Enterprises usually slow to migrate to modern OS, because it costs lots of money and there is no business need for it until official security patch support is discontinued. Those 3% IE usage mentioned cover 'The Internet' only, which is just a slice of the sum of global networks using web applications. But even if it wasn't. 3% of the Internet is still a tremendous amount of people.

I'm myself working for one of the biggest European IT companies, and guess what ... 80% of the standard corporate workstations are still Windows 7 with Office 2007 and IE11 being the default browser. You're free to install a different browser, but most non-technican people won't bother and just "click that internet icon". It's terrible, but it's reality.

I have recently included Tabulator for an intranet application and I was very grateful for the good IE support. So people don't walk in my door asking why they have to use a different browser just for that one website or flooding me with general support tickets like "its not working" or "it looks broken".

We all know IE is a terrible browser, and of course it's not the end of the world if you discontinue IE support. People will have to get used to it or I can just use an older version of Tabulator until Win7 dies. But I just feel that it's a little too early in general to go that way.

Just my two cents ;)

**Comment by michaelongithub** [comment]
Hi all
Nyut0n, thanks for pointing out this type of situation. Win7 EOL would be scheduled 14. Januar 2020. I am myself responsible for some applications for a large international medtech firm, that has a similar situation. (It was possible there, to decide, that the users of these applications use something other than IE11. But that is probably not always possible)

**Comment by donnyv** [comment]
A lot of the clients I do work for are municipal or belong to some type of government org. (US). A decent amount of people in government still use IE and Windows 7. I would agree with @Nyut0n and wait until Win7 is almost completely dead before dropping support.

**Comment by michaelongithub** [comment]
One thing that comes to my mind: If you would consider to start developing in Typescript, You could compile it down to ES5. One would probably still need some polyfills. But that alone is probably not reason enough to consider such a step.

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

I have considered Typescript but for the time being I am happy in pure JS, and with Babel compiling down to ES5 is not a pain, it just wastes some of the efficiency of modern techniques.

I may add Typescript to version 5.0 for next year.

Cheers

Oli

**Comment by VIVIsectI** [comment]
I just integrated tabulator into an ECM platform that will require supporting IE11 platform for 5 years. Please don't drop support.

**Comment by olifolkerd** [comment]
Hey All,

Well I think there is clearly still a strong case for keeping IE11 support in Tabulator. 

So it will remain supported!

Thanks to everyone for the feedback, it has been great to hear what people thing.

Cheers

Oli :)
