### ISSUE TITLE
dataFiltered being called when tabulator is defined

### ISSUE THREAD

**Issue by answerquest** [olifolkerd/tabulator#1049]
I put a console.log under `dataFiltered:function(filters, rows){..` and another just outside the tabulator definition / initialization, for testing. It fires on page load, before anything else has had a chance to load, well before data is loaded. Once the data is loaded, it is called again.

I made a workaround for preventing actions on page load: `getData` from the table, and find its length. If it is zero, then return without executing anything else in the function.

Using v.3.5.0, 
Browser: Chromium Version 65.0.3325.181 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (32-bit)

**Comment by olifolkerd** [comment]
Hey.

Tabulate loads a data set when it is first instantiated to make sure the table is set up correctly. If you pass in data to the ***data*** option it loads this. Otherwise it loads an empty array.

If you only use the ***setData*** function to load your data after the table is created then this is why the filtered callback is triggered.

I hope that explains it for you.

Cheers

Oli

**Comment by answerquest** [comment]
Yes, thanks. I decided it's best to not automate the action with `dataFiltered` as it was running too many times. Instead, put a button for user to launch the action.
