### ISSUE TITLE
row cells not available in sorting when there's scrolling

### ISSUE THREAD

**Issue by jgenyuk** [olifolkerd/tabulator#1054]
First of all, thank you for this amazing software, exactly what I was looking for!

I'm using a custom sorter function which uses other cells in a row to sort. The function below is passed a row from the sorter to get a  specific cell, and returns a DOM object to be parsed further:
`function sort_getCell(row, colName) {	
        var cell = row.getCell(colName);
        return cell.getElement();
}`
However, when the table is scrolling, the rows that aren't showing have row.getCell() undefined.
I used a workaround instead:
`return jQuery(row.getData()[colName]);`
which works perfectly. But I'm wondering if this is a bug or a feature, and whether there's a better way.

**Comment by olifolkerd** [comment]
Hey @jgenyuk 

Great to hear you are enjoying using Tabulator.

The issue you are having is because you are trying to access Cell Components for rows that havn't been rendered yet,

Tabulator uses a Virtual DOM which means it only renders rows that are needed to be displayed as the user scrolls to them. therefore not all cells will be available when the data is sorted.

You should avoid any direct DOM manipulation in tabulator, it will take care of that for you, and manipulating the DOM directly could cause it to malfunction. Tabulator has a huge array of built in functionality for most table manipulation needs.

Can i ask what your sorter is trying to sort by exactly? your sorter does not look like it conforms to the argument list for a Tabulator custom sorter.

```js
{title:"Name", field:"name", sorter:function(a, b, aRow, bRow, column, dir, sorterParams){
        //a, b - the two values being compared
        //aRow, bRow - the row components for the values being compared (useful if you need to access additional fields in the row data for the sort)
        //column - the column component for the column being sorted
        //dir - the direction of the sort ("asc" or "desc")
        //sorterParams - sorterParams object from column definition array

        return a - b; //you must return the difference between the two values
    },
}
```

See the [Sorting Documentation](http://tabulator.info/docs/3.5#sorting) for more information on how to add a custom sorter to Tabulator

Let me know if you need any more info,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
you can use all data safely, it is just DOM elements you should avoid if possible.

Cheers

Oli :D
