### ISSUE TITLE
Ajax method from get to post

### ISSUE THREAD

**Issue by aswzen** [olifolkerd/tabulator#106]
How to change ajax method from get to post?

Thank you in advance

**Comment by olifolkerd** [comment]
I would ***strongly*** recommend against doing that as it would be misusing a POST request.

GET requests are intended for retrieving data, POST requests are for creating/updating records and are not supposed to be used for simple data retrieval.

As Tabulator is not designed to do this, for the reasons outlined above you would need to override the ***_getAjaxData*** function by extending Tabulator. You can do this by inserting the following code, after you have included your ***tabulator.js*** file but before you define your Tabulator table.

```js
$.widget("ui.tabulator", $.ui.tabulator, {
    //get json data via ajax
	_getAjaxData:function(url, params){
		var self = this;
		var options = self.options;

		$.ajax({
			url: url,
			type: "POST",
			data:params ? params : self.options.ajaxParams,
			async: true,
			dataType:"json",
			success: function (data){

				if(self.options.pagination == "remote"){
					self._parsePageData(data);
				}else{
					self._parseData(data);
				}

			},
			error: function (xhr, textStatus, errorThrown){
				console.error("Tablulator ERROR (ajax get): " + xhr.status + " - " + errorThrown);

				self.options.dataLoadError(xhr, textStatus, errorThrown);
				self._showLoader(self, self.options.loaderError);
			},
		});
	},
});
```

**Comment by olifolkerd** [comment]
Due to popular demand Tabulator can now make ajax requests with any HTTP request type.

There are two ways of doing this, if you are defining the request url when building the table using the ***ajaxURL*** option, then you can set the request type using the ***ajaxType*** option:
```js
$("#example-table").tabulator({
    ajaxURL:"http://www.getmydata.com/now", //ajax URL
    ajaxParams:{key1:"value1", key2:"value2"}, //ajax parameters
    ajaxType:"POST", //ajax HTTP request type
});
```
If you are triggering the request using the ***setData*** function, then you can pass the type in as an optional third argument:
```js
$("#example-table").tabulator("setData","http://www.getmydata.com/now", {}, "POST"); //make a post request
```

Full details on how to use this functionality can be found in the [Ajax Documentation](http://olifolkerd.github.io/tabulator/docs/#ajax)
