### ISSUE TITLE
Dropdown in a row in html format

### ISSUE THREAD

**Issue by vipera7** [olifolkerd/tabulator#1064]
Hey @olifolkerd, I'm sorry to bother you again and again

I would like to know if it's possible to put a bootstrap dropdown in a particular cell which formatter is in html. My issue is that the list can't get out of the row. 

Here is a screen of what I got:

![alt text](http://i.imgur.com/0eqveq3.png "Logo Title Text 1")

And my tabulator constructor:

``` javascript
$("#dbl_table").tabulator({
    resizableColumns:false,
    virtualDomBuffer:300,
    height:"81vh",
    responsiveLayout:true,
    layout:"fitColumns",
    index:"id",
    columns:[
        {field:"id", visible:false},
        {field:"name_hidden", visible:false},
        {field:"enc", visible:false},
        {title:"", field:"ico", formatter:"html", responsive:0, width:70},
        {title:"Nom", field:"n_file", responsive:0},
        {title:"Taille", field:"s_file", responsive:2},
        {title:"", field:"action", formatter:"html", responsive:1, cellClick:function(e, cell){ e.stopPropagation();}},
     ],
});
```

and the simple button code in the column action

``` html
<div class='dropdown'>
    <button class='btn btn-secondary dropdown-toggle' type='button' id='dropdownMenuButton' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
    Dropdown button
  </button>
  <div class='dropdown-menu' aria-labelledby='dropdownMenuButton'>
      <a class='dropdown-item' href='#'>Action</a>
      <a class='dropdown-item' href='#'>Another action</a>
      <a class='dropdown-item' href='#'>Something else here</a>
  </div>
</div>
```

Thank you for any help !

**Comment by olifolkerd** [comment]
Hey @vipera7 

The issue you are having is because Tabulator does not allow anything relating to a cell to be displayed outside the boundaries of the cell, so the list gets hidden in the overflow.

Most drop downs have the option for defining where the list should be appended in the DOM, which allows the list to be positioned in the window outside of the cell element.

In the case of bootstrap i think you would be looking at the ***boundy*** option. more details can be found [here](https://getbootstrap.com/docs/4.0/components/dropdowns/#options)

I hope that helps.

Cheers

Oli :)
