### ISSUE TITLE
how can I know the field names from .tabulator("getGroups");

### ISSUE THREAD

**Issue by tolgaulas** [olifolkerd/tabulator#1078]
I want to modify the grouping list. As far as I could inspect; getGroups returns the rowgroups objects. How can I access the column object (or the field names and order for groping) so that I can add remove the existing grouping schema?

**Comment by olifolkerd** [comment]
Hey @tolgaulas 

There is no grouping list as such, you either specify the field to group by or pass in a function that then creates the values that are used to group the rows. you cannot remove one specific item from this otherwise there would be un-grouped rows.

if you want to find out the key for a group you can call the ***getKey*** function on its [Group Component](http://tabulator.info/docs/3.5#component-group).

The ***getGroups*** function returns an array of group components, so you could itterate through that list and get the key for each group.

You can change the grouping function at any time using the **setGroupBy*** function.

I hope that helps.

Cheers

Oli :)

**Comment by tolgaulas** [comment]
Thanks Oli for your usual promptness.. I simply made an outsider set to hold the tablewise current sorting (which I manually handle) and reassign the whole setGroupBy every time a grouping set has changed. The full iteration over getGroups felt like will make my life harder. My two cents, it would be better to implement similar feature to colGrouping as in getSorters-setSort pair which handle simple objectArrays.

All the best.

Tolga :)

**Comment by olifolkerd** [comment]
Hey @tolgaulas 

You can already pass in arrays to the ***groupBy*** property and ***setGroupBy*** function,, but in this case it is use to created nested groups within groups that group by different fields.

I will consider your approach and may add some additional functionality later in the roadmap.

Thanks for your thoughts

Oli :)
