### ISSUE TITLE
Best way to set up square matrix with size set at runtime ...

### ISSUE THREAD

**Issue by mgmoulton** [olifolkerd/tabulator#1084]
I have a square matrix that ranges from 1x1 to 100x100.

The actual size is set at runtime.

What is the best way to set up tabledata?

thank you ...

**Comment by quangkieu** [comment]
@mgmoulton I think you could try to create initialization Tabulator with 1 column. Then at run time use getColumnDefinitions, getColumns, setColumns based on your data[x][y].
http://tabulator.info/docs/3.5#column-management.

Set the columns field to corresponding subindex [y].
The row would be the [x] so you do not need to do anything.
Then use the SetData.

If that not work, I suspect that the problem is Tabulator used Array of Object, not Array of Array so you might need to remap the sub array into Object.

Good luck

**Comment by olifolkerd** [comment]
Hey @mgmoulton 

Tabulator isn't really built to work like that, it is built to show existing data,

To work in this way you would need to programatically generate a set of column definitions and rows for each of the columns/rows you want to add and then use the ***setColumns*** and ***setData*** functions to assign these to the table.

Cheers

Oli :)
