### ISSUE TITLE
When viewing right side of a table, then scroll down, it jumps left!

### ISSUE THREAD

**Issue by dpatel20** [olifolkerd/tabulator#1103]
Hi, I am using v3.5.1. I have a table that is wider than the available space of the screen. If I scroll to the right side of the table to view a particular column of interest and then start scrolling down, after short while the view jumps back to the left side of the table (and the column I'm interested in is no longer visible).

I suspect this is something due to the virtual DOM but when I try disabling the virtual DOM I lost the vertical scrollbar and can no longer scroll through the data! Is this a bug or something I am doing wrong?

Here is the table init:

```
function fixtureTableInit() {
	$("#example-table-demo").tabulator({
		height: "50%",
		index: "objectId",
		history: true,
		columns: [
			// Lots of columns with filters, sorters, editors and formatters
                        // Number of columns such that table is wider than space on screen.
		],
		rowAdded: function (row) {
			newRows.push(row);
		},
		cellEdited: function (cell) {
			// on edit function, removed for clarity.
		},
	});
```

**Comment by dpatel20** [comment]
Some testing shows that the 'jumping to the left' is only in Firefox (v59). There is no issue in Chrome. But the disabling of the virtual DOM issue is in both versions.

**Comment by olifolkerd** [comment]
Hey @dpatel20 

You definitely don't want to be disabling the Virtual DOM.

Are you updating the table data on an interval in the background?

Cheers

Oli :)

**Comment by dpatel20** [comment]
Hi Oli - No, I am not updating the table at all.

> You definitely don't want to be disabling the Virtual DOM.

Why? The API allows it so I assume it should work? As I say, I lose the scrollbars when I do.

**Comment by olifolkerd** [comment]
Hey @dpatel20 

While you certainly can disable the virtual DOM i would not recommend it on anything other than small tables as it will result in very poor performance of the table.

Disabling the virtual DOM will result in a loss of the scroll bars, it causes Tabulator to simply render out the table in one solid block, all at once.

Could you post an example of the table constructor you are using where this issue is present.

are you saying that some time after you have scrolled the table resets to the top, or is it while you are scrolling? no code is executed when the table is not moving so there would be no reason for it to spontaneously to jump to the top.

Im sure we can get to the bottom of what is going on here.

Cheers

Oli :)

**Comment by dpatel20** [comment]
The table constructor is in the first comment in this thread.

Steps to reproduce:

- Have a table that is wider than the space on the screen and the height set such that a vertical scrollbar is shown in the tabulator table.
- Scroll to the right of the table such that the left side of the table is off screen.
- Now begin scrolling down the table.
- After a few rows of scrolling the table will jump back to the **left** (not top).

Hope that clarifies the issue.

**Comment by olifolkerd** [comment]
Hey @dpatel20 

Thanks for the detailed instructions, they really helped get to the bottom of the issue.

I have pushed a fix to the master branch and will include it in this afternoons patch update.

Cheers

Oli :)
