### ISSUE TITLE
Tabulator blocking events from other functions

### ISSUE THREAD

**Issue by TeriyakiBomb** [olifolkerd/tabulator#112]
Hey! I'm having some issues with using Tabulator with Vue.js

I'm using tabulator to display and filter/sort data, but that data is provided (and hopefully updated) by Vue rather than in Tabulator. But tabulator blocks click events from any other JS. 

Is there a way around this? Or is there something I'm missing? #

**Comment by olifolkerd** [comment]
which click events are you trying to capture? which element are you looking for a click on? or are you tring to capture an event after it has propagated?

**Comment by TeriyakiBomb** [comment]
I'm looking for a click on row, I've tried e.stopPropagation and still nothing

**Comment by olifolkerd** [comment]
There is a ***rowClick*** callback for capturing that event:
```js
$("#example-table").tabulator({
        rowClick:function(e, id, data, row){
        //e - the click event object
        //id - the id of the row
        //data - the data for the row
        //row - the DOM element of the row
    },
});
````
If you are trying to make the binding yourself then you will either need to bind to the ***.tabulator*** element and capture the events as they propagate up from the row (because rows are dynamically redrawn so bindings will be lost if made to specific rows), checking that the source had a ***.tabulator-row*** class. 

Or you need to add the binding in the ***rowFormatter***, that way it will be added every time a row is created:
```js
$("#example-table").tabulator({
    rowFormatter:function(row, data){
        //row - JQuery object for row
        //data - the data for the row
        
        row.on("click", function(){
             //do something
        });
    },
});
```

**Comment by olifolkerd** [comment]
has this resolved your issue?

**Comment by olifolkerd** [comment]
Did this resolve your issue? if i don't hear back from u in the next 7 days i will close the issue due to inactivity.

Cheers

Oli

**Comment by TeriyakiBomb** [comment]
Sorry Oil, yes, this worked. Thank you!

**Comment by olifolkerd** [comment]
Great to hear it worked! Happy Tabulating :)
