### ISSUE TITLE
integer sorting not working for value like 1,217,166

### ISSUE THREAD

**Issue by dipeshpatel306** [olifolkerd/tabulator#1122]
Hi Oli, 

     Thanks you doing great!.  3.4.2 version tabulator.  I have a 1 table's column name is recoreds and I set to tabulator-sorter="number">Records</  but still sorting as string instead of integer. i read documentation and it says integer support "," too. but i don't why it not supporting into my application do you have any example where that use integer sort which includes "," separator?
output
![image](https://user-images.githubusercontent.com/16158843/40072057-92de9c06-5840-11e8-8939-3e0460ad5169.png)
code
![image](https://user-images.githubusercontent.com/16158843/40072083-aa481b6a-5840-11e8-9022-a3aa64d38de3.png)

**Comment by olifolkerd** [comment]
Hey @dipeshpatel306 

Thanks for getting in touch,

That is happening because a number with commas in is not a valid JavaScript integer and therefor the sorter will not sort it correctly.

The correct approach for this would be to store the data as an actual integer and then use the money formatter to add the 1000 separator commas for display purposes.

alternatively if you need to keep the data in its existing form you could create a custom sorter to filter out the commas.

I hope that helps

Cheers

Oli :)

**Comment by dipeshpatel306** [comment]
Thanks @olifolkerd  its works, 

       Now I facing precision issue. the Money format works but its adding decimal which I don't want. I using following code to remove decimal but its not working. 
<th width="130" tabulator-sorter="number" tabulator-formatter="money" tabulator-formatterParams ={precision:false}

**Comment by dipeshpatel306** [comment]
Hi @olifolkerd, 

   I changed var precision = typeof formatterParams.precision !== "undefined" ? formatterParams.precision : 2; to  formatterParams.precision : 0; So its works. Thanks for your help.
