### ISSUE TITLE
White space at the end of the table

### ISSUE THREAD

**Issue by adryx92** [olifolkerd/tabulator#1126]
Hi Oli,
I have a rendering issue for some rows: it shows a white space at the end of the page. I set the table div height to fit the page height trough Flexbox and then I set the Tabulator height to 100%. 
I have read other issues on this GitHub project and many resemble my problem but I think none of that resolves it. 
From the tests I made, it seems that reducing the number of columns the problem vanishes.

In addition, as is written in #1090, I have some performance issues, especially when scrolling the table.

I reduced the rows height through CSS like this: 
```
.tabulator-cell { height: 28px; }
```
but i don't think that can cause a rendering problem or impact the performance.

My code is
```
$("#table").tabulator({
    height: "100%",
    virtualDomBuffer:150,
    layout: "fitColumns", //fit columns to width of table (optional)
    columns:[...]
}).tabulator("setData", tabledata);

...
<div id="table" class="fill-height"></div>
```

Is there any way to fix the white space issue and to improve the performance before the Tabulator 4.0 version is released? Consider that I have 8 columns and approx. 4000 rows. I have to use the table in IE, while I notice the performance in FF, Edge and Opera are quite good.

Thanks

**Comment by olifolkerd** [comment]
Hey @vasiliyaltunin 

Thanks for getting in touch,

Could you post an image of the whitespace issue that you have, it will be easier to understand if i can see it. Does it happen when you scroll or when you resize the table?

The performance issues you are experiencing in IE is because its rendering engine is VERY inefficient compared to modern browsers and it simply cant process data fast enough to build the Virtual DOM in real time.

This will improve with the release of version 4.0 in a couple of months as the virtual DOM will be getting some efficiency improvements, but it will never be able to offer the same performance as a modern web browser.

From a development point of view I aim to make Tabulator functional in IE11 but it has a number of fallbacks that allow it to function but with a reduced experience as IE simply can't keep up.

While I understand the continued need for IE, and will continue to support it for the foreseeable future, the majority of the development effort for tabulator goes into ensuring optimum functionality in modern browsers as that is what the majority of its user-base use.

I hope that answers you questions.

Cheers

Oli :)

**Comment by adryx92** [comment]
Hello again,
Here's a screenshot of the white space that I've mentioned: https://dl.dropboxusercontent.com/s/ynzj8zb5wacaac2/screen.PNG

It happens only when I scroll the table, if I resize the window the white space disappears.

I understand what you say regarding IE and I perfectly know when you talk about compatibility... 🙂

**Comment by olifolkerd** [comment]
Hey All,

To make it easier to notify everyone of progress with the rendering system i have created one issue #1437 where i will report progress.

Cheers

Oli :)
