### ISSUE TITLE
Format table with Token/Tag type input

### ISSUE THREAD

**Issue by sumitb555** [olifolkerd/tabulator#1134]
Hi Oli,

I have a custom formatter for the table cells and I am successfully able to update colors and render text as URLs within the cells.

I am now interested in converting the text in the cells to tags/ tokens are is shown in this URL: [https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/](https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)

Can I enhance the formatter to add input tag elements as suggested in the bootstrap-tagsinput library OR is there a better way?

Thanks in advance!!!

**Comment by olifolkerd** [comment]
Hey @sumitb555 

You can certainly use the tagsinput widget if you would like.

In your custom formatter instead of returning text it just needs to return the input element:

```js
var customFormatter(cell, formatterParams){
    var input = $("<input></input>");
   
    input.tagsinput({...config options here...});
    input.val(cell.getValue());)

    return input;
}
```

If you waned to do something really simple you could just put each value in a span and then style that. In the example below I am assuming you are storing your tags as a space separated list:

```js
var customFormatter(cell, formatterParams){
    var contents = $("<span></span>");

    var tags = cell.getValue().split(" ");

    tags.forEach(function(tag){
        contents.append("<span class='tag'>" + tag + "</span>");
    });

    return contents
}
```

```css
.tabulator .tabulator-cell .tag{
    display:inline-block;
    padding:3px;
    background-color:#5bc0de;
    color:#fff;
}
```

I hope that helps.

Cheers

Oli :)
