### ISSUE TITLE
Idea: make cell updates async

### ISSUE THREAD

**Issue by lgraziani2712** [olifolkerd/tabulator#1158]
This issue is related to this comment: https://github.com/olifolkerd/tabulator/issues/1043#issuecomment-391709706

Tabulator keeps the cell editor active while the focus doesn't leave the input element, or doesn't leave the element wrapped in the cell container.

This breakes when a library creates elements outside the cell container, e.g. dhtmlXCombo. OR breakes when the update isn't synchronous (e.g., the updated data is invoked through an event which is triggered after the input events).

Here is a demo: https://codepen.io/lgraziani/pen/yjdZLr?editors=0010

Steps to reproduce:

1. Click on one cell of the "Column 1".
2. Write "a", "b" or "c", or click the dropdown icon.
3. Select an option with a click.

Selecting an option through the keyboard doesn't crash.

Another error (but this I think is something about my code, though I don't know what) is that if the rows are reordered, evey combo fails always.

Thank you!!

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

The issue you are having there isn't with Tabulator as such, it is with the way the custom editors have been defined, your editors call the ***cancel*** function on blur which is when it is then voiding the use of the ***success*** function.

If you create a more precise event bindings this wont be a problem as you wont have called the cancel event.

The reason the editors are "syncronous" is because they integrate with other systems such as Tabulators inbuilt validation system, which does not allow the focus of the cell to be shifted until a valid value has been entered.

You can also call the ***setValue*** function on the cell at any point, even when the edit has finished to change the value.

I hope that helps.

Cheers

Oli :)

**Comment by lgraziani2712** [comment]
Ok!! I could fix it! Thank you Oli :)

Here is the fixed pen: https://codepen.io/lgraziani/pen/Pawzme

BTW, is it ok to add documentation about this? If it is, I would gladly write it.

**Comment by olifolkerd** [comment]
Hey @lgraziani2712 

The source for the Tabulator website is privately maintained, but i would be happy to take suggestions/copy for improvements if you have any.

Cheers

Oli :)

**Comment by lgraziani2712** [comment]
I was thinking about this specific situation that the custom editor cannot update through the `success` function, and instead needs to use the `setValue`.
