### ISSUE TITLE
Why there is no paginationSize chooser built in Tabulator ?

### ISSUE THREAD

**Issue by aswzen** [olifolkerd/tabulator#117]
_"If you set the paginationSize without setting the height, the Tabulator will automatically resize to fit the data"_ that is absolutely a great innovation :+1:  i don't see something like this anywhere except on extjs,
but sometimes we need to overide a pagination size 10,50,100,1000, etc ..but i see there is no builtin feature from tabulator.. do you want to add this feature in the future?

thank you in advance

**Comment by olifolkerd** [comment]
Great idea!

I will add a ***setPaginationSize*** function this evening and give you a message when it is in!

**Comment by olifolkerd** [comment]
There is a ***setPageSize*** function that you can call to change the pagination size. Tabulator does not include the actual select element to allow for maximum flexibility for the developer so you can add the functionality anywhere on the page you like rather than being bound to a specific way of doing things.

To set the page size use the ***setPageSize*** function, pasing in an argument for the size of the page.
```js
$("#example-table").tabulator("setPageSize", 50); // show 50 rows per page
```

In your case if you wanted to use a select box for this you could use the following code:
```html
<select id="pagesize">
    <option value="5">5</option>
    <option value="10">10</option>
    <option value="25">25</option>
    <option value="50">50</option>
</select>
```

```js
$("#pagesize").on("change", function(){
    $("#example-table").tabulator("setPageSize", $(this).val());
});
```

**Comment by sk-karthik** [comment]
here is sample demo <a href="http://jsfiddle.net/KarthikSaravana/z2wta4ne/13" target=_blank>jsFiddle</a>
