### ISSUE TITLE
Bug in callback "rowadded"?

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1182]
Hey!
When use the rowAdded callback, it seems like the row.getCell("column") does not work.
getData works, along with other methods, but this does not seem to work.
Is this because the row is not yet added, and instead gets called WHEN added, so that tabulator does not find the cell because its not loaded yet? Thats my best guess!
(btw the cell I am trying to get, is indeed existing in this object)
```
rowAdded: function (row) {
                    //row - row component
                    
                    console.log("her");
                    console.log(row);              
                    console.log(row.getCell("TOTALCOST"));
 
                },
```
![image](https://user-images.githubusercontent.com/11444201/41089857-22feda3a-6a43-11e8-99c9-c6307ecd8b6e.png)

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

That is happening because the row you have added has not been displayed on the table yet (it is out of view) and therefore hasnt been rendered yet, therefore no cell components exist on the row.

I hope that makes sense.

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
That makes sense, thank you! But I would have thought that the callback fired AFTER it was added:(

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

The callback does fire after the row is added to the table, however the cells in a row are not generated until the row is first visible, This is how the Virtual DOM works to speed up rendering of the table it only creates the parts of the table it need to display, therefor it doesn't have to process all the data the moment it is loaded into the table.

in version 4.0 coming in July i am looking to improve this part of the system, so you may get the ability to get the components then.

Cheers

Oli :)

**Comment by tomasderner97** [comment]
Hello, I have the same problem with version 4.2.6. What is the best way to get to the cell components of the added row after they were created?

**Comment by olifolkerd** [comment]
@tomasderner97  That very much depends on your usage case. could you provide some more details of what you are trying to achieve

**Comment by tomasderner97** [comment]
It's funny. I'm working on a table of users. It allows editing, adding new users and deleting existing ones. All the changes are stored in an object until the user hits the Save button, then the object is ajaxed to the server. I need to be able to somehow mark edited cells (set their background gray (actually I set the background to rgba(0,0,0,0.05) so it plays nicely with the row selections), I use the bootstrap 4 css) to distinguish the unsaved changes. I haven't been able to find out a) how to set formatters to cells dynamically and more importantly b) how to combine existing formatters with my own (eg. use a tickCross formatter but make the background gray). So I just set a class to the cell element in cellEdited callback (I also use undo and redo, so I had to make sure undo and redo callbacks call cellEdited). 
But when I delete a row and then undo it so the row appears again, the row is apparently formatted again and the cells lose the gray background. So I wanted to go over all cells of the restored row in rowAdded callback and color all the edited cells again (by comparing row id and field with the object containing the changes). Here is where I got stuck (I've since "solved" it in a cheaty way in the undo callback). It's ugly, I know.
So that's the context, but if you want to tell me a better way to achieve this so I don't actually need to get the cells from the row, I'd appreciate it.
