### ISSUE TITLE
Image Height in the Cheese Example - RowFormatter

### ISSUE THREAD

**Issue by u-ilana** [olifolkerd/tabulator#1204]
Hi Oli,

Thanks for taking the time to maintain this project.

I'm using the out of the box working example of the RowFormatter. I can't figure out how to set a max width/height on the images - they end up taking over the whole page. I've tried adding width and max width to the css at all 5 #example-table attributes. I've also tried fixed and absolute strings in the width= section of the rowFormatter function, and in the actual $("tr",table).append.

Could you explain how I can fix this? My goal is to set widths that autoscale with the height and take up about 30% of the page. 

Link to sample image:
http://lorempixel.com/output/animals-q-c-1491-1063-9.jpg

Thank you!!

**Comment by olifolkerd** [comment]
Hey @u-ilana 

You cannot set image heights as percentages in Tabulator due to the way that tabulator resizes cell heights to fill a row it will cause it to scale very badly.

You should set heights in pixels. if you want this to be dependant on table or row size then i would suggest using a custom formatter to set the height of the image element, with the formatter calculating that height in pixels.

But i like the point you raise, for the 4.0 release in July i will look at incorporating this into the img formatter as a param.

I hope that helps

Cheers

Oli :)

**Comment by u-ilana** [comment]
Hi Oli,

Thanks for getting back to me.

How can I set even a fixed width/height? 

![image](https://user-images.githubusercontent.com/40133241/41816104-e7a2ec6a-7730-11e8-864b-d4011affacb8.png)

**Comment by olifolkerd** [comment]
Hey @u-ilana,

You shouldnt be using the rowFormatter to alter the contents of a specific cell. you should the formatter for that specific column.

below is a custom version of the image formatter that sets the height and width of an image

```js
function imageFormatter(cell, formatterParams){
	var value = this.sanitizeHTML(cell.getValue());

	var el = $("<img src='" + value + "'/>");

        el.style({
            height:"10px",
            width:"20px",
        });

	el.on("load", function(){
		cell.getRow().normalizeHeight();
	});

	return el;
},

//column definition
{title:"photo", field:"photo", formatter:imageFormatter}
```
I hope that helps,

Oli :)

**Comment by u-ilana** [comment]
Thanks for writing that function! I added it to tabulator.js

I get the error 'el.style' is not a function.

**Comment by olifolkerd** [comment]
Hey @u-ilana 

sorry for the mixup there ***style*** should say ***css***, i have updated the example.

Cheers

Oli :)

**Comment by u-ilana** [comment]
Hi Oli,

Thanks for updating the function. It no longer returns an error. However, it doesn't affect the table (other than changing the title). Could I be calling something in the wrong order?

Here's my full code. 

Html 1: Index Page, Calls the table page with a filter (Great filter feature! thanks)

head:
![image](https://user-images.githubusercontent.com/40133241/43038312-c61679a8-8ccb-11e8-8fc2-4e3e67365812.png)

table link:
![image](https://user-images.githubusercontent.com/40133241/43038286-7c056cde-8ccb-11e8-9a0a-56b5942ae4d2.png)

`

Html 2 (table page):
![image](https://user-images.githubusercontent.com/40133241/43038314-f1f1d8ce-8ccb-11e8-9dc4-a506390a6ff2.png)

dyn_row_table.js:
![image](https://user-images.githubusercontent.com/40133241/43038391-ea8a5948-8ccc-11e8-9cf0-b3b33deba33c.png)

Thanks! (and sorry for the response delay)

**Comment by olifolkerd** [comment]
Hey @u-ilana 

Looking at your code your ***rowFormatter*** is emptying the entire contents of the row and replacing it with something else, which is why you are running into trouble, the cells that tabulator creates are completely removed by your row formatter.

Im not sure what your are trying to achieve with that formatter, you could be using columns in the table to contain your data.

I hope that helps,

Cheers

Oli
