### ISSUE TITLE
string filters are case sensitive

### ISSUE THREAD

**Issue by ryhill** [olifolkerd/tabulator#1221]
When I try to apply filters, the string filters are always case sensitive.

Is there a way to make sure it is disabled

Thanks

KIRAN

**Comment by olifolkerd** [comment]
Hi Kiran,

Which filters are you trying to use? could you include an example of the code you are using?

Cheers

Oli :)

**Comment by ryhill** [comment]
Hi Oli,

Observation : I see that tabulator is throwing error while converting to lowercase when = filter is applied in js file

**Equals to:**

![image](https://user-images.githubusercontent.com/33457591/41987679-7ab7cfec-7a57-11e8-8ba9-624c78909b79.png)



![image](https://user-images.githubusercontent.com/33457591/41987703-95ded89c-7a57-11e8-847d-e847dec9d59e.png)


**LIKE**

![image](https://user-images.githubusercontent.com/33457591/41987733-b53a1b48-7a57-11e8-8e1d-4669fff329da.png)


![image](https://user-images.githubusercontent.com/33457591/41987760-c700261a-7a57-11e8-83f4-ec090737e0db.png)

**Comment by olifolkerd** [comment]
Hey @ryhill 

That is because the "=" filter is looking for an exact equal which is case sensitive.

To make your own case insesitive filter function i would suggest that you use a custom filter function that converts  the filter value and the row value to lowercase before it is compared.

Cheers

Oli :)

**Comment by ryhill** [comment]
Thanks Oli.

any leads where i can start with
