### ISSUE TITLE
Focus AND select issue on cell

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1258]
Hey!
I try to focus on a cell after I have added a row to the table, this works very well.
However, selecting it by calling "target".select() does not work.
Can someone help me with this? 
What I want is that the INPUT, where the cell now is "0" should be marked/selected, so that you can easily edit without having to backspace the 0.
![lalala](https://user-images.githubusercontent.com/11444201/42510358-f0c08cd2-844e-11e8-9c22-6acae9804f66.gif)
![2018-07-10 14_35_31-window](https://user-images.githubusercontent.com/11444201/42510434-2adfee12-844f-11e8-8613-f42a9b71a87d.png)

**Comment by Nyut0n** [comment]
Hey @Rodbjartson,

the cell element is always a div I think, which you can't focus or run select() on.
You'll probably want to grab the input inside the div first.
Maybe something like $(cellElement).find("input");

**Comment by Rodbjartson** [comment]
Hey, thanks for your answer. The problem is, what is this input field called?

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

@Nyut0n is correct, the cell itself is a div

The issue you are having is because editor elements is only created after the focus event has been processed (editors are added to cells in real time, they do not sit their waiting to be used)

You do not need to know what the input field is called to select it, as it is the only input element in the cell @Nyut0n method of selection will work, but you many need add a ***setTimeout*** of around 100ms before calling it to give Tabulator the time to render the input element.

The other option would be to use a custom editor, you could then set the editor to automatically select the input elements contents as soon as it has focus.

I hope that helps

Cheers

Oli :)
