### ISSUE TITLE
How to reload data ??

### ISSUE THREAD

**Issue by nwoow** [olifolkerd/tabulator#1274]
I can set data using : 

`          $("#example-table").tabulator("setData", tabledata1);
`

I am using this onclick method but when I am trying to click again I am getting : 

`tabulator.min.js:4 Options Error - Tabulator does not allow options to be set after initialization unless there is a function defined for that purpose`

Is there any way before I setdata I can empty table data.

**Comment by ryhill** [comment]
$("#example-table").tabulator("destroy");

**Comment by Rodbjartson** [comment]
Please post the table constructor, and the whole onClick() method.

**Comment by olifolkerd** [comment]
Hey @nwoow 

If you are only updating the table data then there is no need to destroy your table as @ryhill suggests.

Your are likely receiving that warning because you are trying to instantiate your entire table again in your onclick function, where you should just be calling the ***setData*** function.

I hope that helps,

Cheers

Oli :)

**Comment by MaxieZ** [comment]
Hi there,

I want to automatically update data every X seconds, so I've been using 

`		window.setInterval(function(){
		  table.replaceData()
		}, 5000);`

However, I also want to be able to edit the data and send it back to the database. Whenever it executes **table.replaceData()**, it closes the input form and clears the data before I can complete the update. Is there a way around this? Or should I update the table less frequently?
