### ISSUE TITLE
Problem with grid on Partial page in MVC

### ISSUE THREAD

**Issue by NHSDevGuy** [olifolkerd/tabulator#1337]
Hi all,

Tabulator looks exactly what I'm looking for so - of course! - I'm running into a problem.

I'm using v3.5.3, jquery 3.3.1 and the latest jquery UI. I'm also using UIkit rather than Bootstrap and (the killer) MVC. The issue occurs with IE11 (which, being NHS is the preferred browser) and Firefox 61 but not Chrome 68.

Using the Getting started code, I have a Tabulator grid on a partial page. This is a snippet of the main page:
@using (Ajax.BeginForm("Save", "Home", null, null, new { id = "home", name = "home", @class = "uk-form inputForm" }))

<code>

    <ul id="iccMenu" class="uk-switcher uk-margin">
        <li aria-hidden="true">@Html.Partial("_Events", Model)</li>

and this is the total of the partial _Events:

@model ICC.Models.ICCViewModel

<fieldset data-uk-margin class="uk-fieldset">
    <div class="uk-grid">
        <div class="uk-width-1-1 uk-margin-bottom">
            <div id="eventsGrid"></div>
        </div>
    </div>
</fieldset>

and in the document ready:
    $("#eventsGrid").tabulator({
        height: 205, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
        layout: "fitColumns", //fit columns to width of table (optional)
        columns: [ //Define Table Columns
            { title: "Name", field: "name", width: 150 },
            { title: "Age", field: "age", align: "left", formatter: "progress" },
            { title: "Favourite Color", field: "col" },
            { title: "Date Of Birth", field: "dob", sorter: "date", align: "center" },
        ],
        rowClick: function (e, row) { //trigger an alert message when the row is clicked
            alert("Row " + row.getData().id + " Clicked!!!!");
        },
    });

    //define some sample data
    var tabledata = [
        { id: 1, name: "Oli Bob", age: "12", col: "red", dob: "" },
        { id: 2, name: "Mary May", age: "1", col: "blue", dob: "14/05/1982" },
        { id: 3, name: "Christine Lobowski", age: "42", col: "green", dob: "22/05/1982" },
        { id: 4, name: "Brendon Philips", age: "125", col: "orange", dob: "01/08/1980" },
        { id: 5, name: "Margret Marmajuke", age: "16", col: "yellow", dob: "31/01/1999" },
    ];

    //load sample data into the table
    $("#eventsGrid").tabulator("setData", tabledata);

In Chrome, this works perfectly:
![image](https://user-images.githubusercontent.com/42267843/43951543-57f71fac-9c8b-11e8-8b20-446dc95ef0da.png)

In Firefox/IE11, however, this happens:
![image](https://user-images.githubusercontent.com/42267843/43951635-88649598-9c8b-11e8-86c2-6c7c42ae13e2.png)

Resize the browser and:
![image](https://user-images.githubusercontent.com/42267843/43951592-6fd82b2a-9c8b-11e8-806c-b844e5d36020.png)

However, if I move the grid outside of the menu, it works:

<div id="eventsGrid"></div>
<ul id="iccMenu" class="uk-switcher uk-margin">

Is this a bug or (more likely) am I doing something wrong?

Paul

**Comment by olifolkerd** [comment]
Hey @NHSDevGuy 

Thanks for getting in touch, 

am i missing something or are both the screenshots for ie the same image?

If you are experiencing visual corruption of the table, this is because Tabulator needs to be visible when it is loaded in order to correctly layout its components (hidden elements have no initial size in the DOM so tabulator cannot work out how to lay them out).

To get round this you need to call the ***redraw*** function on your Table when the tab it is in is made visible.

Resizing the browser fixes the visual corruption because Tabulator listens for this event for you and redraws the table when the window changes shape.

It works better in chrome, because of a natty ES8 feature that is currently only available in chrome that allows Tabulator to detect any chance to the size of its containing element and automatically redraw itself, which allows it to handle more unusual situations.

I hope that helps,

Cheers

Oli :)

**Comment by NHSDevGuy** [comment]
Hi Oli,

Thanks for you help (I was on holiday for a couple of weeks :-D )

It helped a lot but UIKit seems to be a swine with notification of a tab being visible.

Just for anyone's interest I ended up creating the table  on the main page then moving it to the required tab. A rubbish work-around but it does what I need!

Thanks for a very nice plugin.

Paul
