### ISSUE TITLE
formatter:"color" rgba(166,32,72,0.5)  not work

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#135]
Hi Oli,

I have a column with formatter:"color" and the value is rgba(166,32,72,0.5).
But the visible color in the cell is rgb(166,32,72).
See the screenshot.
![bildschirmfoto 2016-12-14 um 22 37 21](https://cloud.githubusercontent.com/assets/22855656/21202290/99d48d7e-c24e-11e6-8ca1-e006e04ee085.png)

MG Kurt

**Comment by olifolkerd** [comment]
I can't seem to replicate your issue

Which browser are you using? could you send over your tabulator constructor and a sample of the data set.

Cheers

Oli

**Comment by kurtknippschild** [comment]
Hi Oli,

I tested with Safari, Firefox and Chrome.
[aktivitaeten_tabulator.zip](https://github.com/olifolkerd/tabulator/files/653926/aktivitaeten_tabulator.zip)

You can see the issue on the index_color.html.
Sort on column "ID" and the row with the ID 2 there is the color-value "rgba(166,32,72,0.5)"

MG Kurt

**Comment by olifolkerd** [comment]
Looking at the page the colour is being set correctly.

The issue you have is that there is a red background to the row in the theme you are using (it is how the coloured handles on the left of the rows are achieved), the cells of each row then have an alternating white/grey background depending on the row, which you are then overriding with your chosen colour. because it is partially transparent you can see the row background colour coming through.

To fix this I would recommend creating a custom formatter that fills the cell with a div that you can then assign the background colour to:

```js
//custom color formatter function
function colorFormatter(value, data, cell, row, options, formatterParams){
	var block = $("<div></div>");

	block.css({
		"display":"inline-block",
		"position":"absolute",
		"top":0,
		"bottom":0,
		"left":0,
		"right":0,
		"background-color":value,
	});

	return block;
}

//assign in the column definition array of your tabulator constructor
$("#tabulator_objektgruppe").tabulator({
    columns:[ 
        {title:"Backgroundcolor", field:"og_color", sorter:"string", align:"center", width:60, formatter:colorFormatter, tooltip:true },
    ],
});
```

**Comment by kurtknippschild** [comment]
Hi Oli,

thanks.
It's okay now.

MG Kurt
