### ISSUE TITLE
Sort by Rownum Column

### ISSUE THREAD

**Issue by Coroecram** [olifolkerd/tabulator#1359]
If I have a column defined as:
{'name': "rownum", 'title':"Row", 'formatter':"rownum", 'align':"center", 'width':60, 'sortable': true, 'sorter': "number"}

in an array of columns and build my table:

$("#csv-table").tabulator({'columns': columns,
                                      'layout':"fitColumns",
                                      'addRowPos':"top",
                                      'pagination':"local",
                                      'paginationSize':10,
                                      'movableColumns':true,
                                      'resizableRows':true
                                    });

The rownum column will not be sort. I have tried to add a custom function as well, but a and b are returned as undefined, and I can not find the column anywhere in the arguments for the functions.

The click action and ASC or DESC arrow are always present regardless of 'sortable', and changes direction on click. This is a separate issue but shows that some sort of functionality is there...

Is there some way to sort by formatter: rownum? If not, I think it would be a valid feature.

**Comment by Coroecram** [comment]
I got to a point with the following column where it does sort by the rownum but the rowNum  column itself is not sorted:

``` 
var rowNumCol = {
          'name': "rownum",
          'title':"Row",
          'formatter':"rownum",
          'align':"center",
          'sortable': true,
          sorter: function(a, b, aRow, bRow, column, dir, sorterParams){
            //a, b - the two values being compared
            //aRow, bRow - the row components for the values being compared (useful if you need to access additional fields in the row data for the sort)
            //column - the column component for the column being sorted
            //dir - the direction of the sort ("asc" or "desc")
            //sorterParams - sorterParams object from column definition array
            b = parseInt($(bRow.row.element).children()[0].textContent)
            a = parseInt($(aRow.row.element).children()[0].textContent)

            return a - b; //you must return the difference between the two values
          }}
```

**Comment by Coroecram** [comment]
I think I understand the concept of rownum now (after spending so much time hacking away here). It is the rownum of the data is **in** the table, **not the data passed**** to the table. The rownum will change on pagination **but** it will not change on sorting because it is the **table's** rownum, not the data's.

Is that what I'm figuring out?

**Comment by olifolkerd** [comment]
Hey @Coroecram 

Thanks for getting in touch, looks like you have been diving into the code there.

Formatters only affect the appearance of the table and have no effect on the underlying data, and sorters sort using the table data itself. therefore nothing you do in a formatter will affect the sort.

The rownum formatter is intended to help display the position of a row in the table, the numbers themselves are in no way bound to the rows, for example if you filter the table different row numbers will appear against different rows.

If you want this column to be sortable then i would suggest that you either set an id on each of your rows data before it is entered into the table, OR instead of using a formatter you use a [Mutator](http://tabulator.info/docs/3.5#get-set), mutators allow you to alter data as it is entered into the table. you could use this to create a column with an incrementing number that could then be sorted.

I hope that helps,

Cheers

Oli :)

**Comment by Coroecram** [comment]
Oli,

Mutator is the way to go. I came across Formatters first searching for "rownum".

Thanks for the thoughtful reply, I will go ahead and close this.

Cheers
Michael
