### ISSUE TITLE
On Sorting table or change page using pagination removed my custom handling 

### ISSUE THREAD

**Issue by sarkariajatt** [olifolkerd/tabulator#1422]
HI,
I am adding custom tooltip which initiate using $('[data-toggle="tooltip"]').tooltip(); and i run this function after table build. But when i sort table by clicking on column header then i loose the tooltip.
Same happens on page change. Is there a way by using which i can call all the required call backs again when tabulator done with page change and also same thing on sorting table.

**Comment by olifolkerd** [comment]
Hey @sarkariajatt 

Thanks for getting in touch.

This is happening because Tabulator uses a virtual DOM which means it creates and destroys the elements of the table as you interact with it, only rows that are visible actually exist, when they are hidden by scrolling etc they are destroyed.

Therefor any attempt to manipulate the DOM inside Tabulator from outside will break.

The correct way to do this would be to use a formatter on the column you want to put the tooltips on:

```js
//define custom formatter
function tooltipFormatter(cell, formatterParams){
    ///create custom tooltip
    $(cell.getElement()).tooltip();

    //return correct value for cell
    return cell.getValue();
}

//in your column definition you then set this as the formatter:
{field:"name", title:"Name", formatter:tooltipFormatter},
```

I hope that helps,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @sarkariajatt 

There would be nothing to stop you creating two formatter functions and calling one from inside another.

Cheers

Oli :)
