### ISSUE TITLE
Different selection behaviour for multiple row selection

### ISSUE THREAD

**Issue by mikila85** [olifolkerd/tabulator#1425]
The multiple row selection is really bad currently and should be improved...
it is not intuitive and doesn't work as expected, we had many complaints from customers about it.

**Current behavior:**
Clicking on a row, to toggle its state.
Holding down the shift key and click dragging over a number of rows to toggle the state of all rows the cursor passes over.

**Desired behavior:**
Clicking on a row, single select it.
Clicking on a row with **CTRL** , select/deselect it in addition to currently selected rows.
Clicking on a row with **SHIFT** ,select all rows in between the currently *("focused" row) and the clicked row.
Clicking on a row with **CTRL+SHIFT** ,  select/deselect all rows from the currently "focused" row to the clicked row in addition to currently selected rows.

*("focused" row) is the last clicked row without shift

**Comment by erez86** [comment]
[Pull request with a fully working fix](https://github.com/olifolkerd/tabulator/pull/1426)

**Comment by olifolkerd** [comment]
Hey @erez86 ,

There is indeed a single selection mode, you just set the ***selectable*** property to ***1***
```js
$("#example-table").tabulator({
	selectable:1,
});
```

**Comment by olifolkerd** [comment]
Hey @mikila85

Thanks for getting in touch. I appreciate your feedback, but would appreciate it if you could work on your tone of your issues in future.

Tabulator is an ongoing project and I always welcome suggestions for improvement, but not everyone has the same view point on issues, so please make enhancement suggestion in future not personal criticisms.

The click to toggle aspect has been specifically requested by a large number of users which is why it is there.

I do agree that there is room for improvement in the interaction with selected rows and think that your suggested options make sense.

I am currently working on the 4.0 release this weekend and do not have time to get these changes in before that release, but i will look at adding it to the roadmap for the 4.1 release.

Thanks for the input,

Oli :)

**Comment by mikila85** [comment]
Hey @olifolkerd 

Sorry if you got me in that tone, we love your table and really appreciate the hard work you guys put in and want to contribute and help out if it is possible,

As you can see me and @erez86 made a pull request for it to work just like windows explorer for files list and better than other JS tables like [AG-GRID](https://plnkr.co/edit/GYcaaymCEC7yUs0HeVcn?p=preview).
take a look at our pull request, if it is possible to merge it or maybe if you want to keep the old behavior we can change it to have multiple states of single/multiple/drag(like today which can be default to not effect other members)

Thanks, Miki :)

**Comment by olifolkerd** [comment]
Hey @mikila85  an @erez86 

Thanks for your pull request,

While i do appreciate the functionality you are after (and it is great that you have sumbitted a pull request with your ideas),

Im afraid your suggestion completely replaces the current selection method, which while i am sure it is great for your usage case it goes completely against what other users have requested.

The drag selection mechanic was specifically requested a number of times when this section was being developed.

I would be happy to look at adding a option to choose between a between drag select and shift range select to allow both approaches, but i would not be looking to remove the drag select from the code.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @mikila85 

Version 4.1 has been released with your pull request included and now has the ***selectableRangeMode*** option to enable click selection:

```js
var table = new Tabulator("#example-table", {
  selectableRangeMode:"click",
});
```

Thanks for your input on this.

Cheers

Oli :)
