### ISSUE TITLE
dataFiltered function not working properly

### ISSUE THREAD

**Issue by LastExile16** [olifolkerd/tabulator#143]
Hi Oli
the function 
```javascript 
dataFiltered:function(data, field, type, value) {
        console.log("field: "+field+" with data "+value);
},
``` 
not receiving the variables field and value, the output for the above code is
```javascript
function colFilter(data){
	var match = true;

	for(var field in filters){
		if(typeof data[field] == "string"){
			if(data[field].toLowerCase().indexOf(filters[field].toLowerCase()) == -1){
				match = false;
			}
		}else{
		    //match everything else explicitly
		    if(data[field] != filters[field]){
		    	match = false;
		    }
		}
	}

	return match;
} with data undefined
```
as you can see the field is returning a function and data returning undefined
I don't know what is the matter could you check it, please?
Thank you

**Comment by olifolkerd** [comment]
This is because you are using header filters. In this case a custom filter callback is used (to combine multiple possible header filters), which is the function that is being passed to the field argument of the ***dataFiltered*** callback.

In this situation it is not possible to access the filter fields directly, as the filter is applied as a sum of all of the filtered fields.

What you can do instead is iterate through all of the headers in when the ***dataFiltered*** callback is triggered to check which ones have a value:
```js
$("#example-table .tabulator-header-filter input").each(function(){
    var value = $(this).val();

    if (value !== ""){
        //process filtered field
    }
});
```

in this example we only iterated through input element filters, but you could adjust this to include select elements etc if needed.

Incidentally, it looks like you are using an old version of Tabulator, I would suggest downloading the latest version as there have been significant improvements to the header filters in the last week.

Let me know if this helps you out.

Cheers

Oli

**Comment by LastExile16** [comment]
Thank you Mr.Oli it's working, but how can I get filtered column name, as you know the "input" doesn't have any attribute to indicate its' column.
could you add an enhancement to it, I mean create a special callback for header filters in which we can get the column name and the filtered value of used header filter with looping inside all of them.

**Comment by olifolkerd** [comment]
You can easily find out the field by looking for the containing ***.tabulator-col*** element and using its ***data-field*** property:

```js
$("#example-table .tabulator-header-filter input").each(function(){
    var value = $(this).val();
    var field= $(this).closest(".tabulator-col").data("field"));

    if (value !== ""){
        //process filtered field
    }
});
```

I will have a think about the header filter callback, but it is a bit too specific a usage case for a callback, i usually only add them for events that happen as part of standard flow, and it would conflict a bit with the existing dataFiltered callback. i will have a think. in the mean time the above code should sort you out.
