### ISSUE TITLE
V4 visibility problem for tabulator div in edge and firefox

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#1432]
Hi Oli
Chrome ok
but if one programmatically changes the visibility of the div where the tabulator resides, 
The header is shown but the data part remains invisible.
the div with div  class = tabulator-table remains empty, no rows.
Is displayed as soon as Developer mode is toggled (F12 in Browser) or Browser viewport size is changed with mouse.
Same effect if i modify tabulatorDivElement.style.display or if I add/remove class for display attribute.

Initally; set to not visible
then: 
tabulator.setData(data);
tabulatorDivElement: change visibility

Same behaviour also even if I make a surronding div and manipulate visibilty there.

Know Problem?
Wait for later Beta?

Cheers, Michael

**Comment by michaelongithub** [comment]
If one first makes the div for the tabulator visible again, and abulator.setData(data);, the problem doesent occur.
Howewer: if the div for the tabulator is inside a Bootstrap Modal (inside the <div class="modal-body">) this does not help,

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

This is not a version 4.0 issue, this has been the case for Tabulator (and a lot of graphical layout JS libraries) since the dawn of time.

The issue is because elements in the DOM do not have dimensions until they are first made visible, so if the table is hidden when it is created or updated Tabulator does no know how to lay things out, hence the visual corruption.

Because there are no JS events fired when the table is made visible it has no way to know when to redraw itself when it becomes visible, changing the screen size in any way (opening the dev console for example) triggers the window resize event which Tabulator listens to and redraws itself.

The reason it works fine in Chrome is because chrome is the first browser to implement an ES8 feature called a ***ResizeObeserver*** which allows individual DOM elements to know when they are being resized, and also triggers on an object changing visibility as it gains a size at that point. Tabulator uses this if it is present, so as other browsers add support for this the issue should resolve itself.

I hope that clears things up.

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Hi Oli
thanks a lot for taking the time and trouble to clarify this for me. Probably another late JS programmer bloomer effect of not having known this. So thank you for bearing with me.

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

No problem,

They way round it is to call the ***redraw*** function when the table becomes visible.

Cheers

Oli :)
