### ISSUE TITLE
Question: Set the page of a specific row (Ajax)

### ISSUE THREAD

**Issue by dedacpo** [olifolkerd/tabulator#1433]
Hello!

Sorry if the question sounds dumb, but I couldn't find the answer on documentation.

I have a table with the data comming from a url and the pagination is remote.

My question is:

There is a way to use something like the scrollTo() when the row that I want is not visible on the table? 

In this case, the table should go directly to the page of that row and fill the whole page with the other registers of that page?

Or in order to do that I will need to send a request to the server by myself? In this case, the server will return the page number and then I'll set the page number on the table

**Comment by olifolkerd** [comment]
Hey @dedacpo 

Thanks for getting in touch, there is no specific function for that, though it is an interesting idea.

You could call the ***getPosition*** function on the row component, this would let you know where in the list of data the row is, if you devide this by the page size it will tell you waht page it is, you can then call the ***setPage*** function to load that page.

I hope that helps,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
if the data is remotely on your sever then Tabulator has no idea whether the row exists or not. it only creates rows as the data is loaded into the table.

In order to load the right page you will either have to know what page it is on or be able to calculate it buy its position.

either that or you would need to create a function that queries your server to find the correct page for given row details, but that is outside of the scope of Tabulator im afraid

Cheers

Oli :)

**Comment by dedacpo** [comment]
@olifolkerd, yes, that is what I was thinking. I will then create a function on server that returns to me the correct page and then I will set the page on tabulator. Thanks!! =)
