### ISSUE TITLE
String with LF/CR 

### ISSUE THREAD

**Issue by kurtknippschild** [olifolkerd/tabulator#144]
Hi Oli,

i have a Problem with Lines containing a CR / LF.
You can see the Problem in the index_question.html.
[aktivitaeten_tabulator 2.zip](https://github.com/olifolkerd/tabulator/files/673821/aktivitaeten_tabulator.2.zip)

In the row 91
			, fr_antwort:"Wird mit dem Projektteam gerade analysiert. 
Werde morgen die Frage vollständig beantworten"
is the problem.

MG Kurt

**Comment by olifolkerd** [comment]
Hey,

Looking at your code, that is a general JavaScript error and not a Tabulator issue.

This issue is you are trying to use a carriage return in string literal which is not possible in js.

There are two ways you can deal with this, you can use the ***\n*** character to insert the caridge return into your string
```js
fr_antwort:"Wird mit dem Projektteam gerade analysiert. \nWerde morgen die Frage vollständig beantworten",
```
Or you can use backtics *`* (not single quotes) instead of quotation marks, which would produce a template string which can use standard caridge return characters
```js
fr_antwort:`Wird mit dem Projektteam gerade analysiert. 
Werde morgen die Frage vollständig beantworten`,
```

I hope this helps

Cheers

Oli
