### ISSUE TITLE
Column misalignment when adding new row

### ISSUE THREAD

**Issue by haferje** [olifolkerd/tabulator#1446]
**Describe the bug**
The column headers become misaligned with the body columns when horizontally scrolled and add a new row.

**Tabulator Info**
v4.0.0
Using the example grid on the Tabulator website

**To Reproduce**
1. Go to the Tabulator website
2. On the example grid, resize a column so the grid becomes horizontally scrollable
3. Partially scroll the grid horizontally
4. Click the example "Add Row" button
5. See that the header columns are no longer aligned with the body columns
6. Scroll the grid horizontally again and and columns will correctly re-align

**Expected behavior**
When adding a new row, the column headers should stay re-aligned

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69.0.3497.92

**Comment by olifolkerd** [comment]
Hey @haferje 

Thanks for the heads-up,

Looking into it further it is actually being caused by a weird interaction with the spakline formatter, which is an en external library that was being used to demo a custom formatter.

I have removed that formatter from the example, and will have a play with the sparkline library on the weekend to see where the issue is coming from and update the documentation accordingly.

Thanks for getting in touch.

Cheers

Oli :)

**Comment by haferje** [comment]
Yep, seems to work better after removing that.

I've been evaluating a large amount of grid libraries recently and I wanted to commend you on your project!

**Comment by olifolkerd** [comment]
Hey @haferje 

Thanks for the kind words, it is always nice to hear people are enjoying using Tabulator.

The roadmap for Tabulator is driven by its users so if there are any features that would be useful to you just raise an issue and they will get added to the roadmap.

Happy Tabulating!

Oli :)
