### ISSUE TITLE
4.* - bundling only selected modules?

### ISSUE THREAD

**Issue by studio404pl** [olifolkerd/tabulator#1447]
I was wondering if there's a way to load/bundle only specific modules? For example could we require only core functionality and then decide what modules we want to use? Currently entire library is not so lightweight and it would be a good thing to optimize it according to developers needs.

**Comment by olifolkerd** [comment]
Hey @studio404pl 

Absolutely.

There are two ways you can do this

#### Core Library
Instead of using tabulator.min.js you can use tabulator_core.min.js which includes just the code needed to get the table to function.
You can then include any specific modules you like after this, then can be found in the `/dist/js/modules` folder.
```html
<script type="text/javascript" src="dist/js/tabulator_core.min.js"></script>
<script type="text/javascript" src="dist/js/modules/format.min.js"></script>
```

#### Custom Build
You can create your own custom build of Tabulator using Gulp.

You can choose which modules you want installed by adding/removing them from the `/src/js/modules_enabled.js file and running the ***gulp*** command.

Details of the various install options can be found in the [Install Documentation](http://tabulator.info/docs/4.0/install)

Let me know if you need any more info,

Cheers

Oli :)

**Comment by ilmari-lauhakangas** [comment]
How can one do this with the current Rollup based setup?

**Comment by olifolkerd** [comment]
@ilmari-lauhakangas you don't need to do anything custom to take advantage of the esm tree shaking , simply import the modules as per the docs. You need to make sure that your build tools support esm tree shaking otherwise you will not see the benefits

**Comment by ilmari-lauhakangas** [comment]
> @ilmari-lauhakangas you don't need to do anything custom to take advantage of the esm tree shaking , simply import the modules as per the docs. You need to make sure that your build tools support esm tree shaking otherwise you will not see the benefits

Thanks, but I don't understand why the bundle created by Rollup includes all the optional modules even though Rollup supports tree-shaking. Using the example from the docs, what Rollup command do I have to give to get a tree-shaked bundle?
