### ISSUE TITLE
Scrolling problems / glitches on iOS

### ISSUE THREAD

**Issue by methyl** [olifolkerd/tabulator#1451]
**Describe the bug**
When you scroll the table horizontally it glitches on iOS. The header is sometimes out of sync with table columns and you see a lot of flickering.

**Tabulator Info**
Examples on tabulator.info.

**To Reproduce**
1. Open http://tabulator.info/examples/4.0 on iOS
2. Scroll the tables 

**Expected behavior**
Consistent scrolling with no flickering.

**Video**
https://gfycat.com/NiceHauntingHoneycreeper

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 12
 - Browser Safari

**Comment by olifolkerd** [comment]
Hey @methyl 

Thanks for the detailed explanation.

That looks like an issue related to scroll bounce on mobile browser, it should be a quick fix with some CSS. i will include a fix in this weekends patch update.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @methyl 

Having looked into this further i can only fix this at the moment by disabling the momentum scrolling, which would make for a much less pleasant experience using the table on mobile devices.

when iOS implements the ***overscroll-behavior*** CSS property i will be able to correctly address the issue.

In the mean time i am going to leave it as is, because a small header misalignment during a scroll bounce is preferable to losing momentum scrolling on the lists.

Thanks for your feedback.

Oli :)

**Comment by rtman** [comment]
Hi @olifolkerd ,

I started testing tabulator on ios safari today and noticed the jitter is quite a lot more pronounced than on android chrome, is there any update to this issue? Are there any tabulator settings that can help to reduce this?

Thanks
