### ISSUE TITLE
CDN Links not working 

### ISSUE THREAD

**Issue by praseetht** [olifolkerd/tabulator#1459]
**CDN Links for 4.0.1 release not working**

**Tabulator Info**
- 4.0.1 
- http://tabulator.info/docs/4.0/install#sources-cdn

**To Reproduce**
`<link` href="https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.0.1/css/tabulator.min.css" rel="stylesheet">
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.0.1/js/tabulator.min.js"></script>
`

**Comment by olifolkerd** [comment]
Hey @praseetht 

I have raised an issue with CDNJS and they are currently looking into it, i will let you know as soon as it has been resolved.

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
Is there any progress here?:)

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

I have [Raised an Issue](https://github.com/cdnjs/cdnjs/issues/12963) with CDNJS but havn't heard anything back from them in over a week, which is very unlike them.

I would welcome it if anyone else wanted to either add to that issue or knew a more expedient way to resolve the problem.

They are usually very fast to respond, but they don't seem to be responding to any issues in the last week and their issues list seems to have been spammed by one of their bots so i don't know if they are having issues themselves. There is a pull request mechanic for updating CDNJS but i have no experience with it.

Im fairly certain the reason it has stopped working is because the NPM package has changed and because the structure of the `/dist` folder has changed which has caused issues in the past.

Unfortunately this is out of my hands at the moment, so im just waiting to hear back from CDNJS.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

I have switched CDN supplier to UNPKG so you can now access the files you need with the following links

```js
<link href="https://unpkg.com/tabulator-tables@4.0.4/dist/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.0.4/dist/js/tabulator.min.js"></script>
```

Thanks for your patience.

Cheers

Oli :)
