### ISSUE TITLE
Question about the popularity of this library

### ISSUE THREAD

**Issue by kasajian** [olifolkerd/tabulator#1467]
I would post this on stackoverflow if my question were allowed to be asked on stackoverflow, but it's not because I don't have a specific technical question, and stackoverflow is not a "discussion forum"

I want to know why his this component not more popular on npm.    It got 77 downloads per week.  react-table has 69K downloads per week.  react-virtualized has 143K downloads per week.

I'm pretty good with react.  I tried both of those other solutions and got things to work after about 3 to 4 hours.

With tabulator, it took me literally 5 minutes.

Tabulator seems to have some affinity to jquery and is currently making a big deal about the fact that it no longer needs it.  That's good.  The fact that that's a statement being made in 2018, to me, means that may be Tabulator was just ignored because it's part of the jquery wave of components -- very powerful and amazing, but last-generation.   An interestingly, I don't see the words "reactjs" or anything like that in any of the docs -- seems like the sea of programmers wanting to use it with angularjs or reactjs are on their own.

Yet, the Tabulator product has amazing, high-quality documentation, compared to comparable packages, and one of the easiest to "grok" and use quickly, never-mind the amazingly rich set of features.

So what's the deal?  Not enough marketing?

I bet a ReactJs version was released, the number of downloads per week would increase by at least two orders of magnitude.

**Comment by olifolkerd** [comment]
Hey @kasajian 

Thanks for getting in touch and thanks for your kind words

That is because tabulator has just changed package names. it used to be called jquery.tabulator [Old Package](https://www.npmjs.com/package/jquery.tabulator)

which as you can see has had tons of downloads. but as i just removed jquery a new package name was needed.

Tabulator has 1000's of users across NPM, CNDJS and a number of other sources.

Of course if you want to spread the word of Tabulator please do :)

Cheers

Oli

**Comment by kasajian** [comment]
Thank you, but I do have another question -- it's hard to explain, so I created a video asking the question -- https://youtu.be/sXHB0-3ZMZ4

It's about the Driver column in Editable Data.

**Comment by ngduc** [comment]
I agree. tabulator is a great table library. This is the React version of tabulator
https://github.com/ngduc/react-tabulator
Any PR is welcome. Thanks.

**Comment by olifolkerd** [comment]
Hey @ngduc 

Thanks for your kind words, and thanks for the react wrapper that looks great!

Would you mind me linking to your wrapper from the Tabulator website?

A quick bit of feedback for you, i notice that you instantiate the table by using a randomly generated id, you can also pass in the DOM node for the div directly into that argument instead of the selector, which might be a more durable approach.

Thanks again

Oli :)

**Comment by ngduc** [comment]
@olifolkerd it will be great if you link it there. Thanks.

Passing a DOM node is a good idea, I'll do that tonight. Random id is still useful though if user wants multiple table instances.

p/s: I used adazzle/react-data-grid before but I feel that this is a better table library (great features: auto fit, virtualization, col grouping, nesting table, etc.). A small issue I found on mobile, I can't edit cells with tabulator. (will report it separately)

**Comment by ngduc** [comment]
wonder if you have a few mins to review [react-tabulator](https://github.com/ngduc/react-tabulator) @olifolkerd ?
later on, in your repo, I'll open some PR to create some custom cell editor & style the default theme a bit, is that ok to make it look more modern? :]

**Comment by olifolkerd** [comment]
Hey @ngduc 

Thanks for adding me as a contributor, much appreciated. 

You will be happy to hear i have included the react-native compnent in the docs: http://localhost:8080/docs/4.0/frameworks#angular

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @ngduc 

I have just created an issue for you #1513 to talk about some new built in editors if you were interested in contributing some code?

Cheers

Oli :)
