### ISSUE TITLE
Ajax post sending params - repeated requests

### ISSUE THREAD

**Issue by tomvanlier** [olifolkerd/tabulator#1469]
**Describe the bug**

It seems that tabulator cannot send post data as in the example included, or I am doing something wrong.

**Tabulator Info**
Version 4.0

    ajaxURL:"http://www.getmydata.com/now", //ajax URL
    ajaxParams:{key1:"value1"}, //ajax parameters
    ajaxConfig:"POST", //ajax HTTP request type

If I omit the ajaxconfig and perform a GET-request, I catch the sent data perfectly in my php-script with 

    $var1 = mysqli_real_escape_string($connection,$_GET[key1]);

The query after then performs perfectly.

If I however put a post-request there, and change the get to post serverside, it does not work. Analyzing this with chrome dev tools,  I found that the request payload contained a json-object of my key/value pair. I am able to catch the data there, adding

    $content = file_get_contents("php://input");
    $var1 = json_decode($content);    

 and then accessing the php array. So the data is sent, it just comes there harder to handle

**Expected behavior**

Same as with get.

**Additional context**

Sorry if it's me doing something wrong :) or expecting something that was not meant. I've searched stack overflow for this issue, but couldn't find it and maybe it's a bug, maybe not ...

**Comment by olifolkerd** [comment]
Hey @tomvanlier 

Thanks for getting in touch,

That was because the modern approach is to send things as JSON data in POST, but i agree that it is not consistent with the GET behaviour so i have just pushed an update to the master branch to make it use post data like the get request.

I will include it in tonight's update, and will include in a latter release the ability to chose the data encoding format for requests.

Thanks for your feedback.

Cheers

Oli :)
