### ISSUE TITLE
Why does check box transition styles and require two clicks instead of one?

### ISSUE THREAD

**Issue by kasajian** [olifolkerd/tabulator#1477]
This one's a little hard to explain, but I think this may be a bug.  There's a workaround which is to toggle in the app when the user clicks on the cell, but why?

The problem is hard to explain, so I created a video asking the question -- https://youtu.be/sXHB0-3ZMZ4

It's about the Driver column in Editable Data.

**Comment by olifolkerd** [comment]
Hey @kasajian 

Thanks for getting in touch,

That is because there is a difference between the tick formatter which makes the green arrow and the tick editor which is a checkbox style input element.

If you would like to be able to toggle the tick without the input element you just need to use the following code in the cellClick event for that column instead of the editor:

```js
{title:"Can Drive", field:"drives", cellClick:function(e, cell){
    //e - the click event object
    //cell - cell component
        cell.setValue(!cell.getValue());
    },
}
```

Cheers

Oli :)

**Comment by kasajian** [comment]
Thank you, but shouldn't the example on the web site show the right thing?    It's not correct currently, right?
