### ISSUE TITLE
Migrating from 3.5 to 4.0.4 causes typeerror

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1478]
**Describe the bug**
Migrated from 3.5 to 4.0.4 
I use the jquery wrapper.

**Tabulator Info**
4.0.4
Multiple tables with a lot of code, makes it hard to reproduce and for me to debug what exact function fails.

Has this been seen before? Is there some kind of bug in the wrapper that returns the wrong type?
Or am I doing something completely wrong?

![bug](https://user-images.githubusercontent.com/11444201/46465558-3963dd00-c7c9-11e8-8bfe-5d7932b69ce4.png)

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

Could you run it using tabulator.js instead of tabulator.min.js and let me know the line number it errors on, i can track it back from that.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

Another thought on that error, if you are migrating 3.5 to 4.0 you need to make sure that any of the callbacks you are using that used to accept jQuery obects as return values (such as editors and formatters) now return a DOM node instead. as that is likely the root cause of the error.

It is really simple to do, if this was your original code:
```js
var customEditor = function(cell, onRendered, success, cancel){
	var editor = $("<input></input>");
	return editor;
}
```

Then this is the replacement:
```js
var customEditor = function(cell, onRendered, success, cancel){
	var editor = $("<input></input>");
	return editor[0];
}
```

I hope that help,

Let me know how you get on,

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
You were correct.
My problem was the footer that I added to my tabulator table object in the constructor.

> Worked in 3.5:

`footerElement: $("<div class='tabulator-footer'></div>")`

Solution:

> 4.0 compatible by appending [0]

`footerElement: $("<div class='tabulator-footer'></div>")[0]`
