### ISSUE TITLE
Inserted DOM elements into rows and sorting

### ISSUE THREAD

**Issue by Keyframe** [olifolkerd/tabulator#1484]
**Describe the bug**
I'm not sure if this is a bug, or just a 'feature' of the DOM. I've inserted some stuff (divs) into rows (I'm using row formatter). Later on, during the page rendering, I have appendChild more stuff to it - everything in order to get what I want, obviously. Everything is working alright, until I use sorting (possibly filtering as well, but haven't tested that yet). What happens is that new/added stuff is gone, and everything is rendered anew as if I haven't done any appendChild to it. Question here is, should this happen and if yes, is there a way to preserve functionality while appending stuff to rows? 

**Tabulator Info**
- 4.0.4

To make it more clear of what I'm doing. I have several nested tables per row, some of which have nested tables too. I wanted a common header for those nested tables in order to have them collapsed, like groups in tabulator. Not to show everything at once. Since I haven't found that feature in tabulator, I've wrapped all of them into a div which does that. It works great, I can sort nested tables just fine, but it's not working if I sort (per column) the parent table, of course.

**Comment by olifolkerd** [comment]
Hey @Keyframe 

Thanks for getting in touch. 

The only safe place to make additions to table elements is inside a formatter function, either the ***rowFormatter*** or the ***formatter*** property of a column definition. if you make changes anywhere else then there is a good chance that the changes will be lost when the table is regenerated.

The reason for this is Tabulators virtual DOM. To allow Tabulator to handle 1000's of rows of data without a loss of performance it only renders the rows that are visible, as you scroll through the table (or sort or filter it) the rows are dynamically created and destroyed as the become visible/scroll out of view. This is because creating 1000's of DOM elements for a big table would take a Huge amount of time and freeze the website while it is happening, so Tabulator only does it when it is needed.

There are lots of events that can trigger a redraw so it is not safe to manipulate data outside of a formatter.

If you have a specific thing you are trying to achieve let me know and i can suggest how to setup the formatter correctly.

Cheers

Oli :)

**Comment by Keyframe** [comment]
I figured it was a stupid thing to do, but had to ask just to be sure. I'm wrapping nested tables into a div for collapse/show, because by default it's too much info to show to user (several nested tables per row, lots of fields...). I can and will do that within a rowFormatter then.

Groups have this behaviour already, but you have to group by something, and I don't have anything to group by. It would be maybe nice, in the future, to offer the same functionality but without grouping by something.
