### ISSUE TITLE
Unchanged edits considered cancelling

### ISSUE THREAD

**Issue by Jeerachee** [olifolkerd/tabulator#1488]
I'm trying to create an "edit mode" with tabulator where when one of the cells is double clicked, the entire table becomes editable so that tab/arrows/etc. allow for maneuvering about the table, and then goes back to a "selectable" state when editing is cancelled, which works fine by using **cellDblClick** for entering the edit mode, **editable** for detecting the edit mode, and **cellEditCancelled** for exiting the edit mode. Unfortunately though, I can't find a way to detect when an edit is "cancelled" by pressing enter without changing the cell data. It works great for clicking/tabbing/esc'ing out of the table/cell/etc, but I can't even try to detect it otherwise with the **cellEdited** and **dataEdited** callbacks, as they don't fire when the data isn't changed, which makes sense seeing as nothing was edited. 

I propose that pressing enter/submitting changes during cell editing without changing the data should be considered a cancelled edit, seeing as it's not considered an edit in regards to calling the **cellEdited** and **dataEdited** callbacks

**Comment by Jeerachee** [comment]
I was able to get around this by attaching a keydown event listener on the **cellEditing** callback to the cell's element and handle the enter key accordingly, but it feels a bit hacky

**Comment by olifolkerd** [comment]
Hey @Jeerachee 

As long as you define editors on the table it is already editable and navigatable with the keyboard.

If you are looking to lock out editing on the table until it is explicitly enabled, then you can pass a function to the ***editable*** property of the column definition that would check some global variable before allowing an edit:

```js
//define global editable variable
var canEdit = false;

//define edit checker
var editCheck = function(cell){
    //cell - the cell component for the editable cell
    
   return canEdit ;
}

//in your column definition for the column
{title:"Name", field:"name", editor:"input", editable:editCheck}
```

The editors call cancel by design because the value has not changed at that point so no edit has occurred and no data needs to be updated. You are of course welcome to make your own [Custom Editors](http://tabulator.info/docs/4.0/edit#edit-custom) that do not behave this way if you have a specific need for that functionality.

Cheers

Oli :)
