### ISSUE TITLE
Allow resizing columns but let the last column be responsive

### ISSUE THREAD

**Issue by ngduc** [olifolkerd/tabulator#1506]
**Describe the bug**

I tried different layouts: fitDataFill, firColumns & widthGrow and widthShrink but the last column still moves when resizing other columns. Ultimately I need the last column be responsive when resizing columns.

**Tabulator Info**
- Which version of Tabulator are you using? 4.0.x
- Post a copy of your construct object if possible so we can see how your table is setup

**To Reproduce**
![image](https://user-images.githubusercontent.com/639189/46997136-c5cca480-d0d3-11e8-81ee-812f83c0de2a.png)

**Expected behavior**
The last column should be responsive when resizing other columns.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

Thanks!

(Edit: I removed the JSFiddler link because it also moves the last column, which is not desireable)

**Comment by olifolkerd** [comment]
Hey @ngduc 

Thanks for the info, i would consider this a new feature rather than a bug, it is just another way to lay out the table. 

The fitColumns layout is designed to fit data to the table where possible and allow it to overflow when it is bigger than the table, which when the column resizes is the case. Which is a mode of operation used by a lot of users.

I can certainly see where this version could be useful so i will stick it on the roadmap for a future version.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @ngduc 

I have just pushed an update for this to the 4.5 branch that will be released in the next few weeks.

There will be a new ***fitDataStretch*** layout mode that will stretch the last column to fill the width of the table.

Cheers

Oli :)
