### ISSUE TITLE
Tabulator throwing error saying "Object doesn't support property or method 'forEach'"

### ISSUE THREAD

**Issue by shambu-ho** [olifolkerd/tabulator#1522]
**Describe the bug**
When opening tabulator in microsoft edge , it is throwing error saying forEach method not supported. The offending line of code in from tabulator.min.js

**Tabulator Info**
- Which version of Tabulator are you using?4.0.5

**To Reproduce**
1. open the a tabulator table in microsoft edge 
version - Microsoft Edge 38.14393.2068.0
Microsoft EdgeHTML 14.1439
2. Table doesn't get populated with data and instead it throws error saying method forEach not supported by Object

**Expected behavior**
Table should be displayed.

**Desktop (please complete the following information):**
 - Windows 10
 - Browser 
Microsoft Edge 38.14393.2068.0
Microsoft EdgeHTML 14.1439

**Comment by olifolkerd** [comment]
Hey @shambu-ho 

Sorry to hear you are having issues, could you post a copy of your table constructor so i can see how your table is setup so i can replicate the issue.

Cheers

Oli :)

**Comment by aklaver** [comment]
I just ran across that and it turned out the issue was that I was sending Tabulator a single JSON object and not an array with a single object. So {} instead of [{}]. forEach() is an array method not an object one.

**Comment by olifolkerd** [comment]
Hey @shambu-ho 

It is not your data that i am after, i just need to understand how your columns/table are setup so i can replicate the issue more precisely, could you send your table constructor object (the object you pass in when you call `new Tabulator`), feel free to remove titles and field names if that make it sufficiently anonimous for you.  Otherwise it is really hard to know what has been provided to Tabulator to trigger that error.

Cheers

Oli :)
