### ISSUE TITLE
Odd scroll issues inside flexbox (no scroll wheel or missing scroll bar)

### ISSUE THREAD

**Issue by c-dante** [olifolkerd/tabulator#1535]
**Describe the bug**
When the table is nested in a flex box and virutal dom is ON, I get no scroll wheel interaction.
When virutal dom is OFF, I get no scroll bar at all (?)

Fiddle: http://jsfiddle.net/ny54qgfe/54/

This is using the simple css layout. but also happens without it.
Simple patch is to wrap the table in an extra div -- as a direct flex child, lots of weird scroll interactions break.

**Tabulator Info**
4.0
```jd
{
  index: 'row-id',
  // odd results when toggling these on/off with regard to scroll functionality
  layout: 'fitColumns',
  columnVertAlign: 'bottom',
  height: '100%',
  // Toggle virtual dom off breaks scoll
  /* virtualDom: false, */
}
```

**Expected behavior**
Functional scrolling within a flexbox.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chrome. Version 71.0.3578.10 (Official Build) dev (64-bit)

**Comment by olifolkerd** [comment]
Hey @c-dante 

Your example is working fine in my browser, scroll bar and all. do you have a screenshot of what you are experiencing?

Cheers

Oli :)

**Comment by c-dante** [comment]
Sure -- I can't screen shot my scroll wheel not working (but that's, as you said, probably a personal issue).

If I disable the virtual dom in that example, the scroll bar is no longer there:
![image](https://user-images.githubusercontent.com/6332726/47591463-b05e4280-d93d-11e8-80d3-efd55ac73500.png)

```js
const table = new Tabulator('#table-here', {
  index: 'row-id',
  layout: 'fitColumns',
  columnVertAlign: 'bottom',
  height: '100%',
  // Toggle virtual dom off
  virtualDom: false,
});
```

**Comment by olifolkerd** [comment]
If you disable the Virtual DOM there will be no scroll bar

At that point the table looses all shiney UI functionality and acts as a simple HTML table it is up to the containing element how it handles that. without the Virutal DOM I would suggest that you do not set a height on your table as that is probably where the issue lies.

As for a lack of scroll wheel functionality when the Virtual DOM is on i don't know what to say there, the fiddle you have posted is working fine in chrome on my computer :(

**Comment by c-dante** [comment]
Sure sure, no problems there.

I have a page that is using virtual dom AND has no scrollbar (many nested flexbox and angular directives possibly mucking up the DOM), I'll see what I can do about getting a fiddle for that exact case. I'll close this for now and possibly re-open it if I can get something reproducible to you

**Comment by olifolkerd** [comment]
Ahh that might be a unique interaction with angular there.

So Tabulator only knows how to layout the table when it is visible (hidden DOM elements have no dimensions so Tabulator cant do the math). Tabulator listens for the ***resize*** event on the document in all browsers, and in chrome also uses a ***ResizeObserver*** to determine when it is visible/changes size to trigger a redraw of the DOM.

It may be that angular is somehow preventing this detectin from working. if that is the case you just need to call the ***redraw*** function on the table when it is in its new size/visible and it should sor itself out.

I hope that helps

Cheers

Oli :)

**Comment by c-dante** [comment]
One thing I did notice is that I was getting a chrome exception when I have `virtualDom` enabled AND `height` set -- `ResizeObserver loop limit exceeded` error gets thrown to the window.  That _might_ muck up the rendering, unsure.

I've played around with requesting animation frames, timeouts, and my own listening for the DOM.

It's definitely building the table while it's positioned and has a box size. I'll be digging more on my end and doing whatever workarounds I need. I also want to try and get a fiddle up showing that.

**Comment by olifolkerd** [comment]
Right, so that is definitely angular or the flex layout (or both) confusing the resize observer, ***ResizeObservers*** are an ES8 feature and currently only available in chrome so it entirely understandable that it might be causing issue.

calling the ***redraw*** function on the table once it has been resized will fix the layout issues you are experiencing, you just need to find a suitable resize to handle it.

You can disable table auto resizing using the ***autoResize*** property:
```js
var table = new Tabulator("#example-table", {
    autoResize:false, // prevent auto resizing of table
});
```

and then implement something more compatible with the the environment the table is in.

I hope that helps, let me know how you get on, i would be interested to see the results.

Cheers

Oli :)

**Comment by c-dante** [comment]
Okay, updated a fiddle with the crazy flexbox nesting I have.

http://jsfiddle.net/ny54qgfe/83/

When it's that many layers deep of flexbox, I can't seem to get the virtual dom scrolling to work.
If the virtual dom is off, do you get fixed column headers? As in, rows scroll beneath the table header?
