### ISSUE TITLE
Numeric value edits do not differentiate between '' and 0

### ISSUE THREAD

**Issue by c-dante** [olifolkerd/tabulator#1543]
**Describe the bug**
The default editor does not differentiate between "0" and ""

https://github.com/olifolkerd/tabulator/blob/37374df0af1a6ad8d7c15b79ba60e07727a62b1d/src/js/modules/edit.js#L284-L290

Can we change all of these to be strict equality? `!==`? That way it's up to the callback to decide what to do if the value and cell are falsy, but not strict.

**Tabulator Info**
- 4.0.5

**Comment by olifolkerd** [comment]
Hey @c-dante 

Thanks for your feedback.

Sadly it is not as simple as that, because an input element cannot correctly handle null or undefined values the comparison does need to be falsey, but i will add some additional functionality to help with that particular edge case in the 4.1 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have just pushed this change to the 4.1 branch and will include it in tommorows release
