### ISSUE TITLE
Tables not updating on loading in mobile devices

### ISSUE THREAD

**Issue by charlesfrisbee** [olifolkerd/tabulator#1557]
**Describe the bug**
On load my app constructs a few Tabulator tables, and has an Ajax data loader within the constructor.

When I run this app on Google Chrome desktop, the tables are shown correctly constructed with the data in there. On iPhone/iPad Safari/Google Chrome, the tables are correctly constructed in terms of column layout but are empty. They require me to click on the table header in order the show the data. This problem is only at page load as all further setData() calls work as expected following page load.

I have also tried constructing the table without the intrinsic ajax data loader, and loading data at runtime with the setData function, which also showed the same results. Adding static data via the data: [] call within the constructor also made no difference.

**Tabulator Info**
- Tabulator 4.1 

**To Reproduce**
1. Construct table with the below constructor
2. Add data to table via the _setData()_ function (if constructor doesn't include ajax data loader) 
3. On load on mobile devices, tables are shown constructed correctly but with no data

**Tabulator constructor**
            var project_staff_table = $("#project-staff-table").tabulator({
                height: "300px",
                fitColumns: true,
                columns: [
                    { title: "ID", field: "ID", sorter: "string", width: 150, editor: "input", visible: false },
                    { title: "Initials", field: "intials", sorter: "string", width: 150, editor: "input", visible: false },
                    { title: "Name", field: "name", sorter: "string", width: 150},
                    { title: "Level", field: "level", sorter: "date", width: 150 }
                ],
                index: "ID",
                ajaxURL: 'Main.aspx/Get_project_staff', //ajax URL
                ajaxConfig: "POST", //ajax HTTP request type
                ajaxParams:{project_number:"00000"}, //ajax parameter
                ajaxContentType: "json", // send parameters to the server as a JSON encoded string
                ajaxResponse: function (url, params, response) {
                    return JSON.parse(response.d); //pass the data array into Tabulator
                },
            });

**Expected behavior**
I expect the table to be shown with their data as set in the setData function

**Screenshots**
I have shown three tables but the same problem persists for however many tables:

![image](https://user-images.githubusercontent.com/32081962/48032505-fcb24980-e1ab-11e8-86c1-785efafad342.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome version 70.0.3538.75

**Smartphone (please complete the following information):**
 - Device: iPhone 6/iPad Pro
 - OS: 12.1/12.1 (have also tried on older iphone version 11.1)
 - Browser Safari/Google Chrome
 - Version: 5/70.0.3538.75

Please let me know if you need any more information to recreate this, thanks.

**Comment by olifolkerd** [comment]
Hey @charlesfrisbee 

I am unable to replicate this bug, tables seem to load fine on an iPad for me. could you try a blank HTML page with just one table on it and see if that data loads correctly for you?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @charlesfrisbee 

Glad to hear you found the issue.

If your desktop browser is Chrome then that is not surprising at all. let me give you a bit of technical detail on Tabulator so you know for future.

DOM elements only have dimensions once they are first made visible, which means that Tabulator does not know how to layout itself when it is hidden (inside an accordion for example), which is why the docs encourage people to call the ***redraw*** function when an element is made visible.

Tabulator watches the window for resize events and automatically redraws itself if the window changes size, but due to limitations on most browsers it can only know if the window was resized, not if the table itself has been resized. This all changed when ES8 introduced the ***ResizeObserver*** this allows any DOM object to know if it is resized, and at the moment it is only available in Chrome. Tabulator uses this observer when it is present as it means the table always knows when it needs to be redrawn. In this case when it goes from hidden in the accordion to being visible, the element gains dimensions and the redraw is triggered.

Cheers

Oli  :)
