### ISSUE TITLE
Make select editor great again

### ISSUE THREAD

**Issue by Keyframe** [olifolkerd/tabulator#1584]
Please consider re-introducing classic dropdown back into tabulator: https://github.com/olifolkerd/tabulator/commit/be9896e5c0f7ccf5490607106e2d66d15d4de5e3

It's a standard input, and you can easily add it back. No need for us (users) to carry around editor that is basically a standard input. You can call it selectClassic or something even without clashing with the new changes. New one might be a good idea eventually, but it's not working really well UX-wise. It's not filtering text (from dropdown) as you type, it isn't pre-selecting what you have selected before, and it's not a standard input.

**Comment by olifolkerd** [comment]
Hey @Keyframe 

Thanks for getting in touch.

The select editor was replaced for a number of reasons:

- Due to browser security restrictions it was impossible to open the list directly, it needed to be taped a second time to open, which was inconsistent with other editors
- Users wanted the ability to select multiple items at a time from a select, which is not possible on a select element, a feature that is coming in the next release to the new select element
- It was not possible to style the list that heavily

The new select editor has had very good feedback from the user base and will be kept as it is and improved going forward.

In response your points:

- If you want to be filtering items in the list as you type, you should look at the new ***autocomplete*** editor that does exactly that
- It most certainly should select your previous value, if you have a look at the [Editors Example](http://tabulator.info/examples/4.1#editable) the gender column uses the new select editor and keeps the previous value, if this is not the case for you if you post your code i would be happy to offer advice on how to resolve it.
- It uses a standard input element to capture user data entry, no editor in tabulator has to be a standard element (in fact most of them arn't) and in this case there is more benefit to moving away from it than there is staying with the old element. 

If there are features you feel are missing from the new editor i would be happy to add the to the roadmap for inclusion in a later version.

For those reasons i would not be looking to include the old select editor in Tabulator. That being said, it would be really easy for you to put it back in yourself, as Tabulator already comes with the ability to extend modules.

In this case you would need to include the following code after you pull in the Tabulator source files, but before you instantiate your first table:

```js
Tabulator.prototype.extendModule("edit", "editors", {
	selectClassic : function (cell, onRendered, success, cancel, editorParams) {
		//create and style select
		var select = document.createElement("select");
		var isArray = Array.isArray(editorParams);

		if(typeof editorParams == "function"){
			editorParams = editorParams(cell);
			isArray = Array.isArray(editorParams);
		}

		function optionAppend(element, label, value, disabled){

			var option = document.createElement("option");

			option.value = value;
			option.text = label;

			if(disabled){
				option.disabled = true;
			}

			element.appendChild(option);
		}

		function processOption(element, option){
			var groupEl;

			if(option.options){
				groupEl = document.createElement("optgroup");

				groupEl.setAttribute("lavel", option.label);

				option.options.forEach(function(item){
					processOption(groupEl, item);
				});

				element.appendChild(groupEl);
			}else{
				optionAppend(element, typeof option.label == "undefined" ? option.value : option.label,  typeof option.value == "undefined" ? option.label : option.value, option.disabled);
			}
		}

		if(!isArray && typeof editorParams === "object"){
			for(var key in editorParams){
				optionAppend(select, editorParams[key], key)
			}
		}else if (isArray){
			editorParams.forEach(function(item){
				processOption(select, item);
			});
		}

		//create and style input
		select.style.padding = "4px";
		select.style.width = "100%";
		select.style.boxSizing = "border-box";
		select.style.fontFamily = "";

		select.value = cell.getValue();

		onRendered(function () {
			select.focus();
		});

		//submit new value on blur
		function onChange(e) {
			if(select.selectedIndex > -1){
				success(select.options[select.selectedIndex].value);
			}else{
				cancel();
			}
		}

		select.addEventListener("change", onChange);
		select.addEventListener("blur", onChange);

		//submit new value on enter
		select.addEventListener("keydown", function (e) {
			if (e.keyCode === 13) {
				success(select.options[select.selectedIndex].value);
			}
		});
		return select;
	},
});
```

You could then access it in any column defintion as:
```js
{title:"Favourite Color", field:"col", editor:"selectClassic "},
```

Thanks for your feedback,

Cheers

Oli :)

**Comment by Keyframe** [comment]
I really appreciate your response. I see the reasoning now behind it and am looking forward to multi-select feature (optional, I hope)! I'll test some more to see what's causing the issue with pre-selection not functioning in my case (It's a large list of all of the countries), since it obviously works in the example. 

Thanks again
