### ISSUE TITLE
multiple custom filters don't work with binded functions

### ISSUE THREAD

**Issue by susdu** [olifolkerd/tabulator#1591]
I'm trying to use multiple custom filters and passing each one different data along with shared parameters for all filters.

This works:

```
table.addFilter(customFilter.bind(var1), params);
table.addFilter(customFilter.bind(var2), params);
table.addFilter(customFilter.bind(var3), params);
```

This doesn't:
```
table.setFilter([
    customFilter.bind(var1), customFilter.bind(var2), customFilter.bind(var3)
], params);
```

This also affects the callbacks, I want to apply multiple custom filters at one go and get one dataFiltered callback, this way I get a cb per call.

**Comment by olifolkerd** [comment]
Hey @susdu,

The ***setFilter*** function is designed to either take a single filter with three arguments, or an array of filter config objects passed into the first argument only. Your current use of the function is neither of these, which is why it isn't working.

In your case you will need to slightly misuse the filter object structure:
```js
table.setFilter([
    {field:customFilter.bind(var1), type:params},
    {field:customFilter.bind(var2), type:params},
    {field:customFilter.bind(var3), type:params},
]);
```

I hope that helps,

Cheers

Oli :)

**Comment by susdu** [comment]
Thanks for clearing things up, amazing library!
