### ISSUE TITLE
Other option for cellclick when field has dropdown

### ISSUE THREAD

**Issue by pPratik7** [olifolkerd/tabulator#1593]
Hello,
We can use cellClick function in tabulator but if cell contains dropdown editor like... 
{
title: "Gender", field: "gender", width: 100, editor: "select", align: "center", editorParams: {
                                        "male": "male",
                                        "female": "female",
}, 
},

how do i get to know selected value...because cellclick does not allow me to select from dropdown...is there any function...please let me know

Thanks,
pp

**Comment by olifolkerd** [comment]
Hey @pPratik7 

You should be using the ***cellEdited*** callback which is called whenever a cell is editied. you can either listen to it on  a specific column definition:

```js
{title:"Name", field:"name", cellEdited:function(cell){
    //cell - cell component
    var newVal = cell.getValue();
    },
}
```

Or on the table as a whole:
```js
var table = new Tabulator("#example-table", {
    cellEdited:function(cell){
    //cell - cell component
    var newVal = cell.getValue();
    },
});
```

I hope that helps,

Cheers

Oli :)

**Comment by pPratik7** [comment]
thank you for your quick reply

**Comment by rs199483** [comment]
@olifolkerd Is there a way to get the "value" of the select?  So in the below case I would want "1" instead of "male" in the cellEdited function.  Seems like there should be an event for selecting an option in the dropdown where i can retrieve the label and/or the value.  Thanks

{
title: "Gender", field: "gender", width: 100, editor: "select", align: "center", editorParams: {
"male": "1",
"female": "2",
},
},
