### ISSUE TITLE
variableHeight not working (minimal example)

### ISSUE THREAD

**Issue by mestaritonttu** [olifolkerd/tabulator#1614]
**Describe the bug**
variableHeight:true is not taking effect in the most minimal example possible.

**Tabulator Info**
Version 4.1.3. Same result with 3.2 and 3.5 (tested to check, if it would have been a regression).

**To Reproduce**
See https://codepen.io/anon/pen/NEobod
I also tried using it with a custom formatter as that is the exact context of the docs, but same result.
Firefox, Chrome and Edge all give the same result.

**Comment by olifolkerd** [comment]
Hey @mestaritonttu 

That is because you are using the property on  the default text formtter which is not designed to be multi-line. 

In this case you want to be using the ***textarea*** formatter, which is designed to display multi-line text:

```js
{title:"Name", field:"name", formatter:"textarea"},
```

The ***variableHeight*** option is not there to force a formatter to be multi-line, it should be used to let Tabulator know that a custom formatter you have built will vary in height if it is resized and should be regenerated on a width change, if the formatter is not designed to change height it will do nothing.

I hope that clears things up.

Cheers

Oli :)

**Comment by mestaritonttu** [comment]
Aah, thanks a lot! *goes looking at modules/format.js* So I just steal what textarea is doing - and it was so simple: just white-space: pre-wrap style!

```
formatter: function (cell) {
                                cell.getElement().style.whiteSpace = "pre-wrap";
                                return (cell.getValue());
                            }
```
I had used ag-Grid before and it was such a pain on this front :)
Maybe it could be somehow mentioned in [the docs](http://tabulator.info/docs/4.1/format#format-height)?

**Comment by olifolkerd** [comment]
Hey @mestaritonttu 

While the "pre-wrap" allows the carriage return that will only help you on first render, if you resize the column without using the ***variableHeight*** option it will not vertically resize the row to fit it all in.

The ***textarea*** formatter is an exception to this, because it is a built in formatter and Tabulator knows it is multiline it sets the ***variableHeight*** property for you so you don't need to.

There is already a section that covers the use of the ***textarea*** formatter and the ***variableHeight*** property in the [documentation](http://tabulator.info/docs/4.1/format#format-height)

Cheers

Oli :)

**Comment by mestaritonttu** [comment]
Sure, but the current docs lead me to believe I **only** need variableHeight. There is no mention of having to set pre-wrap in my custom formatter and that threw me off.

**Comment by mestaritonttu** [comment]
Yep, I know the inner workings of CSS quite well and I did run into the topic of images affecting the height. Yet, the docs did not convey the essence of the matter, while your answer to my issue was perfect:

> it should be used to let Tabulator know that a custom formatter you have built will vary in height if it is resized and should be regenerated on a width change, if the formatter is not designed to change height it will do nothing
