### ISSUE TITLE
values:true doesn't populate Select dropdown

### ISSUE THREAD

**Issue by RyberNL** [olifolkerd/tabulator#1620]
**Describe the bug**
_{title:"Example", field:"example", editor:"select", editorParams:{values:true}_ Doesn't populate the Select dropdown. The Select dropdown also doesn't appear. Editor remains to be an input field.
**Console log:** 
DEPRECATION WANRING - values for the select editor must now be passed into the values property of the editorParams object, not as the editorParams object
- I have tried values:true and the code snippet in the Tabulator docs (http://tabulator.info/docs/4.1/edit)

**Tabulator Info**
- Which version of Tabulator are you using? 4.1.3 - Latest from Github
- Code snippet: {title:"Manufacturer", field:"manufacturer", width:200, align:"center", headerFilter:"select", headerFilterPlaceholder:"Enter manufacturer..", editor:"select", editorParams:{values:true}, cellEdited:function(cell){$AJAXCALL}

**Expected behavior**
I would expect a select dropdown to appear and to populate with all available options in my column.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 70

**Comment by olifolkerd** [comment]
Hey @RyberNL 

Sorry to hear you are having trouble.

When i test using that config it all works fine this end,

You are getting the deprecation warning not because of the editor, but because of the header filter, if you want that to also pull in the values from the column you need to set its values to:
```js
headerFilterParams:{values:true}
```

The warning message is showing in error if no params are set, an issue i will fix in this weekends patch release.

As for why your editor isnt working, im afraid it seems to work fine my end. Would you be able to post your full table constructor so i can see how your table is configured or better yet create a [JS Fiddle](https://jsfiddle.net/) showing the issue in action.

Cheers

Oli :)

**Comment by RyberNL** [comment]
Thanks for the super quick reply @olifolkerd 

Setting headerFilterParams:{values:true} fixed my deprecation error, however it is duplicating behavior of the Editor, still showing an input field and no dropdown.
![image](https://user-images.githubusercontent.com/295943/49431079-e9939900-f7ac-11e8-9e94-f3c004e7ac48.png)

Theme is a lightly customized Semantic-UI

Fiddle of my table constructor: https://jsfiddle.net/8bL9x41d/
(I have removed all custom functions for privacy reasons)

**Comment by olifolkerd** [comment]
Hey @RyberNL 

Thanks for that, your js fiddle dosnt appear to be working, i dont think you have created a div for the table, or passed in some sample data.

It will be hard to fix unless i can see this issue in action.

Cheers

Oli :)

**Comment by RyberNL** [comment]
You are correct. It is a CSS issue! Removing the Semantic-UI css messes up my layout but shows the options being rendered in the background.

Thank you Oli!

**Comment by olifolkerd** [comment]
OK,

Leave it with me there have been a couple of CSS issues with the new select editor on some of the themes, im doing a patch release this weekend that should address the issue.

Thanks for the information.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey All,

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)
