### ISSUE TITLE
scrolling does not work

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1629]
**Describe the bug**
Scrolling with mouse wheel does not work when I am in top of the table:
![__](https://user-images.githubusercontent.com/799021/49652772-af8bf680-fa3b-11e8-8d12-fe2b02be3321.jpg)

**Tabulator Info**
- Which version of Tabulator are you using? 4.1.3
- Post a copy of your construct object if possible so we can see how your table is setup
```
<link href="/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="/js/tabulator.min.js"></script>

<div id="example-table"></div>

<script type="text/javascript">
	var table = new Tabulator("#example-table", {
		height: "25rem",
		ajaxURL: "/config",
		columns: [
			{ title: "id", field: "id" },
			{ title: "docn", field: "docn" },
		],
	});
</script>
```

The returned count of objects is 2959

**To Reproduce**
1. When data is loaded try to scroll (nothing is happened)
second variant:
1. drag vertical scroll bar with mouse
2. rotate mouse wheel (scroll) forward, thus we are scrolled to top (first record)
3. When we are in top try to scroll backward to bottom (last record). Nothing is happened

**Expected behavior**
Scroll should work

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser FireFox 
 - Version v61.0.1

**Additional context**
scrolling on this page works fine
http://tabulator.info/examples/4.1

**Comment by KES777** [comment]
Here I make screencast. I try to scroll with mouse wheel extensively.
In the top nothing is happened. In the bottom I must do much scrolling until one record is scrolled.
After I press F12 everything works fine.
[Kazam_screencast_00002.mp4.zip](https://github.com/olifolkerd/tabulator/files/2657598/Kazam_screencast_00002.mp4.zip)

**Comment by KES777** [comment]
Another note: events from keyboard also does not work: arrow up/down, pageup/down

end/home - works fine.

**Comment by KES777** [comment]
another example where I encounter this issue: 
[Kazam_screencast_00004.mp4.zip](https://github.com/olifolkerd/tabulator/files/2657839/Kazam_screencast_00004.mp4.zip)

**Comment by olifolkerd** [comment]
Hey @KES777 

It sounds like your table may be hidden when it is first created. If this is the case you need to call the ***redraw*** function when the table is first made visible, otherwise the Virtual DOM is unable to calculate the correct layout of the table as hidden elements have no dimensions.

Cheers

Oli :)

**Comment by KES777** [comment]
No hiddens, I show all the code. 
also [the last video](https://github.com/olifolkerd/tabulator/issues/1629#issuecomment-445272834) is from tabulator site's example

**Comment by olifolkerd** [comment]
Hey @KES777 

Please could you post a js fiddle with code that replicates the issue as i am unable to replicate it here, the scroll just works for me on all browsers.

Cheers

Oli

**Comment by olifolkerd** [comment]
Im afraid that code also works fine in all browsers on my computer

**Comment by KES777** [comment]
seems it is. I install Chrome and everything works fine

**Comment by KES777** [comment]
Probably this belongs to `This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! mismatch.html`

**Comment by KES777** [comment]
>seems it is. I install Chrome and everything works fine

No. It does not work. With many rows when I nest many tables like [this](http://tabulator.info/examples/4.1#nested-tables). Same as in attached video.

Trying to investigate...
Next code seems dead:
https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L2518

At this point `self.scrollTop` already equal to `top`. What you are trying to achieve with this assignment?

**Comment by olifolkerd** [comment]
@KES777 

I can see the issue in the nested table example but that is not the the issue that this was originally created for.

The issue in that case is related to the large row height, and is due to a calculation glitch when the row height approaches the size of the table. I am well aware of it, it has been discussed in multiple threads and will be fixing it as part of an overhaul of the virtual DOM in the next release.

As for your earlier post with the warning of "scroll-linked positioning effect" That is 100% correct, that is exactly how a scrolling virtual DOM works.

Cheers

Oli :)

**Comment by KES777** [comment]
This also looks strange:
https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L4106
https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L4111

Probably you mean `bottomDiff`

**Comment by olifolkerd** [comment]
@KES777 

Thanks, that does look like a typo there.

You seem to be spending a lot of time on this. If testing is something you are into then i would love to work with you on a testing plan for Tabulator if that is how you would like to contribute to the project.

There are several areas that could benefit from more detailed testing, it would be easier for me, if we could come up with a structure for the testing rather than the current shotgun approach. Tabulator is very complex with lots of systems depending on other systems, and so there are certain areas that would be preferable to testing first, it would also make life easier on me to be able to fix issues one system at a time rather than being pulled all over the place.

If that would be of interest to you please let me know.

Cheers

Oli :)

**Comment by KES777** [comment]
Yes, I could spent time. Only if that functionality cross/meet with my main job tasks.

Thus just tell me what to do and I will try to finish that. probably if you have roadmap you may put a link, so I can choose which one fit me better.

Cheers

**Comment by KES777** [comment]
After updating to 4.2.1 issue in FF disappear
