### ISSUE TITLE
allow select editor to handle object values

### ISSUE THREAD

**Issue by GTHell** [olifolkerd/tabulator#1654]
It's so frustrating that the the value link with the field. When try to do the update the select editor, it's a pain. I have a JSON as below:
```
{
"id": 1,
            "first_name": "Jovanny",
            "last_name": "Simonis",
            "vehicle_id": 2,
            "vehicle": {
                "id": 2,
                "type": "car",
                "created_at": null,
                "updated_at": null
            }
}
```
And as you can see that to show vehicle type in the column I need to do something like ``` {title: "Category", field: "vehicle.type", editor: "select", editorParams: {values: myVals}} ```
myVals:
```
{
    "1": "car"
    "2":"motorcycle"
}
```
the update JSON is like below (notice that the vehicle.type is now the number):
```
{
"id": 1,
            "first_name": "Jovanny",
            "last_name": "Simonis",
            "vehicle_id": 2,
            "vehicle": {
                "id": 2,
                "type": 2,
                "created_at": null,
                "updated_at": null
            }
}
```
So yeah, in the backend, I need to reassign the vehicle.type to vheicle_id. What a joke. Without another field to specify the value, there's no way to assign this without some work. 

The solution is just separate the value from the field. Value is what suppose to display while field is where thing should be update. This is a problem with select editor.

**Comment by olifolkerd** [comment]
Hey @GTHell 

Thanks for getting in touch. Sorry to hear you are having issues.

You have a rather specific usage case there, that is beyond the scope of the standard select editor. it is only designed to handle simple values like strings, numbers and booleans.

Objects always create a bit of a complicated scenario because meaningful comparison of them is always very tricky.

In the next release in January i will be adding additional functionality to the select editor so i will look to address your issue there.

In the mean time there would be nothing to stop you creating your own [Custom Editor](http://tabulator.info/docs/4.1/edit#edit-custom) based off the select editor to handle your particular usage case.

Cheers

Oli :)

**Comment by GTHell** [comment]
In DevExtreme DataGrid they have something call look up column. The thing is the value is bind to `vehicle_id` while the display is the `vehicle.type`. It would be great if your next upgrade provide this features. It's the same as separate value from caption.
