### ISSUE TITLE
dataFiltering callback is getting empty filters parameter

### ISSUE THREAD

**Issue by 13Homer** [olifolkerd/tabulator#1698]
Filter.getFilters method is gathering filters from headers only when called from Page.getRemotePage and RowManager.genRemoteRequest but callback is triggered by Filter.filter which does not gather from "all" sources.
Is it intentional or I'm missing something?
I'm trying to use this callback to build ribbon with selected filters, something like this:

![image](https://user-images.githubusercontent.com/3685431/50641097-31057480-0f67-11e9-9121-ed6b5504823d.png)

**Comment by olifolkerd** [comment]
Hey @13Homer 

Please include examples of the function you are calling and include an example of your table definition code so that we can offer the correct advice.

Also please ask questions on Stack Overflow not here, this issue list is only for reporting bugs and making feature requests.

Cheers

Oli :)
