### ISSUE TITLE
Columns are resized back when moving browser window from one monitor to another

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1704]
**Describe the bug**
After page is loaded I resize columns manually (by mouse). But when I move browser from one monitor to another columns are resized back to its original state. Resizing also happens when I open/close debugger `F12`

**Tabulator Info**
- Which version of Tabulator are you using? 4.1.3

**To Reproduce**
1. Resize columns
2. Resize browser window (force `resize event`

**Expected behavior**
Columns should keep theirs sizes

**Solution**
Calculate column width only when table is created. Keep columns width later when `resize` event occur

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser Chrome v71 ,FF v64

**Comment by olifolkerd** [comment]
Hey @KES777 

Whether this is correct behavior or not depends on the layout mode you are using, which mode are you using?

Could you include a copy of your table constructor so i can better understand how your table is configured

Cheers

Oli :)

**Comment by olifolkerd** [comment]
That is exactly the purpose of the ***fitColumns*** layout.

It ensures that columns are resized to fit the width of the table. in most cases people use this in a window or dialog that is likely to be resized during use and they want all the columns to remain visible. it is often used in conjunction with the responsive functionality to ensure that the columns remain all visible.

This functionality has been specifically requested by a number of users and has been in use almost since the beginning of Tabulator. While i am sorry it dosn't meet your need im afraid i have no intention of changing it.

Cheers

Oli :)
