### ISSUE TITLE
Virtual DOM rendering, doesn't sort on redraw

### ISSUE THREAD

**Issue by deepikaveer** [olifolkerd/tabulator#1706]
To create a table and then add to the DOM, the table is created, with loaded data and columns, but the columns are not clickable.

**Tabulator Info**
- Tabulator v4.1.4
- 
```
function createTable() {
let newShareTable = document.createElement("div");
    	newShareTable.classList.add('newtable');
    	
		let table = new Tabulator(newShareTable, {
			data:shareTableData, //set initial table data
			layout:"fitDataFill",
   			columnMinWidth:80,
   			headerSort: true,
   			selectable:true,
   			ajaxSorting : true,
			columns: [
    {title:"Share class", field:"name", align:"right", sorter:"string", width:'50%'},
    {title:"ISIN", field:"isin", align:"right",sorter:"alphanum", width:'50%'}],
			columnHeaderSortMulti:true,
			initialSort: [{
				column: 'name', dir: 'asc'
			}]

		});
		
			table.redraw(true);
return table;
}

function addToDOM() {
let createTable= createTable();
$('body').append(createTable..element.outerHTML);
}
```

Table is created with provided data, added to body-
Column width doesn't take width
But click events are not triggered.
Even on inspect element- the event listeners are not displayed for table-sortable.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/25291661/50738477-6bd30b00-11fa-11e9-8828-90e760a43a21.png)

Thanks in Advance Oli!

**Comment by olifolkerd** [comment]
Hey @deepikaveer 

Could i ask that in future you ask questions on Stack Overflow, this issue list is only for bug reports and feature requests.

This is failing because you are copying the HTML content of the cell to another element with your line:
```js
$('body').append(createTable..element.outerHTML);
```

this is essentially taking the HTML that Tabulator has created and detaching it from all the JavaScript that makes it work.

I would always recommend that you append the element you want the table to be in *(just an empty div will do*) then create your table on that element.

you also don't need to redraw the table immediately after creating it, you would only need to do this if you have built it when hidden then added it to the DOM (which you seem to be doing in this instance for some reason).

If you absolutely have to use the approach above *(and i would strongly recommend that you don't)* then you should use the following code to append it to the body

```js
function addToDOM() {
    let createTable= createTable();
    $('body').append(createTable.element);
    createTable.redraw(true);
}
```

I hope that helps,

Cheers

Oli :)

**Comment by deepikaveer** [comment]
Thanks Oli! It worked.. :)
