### ISSUE TITLE
addRow({}, true/false ) has no effect when grouping is ON

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1711]
**Describe the issue**
When table has enabled grouping.

    table.addRow({}, true);
    table.addRow({}, false);

both will add new row/group at the end of table

**Tabulator Info**
- Which version of Tabulator are you using? 4.1.3
- Post a copy of your construct object if possible so we can see how your table is setup
https://jsfiddle.net/KES777/rhcv3aw8/

**To Reproduce**
1. use `groupBy` parameter
2. call `table.addRow({}, true);`
3. Scroll to the bottom of table
4. despite on parameter new row/group will be added to the end of table

**Expected behavior**
I am not sure how this should be, but current behavior seems ugly.

Probably new row should not belongs to any group, because it is not exists yet,
it has no values thus can not be grouped

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser FF v64

**Comment by KES777** [comment]
>Probably new row should not belongs to any group, because it is not exists yet,
it has no values thus can not be grouped

Just like new row is not filtered out when some filter is active

**Comment by olifolkerd** [comment]
Hey @KES777 

This is not a bug, let me explaing the functionality for you.

The reason this is happening is because you are adding a blank row with no grouping information in it so a new group is being created.

If you were to include the correct grouping information in the data then the new row would be added to the top or bottom of group that it matches.

In grouped mode it is not possible to have a row that sits outside of a group due to the way that the data is handled they must all exist in groups.

Filtering data is a different case because in that situation most new rows would never appear on the table in the first place if they had no data so it is done to allow you to add data first.

Cheers

Oli :)
