### ISSUE TITLE
Tabulator table not view properly

### ISSUE THREAD

**Issue by dianeryanto** [olifolkerd/tabulator#1719]
Hi Oli, thanks for your great job, 

I have a button when the button clicked will show the table (tabulator) but the problem is when button clicked, the table not show properly, table is view but the content isn't display, im need trigger action like resize window or press F12 to show the content.

**Screenshots**

When button clicked, show nothing
<img width="862" alt="show1" src="https://user-images.githubusercontent.com/33514077/51011454-2bbdb080-158b-11e9-9bf0-bebd49ebaa24.PNG">

When i press F12, content view but the header is missing (red line)
<img width="858" alt="show2" src="https://user-images.githubusercontent.com/33514077/51011452-2bbdb080-158b-11e9-8bc6-3c828c50b949.PNG">

When i try to test in jsfiddle, header is show but the content isn't (need to resize window to show data)
<img width="451" alt="jsfiddle" src="https://user-images.githubusercontent.com/33514077/51011453-2bbdb080-158b-11e9-8e96-33fb1dd3c2e0.PNG">

I already ask in stackoverflow, you can check [here](https://stackoverflow.com/questions/54139731/tabulator-table-not-view-properly) 

**Tabulator Info**
- Tabulator v 4.1.5 

**Desktop Information:**
 - OS: Windows 10 Pro 64-bit
 - Browser firefox
 - Version 64.0.2 (64-bit)

**Comment by olifolkerd** [comment]
Hey @dianeryanto 

This is likely because you are creating the table when it is hidden. Tabulator needs to be visible when it is drawn because the Virtual DOM needs to calculate the lengths of the elements that make up the table to layout the table correctly. a DOM element has no dimensions until it is first made visisble which can lead to some corruption in the table.

The easiest way round this is to call the ***redraw*** function on the table immediately after it is made visible.

```js
table.redraw(true);
```

This topic is covered in detail in the [Quickstart Guide](http://localhost:8080/docs/4.1/quickstart) on the Tabulator website.

Could i ask that in future you ask questions on Stack Overflow, this issues list is for bug reports and feature requests only.

Cheers

Oli :)
