### ISSUE TITLE
Bootstrap Popover appears underneath column headings

### ISSUE THREAD

**Issue by dneimke** [olifolkerd/tabulator#1720]
**Describe the bug**
I have a Bootstrap popover that I show when a user clicks on a button in the table.  When the popover is shown for the first row, the popover appears underneath the table header.  

Refer image below.

I've tried playing with z-index on the popover element but it had no effect. 

**Tabulator Info**
- Tabulator v4.1.5  (minified)
- Here is my formatter (TypeScript):

```
errorFormatter(cell: any, formatterParams: any, onRendered: any): any {

    const data = cell.getValue() as models.ValidationResult;

    if (!data || data.isValid)
        return "";

    onRendered(function () {
        const el = $(cell.getElement());
        const btn = el.find('.validation-btn');

        btn.click(function () {
            el.popover('show');
        });

        el.popover({
            title: "Error Title",
            content: 'Error decsciption goes in body',
            html: false
        });
    });

    return "<button type='button' class='btn btn-pill btn-danger validation-btn'><span class='glyphicon glyphicon-warning-sign' aria-hidden='true'> </span></button>"
}
```

**To Reproduce**
Here is the column definition:
```
{ title: '&nbsp;', field: "validationResult", align: "center", headerSort: false, formatter: this.errorFormatter }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/720792/51015750-5294da80-15bd-11e9-989a-49f5ed2ae0f2.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Tested in Chrome and IE Edge latest builds

**Comment by olifolkerd** [comment]
Hey @dneimke 

This issue you are having is because the popover element is included inside the ***.tabulator-tableHolder*** element, which scrolls on overflow. so the popup is hidden by the scroll.

Most JavaScript popup libraries let you choose what part of the DOM the popup should be appended to, you need it to be added to the body element, that way it wont get hidden by the scroll of the table.

Could i ask that in future you ask questions on stack overflow, this issues list is reserved for bugs and feature requests.

I hope that helps,

Cheers

Oli :)

**Comment by dneimke** [comment]
Thanks @olifolkerd - apologies for the issue spam :-)

Great job on tabulator, I really appreciate you work!
