### ISSUE TITLE
virtual DOM rendering with custom row styling

### ISSUE THREAD

**Issue by rflmk** [olifolkerd/tabulator#1722]
Hi Oli, still loving this project! I have a question about virtual DOM row creation/deletion with custom formatted rows that have an expanding element

**Describe the bug**
I'm using rowFormatter function to append a div to the row element containing extra details about the row. similar to how you do responsive collapse details but this detail div is customized with additional ajax data and styling. this detail box is hidden by default. i add a class to the row in the row click handler which causes the detail box to become visible with `display: block`.  i'm also using progressive scroll ajax loading 

it works fine except for the following 2 cases.
first, when the row scrolls out of view, it loses the class i added. i worked around this by saving the id of any expanded detail boxes and re-expanding them on each table render.

secondly, when i scroll down to the end of the table (no more data to fetch) and expand a row, and the detail box is large (in some cases taller than the visible table height), and i scroll down to view all the details, i think the virtual DOM removes the row and redraws it, which collapses the detail box i'm looking at. upon which time i re-expand the box. but the effect is that i can never scroll to the end, it keeps closing and opening back at the top of the detail box.

**Tabulator Info**
tabulator 4.1.2

is there a better way for me to add a custom detail box that expands below the row upon click, such that the state of expansion gets saved even when out of view in the virtual DOM?

thanks!
Mike

**Comment by olifolkerd** [comment]
Hey @rflmk 

Thanks for your kind words, it is great to hear you are enjoying using Tabulator.

In answer to your questions:

The class is being lost because Tabulator uses a virtual DOM it will create and destroy row elements as it needs, so the only way to guarantee something persists is to store that state in the row data and make the formatter depend on that value for whether or not the collapsed element should start open or not.

The second issue is likely because you have changed the height of the row after Tabulator has drawn the last line of the table and it isnt expecting there to be any more to scroll down. There is a bug with this part of the Virtual DOM calculations that i am looking to resolve as part of the 4,2 release that should be coming out at the end of january.

I hope that helps

Cheers

Oli :)

**Comment by rflmk** [comment]
Thanks for the quick reply.

For now I am able to work around the second issue by forcing vDomWindowBuffer to a large value (big enough to hold enough rows plus a large details box). I had to do this manually, for some reason it wasn't getting set by the `virtualDomBuffer` option in my constructor.
