### ISSUE TITLE
case sensitivity in ajaxConfig method option

### ISSUE THREAD

**Issue by rflmk** [olifolkerd/tabulator#1728]
**Describe the bug**
Between 4.1.2 and 4.1.5 I started getting ` Load Error:  TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.` when loading a certain table.

**Tabulator Info**
- Tabulator 4.1.5
relevant constructor options:
```
    ajaxConfig: {
      method: 'GET',
    },
```
**To Reproduce**
Load the page with the above configuration

**Expected behavior**
It should fetch the requested data, but it fails before sending the request

**Additional context**
It looks like your `defaultLoaderPromise` method is doing a comparison of `"get" != e.method` which fails because i'm passing in capitalized method like the documentation shows.
changing my ajaxConfig to:
```
ajaxConfig: {
  method: 'get',
},
```
makes it work again. I don't have this problem on other tables, even on the same page, which also use the same ajaxConfig options.

**Comment by olifolkerd** [comment]
Hey @rflmk 

in version 4.0 Tabulator moved to using the [Fetch API](https://developers.google.com/web/updates/2015/03/introduction-to-fetch) which is built into all browsers rather than being dependent on the 3rd party jQuery ajax library.

As a result of this the properties used in the ***ajaxConfig*** object must be valid fetch config options rather than jQuery ajax config options.

In this case the method must be in lower case. as this is implements as part of the fetch API specification it is outside of the scope of Tabulator.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rflmk 

Could you let me know which example (page url etc) i will get that fixed immediately.

Cheers

Oli :)

**Comment by rflmk** [comment]
I noticed it here: http://tabulator.info/docs/4.1/data#ajax-advanced

I think the comment for `POST` also has a typo in the code examples 😀

**Comment by olifolkerd** [comment]
great thanks, i will get those all fixed :)
