### ISSUE TITLE
Table validation and pagination issue.

### ISSUE THREAD

**Issue by n4ks** [olifolkerd/tabulator#1733]
When i validate cell and click to another table page - > i can't edit cells after.

Set cell validator: "required";
Click on cell, delete value, click to another place, callback validation
Click to another page on pagination
Can't edit any cell after it (on previous page too)

**Tabulator Info**
4.1.5.

If i disable pagination buttons  in validationFailed callback user can't "break" the table. (and turn them on in cellEdit callback). but it is rather a temporary solution.
`                // disable pagination
                for (var button = 0; button < paginationButtons.length; button++) {
                    if (!paginationButtons[button].hasAttribute("disabled")) {
                        paginationButtons[button].setAttribute("disabled", "");
                    }`

**Comment by olifolkerd** [comment]
Hey @n4ks 

This is caused because the validation system blocks the focus shifting from the cell, keeping the edit on it, but it cannot stop the click event on the other element triggering other actions on the table, putting the table into the situation where the edit is still in effect on the cell but the cell is no longer visible so you are essentially trapped.

I have just pushed a fix to the 4.2 branch that cancels any active edit when the active rows of the table are recalculated which should prevent this happening in future

this will be included in mondays release.

Cheers

Oli :)
