### ISSUE TITLE
Scrolling to Top Android Mobile Chrome and Firefox

### ISSUE THREAD

**Issue by cswroe** [olifolkerd/tabulator#1741]
I am noticing that the page is jumping all the way to the top on Chrome Mobile and Firefox on Android.  I do not see that same action in DuckDuckGo or LastPass browser.

Running latest commit as of 1/12/2019

Open webpage.  Scroll down and it will jump back to top.  After the first time, I can scroll down but once I start scrolling up at all, it will jump to top.  

Test Device was a Pixel 2

The code is pretty vanilla. I tried with/without responsive collapse and header filters, moveable columns, different layouts, but the same result.
var table = new Tabulator("#opd-table", {
		pagination:"local",
		paginationSize:15,
		movableColumns:true,
		layout:"fitDataFill",
		responsiveLayout:"collapse",
		columns:[
			{title:"Date",field:"Date", headerFilter:"input"},
			{title:"Time",field:"Time", headerFilter:"input",responsive:2},
			{title:"Incident #",field:"Incident #", headerFilter:"input",responsive:3},
			{title:"Nature", field:"Nature", headerFilter:"input"},
			{title:"Address",field:"Address", formatter:"html",headerFilter:"input",align:"center",width:200},

A video showing what is happening in Chrome, Firefox, LastPass and DuckDuckGo: https://youtu.be/wcuEHN_EyJ0   sorry, the blank section is last pass browser, it must block screen recording.

Thought it may be php or fget, but the same result on a plain html page.
http://www.openpolicedata.com/CedarLakeIN/CFS/2017CFS.php
http://www.openpolicedata.com/CedarLakeIN/CFS/2017CFS.htm

**Comment by cswroe** [comment]
After messing with this, it looks like specifying the height resolves the issue.  I left it out to self adjust, but at least have a workaround.

**Comment by olifolkerd** [comment]
With no height set the table will render in classic render mode where it will draw all rows on the table at once. in this mode it is essentially a dumb HTML table therefor any scrolling effects you are experiencing will be caused by the page that the table is on as it has no ability to scroll itself.

Tabulator will only scroll internally in the table if you have the height set on the table at which point it will use the virtual DOM and only display a certain number of rolls and a scroll bar.

I hope that makes a bit more sense,

Cheers

Oli :)
