### ISSUE TITLE
Rows with only progress bars become too short

### ISSUE THREAD

**Issue by jegger42** [olifolkerd/tabulator#1743]
**Describe the bug**
When my row only contains progress bars, then the row collapses so I can't see the progress bars

**Tabulator Info**
- Which version of Tabulator are you using?
4.1.4
- Post a copy of your construct object if possible so we can see how your table is setup
            var table = new Tabulator("#ADHD", {
               data:adhdData,
               columns:[
               {title:"A Percentile", field:"a_percent", formatter:"progress", formatterParams:{
                 min:0,
                 max:100,
                 color:["red", "yellow", "green"],
                 legendColor:"#000000",
                 legendAlign:"center",
               }},
               {title:"B Percentile", field:"b_percent", formatter:"progress", formatterParams:{
                 min:0,
                 max:100,
                 color:["red", "yellow", "green"],
                 legendColor:"#000000",
                 legendAlign:"center",
               }},
               {title:"C Percentile", field:"c_percent", formatter:"progress", formatterParams:{
                 min:0,
                 max:100,
                 color:["red", "yellow", "green"],
                 legendColor:"#000000",
                 legendAlign:"center",
               }},
               {title:"E Percentile", field:"e_percent", formatter:"progress", formatterParams:{
                 min:0,
                 max:100,
                 color:["red", "yellow", "green"],
                 legendColor:"#000000",
                 legendAlign:"center",
               }},
               ],
             });

**To Reproduce**

Use the above constructor for a table
The bars are not visible

**Expected behavior**
The bars should appear in the row

**Screenshots**

**Desktop (please complete the following information):**
Mac OS
Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @jegger42 

Thanks for getting in touch, that is an extremely unusual table setup you have there.

It is not so much a bug, but a misunderstanding of how the progress bar formatter works.

Rows in Tabulator have no specific height, their height is set by the size of the rows contents. The progress bar formatter is designed to take up all the vertical space in the cell to automatically resize to fit in with what ever contents is in the row.

In this case it is disappearing because the rows have no height. to get round this i would suggest that you include the following CSS in your code after you have imported your tabulator.css into your projet to force the cells to have a height:

```css
.tabulator .tabulator-cell{
	min-height:20px !important; //set whichever height you like
}
```

that should force a height to the cells and make the formatter work.

I hope that helps,

Cheers

Oli :)
