### ISSUE TITLE
Make rownum formatter respect sorting and filtering

### ISSUE THREAD

**Issue by NickolayMitev** [olifolkerd/tabulator#1767]
**Describe the bug**
When column formatter is set to "rownum" row numbers get scrambled after sorting.

**Tabulator Info**
- Tabulator v4.1.5

**To Reproduce**
1. Go to [http://tabulator.info/examples/4.1#formatters](http://tabulator.info/examples/4.1#formatters)
First column shows correct row numbers (1, 2, 3, 4, 5 ...)

2. Click on column "Name" to sort
Now the first column shows 4, 3, 9, 6, 8 ..

**Desktop:**
 - Browser Chrome v 71.
-  The same behavior with other browsers

**Comment by olifolkerd** [comment]
This is a known limitation of the rownum formatter and occurs because the rows are not redrawn on sort, only when the data changes so the formatter does not update.

I will add this feature request to the roadmap but it will likely not make it in until version 4.3

I will update the documentation to make it clear of the current limitations of this formatter

**Comment by olifolkerd** [comment]
Hey @NickolayMitev 

You will be happy to hear i have just pushed this feature to the 4.5 branch that will be released in a few weeks time.

Cheers

Oli :)
