### ISSUE TITLE
Tabulator 4.2 Released Today!!!

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#1785]
### Tabulator 4.2 Out Now!

The latest version of Tabulator is now available, it is jam packed full of new features and bug fixes, checkout the [Release Notes](http://tabulator.info/docs/4.2/release) for more information!

Cheers

Oli :)

**Comment by drunkskunk** [comment]
`var table = new Tabulator("#view360-table", {
    width:"100%",
    dataTree:true,
	layout:"fitDataFill",
rowContext:function(e, row){
	alert(row.getIndex());
    },
    dataTreeStartExpanded:false,
	ajaxURL:"http://localhost/JSONNew/rum.json?v="+Math.floor(Math.random()*100000),
	ajaxError:function(xhr, textStatus, errorThrown){
	alert("Sorry Error Loading The Table!");
    },
	 dataTreeRowExpanded:function(row, level){
        //row - the row component for the expanded row
        //level - the depth of the row in the tree
		var index= row.getIndex();
    $.get("http://localhost/JSONNew/id_"+index+".json", function(data, status){
    //  alert("Data: " + data + "\nStatus: " + status);
	
	 var obj = JSON.parse(data);
	 alert(data);
	  row.update({_children:obj});
    },"text");
	
    },
    columns:[
    {title:"Name", field:"name", width:200, responsive:0}, 
	{title:"Status", field:"status", align:"center",formatter:"tickCross",formatterParams:{allowEmpty:true},width:150, responsive:0},
	{title:"Acknowledge", field:"ack", align:"center",formatter:"tickCross",formatterParams:{allowEmpty:true}, width:150, responsive:0},
    {title:"Application",columns:[{title:"Application Performance",field:"apperf",formatterParams:{allowEmpty:true} ,align:"center",formatter:"tickCross",width:100,responsive:0}
	,{title:"Application Availablity", align:"center",formatter:"tickCross",formatterParams:{allowEmpty:true},field:"appavail",width:100,responsive:0}]},
    {title:"Last Status Change",align:"center", field:"statchange", width:200, sorter:"datetime",sorterParams:{allowEmpty:true,format:"DD-MM-YYYY hh.mm AM/PM", alignEmptyValues:"top",},responsive:2},
    ],
});`

I am trying to load data from a URL everytime Tree Row is expanded. However since after every row update the table is redrawn , the  dataTreeStartExpanded is set to false and the tables collapses back making me not able to see the children. Is there anything that can be done to avoid this.

Thanks in advance,
Vaidhyesh

**Comment by olifolkerd** [comment]
@drunkskunk 

Please create issues as needed, dont hijack other issues!

**Comment by Rodbjartson** [comment]
Thank you so much, our dev team has looked forward to this for a long time!
Some of the features we are extremely excited to see in action are:

1. **Include Hidden Column in Download** - a must have for our application, and a very important feature for many people who use hidden columns
2. **Column Calculations Now In Downloads** - yey!
3. **Load Page for a Specific Row** - no more modulo stuff going on in our code haha
4. **Programmatic Row Moving** - might come in handy!
+++

Although this is already pointed out in the release notes, I want to mention that in order to make use of the new features related to downloading of tabulator tables, you need to:

_Autotable Depedency Version Change
The PDF downloader now uses the 3.0.5 version of the jspdf-autotable plugin to allow even more features for PDF downloading._

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.0.5/jspdf.plugin.autotable.js"></script>
```

**Comment by michaelongithub** [comment]
Thanks a lot, great as always.

For me hidden column download was much needed.  Download to new browser tab was asked for from my clients too. An of course happy for the byte order mark, I asked for.

Really very thankful for your great persistence.

Cheers, Michael

**Comment by Jojoshua** [comment]
I just found this software yesterday. I've been researching similar products such as hansontable, slickgrid, datatables, and jExcel but tabulator seems to be the best for my needs. I will continue reviewing source & docs, and report any issues during testing.

Thanks for managing such a high quality product.

**Comment by rspadim** [comment]
when editing a select with a movable row, at the end of a big table (500 lines full page (height=100%) table), if you click the select cell it start movable function instead of start cell editing

**Comment by olifolkerd** [comment]
Hey @rspadim 

Please dont spam unrelated topics if you think you have found a bug please create a separate issue with the bug template

**Comment by BernhardBaumrock** [comment]
Hi @olifolkerd 
I'm also reviewing your library as it might serve as a replacement for two modules that I've built for the ProcessWire CMF using aggrid and handsontable. First few hours reading the docs and playing with the examples are very promising! Congrats for this great work!
Just wanted to mention that the 4.2 release is not listed in the news http://tabulator.info/news :)
Looking forward to testing tabulator soon. Thx

**Comment by olifolkerd** [comment]
Hey @BernhardBaumrock 

Thanks for the kind words, great to hear you are enjoying Tabulator.

Thanks for the headsup, i will update the website shortly.

Cheers

Oli :)
