### ISSUE TITLE
Formatter Not Working when AutoColumn is True

### ISSUE THREAD

**Issue by kevalkothari** [olifolkerd/tabulator#1806]
When Using Autocolumn "True"

`autoColumns:true`

It's not allowing to inject column for Button, So for example I have auto column and want to add button as below but it's not working 

```
columns: [
          { title:"","field":"agent_id", formatter:function(cell, formatterParams){
            return "<i class='cui-info icons '></i>";
    ]
```

So the field "agent_id"  not rendering the formatting for button when autoColumns is true.

**Comment by olifolkerd** [comment]
Hey @kevalkothari 

Please ask questions on Stack Overflow, the issues list is for Bug Reports and Feature Requests only.

When using autocolumns the columns array is completely replaced by the auto generated columns, you cannot use autocolumns and defined columns at the same time.

I will update the documentation to make this clearer

Cheers

Oli :)

**Comment by ModelEarth** [comment]
I tried the following, but only using this css worked for right alignment:
 .tabulator-cell{text-align: right;}

//table.on("dataLoaded", function(data){
table.on("tableBuilt", function(data){
    table.getColumns().forEach(function(column){
        //column.definition.cellHozAlign = "right";
        //column.setHozAlign("right");
        //column.setHozAlign("right");
        //column.setHorizontalAlignment("right");
        //column.setAlign("right");
        //column.hozAlign("right")
        //column.align = "right"; // No error, no effect
        //column.hozAlign ="right"; // No error, no effect
    });
});

Page for testing:
https://model.earth/data-pipeline/timelines/
Javascript:
https://model.earth/localsite/js/earthscape.js

**Comment by olifolkerd** [comment]
That isn't working because that is not the correct way to set the column options.

You can't just assign values to props after the table has built, the table has no way to know to update them.

If you want all the columns to have the same props use the 'columnDefaults' setup option

https://tabulator.info/docs/5.6/columns#defaults

If you need more control per column then there are several different approaches that are outlined in detail on the auto columns documentation

https://tabulator.info/docs/5.6/columns#autocolumns

Cheers

Oli
