### ISSUE TITLE
initialSorter not working when using autoColumns 

### ISSUE THREAD

**Issue by simon1tan** [olifolkerd/tabulator#1807]
Version 4.2. Chrome 72.0.3626.109

Init is: 
`
    autoColumns:true,
    initialSort:[
        {column:"date", dir:"asc"},
    ]
`

I am getting "Sort Warning - Sort field does not exist and is being ignored:  date". Date field does exist. After removing autoColumns and adding custom defining columns,
`
      columns:[
	    {title:"Date", field:"date", width:160}
    ]
`
Warning goes away. autoColumns is awesome and being able to initial sort a known (mandatory) field would be even better. Thanks.

**Comment by olifolkerd** [comment]
Hey @simon1tan 

That is because the column definitions are not defined until the data is loaded into the table, which is after the initial sorters have been set.

I have added an update to the master branch to tweak the initialization order when autocolumns is enable and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by HenriqueSabino** [comment]
Hi, it's not working for me in version 5.5. I have remote sort option, initialSort and autoColumns but still I get an error stating that the column doesn't exist.

https://jsfiddle.net/L5umr4ko/

**Comment by temaxuck** [comment]
> Hi, it's not working for me in version 5.5. I have remote sort option, initialSort and autoColumns but still I get an error stating that the column doesn't exist.
> 
> https://jsfiddle.net/L5umr4ko/

+1, I'm using version 6.3.
