### ISSUE TITLE
replaceData with no fixed height

### ISSUE THREAD

**Issue by noluckman** [olifolkerd/tabulator#1813]
**Describe the bug**
When calling replaceData on a non defined height table not refresh done.

**Tabulator Info**
- Which version of Tabulator are you using? 4.2
- Post a copy of your construct object if possible so we can see how your table is setup:

var table = new Tabulator("#example-table", {
                layout: "fitColumns",
                history: false,
                ajaxURL: "./PESRest/PCO/LTE/ALL/DOWN",
                columns: [
                    {title: "Causes", field: "causes", headerSort: false, width: "35%"},
                    {title: "Start", field: "start", headerSort: false},
                    {title: "End", field: "end", headerSort: false},
                    {title: "Time (min)", field: "time", align: "center", headerSort: false}
                ]
            });

**To Reproduce**
call replaceData function on table with no height defined

**Expected behavior**
replace data even if no height defined

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 7
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  71.0.3578.98

**Additional context**
No problem when calling replaceData on following code:

var table = new Tabulator("#example-table", {
                layout: "fitColumns",
                history: false,
                height: "20vh",
                ajaxURL: "./PESRest/PCO/LTE/ALL/DOWN",
                columns: [
                    {title: "Causes", field: "causes", headerSort: false, width: "35%"},
                    {title: "Start", field: "start", headerSort: false},
                    {title: "End", field: "end", headerSort: false},
                    {title: "Time (min)", field: "time", align: "center", headerSort: false}
                ]
            });

**Comment by olifolkerd** [comment]
Hey @noluckman 

That is because the replaceData function is used to replace all data in the table keeping the scroll in the same, in classic mode (when no height is set there is no virtual DOM and thus no scroll bar so no way to replace the data and keep the table in the same position, in that configuration the ***setData*** function would be more appropriate.

However i do take the point that it should do something. in the next release i will add a patch to cause it to behave the same as the ***setData*** function when in classic render mode.

Thanks for the feedback.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed a fix for this to the master branch and will include it in the patch release this evening

Cheers

Oli :)
