### ISSUE TITLE
Adding a new row is not groupped when there is a groupBy

### ISSUE THREAD

**Issue by Paraplegix** [olifolkerd/tabulator#183]
Example code for reproduction : 
`$("#example-table").tabulator({
	height: "320px",
	fitColumns: true, 
	selectable: true,
	selectableRollingSelection: true,
	columns:[	{ title: "Name", field: "name", sorter: "string", sortable: false, headerFilter: "input",editable:true },
		{ title:"First Name", field:"fname" , sorter:"string"},
		{ title: "Age", field: "age", sorter: "string", sortable: false }],
	groupBy: "name"
});
var tabledata = [{name:"Doe",fname:"John",age:20},
	{name:"Doe",fname:"Jane",age:21},
	{name:"Bar",fname:"Foo",age:22},
	{name:"Bar",fname:"Fuu",age:23},];
$("#example-table").tabulator("setData", tabledata);`

Simple table with Name, First name and age, groupped on **Name** column, and 4 entries
Type the following command in the navigator console : 
`$("#example-table").tabulator("addRow",{name:"Doe",fname:"Faa",age:23});`
The row will be added at the end, when it should be added to the "Doe" Group.

The row adding related functionnalities seems very poors (just a note), is there any plan to upgrade/improve or add more functionnalities concerning row addition? Like addition after another row?

Also when you edit the data in the grouping column, its not update and stay in the same group. (try changing a "Doe" to "Bar" in the example)

I've noticed that filtering the data made everything go to their respective group so the fix might only be to call a pre-existing function on row insertion or cell edition.

Edit: Oh and it might be interessting to add callback for click on a group header ;)

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch.

You are correct, at present added rows ignore the group structure and are placed at the top or bottom of the table.

Luckily next months release is all about rows! In next months release i will be having an overhaul of a lot of the row functionality including:
- Adding rows in groups
- Inserting rows next to existing rows
- an updateOrAdd function for updating a row if it exists or creating it if it dosnt
- a getRow function for retreiving a specific row or rows rather than the total data set.
- more comprehensive row updating
- and i like your group header callback idea, i will add a click, dblclick and context callback for the group header.

Let me know if you can think of any other features that would be of use to you.

Thanks for the feedback

Oli

**Comment by Paraplegix** [comment]
I've made modifications on my working copy of tabulator.js (not with github) and i have a solution to "part" probleme, very simple enhancement in the way addRow function work (12 new lines and 2 modified), and if the row can be directly grouped (passing the row in groupBy provided function give a existingvalue) its directly appended at the right place without refreshing the whole view, and it look like its working-ish. (It doesnt update the group header)

Do you accept modificationmade by others? (by pull request or directly sending them via MP)

**Comment by olifolkerd** [comment]
Hey,

Great stuff! please submit your changes as a pull request, it would be great to see the solution you have come up with!

Thanks

Oli :)

**Comment by Paraplegix** [comment]
I think i have submited the pull request but i can't see it anywhere.
I also included a quick fix for the other bug i have signaled to you (issue #193 ). It will do the job for row adding, but I don't know if there is no similare bugs somewhere else

**Comment by vasilich6107** [comment]
Hi @olifolkerd I appreciate your work. Just want to tell that I am awaiting on additional functionality about rows. When do you plan to release them?

**Comment by olifolkerd** [comment]
Hey,

I've had a hectic work at month so im running a bit behind on this months release. it will be a week or two now before the next release is out.

Thanks for your patience.

Cheers

Oli

**Comment by olifolkerd** [comment]
Great News!

I have just committed all the features listed above to the repo! I will be doing an official release in the next couple of days but if you want faster access just pull the latest code from the repo.

The new functionality includes:

### Updated Add Row function
The updated **addRow** function lets you specify the existing row next to which the new row should be inserted.
```js
$("#example-table").tabulator("addRow", {name:"Billy Bob", age:"12"}, true, 3); //insert new row before existing row with index of 3
```
### Update or Add Row
The new **updateOrAddRow** function will update an existing row if it can find it, otherwise it will create a new row.
```js
$("#example-table").tabulator("updateOrAddRow", 3, {id:3, name:"steve", gender:"male"});
```

### Update or Add Data
The new **updateOrAddData** function will iterate through an array of row data and update existing rows or create new rows if they don't exist.
```js
$("#example-table").tabulator("updateOrAddData", [{id:1, name:"bob"}, {id:3, name:"steve"}]);
```
### Get Data for Row
The new **getRowData** function will return the data for a single row
```js
var rowData = $("#example-table").tabulator("getRowData", 1); //return data for row with index of 1
```

### Get Row Element
The new ***getRow*** function will return the jQuery object for an existing rows DOM element.
```js
var rowElement = $("#example-table").tabulator("getRow", 4);
```

### Column Header Click
The **headerOnClick** callback is triggered when a user left clicks on a column or group header, it can be set on a per column basis using the option in the columns data.
```js
{title:"Name", field:"name", headerOnClick:function(e, header, field, columnDef){
        //e - the click event object
        //header - the DOM element of the column header
        //field - the field name of the column
        //columnDef - the column definition object for the column
    },
}
```

### Column Header Double Click
The **headerOnDblClick** callback is triggered when a user double clicks on a column or group header, it can be set on a per column basis using the option in the columns data.
```js
{title:"Name", field:"name", headerOnDblClick:function(e, header, field, columnDef){
        //e - the couble click event object
        //header - the DOM element of the column header
        //field - the field name of the column
        //columnDef - the column definition object for the column
    },
}
```

### Column Header Right Click
The **headerOnContext** callback is triggered when a user right clicks on a column or group header, it can be set on a per column basis using the option in the columns data.
```js
{title:"Name", field:"name", headerOnContext:function(e, header, field, columnDef){
        //e - the couble click event object
        //header - the DOM element of the column header
        //field - the field name of the column
        //columnDef - the column definition object for the column
    },
}
```
I have update the [documentation](http://olifolkerd.github.io/tabulator/docs/) to match the new functionality.

Let me know how you get on.

Cheers

Oli
