### ISSUE TITLE
Cell user data

### ISSUE THREAD

**Issue by lbaird13** [olifolkerd/tabulator#1838]
I have searched the documentation and asked on stackoverflow. Hopefully what I am after is not something that is already present. I am using JSON where each cell data is a JSON object containing a "value" to be displayed and an optional "style" to apply to the cell. I initially used a mutator to change cell object to only be the value, but I lost the optional style. I would like a way to save optional data on a cell by cell basis. I could then use this method in a mutator to save the style where it would be later available for a formatter.

Currently I am use custom accessors, sorters and formatters. This works, but I feel like I am rewritting lots of functionality built into tabulator. For example, I have my own sorters for strings and numeric. The layout of Tabulator is designed so well, I feel like I have to be doing something wrong.  It seems like there has to be a better way?

**Comment by morficus** [comment]
Hey @lbaird13 - 

I sounds to me like you need to create a [custom cell formatter](http://tabulator.info/docs/4.2/format#format-custom) in order to use your JSON object to apply both a cell value and style. From with in a custom formatter you have full access to the [cell component](http://tabulator.info/docs/4.2/components#component-cell), meaning you can use `cell.getElement()` to get the DOM node and directly apply your CSS styles on it and `cell.setValue()` to set the value.

You may still need a custom mutator if your users can edit data in the table, but you won't need a custom accessors or custom sorting functions.

If you can provide code samples (using something like [JSFiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/)) I should be able to give more concrete suggestions.

**Comment by waruyama** [comment]
The best would certainly be to provide a reduced test case for your table so people can look at how you handle cell formatting.

Alternatively, an example value object and a screenshot to show how you want your cells to be formatted would be helpful.
