### ISSUE TITLE
Download as CSV throwing Access Denied error in IE 11 but working fine in firefox and chrome.a

### ISSUE THREAD

**Issue by Prabhu-Gowd** [olifolkerd/tabulator#184]
Hi, This is an amazing framework that i have ever used till now. Thanks for developing such an awesome framework. Thanks for making it open source, which helps the developers life's a lot easier. 

Issue : 
Download as CSV throwing Access Denied error in IE 11 but working fine in firefox and chrome. I cross checked this on the tabulator site's interactive demo suing IE 11, but there also some problem exists and it is not prompting the download. Your help is really appreciated.

Thanks,
Prabhu.

**Comment by olifolkerd** [comment]
Hey,

Thanks for your kind words, it is always great to hear people are enjoying their time with Tabulator.

The error appears to be due to security settings in IE. It appears to have a number of options to either prevent data url's from being run.

Sadly as this is part of an individual browsers config there is not much i can do on my end to resolve it. I would suggest you have a play with your security settings to get it working.

If you have a copy of the console log you receive i would be happy to see if there is anything i can do.

Sorry i couldn't be more help there.

Cheers

Oli
