### ISSUE TITLE
We need to help Oli!

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#1840]
Hey guys, we need to help Oli out with questions.
There are so many questions lately, many of them are not bug issues, and many can be answered by us who have used tabulator for some time. 

So I ask my fellow tabulator friends to help contribute to this project: the less time Oli needs to answer questions, the more time he will have to enhance this wonderful tool. Let us make this the best javascript library! 

We also need new ideas, so feel free to add pull requests if you have some great ideas:)

**Comment by olifolkerd** [comment]
Thanks @Rodbjartson 

That really would help out a great deal, since the 4.0 release of Tabulator the number of users has exploded, and it is pretty much a full time job answering the questions on here.

If any of the experienced users out there could spare a few minutes a week to help the new starters out that would be a great help

Cheers

Oli 😄

**Comment by waruyama** [comment]
I am new to Tabulator but I have quite some experience using Javascript, CSS, and I claim to be a master in using Chrome's debugger, so I will try to help.
Also, you should somehow think about offering a commercial license. The company that I am currently working for would be able and willing to purchase such a license, while giving donation is always a problem for accounting. They are even reluctant to use Tabulator because it is free of charge :)

**Comment by olifolkerd** [comment]
Hey @waruyama 

Thanks for your feedback, for the time being i'm avoiding going down the commercial licensing route because a lot of organisations (especially public sector) have policies that prevent their staff using software with restrictive licensing.

I see so many sites out there that either have terrible tables because of the restrictive licensing of other tables, or paying insane amounts of money for access to other table libraries, and i want to keep tabulator open source and accessible to all.

That being said i do spend 1000's of hours a year maintaining Tabulator so a bit of support would be great 😃 . I have been considering adding sponsorship packages to Patreon to allow for corporate sponsorship of the library (a primary sponsor and secondary sponsors) with logos displayed on the website etc. i would love a bit of feedback to the community if this is something they would be interested in.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
> Im also looking for someone with experience in TypeScript who would be willing to sort out some TypeScript Typings for Tabulator, i dont use it myself so dont really know what it entails. the issue for this one is #86
> 

@olifolkerd -- This would be a massive typescript definition. I'll give it a shot since I am trying to learn this library anyway. Would you expect the definition to be shipped with Tabulator or published to DefinitelyTyped?

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Thanks for your kind offer of help, could i ask that if you have any questions about the typings that you ask them in issue #86 it will help me keep track of the whole issue in one place.

Cheers

Oli :)

**Comment by JKirtz422** [comment]
Hey I wanted to chime in and say thanks to Oli and everyone else that works on Tabulator, it really is an awesome library. I'm using it in GIS web development and it works great with very little headache. I think getting a way for corporate sponsorship with logos/links to websites would be a fantastic idea.

**Comment by haferje** [comment]
I've submitted a few issue reports that resulted in code fixes.  Many were ones I believe I could have submitted pull requests for, but have been very hesitant about it.  I don't want to submit code that doesn't fit the developer's coding styles or is incomplete because of my lack of knowledge for how all the small parts interact with each other.  How should I go about this?

If I submit a pull request that doesn't fix it properly (like accounting for all conditions and influences) or if Oli decides he would have done it a different way, how is the PR handled from there?  Would I be better off just submitting an issue with more detail from a code stand-point, possibly targeting function names and line numbers?

@olifolkerd
I love the fact that this library is free and open source.  I have not found a better open source table/grid library that offers so many features, performs as great, or has such a responsive developer.  The company I work for plans to donate as soon as we push our code that has replaced our old commercial grid control with Tabulator!

Thank you!

**Comment by olifolkerd** [comment]
@haferje 

Im happy to work with you on pull requests, if a request dosnt fit in with Tabulators coding style, or dosnt use some of the internal functionality correctly, i will provide feedback and itemise the changes that need to be made for the pull request to be accepted.

The biggest issue i face with pull requests is when developers only consider their usage case when submitting a pull request, so please try and think about how any changes would interact with other modules in Tabulator.

Also make sure changes are submitted on the src files not the dist files.

Thanks for your kind words, it is really great to hear how much people appreciate Tabulator. any donations are very gratefully received.

Cheers

Oli :)

**Comment by angeliski** [comment]
He @olifolkerd Just to know, you think in put some tests in the Tabulator?
I see that big project without any test and I think can be scary to change something
What do you think putting some tests using Jest? Cypress?

**Comment by olifolkerd** [comment]
Hey @angeliski 

I would love it if we could have some automated testing, sadly i dont have time to do it myself, but if you have a proposal please create an issue as a feature request and add the details for how you think it should be approached and what tests you would recommend.

We could then get some community feedback and then plan things out.

Cheers

Oli :)
