### ISSUE TITLE
Vertical scroll via scroll bar very slow and jumpy

### ISSUE THREAD

**Issue by zixy99** [olifolkerd/tabulator#1847]
Tabular version 4.0.5 on Windows 10 pro.
Table has 500 rows (or more) and many columns (>20). 
Scrolling vertically via the scroll bar has the following problems:
In Chrome: Scrolling is very slow and jerky.  
In Firefox: Scrolling is faster than in Chrome but is "blinking" i.e. get empty and then filled up. 
Note that it is way slower than the same table just rendered directly with HTML. 
I have tried adding:
progressiveRender: true,
progressiveRenderSize: 5,
progressiveRenderMargin: 100,
But it didn't make any difference. 
Please help. Thanks.

**Comment by olifolkerd** [comment]
Hey @zixy99 

If you are asking a question you need to do so on Stack Overlfow, not here.

If you think you have found a genuine bug, then you need to use the bug template when creating an issue as it prompts you to enter all the information we need to fix the issue.

it is very hard to determine what is wrong with your table without seeing a working example, please create a JS Fiddle or Code Pen so we can see your table setup in action.

it is likely because you havnt given your table a height so the virtual DOM is disbaled.

Cheers

Oli :)

**Comment by zixy99** [comment]
Hi Oli,
Thanks for the input, I am still a bit newbie with both GitHub and Stack Overflow so apologies on getting them confused with each other. I shall transfer this question to Stack Overflow. BTW I have used "height: 100%" so am to enter a specific value to enable DOM? 
I will look into JFiddle and see how to upload my files (it's an ajax load table and requires several files. Thanks.

**Comment by jakefinamore** [comment]
> Tabular version 4.0.5 on Windows 10 pro.
> Table has 500 rows (or more) and many columns (>20).
> Scrolling vertically via the scroll bar has the following problems:
> In Chrome: Scrolling is very slow and jerky.
> In Firefox: Scrolling is faster than in Chrome but is "blinking" i.e. get empty and then filled up.
> Note that it is way slower than the same table just rendered directly with HTML.
> I have tried adding:
> progressiveRender: true,
> progressiveRenderSize: 5,
> progressiveRenderMargin: 100,
> But it didn't make any difference.
> Please help. Thanks.

I am also experiencing choppy scroll.

**Comment by olifolkerd** [comment]
do you have a height set on your table? as i mentioned without a working JS fiddle demonstrating the issue it is very hard to offer a solution to your issue.

Cheers

Oli :)
