### ISSUE TITLE
Small table freezes when using grouping feature

### ISSUE THREAD

**Issue by z3rohour** [olifolkerd/tabulator#1848]
**Describe the bug**
First issue I got : when all groups are expanded and I try to collapse one of them in the middle of the table webpage freezes for a few second and then automatically scrolls up. Selected group is being collapsed, but it's a bit inconvenient to scroll the webpage down again. The same happens when I try to expand group from the middle of the page

Second one : bulk collapsing/expanding. Because of this 'collapse freezing' issue I mentioned above when I try to collapse all the groups (table.getGroups().forEach(function(gr, ind) { gr.hide(); } )) it takes about 30-40 seconds to be done.

Sample here - https://codepen.io/anon/pen/bZEWZO

**Tabulator Info**
4.2.1
```
let table = new Tabulator("#data-table", {
    height: "95%",
    data:db_data,
    placeholder: 'No data available',
    layout:"fitColumns", //fit columns to width of table (optional)
    selectable:true,
    groupToggleElement:"header",
    groupStartOpen:true,
    groupBy: function(data) { return data.column_0; },
    columns:[
        {title:"Column_0", field:"column_0", visible: false},
        {title:"Column_1", field:"column_1", headerFilter: "input"},
        {title:"Column_2", field:"column_2", headerFilter: "input"},
        {title:"Column_3", field:"column_3", headerFilter: "input"},
        {title:"Column_4", field:"column_4", headerFilter: "input"},
        {title:"Column_5", field:"column_5", headerFilter: "input"},
        {title:"Column_6", field:"column_6", headerFilter: "input"},
        {title:"Column_7", field:"column_7", headerFilter: "input"},
        {title:"Column_8", field:"column_8", headerFilter: "input"},
        {title:"Column_9", field:"column_9", headerFilter: "input"},
        {title:"Column_10", field:"column_10", headerFilter: "input"},
        {title:"Column_11", field:"column_11", headerFilter: "input"},
    ],
});
```

**Working Example**
https://codepen.io/anon/pen/bZEWZO

**To Reproduce**
1. Go to the middle of the table
2. Click on any group to collapse it
3. Page will freeze for a few seconds, then group will be collapsed and page will be automatically scrolled up
4. There is a 'Collapse all' link on top of the page. It simply tries to collapse all groups in the table - and it takes few minutes for presented table to collapse all groups

**Expected behavior**
Perhaps it might be a bit faster :)

**Comment by olifolkerd** [comment]
Hey @z3rohour 

The issue is in how you have setup your DOM.

by putting the element directly in the body, without setting a height on the body element you are allowing the table to expand to take up as much space as it needs to fit in all the rows, therefore it is taking up a huge amount of space, producing thousands of DOM elements which is what is slowing things down. You can tell this is the case by the fact there is a scrollbar on the page itself not the table.

If you want to size your table in this way you need to tell the html and body elements to take up the full screen only with a bit of CSS:

```css
html, body{
  height:100%;
}
```

I hope that helps,

Cheers

Oli :)
