### ISSUE TITLE
Tabulator 4.2.1 dist has no linebreaks.

### ISSUE THREAD

**Issue by adamxi** [olifolkerd/tabulator#1851]
Hey Oli,

It would be convenient for debugging purposes if the unminified tabulator.js 4.2.1 distribution had line breaks and proper human readable formatting ;)

**Comment by olifolkerd** [comment]
Hey @adamxi 

Thanks for the headsup, that was because the unminified dist file had become rather large so Babel had stopped formatting it.

I have updated the settings for the file generation on the master branch so line breaks will be restored to the unminified files in the patch release tommorow.

Cheers

Oli :)
