### ISSUE TITLE
Download Table Causes Table Refresh - Clearing Filters/Sorts etc

### ISSUE THREAD

**Issue by xXmrotsXx** [olifolkerd/tabulator#1857]
**Describe the bug**
When exporting the table data to excel using `$("#example-table").tabulator("download", "xlsx", "data.xlsx");` the table is immediately refreshed - clearing previously set filters and sorts.

**Tabulator Info**
- 3.5.3

**To Reproduce**
1. set filters
2. download
3. table reloads in the background while the user is choosing download location

**Expected behavior**
Filters and Sorts remain for viewing after the download

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 72

**Comment by olifolkerd** [comment]
Hey @xXmrotsXx 

Thanks for getting in touch, it looks like you are running on an old version of Tabulator there, we are now on version 4.2.2 and this issue is not present in the newer versions.

Have a look at the [Upgrade Guide](http://tabulator.info/docs/4.0/upgrade) for more information of the process of upgrading

Cheers

Oli :)

**Comment by xXmrotsXx** [comment]
I used the following function to avoid having to upgrade Tabulator post jQuery if anyone else needs it. It is still dependent on the same _ SheetJS Library_ that Tabulator uses...

`function exportTable(table) {
	var tableData = $(table).tabulator("getData", true); //true for filtered data only
	var workbook = XLSX.utils.book_new();
	var worksheet = XLSX.utils.json_to_sheet(tableData);
	var sheetname = "Exported";
	XLSX.utils.book_append_sheet(workbook, worksheet, sheetname);
	XLSX.writeFile(workbook, "TSExport.xlsx");
}`
