### ISSUE TITLE
Use of editorParams for input

### ISSUE THREAD

**Issue by pynog** [olifolkerd/tabulator#1869]
I am currently working with Tabulator and I find the library very well designed and easy to use! Nevertheless I have a question regarding the input editor. Why do not you use the parameter editorParams to set some input HTML attributes by adding by default something like:

  for (var k in editorParams){input.setAttribute(k, editorParams[k])};

This might help on remonve the default spellcheck.

Indeed it is possible to write easily bespoke editor but the spellcheck would be good to be removed. Please let me know if I am missing something.

**Comment by olifolkerd** [comment]
Hey @pynog 

Thanks for getting in touch, I think that is a great idea, i would look at adding an ***elementProps*** property to the ***editorParams*** object that you can pass these into rather than on the editorParams property itself as that cointains a lot of internal functionality that should not be assigned to a DOM element.

I will look at getting that in the next 4.3 release.

In the mean time you could certainly add that functionality yourself using a [Custom Editor](http://tabulator.info/docs/4.2/edit#edit-custom)

Thanks for the feedback

Cheers

Oli :)

**Comment by pynog** [comment]
Hi,

Thanks for your quick answer and I am absolutely happy with your proposal. Indeed for the time being I have overridden the editor.

Thanks,
Olivier

**Comment by olifolkerd** [comment]
Hey @pynog 

You will be happy to hear i have just pushed an update to the 4.4 branch that includes a new editor param of ***elementAttributes*** to the ***editorParams*** object to allow this functionality

It will be included in the 4.4 release.

Cheers

Oli :)
