### ISSUE TITLE
Feature Request/Question - Built in UI Configurator

### ISSUE THREAD

**Issue by Jojoshua** [olifolkerd/tabulator#1885]
**Describe the solution you'd like**
An optional user interface geared towards developers or power users(with instructions) to generate a Tabulator table instance. It would configure basic table options and the ability to add columns with a basic definition. For example you could add a column specifying the name, type of editor along with some editor options, and validators.

Then the entire table definition could be saved as JSON to a database and regenerated for a different set of users to actually fill out the table.

**Describe alternatives you've considered**
Not sure if this request would be the scope of Tabulator itself or a separate project should be created. This would be something I would need to create myself anyway.

**Additional context**
See rough drawing attachment.
![20190309_133126](https://user-images.githubusercontent.com/5598169/54075771-2a4df300-4271-11e9-82b7-1ac7efe381bd.jpg)

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Thanks for getting in touch,

You are not the first person to make this request, and i certainly think it has merit.

My biggest concern is that there are 1000's of options for configuring Tabulator and it would be tricky to get all of those in one configuration.

If this is something you would be interested in putting together i would be happy to include it in the website.

If you would e interested in contributing that to the website please let me know and i can make arrangements to give you access to the repo.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
Thanks for the info @olifolkerd 

I actually was thinking this would be a new code base. It would be a layer on top of the tabulator API, a "Puppeteer" of sorts so it could be reused in different parts of anapplication. It would also create/load this JSON output in order to make revisions to the table definition. It might look like..

let tabulatorUI = new TabulatorUI(targetElement) //Generate all the controls necessary to instantiate a Tabulator onto a div

tabulatorUI.save(); //JSON config 
tabulatorUI.load(config);//load config to recreate entire table.

I know how difficult it would be considering all the options. Maybe with the typescript definitions it would be possible to auto-generate the UI controls for all of the options, or at least the ones that make sense for a UI.

**Comment by olifolkerd** [comment]
Hey @Jojoshua,

That seems a bit counter intuitive for using on a live website, i can certainly see how it would be useful in generating the initial constructor, but after that point that object could then be reused ad infinitum without the configuration being used again (IE at the moment you can already store a tabulator config as a JSON object and pass it back in again, which exactly what happens with the persistent layout modes)

The option for generating the buttons as well is nice, i had initially considered including this in Tabulator, but quickly came to the opinion that everyone wants to implement their own functionality in their own way to fit with the design of their site, and by trying to impose my ideas on their site i was making more work rather than less.

It also get tricky when you are trying to store callbacks or any functional code in JSON as they cannot be meaningfully represented, so the moment someone wants to add any functionality of their own it then cant store that directly.

That being said it is always interesting to see what others come up to do with Tabulator, and i would be happy to support you in your development of this, My statements above are more to pass on my experiences in this area and not meant to discourage you.

If you do come up with a working configurator that helps people build Tabulator tables i would love to include a working version of it on the website along a link to your project.

Let me know if i can provide any info that would help you out,

Cheers

Oli :)

**Comment by Jojoshua** [comment]
Agreed @olifolkerd. My particular use case is quite specific and this kind of UI would never please everyone due to all the options and advanced scenarios like custom callbacks. I was hoping to start small and only use some of the most basic functionality akin to what an Excel user would be comfortable with.

I'll see what I can come up with.  I don't know what this will end up looking like yet but I will try to make it generic and not too specific to my use. If I can I'll be happy to share.

Thanks for the support!

**Comment by olifolkerd** [comment]
I do not have time to put this togeather myself, If anyone else would be interested in taking it on i would be happy to advise, but for now im going to close this issue

Oli :)
