### ISSUE TITLE
Group Date after saving to json

### ISSUE THREAD

**Issue by opiums9** [olifolkerd/tabulator#1905]
Good day! After exporting Group Date to json, I get corrupted data that does not open in my table later. How can I fix this?
Before:
```
[
	{
		"dob": "11/03/2019",
		"name": "1",
		"price": "1",
		"suc": true,
		"numb": "2"
	}
]
```
After: 
```
[
	{
		"type": "group",
		"key": "2",
		"rows": [
			{
				"dob": "11/03/2019",
				"name": "1",
				"price": "1",
				"suc": true,
				"numb": "2"
			}
		]
	}
]
```
![screenshot](https://files.opiums.eu/pub/2019-03-16_152224.png)
[For test](https://jsfiddle.net/opiums/54mjdL98/)

**Comment by aklaver** [comment]
Per the docs here:
http://tabulator.info/docs/4.2/data#local
"Data Format
The data must be stored as a valid json string matching the the structure of an array of objects as defined in the Load Data from Array section."

One way to do that is to use the example here:
http://tabulator.info/docs/4.2/download#advanced-config
Download Configuration

Then you get:
`[
	{
		"dob": "11/03/2019",
		"name": "1",
		"price": "1",
		"suc": true,
		"numb": "2"
	}
]`

Otherwise you will need to read the file in using something other then setDataFromLocalFile() and strip out the 'rows' array and then use that with setData().

**Comment by aklaver** [comment]
I modified the fiddle to to show what I was talking about:

https://jsfiddle.net/aklaver/x9p8us0y/8/

**Comment by opiums9** [comment]
Good. Thank you very much!
