### ISSUE TITLE
Inline editing on button click

### ISSUE THREAD

**Issue by nrietsch** [olifolkerd/tabulator#1918]
Hi,

Tabulator is fantastic, let's get that straight.

I like the inline editing function a lot but I'm having a challenge with it.

What I'd like to do is to click on a 'edit' button which will then allow to edit the row.

As far as I can see, the edit functionality is on the cell level, not the row level.

There is a function for conditional formatting but again, that's on the cell level.

On a previous project, I have the edit button and then launch a modal.
The thing is that the 'base' table is used with 3 different datasets that I load depending on the tab that is selected.
As a result, I had to create 3 different models, element by element from the code behind. 
It's a lot of code, it's slow and frankly, not clean.

Inline editing is PERFECT but I have to be able to enable the editing by a button click only.

Is it possible? How?

Note: if possible, step 2 will be to create a save button on the row level as well....

**Comment by aklaver** [comment]
Possibly use:
http://tabulator.info/docs/4.2/edit#optional

Have the callback monitor another column(possibly hidden) and use that to set the cells in a row editable.

**Comment by nrietsch** [comment]
The problem with the optional is that it's on the cell level.
I'd need something on the row level.

**Comment by aklaver** [comment]
If you set the editable option for each column to the same callback then you have effectively made it row level.

**Comment by aklaver** [comment]
Plan B would be to use:

http://tabulator.info/docs/4.2/components#component-row

Get Cells

and then walk over the cells and:

http://tabulator.info/docs/4.2/components#component-cell

Edit

**Comment by nrietsch** [comment]
> If you set the editable option for each column to the same callback then you have effectively made it row level.

It's doable of course but sounds like re-inventing the wheel to me.

If that's the only option, then that's what I'll do obviously.

With all the great functionalities in Tabulator 'out of the box', I thought that I'm maybe missing something.

**Comment by aklaver** [comment]
You could open a feature request.

**Comment by nrietsch** [comment]
I may do that. Was waiting for Oli to weight in to be honest with you to see if there is an easy way to achieve this or not.
If not, I'll make the feature request....

**Comment by olifolkerd** [comment]
Hey @nrietsch 

As requested im weighing it...

@aklaver is correct, the approach would be to use a callback to determine whether the row is editable, you could use a click event on your button to set a boolean value on your row data that your callback checks to see if the row is editable.

Because tabulator handles editing at a cell level there is no such thing as an "editable row"  tabulator as no way to know when a specific row is finished editing for example. people often ask me why there isnt a "rowEdited" callback for when a user is editing a single row, and i can understand that if all you are using is input editor that this makes perfect sense, but there are a lot more advanced editors that are only trigger a successful focus on a blur, or on another event that will take focus away from the row.

This is why the idea of "row editing" dosn't work on a larger scale, i see where you are coming from, but when i make changes to Tabulator i have to consider all usage cases and i try not to tie people down to specific design paradigms where possible.

In your usage case you clearly have a specific goal in mind, in that case using the callbacks is the correct course of action, they are there specifically to allow for persoanlisation of functionality.

I hope that helps,

Cheers

Oli :)

**Comment by nrietsch** [comment]
I do appreciate your feedback Oli and understand where you are coming from as well.
Reading you, it is clear that the option won't be added so no need to make a change request.

Also thank you to Adrian for your help.

One last question if you don't mind: 

The editable option is set at creation:
```
var table = new Tabulator("#example-table", {
    editable: true,
    [...]
});
```

Can the editable option be turned on and off 'on its own' once the table is initialized?

**Comment by aklaver** [comment]
I know of no table editable option:

http://tabulator.info/docs/4.2/options

There is the aforementioned editable cell callback.

**Comment by olifolkerd** [comment]
@aklaver  is right it is set per column, and you can pass a callback to it that returns weather the cell is editable when it is clicked

**Comment by nrietsch** [comment]
I found a work around (changed my editing philosophy...).

Thank you

**Comment by tkim90** [comment]
Hi @nrietsch, I'm trying to do the same thing - would you mind sharing how you got it working?

Seems like you can only control if something is "editable" at the column level, not row level. So if I use the editable callback, it ends up unlocking all the rows for editing, rather than only the selected one(s).

**Comment by aklaver** [comment]
See Oli's suggestion upstream(March 25, 2019).
