### ISSUE TITLE
row over 2 lines

### ISSUE THREAD

**Issue by mikehobson** [olifolkerd/tabulator#1968]
Hi Oli is it posisble to have a row which spans 2 lines, I want to create something like the attached picture for mobile devices
![image](https://user-images.githubusercontent.com/2518239/55823494-bade5400-5af9-11e9-91d2-f047cdf5bcbd.png)

This would mean each tabualtor row was able to span 2 lines

Thanks

Mike

**Comment by olifolkerd** [comment]
Hi @mikehobson 

Rowspan is not currently available, this will be comming in version 5.

In the mean time there are a few things you could look at that may offer you something similar if used correctly:

[Row Formatters](http://tabulator.info/docs/4.2/format#row) - could be used to add additional content outside of cells, or you could use this to hide the border at the top of each "second" row making them appear to be part of the first row.
[Nested Tables](http://tabulator.info/examples/4.2#nested-tables) - could be used to create a sub-table for each row
[Data Trees](http://tabulator.info/docs/4.2/tree) - to nest the data in "sub rows"
[Row Grouping](http://tabulator.info/docs/4.2/group) - to group the two rows togeather

I hope that helps,

Cheers

Oli :)

**Comment by mikehobson** [comment]
Many thanks Oli, i'll investigate these, do you have a rough ETA on version 5

**Comment by olifolkerd** [comment]
Hi Mike. We are probably a year away from version 5. There are still plenty of versions to come out in 4.

The reason for the delay is it will require a total rebuild of the render to work at a cell based level instead of a town based level.

I think in your case a styling tweek to the rows should yeild the exact layout you are after.

Cheers

Oli :)
