### ISSUE TITLE
Table's data is not displayed

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#1977]
**Describe the bug**
I am using dom element to create Tabulator.
but data is not displayed. But it is displayed when window is resized.

**Working Example**
https://jsfiddle.net/KES777/1d276e09/6/

**To Reproduce**
1. Open snippet
2. resize browser's window

**Expected behavior**
data should be displayed when tabulator is attached to DOM

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1
 - Browser FF 65

**Comment by KES777** [comment]
Also column width is broken when left side of window is moved.

![__](https://user-images.githubusercontent.com/799021/56079229-4e659c80-5dfa-11e9-8ba0-18d81f793242.jpg)

**Comment by olifolkerd** [comment]
That is expected behaviour.

The reason that is happening is because you are instantiating the table on an element that isnt visible in the DOM yet.

Elements only gain width and height when they have been added to the DOM, this means that if you try and instantiate a Tabulator on a hidden element it is unable to do the calculations it needs to be able to layout the table correctly.

The reason a resize fixes it is because it triggers the redraw function on the table.

You should either be adding the element to the DOM before you turn it into a Tabulator, or calling the redraw function when you first add it to the DOM

Cheers

Oli :)

**Comment by KES777** [comment]
>You should either be adding the element to the DOM before you turn it into a Tabulator, or calling the redraw function when you first add it to the DOM

or tabulator can put observer and call redraw automatically when detect that it is added to DOM ;-)

**Comment by olifolkerd** [comment]
@KES777 Tabulator uses resize observers exactly for this purpose, but there are are a new feature that is currently only implemented in chrome and opera.
