### ISSUE TITLE
Retrieving a Variable within editorparam

### ISSUE THREAD

**Issue by BenTongue** [olifolkerd/tabulator#1994]
Hi all,

Before I start I would like to say that this library is amazing! I do however have a question.

I'm trying to dynamically set the select options but for some reason the variable is returning undefined despite it having a value, my code is below:

`{title:"Consignor", field:"Consignor", sorter:"string", editor:"select", headerFilter:true, editorParams:function(cell,e){`

    //create a options list of all values from another column in the table
    var ConsigneeSelect;
    $.ajax({
        url: "http://10.28.1.150/CTTools/?page_id=109",
        type: "post",
        success: function(response, textStatus, xhr){
                alert("AJAX result: " + response);
                ConsigneeSelect = response;        
        },
    });
    return {ConsigneeSelect:ConsigneeSelect};
}
`},`

So in the AJAX request the response variable has a value of "2PHMARBNE". I then return this as follows return {ConsigneeSelect:ConsigneeSelect}; but for some reason it shows undefined?

When I know this works I will then return an array with multiple select options.

Your help would be much appreciated.

Cheers

Ben

**Comment by takuy** [comment]
The problem here is that **by default** ajax, by it's nature, is asynchronous. By the time the ajax `success` callback has completed, the `editorParams` function has already been returned with an undefined area. $.ajax returns as soon as it's called. 

Good thing is, you can override that - add `async: false` in your $.ajax options. This will make $.ajax wait until success (really, all callback functions) have finished executing.

Note that your return value is also technically incorrect. You should be returning an object with the field values. like so:

```
return { values: CosigneeSelect }
```

Just be sure `CosigneeSelect` is a paramaterized array/object of key:value pairs like the documentation.

**Comment by BenTongue** [comment]
Thank you for your quick response, this makes a lot of sense. I do however have one more issue that you may be able to help me with. So i'm now getting the editorparam in a function:

So the following works if var arr is written as below. As soon as I change ` var arr=[{"name2":"value2"}];` to ` var arr=Consignee ;` it throws a Uncaught TypeError: arr.forEach is not a function error.

consignee has a value of {"2PHMARBNE":"2PHMARBNE"}. 


`function paramLookup(){`
    `Consignee = ConsigneeSelect;`
    `alert("AJAX result: " + Consignee);`
   ` var arr=[{"name2":"value2"}];`
   ` var obj = {}; //create the empty output object`
   ` arr.forEach( function(item){ `
    `var key = Object.keys(item)[0]; //take the first key from every object in the array`
    `obj[ key ] = item [ key ];  //assign the key and value to output obj`
    `});`
   ` console.log( obj );`
    `return obj;`
}`

if I do **this** then the obj looks like this in the console.log: `{Consignee:` `"{"2PHMARBNE":"2PHMARBNE"}"}`

`function paramLookup(){`
    `Consignee = ConsigneeSelect;`
    `alert("AJAX result: " + Consignee);`
   **` var arr=[{Consignee}];`**
   ` var obj = {}; //create the empty output object`
   ` arr.forEach( function(item){ `
    `var key = Object.keys(item)[0]; //take the first key from every object in the array`
    `obj[ key ] = item [ key ];  //assign the key and value to output obj`
    `});`
   ` console.log( obj );`
    `return obj;`
}`


Sorry i'm not too great with Jquery/ Java.

P.S I will 100% be donating.

Regards,
Ben

**Comment by takuy** [comment]
so, I just re-read the documentation because I wasn't sure, but you should be able to just pass an array of values. Doesn't always need to be paramaterized if your "value" is the same as what you want to display. 

I'm still not quite clear on what the initial value of ConsigneeSelect is. How does that data look? That'll make things easier to explain.

**Comment by BenTongue** [comment]
So ConsigneeSelect is from an AJAX response where I have used SQL to query a database and return a variable which looks like the following:  {"2PHMARBNE":"2PHMARBNE"}. 

I then want to show that as a select options but to do this I need to turn that into an object right?

**Comment by takuy** [comment]
If your data already looks like that, you should be able to just return that as a value for the `values` field. However, if your server is returning JSON as just plain text, you'll want to make sure to convert it to a proper object. You can either set another option on the $.ajax call (I think contentType) to 'json' or parse it like this:

```js
var ConsigneeSelect
$.ajax({
   ... 
    success: function(response, textStatus, xhr){
            ConsigneeSelect = JSON.parse(response) ;        
    },
});

return {values:ConsigneeSelect}
```

**Comment by BenTongue** [comment]
Perfect!! This is working, you have been a great help.

This was my problem!

 **ConsigneeSelect = JSON.parse(response);**

Ben
