### ISSUE TITLE
Select Children Row

### ISSUE THREAD

**Issue by scott-oliver** [olifolkerd/tabulator#2044]
Adding the ability for you to select a child row (ideally in my case on render) by calling an identifier of the child directly. So for example, parsing a child rows ID within an select row statement.

I have considered selecting the row through its parents (as shown in the solution linked below), however this is not ideal given a particular child may be four levels deep (or more).

I've discussed this with another user in my SO post here, which may provide further context: https://stackoverflow.com/questions/55913089/selecting-row-after-render-table-load

**Comment by aklaver** [comment]
See also:
https://github.com/olifolkerd/tabulator/issues/1607

**Comment by olifolkerd** [comment]
Hey @scott-oliver 

At the moment i feel adding this functionality directly would cause more problems than it solves. There is no guarantee that child id's are unique from the parent row id's.

If you have the row component you can call the ***select*** function directly on that. otherwise you would need to iterate down from the parent to find the child rows.

Cheers

Oli :)

**Comment by AlainEdwards** [comment]
Not sure if this will help anyone, but I wrote a recursive function to traverse all the rows. In the code below, `sidebarPackageTable` is my tabulator table object. Just remember you will have to call the `getAllRows()` function every time you want to find a row because the `allRows` field is static.

```javascript
sidebarPackageTable.allRows = [];

sidebarPackageTable.traverseRow = function(row){
    sidebarPackageTable.allRows.push(row);

    if (row.getTreeChildren && row.getTreeChildren().length > 0){
        for (let cRow of row.getTreeChildren()){
            sidebarPackageTable.traverseRow(cRow);
        }
    }
}

sidebarPackageTable.getAllRows = function(){
    sidebarPackageTable.allRows = [];

    for (let row of sidebarPackageTable.getRows()){
        sidebarPackageTable.traverseRow(row);
    }

    return sidebarPackageTable.allRows;
}
```
