### ISSUE TITLE
Scroll bar gets jumpy when nesting tables or inserting other things

### ISSUE THREAD

**Issue by takuy** [olifolkerd/tabulator#2074]
**Describe the bug**
When using the nested table example, or inserting other data under the row (like #1997) - the scrollbar gets jumpy when scrolling near the bottom of the table. 

**Tabulator Info**
- 4.27
- See Codepen

**Working Example**
https://codepen.io/tako1337/pen/ROMWLy

**To Reproduce**
1. expand all elements in codepen (click on "show image")
2. try to scroll down to the bottom with scroll wheel
3. watch as scroll bar jumps back up

**Expected behavior**
smooth scrolling

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 74

**Comment by olifolkerd** [comment]
Hey @takuy 

This is happening in your example because of two reasons:

First of all in your pen you are trying to update the rows data object directly with the line:
```js
cell.getData().state = !currState;
```
This is extremely bad practice because you havnt told Tabulator you are updating the data, so it dont know to re run the formatters, the correct approach is to use the ***update*** function on the row component, this way you also wont need the reformat function on the row after:
```js
cell.getRow().update({"state": !currState})
```

The second issue is because you are significantly altering the height of the line in a very short table to the point where it is a significant portion of the table, and where there is very little data in the table so there is no virtual DOM buffer left to absorb the change in height.

For this reason i would recommend calling the ***redraw*** function on the table after calling the ***update***function to force a recalculation of the virtual DOM buffer which will smooth things over, so it would end up looking like:

```js
cell.getRow().update({"state": !currState})
cell.getRow().getTable().redraw();
```
I hope that helps,

Cheers

Oli :)

**Comment by takuy** [comment]
Thanks, @olifolkerd. I implemented your suggestions, one note, I still had to do a reformat() for this to work properly. Otherwise, it seems to duplicate the inner rows when trying to toggle them. So, currently I'm doing:

```js
cell.getRow().update({"state": !currState})
cell.getRow().reformat();
cell.getRow().getTable().redraw();
``` 

(it'd be cool if we could do some chaining here lol)

**Comment by olifolkerd** [comment]
Hey @takuy 

You are correct there it should have been 'redraw(true)'

Cheers

Oli :)
