### ISSUE TITLE
cell.setValue() doesn't trigger validation

### ISSUE THREAD

**Issue by shadlan** [olifolkerd/tabulator#2075]
**Describe the bug**
Validator doesn't trigger on setValue(). 
I understand that the validator shouldn't trigger on setData (too much work to validate the whole input) or when the underlying data changes, but I expected it to trigger when changing a cell value with setValue.

**Tabulator Info**
I'm using tabulator v4.2.7

**Working Example**
https://jsfiddle.net/n3xmq5kt/

**To Reproduce**
Just play the fiddle

**Expected behavior**
The value at column "age" on the first row shouldn't change.

**Comment by olifolkerd** [comment]
Hey @shadlan 

Thanks for getting in touch.

As i have mentioned in several other posts, the API function calls will not validate input, Validators are set only to check user interactions with the table.

This is specifically allowed because it allows the developer to force the value of cells when they need to.

Cheers

Oli :)
