### ISSUE TITLE
Set minimum column width to header text content instead of truncate

### ISSUE THREAD

**Issue by cbracco** [olifolkerd/tabulator#2093]
Hey @olifolkerd! I am wondering if you’ve ever considered implementing an option to set the minimum column width to the width of its header text content, instead of a fixed value or none.

I am trying to avoid column header text wrapping onto multiple lines, and also avoid truncation so the user can see the full column header text (and horizontal scroll if they all don't fit in the container width). You can achieve this pretty easily using regular ol' tables, like so (resize the window to see what I mean): https://codepen.io/cbracco/pen/MdVQGa

Is this possible with Tabulator? If so I’m a bit stumped on how to get that going. Any help is appreciated. Thanks!

**Comment by aklaver** [comment]
Wouldn't fitColumns work?:
http://tabulator.info/docs/4.2/layout#fittowidth

**Comment by cbracco** [comment]
@aklaver Yes I am using that so the table is 100% width of its container, except I want to prevent both truncation and wrapping of each header's text content, so it is always one line, and always visible.

**Comment by aklaver** [comment]
Hmm, I'm going to have to think on this one.

**Comment by aklaver** [comment]
Thinking did not help:( This gets deeper in CSS then my understanding reaches at the moment.

**Comment by olifolkerd** [comment]
Hey @cbracco 

The ***fitData*** option respects column headers widths when determining minimum column size ad the purpose of that layout mode is matching the data in the columns.

That option isn't available in ***fitColumns*** because in that mode its priority is fitting the data into the column regardless of content of the columns.

You are looking for a hybrid mode between the two which isnt available im afraid. If you wanted to create your own layout mode have a look in the /src/js/layout.js file and see how the others are implemented.

Cheers

Oli :)
