### ISSUE TITLE
Retain expanded/collapsed state after data updation

### ISSUE THREAD

**Issue by anurag-23** [olifolkerd/tabulator#2096]
When a row or its children are expanded, and the row is then updated using any of the ways to update data (updateRow(), row.update(), setData(), etc.), the row and its children are automatically collapsed.

It would be great if the expanded state could persist across updates. Currently I'm using a custom function to expand all the previously-expanded rows after updates.

Absolutely love the library, btw!

**Comment by olifolkerd** [comment]
Hey @anurag-23 

Thanks for your kind words, it is great to hear you are enjoying using Tabulator.

Could i ask which version of Tabulator you are using, as they shouldnt change collapsed state on update.

Cheers

Oli :)

**Comment by anurag-23** [comment]
The tabulator version is 4.2.7

I'm trying it on Electron v4.0.7 which uses Chromium version 69.0.3497.128

This is reproducible on both Windows and Linux.

**Comment by olifolkerd** [comment]
Hey @anurag-23 

I have just made a push for this to the 4.6 branch. Which will be released in a few weeks

Trees will then maintain their open state on update as a default behaviour.

Cheers

Oli :)

**Comment by HammerData** [comment]
I'm using 4.9.3 (LOVING this library BTW) and still having this problem. I'm replacing the entire data array. I've tries setData, replaceData, updateData and reactivity both on and off.  In all cases, the tree collapses to its initial state.

**Comment by olifolkerd** [comment]
Do you have a link to a JS fiddle example? It would help to see how your table is configured.

Cheers

Oli

**Comment by HammerData** [comment]
This is highly simplified, but shows the problem. Expand the bottom branch and click the **Test Me** button.
https://jsfiddle.net/hammerdata/kspb2x9L/34/

**Comment by HammerData** [comment]
As I'm running into a number of issues doing something pretty complicated with dataTrees and drag-and-drop, it's looking like the most stable option is to update my underlying structure and regenerate the data. Which means I'm going to need to roll my own way of collecting the expanded nodes and resetting them after each update, unless there is a patch I can implement. I'm dragging and dropping rows to different parents and I'm not finding a way to move children around (since they aren't really rows) without Tabulator getting upset with me and having redraw issues, especially if the row did not already have children. This is not unexpected as I'm taking it someplace it was not meant to go, but that means the full data update needs to at least appear to retain state.

**Comment by rajniszp** [comment]
Still present in 5.6.1: https://jsfiddle.net/fsy86092/Lnp6ut5w/18/
and 6.4.0: https://jsfiddle.net/fsy86092/2j0o1zes/5/
(corrected duplicate ids, removed `dataTreeStartExpanded` to make sure it doesn't interfere, and added more buttons for testing different methods)
