### ISSUE TITLE
Ultra-light theme?

### ISSUE THREAD

**Issue by hrstoyanov** [olifolkerd/tabulator#2098]
**Is your feature request related to a problem? Please describe.**
I love the themes you already provide, especially the very visually light like from Bulma. 

**Describe the solution you'd like**
I wonder if it is possible to make it even lighter by removing cell boundaries, essentially turning 
the table into a "formatted list".

**Describe alternatives you've considered**
I am sure I can do that with custom theme, but wanted to suggest an official "borderless" theme.

**Additional context**
Take a look at the [List](https://getuikit.com/docs/list) I'd like something as light with 1,2,3 columns max, that looks as clean as a list, but is powered by a tabulator.

**Comment by olifolkerd** [comment]
Hey @hrstoyanov 

Thanks for getting in touch,

Im am now only adding in additional themes to match popular UI frameworks.

Any other themes users can easily make themselves by adjusting some of the SCSS variables in the existing theme.

As you can imagine, there are a great many possible themes out there, and i cant add them all to the core code base otherwise it will significantly bloat the size of the library.

Thanks for your suggestion

Cheers

Oli :)
