### ISSUE TITLE
deleting children does not remove expand icon

### ISSUE THREAD

**Issue by ray007** [olifolkerd/tabulator#2130]
**Describe the bug**
Setting the `_children` property of an item to null does not remove the expand icon.
Trying to expand the row later fails.

**Tabulator Info**
- Which version of Tabulator are you using?
4.2.7 as installed by npm

**Expected behavior**
The expand icon gets removed.
calling `redraw()` on the table also does not help here.

**Comment by fr0z3nfyr** [comment]
Why not just remove the element instead of setting it to `null`? if the item `_children` is present, there will be an expand collapse icon. I personally prefer to have it like this as the default behavior because it visually differentiates a group (container) from an item (content). For instance take an example of Product category and Products; every category will have an expand/collapse icon irrespective of whether it has any products or not.

Anyway, if you are processing the data before passing to Tabulator, try deleting the `_children` item instead of setting it to `null` and you will be all set.

**Comment by olifolkerd** [comment]
Hey @ray007 

This is specifically designed that way, it was requested to work that way by users to they could other bespoke child functionlaity and keep the tree icon present.

@fr0z3nfyr is right, you should just delete the property if you dont want the child rows.

Cheers

Oli :)

**Comment by ray007** [comment]
A property delete is not and cannot be reactive, so that does not work. Indicating children but not having them loaded works nicely with an empty array as `_children`.
What else would I need to do to make tabulator realize the row does not have children anymore?
