### ISSUE TITLE
The cursor and cell do not move together accordingly when resize

### ISSUE THREAD

**Issue by phanhuudinh** [olifolkerd/tabulator#2134]
**Describe the bug**
The cursor and cell do not move together accordingly when resize
The bug occur clearly when the zoom of screen not is 100%

**Step**
1. Go to tabulator homepage
2. Change the the page zoom to 125%
3. resize a column of table in homepage

**Screenshots**
![ezgif-2-f485bfcc48ee](https://user-images.githubusercontent.com/8196742/59181333-4a9f8d80-8b91-11e9-8ff0-c075ec87e3c6.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by tentus** [comment]
Can confirm this bug on Mac for Chrome, Firefox, even Safari.

Also it's worth noting that this problem applies even if the page is zoomed before page load, so switching steps 1 & 2 yields the same issue.

Oh, for posterity, at the time of this writing the Tabulator version is 4.2.7

**Comment by olifolkerd** [comment]
Yeah this is a bit of a nightmare, viewport scalling is really hit and miss and can be very inconsistent between browsers and operating systems.

Essentially at this point Tabulator dosn't guarantee perfect matching at other zoom levels because of the way that differnt systems report in terms of px when scalling is used

Oli :)
