### ISSUE TITLE
bottomCalc causes memory leak

### ISSUE THREAD

**Issue by bhanson-techempower** [olifolkerd/tabulator#2162]
**Describe the bug**

Memory leak when using `bottomCalc`

`ColumnComponent._column.cells` gets bigger infinitely

**Tabulator Info**

- Which version of Tabulator are you using? 4.2.7
- Post a copy of your construct object if possible so we can see how your table is setup. See jsfiddle

**Working Example**

https://jsfiddle.net/bhanson_techempower/s6fykugo/

**To Reproduce**

1. Run jsfiddle
2. Open console
3. Click on column header "Age" and check console
4. Close or open groups any number of times
5. Click on column header "Age" again and check console
6. See increasing cell count

**Expected behavior**

`column.getCells()` should return the same number of cells after each call

**Desktop (please complete the following information):**

 - OS: Windows 10 Version 1809 (Build 17763.557)
 - Browser: Chrome 75.0.3770.100

**Additional context**

https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L10765

We looked into it and found line 10765 pretty suspicious.

There seems to be a group display problem specifically on jsfiddle, ignore for the purposes of this issue.

**Comment by olifolkerd** [comment]
Hey @bhanson-techempower 

Thanks for the headsup, good spot,

i will have a look into that on the weekend.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @bhanson-techempower 

Thanks for the info. The line you referred to is very much needed as the cells have to be bound to the columns in order to be resized correctly when a user resizes the column etc.

The issue was that in classic render mode they were not being removed from the column binding when the calculation row was regenerated.

I have pushed a fix for this to the 4.3 branch along with another to fix the fact that the calculation row was not being hidden correctly when the group was hidden.

They will be available in tomorrows 4.3 release.

Cheers

Oli :)
