### ISSUE TITLE
Validation: providing an alternative behavior

### ISSUE THREAD

**Issue by joshkpeterson** [olifolkerd/tabulator#2212]
There are some choices that have been made about how validation works in tabulator that I think are really constraining.

It diverges from users' expectations, based on how html forms and excel spreadsheets work. Therefore I don't think it's a good UX to:

1. Prevent a user from exiting a cell / setting a cell's value because the new value is invalid. 
2. Validate only on blur (and not on change, as html forms usually would).

As a user, I want to be able to enter data and keep moving. Just set some style and state on the cell that it's invalid. Then for example you can query the tabulator object later to see if it has any cells that are invalid, and from there developer can choose what to do with that information (e.g. prevent a post or export).

At my current job, we have a ton of different apps that all need a data grid. I've been happy with tabulator in pretty much every other aspect, so **I'm interested in extending tabulator to have a different validation mode** you can choose that would have the softer behavior I'm describing. Does this sound like a feasible thing for me to pursue? Curious if existing validation behavior could be made to be sidestepped like this and if contributors have any thoughts or advice.

Thanks!

**Comment by olifolkerd** [comment]
Hey @joshkpeterson 

That sounds like a great idea,

I would be happy for you to submit a pull request, as a bit of guidance on content:

- Your changes should consider all users, not just your specific usage case, I will not accept changes that reduce functionality in one area just to fix an different usage case

- Internal functionality changes should call internal functions, the external API functions are for end users
 
- Please try and match Tabulators current coding style

-  Changes must be made to files in the ***src*** directory, the dist files are auto generated and changes there will be automatically overwritten on the next commit

In terms of how it could fit into the existing infrastructure:

- could you make and validation function specific changes in the ***/src/js/modules/validate.js*** file as i like to keep as much specific code as possible contained to the modules

- could you add a ***validationMode*** property to the table options object so there user can choose between ***blocking*** and your new mode of ***styled***, make it default to "blocking" so that the default behaviour of the table dosn't change on release, this can be set in the ***/src/js/core.js*** file in the ***defaultOptions*** object.

- The triggering of the validation systems can be found on line 169 of the ***/src/js/modules/edit.js*** file, essentially you would just need to alter the logic of this if, to trigger the current programmatic results of the success, but adding in the cell styling for failure if the new validation mode was set to "styled"

- you could then add a new method on the table to then retrieve the list of failed cells from the validate module, public functions are defined in the ***/src/js/core.js*** file

Let me know if that would work with you.

Cheers

Oli :)

**Comment by joshkpeterson** [comment]
@olifolkerd Thanks for this excellent feedback!

**Comment by olifolkerd** [comment]
If you have any other questions feel free to drop them into this issue,

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed an update for this to the 4.7 branch to offer several different validation modes.

Cheers

Oli :)
