### ISSUE TITLE
Documentation Error 

### ISSUE THREAD

**Issue by john159753** [olifolkerd/tabulator#2223]
Hi!

I believe if found an error on the tabulator documentation site. 
The Link: http://tabulator.info/docs/4.0/validate

At the section Custom Validator Functions, I was getting syntax error when using:
```
{title:"Age", field:"age", editor:"input", validator:[
		type:noDivide,
		parameters:{
			divisor:5,
		}
	]
}
```

I looked up a bit at other examples and found it using a curly brace, rather than a bracket.

Please do let me know if this should be submitted somewhere else!

-John

**Comment by olifolkerd** [comment]
Hey @john159753 

That is because you have copied the example incorrectly.

in your usage case it should be an array of objects `[{}]` you have used an array but not wrapped the object in curly braces so the syntax is invalid, it should be:
````js
{title:"Age", field:"age", editor:"input", validator:[{
		type:noDivide,
		parameters:{
			divisor:5,
		}
	}]
}
```

Also i note you are looking at the documentation for version 4.0, there have been significant updates since then, we are now on version 4.3

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Looking at the site, there was an issue in the 4.0 documentation that i have corrected, thanks for the heads up.

I would recommend using the latest version of Tabulator as it is full of performance improvements and bug fixes

Cheers

Oli :)
