### ISSUE TITLE
tabulator col heigth and width set to 0

### ISSUE THREAD

**Issue by Joan1899** [olifolkerd/tabulator#226]
Hi, in some tables I do not get header displayed for heigth and width of tabulator col are set to "0". In others I do not have this problem

Any hint?

**Comment by olifolkerd** [comment]
Hey,

This usually occurs when the tabulator is defined on an element when it is hidden or has a display property set to ***none***.

This happens because when hidden the element has no height or width, so tabulator cannot calculate the correct dimensions for all the elements it contains.

To get round this you need to call the ***redraw*** function when you show the table, this will cause tabulator to recalculate the size of all the elements it contains.

```js
$("#example-table").tabulator("redraw", true);
```

Let me know if that helps.

Cheers

Oli

**Comment by Joan1899** [comment]
Hi,

I am not sure where to call the redraw method. I am making a Column manager to show which cols are displayed and which not.

I want to load the table in a bootstrap modal, where should I call redraw?

THX!

**Comment by olifolkerd** [comment]
You can bind to the ***shown.bs.modal*** event on the modal

```js
$('#modal-content').on('shown.bs.modal', function() {
    $("#example-table").tabulator("redraw", true);
})
```

Let me know if that helps.

Cheers

Oli

**Comment by Joan1899** [comment]
Tested, it works. Thanks a lot
