### ISSUE TITLE
Scrolling Bug - Last dozen rows not rendering

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2267]
Here is a gif of the scrolling bug occurring. 

https://imgur.com/a/YNmjopK

When you start scrolling everything is fine, but as you scroll further down, more and more of the bottom rows in the view stop being rendered.

Also, when you scroll back to the top, the rows are still not rendered.

And finally, the table starts resizing itself after scrolling back to the top, and if you scroll down it resizes back... Very weird.

This happens only when the grouping is enabled.

**Comment by aklaver** [comment]
This needs more information. When filing a bug report please use the Bug Report template here:
https://github.com/olifolkerd/tabulator/issues/new/choose
In this case please supply:
1) Tabulator version
2) OS(version) and Browser(version)
3) The table constructor for your Tabulator table

**Comment by 8483** [comment]
I apologize.

1. Version 4.3
2. OS Windows 10 Pro Version 1803/ Browser Chrome 75.0.3770.142 (Official Build) (64-bit)
3. Table constructor

```javascript
let table = new Tabulator("#content-full", {
            height: "100%",
            data: data,
            groupBy: "odgovoren",
            groupStartOpen: false,
            groupToggleElement: "header",
            layout: "fitColumns",
            columns: [
                { title: "Одговoрен", field: "odgovoren" },
                { title: "Шифра", field: "sifra" },
                { title: "Фирма", field: "firma", formatter: companyLinkFormatter, bottomCalc: "count" },
                { title: "Вид", field: "vid" },
                { title: "Просек Промет Годишен", field: "avgRev", formatter: numberFormatter, bottomCalc: "sum" },
                { title: "Последнa Продажба Денови", field: "lastSaleDays", formatter: numberFormatter },
                { title: "Старост Години", field: "age", formatter: oneDecimalFormatter },
            ]
        });
```

**Comment by aklaver** [comment]
How big is data and where is it coming from?
What are the formatters doing?
Does the browser console show any errors?

**Comment by 8483** [comment]
I edited the code above with the formatters.

The data in this scrolling case is a 2 MB JSON array of 10,700 objects.

The console shows no errors, but ironically, the bug doesn't occur when the console is opened.

**Comment by aklaver** [comment]
My suspicion is that  it is a due to formatting/grouping of 10,700 objects not rendering fast enough to keep up with the scroll. I have seen that console behavior before. Not sure why though I suspect writing to the console slows down other operations enough to make them render in time. To narrow this down I would try:
1) A smaller data set.
2) Play with the render buffer:
http://tabulator.info/docs/4.3/layout#virtual-dom-buffer

**Comment by aklaver** [comment]
Did this happen in previous versions of Tabulator?

**Comment by olifolkerd** [comment]
Hey @8483 

This will be because the table has resized and tabulator has not be told, this issue has been covered ad nausium in about 100 other issues and extensively in various parts of the website.

Elements in the DOM are not aware of when they are resized, so if the table is declared on a hidden element, or on an element that changes height after initialization you have to call the ***redraw*** function on the table to let it know hit has been resized and to allow the table to adjust the virutal DOM row buffers appropriately,

I would bet this dosnt happen if you use the table in Chrome. This is because chrome implements a new feature called the ResizeObserver that Tabulator uses to detect when the element is visible/changes size. At the moment this feature is only available in chrome but the good news is it is planned for most other browsers in their next releases.

I hope that helps,

Cheers

Oli :)

**Comment by aklaver** [comment]
@olifolkerd  This is happening using Chrome. Also from what I see in the GIF the table is not being resized, the user is just scrolling.

**Comment by olifolkerd** [comment]
It will have been resized at some point

**Comment by aklaver** [comment]
Even if that is the case, Chrome is being used so the resize should be caught and dealt with, correct?
