### ISSUE TITLE
Import Data from HTML <table>, ADD editor="input" (full example + screenshot)

### ISSUE THREAD

**Issue by G-WAN** [olifolkerd/tabulator#2274]
Version 4.3 and Firefox 68.0.1 (latest version): building from HTML `<table>` works fine, but then I need to add Column features.

Setting up an `editor` fails to work properly (here is the whole HTML + JS code):
```
<!DOCTYPE html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="css/tabulator_site.css">
<script type="text/javascript" src="js/tabulator.js"></script>
</head><body>
<table id="tablexxx">
 <tr><th>Name</th><th>Favorite Color</th><th>date</th></tr>
 <tr><td>Bob</td><td>Yellow</td><td>1/1/2001</td></tr>
 <tr><td>Michelle</td><td>Purple</td><td>2/1/2000</td> </tr>
</table>
<div id="tablexxx"></div>

<script>
var tablexxx = new Tabulator("#tablexxx",{
 height:"100%",
 virtualDom:true,
 index:'id',
 initialSort:[{column:"id",dir:"asc"}],
 columnHeaderSortMulti:false,
 resizableColumns:true,
 layout:"fitDataFill",
 tooltips:true, tooltipsHeader:true,
 selectable:true,
 pagination:"local", 
 paginationSize:14,
 paginationButtonCount:1,
 persistenceID:"tablex",
 persistenceMode:"cookie",
 persistentLayout:true,
 columns:[
  {title:"id",field:"id",sorter:"number",sorterParams:{alignEmptyValues:"top"}},
 ],
 });

var colDefs = tablexxx.getColumnDefinitions(); // array 
 for(var i = 0; i < colDefs.length; i++) 
 {  if((i % 2) == 0) // 1/2 will be "input", the other half will be "select"
       colDefs[i].editor = "input"; 
    else
    {  colDefs[i].editor = "select";
       colDefs[i].editorParams = function(cell)
       { var rows = tablexxx.getRows(); //create option-list of column values
         var values = {};
         rows.forEach(function(row){ var data = row.getData();
                         values[data.fullname] = data.fullname;
                      });
         return {values:values};
       }
    }
 }
 tablexxx.setColumns(colDefs); 
</script>
</body></html>
```
When I click to edit a cell **the edited text gets blank** and **for "select" the list shows "undefined"**. Yet, if I type in something and press ENTER, **the edits are kept by the table field** (but they cumulate instead of replacing the previous value).

How can I make this work? Do you have an alternate way?

![tabulator-bad-edit-bug](https://user-images.githubusercontent.com/506161/62822012-f6f3f500-bb7d-11e9-91e0-cfb0916e0d6e.png)

**Comment by G-WAN** [comment]
Feedback (that I hope will be useful):

The non-working Javascript code above was copied & pasted from your [website](http://tabulator.info/docs/4.2/edit) (search "values[data.fullname] = data.fullname;").

As many of your examples are using "deprecated" functions, incorrect syntax, partial declarations, or third-party libraries (being only relevant as reminders for those ALREADY KNOWING your library).

Also, most of your JS library code is made SLOWER THAN NECESSARY by using multi-level nested function calls through `x.forEach(function()` instead of ([much faster](https://jsperf.com/for-vs-foreach/9)) `for(;;)` loops.

For what it's worth, here is my working version of your non-working code:
```
 // for each colum, add an 'editor'
 // "select" requires... values:{"blue":"blue", "red":"red", "?":"?"}
 var colDefs = tablexxx.getColumnDefinitions();
 for(var i = 0; i < colDefs.length; i++) 
 { if(!(i % 2)) colDefs[i].editor = "input"; 
   else
   { var colName = colDefs[i].field;
     var rows = tablexxx.getRows(); // create option-list of column values
     var vals = {};
     for(var j = 0; j < rows.length; j++)
     {  var data = rows[j].getData();
        vals[data[colName]] = data[colName];
     }
     colDefs[i].editor = "select";
     colDefs[i].editorParams = {values:vals};
   }
 }
 tablexxx.setColumns(colDefs); 
```
TIP: Dont't make it harder than necessary for users to enjoy using your product.

**Comment by olifolkerd** [comment]
With all due respect @G-WAN please keep a civil tone when messaging on this issue list.

By your own admission you are not that well acquainted with JavaScript, this is a complex library and is not here as a guide in how to use JavaScript/HTML from scratch. While it does appear that you have struggled getting set up there are tens of thousands of users (including large corporations and government branches) who have had absolutely no problem getting setup with Tabulator so possibly consider that before rushing in with brash comments.

And with all due respect in this case it is your poorly formatted HTML that is causing the extra line in the table, the documentation clearly highlights the need to use the correct ***thead*** and ***tbody*** elements.

I dont ask users to pay for a license because the whole point of Tabulator is to be free for people to use, this is not a money making exercise. If you dont feel that Tabulator meets your needs then please feel free to use one of the many other libraries out there that may be a better match for you.

There are no dependencies on 3rd party libraries anywhere in the core of Tabulator. The only external dependencies are for date sorting and for some of the downloaders, and where they are used they are clearly marked in the documentation with links to the libraries in question. *(all examples contain a clear link back to the detailed documentation for that area)*. Tabulator is one of the most dependency free of all of the table generation libraries.

I agree with you on the for loops and you will see that in each release i add performance enhancements in the code base, Tabulator has evolved from a very simple table building system into an advanced tool and it can take time to implement systemic updates. There are a number of hangovers from its old jQuery days that are slowly being removed with each release so as not to delay new features reaching the user base. There is infact a specific issue that exists to keep users up to date with the performance improvements in each release.

If there are any specific areas you notice on the website that you feel are outdated i would be very happy to review them, but please create and issue and be specific, a URL and description of the issue would be most helpful.

Tabulator is an extensive library with extensive documentation and while i make my best efforts to keep it up to date as i update the library things do get missed from time to time, as you will see from previous closed issues i am always happy to promptly update any that people notice issues with.

Please ensure you keep a civil tone on these issue lists or you will not be welcome to post again.

Many Thanks

Oli :)
