### ISSUE TITLE
HI, i have to implement multiple filter on header filter .So i am trying to have dropdown menu in header filter on click of filter like icon it is not working .is it possible to have dropdown menu in header filter ? if yes pls reply

### ISSUE THREAD

**Issue by balajis-13395** [olifolkerd/tabulator#2275]
Please ask questions on www.stackoverflow.com the issues list is now reserved for feature requests and bug reports.

Cheers

Oli :)

**Comment by Remph** [comment]
I think you want to have them in your headers, not in the filter field, right? If so, I asked this question some months ago and I think it could help you, too, because Oli already had an amazing answer: 

[Tabulator - Add menu button to column header](https://stackoverflow.com/questions/53301995/tabulator-add-menu-button-to-column-header)

Please use Stack Overflow for further questions regarding Tabulator.

**Comment by balajis-13395** [comment]
Thanks for your response. I tried that But custom header filter editor won't work. Dropdown menu have to part of header filter editor . If you find solution for that. please help

**Comment by olifolkerd** [comment]
@balajis-13395 

The [Header Filter Example](http://tabulator.info/examples/4.3#filter-header) contains an example of multiple filters in one column header in the progress column.

Cheers

Oli :)
