### ISSUE TITLE
Column.getCells() returns only the VISIBLE (paged) entries

### ISSUE THREAD

**Issue by G-WAN** [olifolkerd/tabulator#2282]
The code below is reformat Dates for all Columns which Title contains 'date'... but only for the VISIBLE entries (pressing the `[Next]` page button shows old-format Dates).

Wheter or not this is the intended behavior, you can force `Column.getCells(true)` to return ALL the column entries to avoid breaking existing code (and extend the function's reach).

```
 var xxxtable = new Tabulator("#ex-table",{
 height:"100%",
 virtualDom:true,
 autoColumns:true,
 resizableColumns:true,
 layout:"fitDataFill",
 tooltips:true, tooltipsHeader:true,
 selectable:true,
 pagination:"local", // load all data, then generate paged view
 paginationSize:14,
 paginationButtonCount:1,
 persistenceID:"tablex",
 persistenceMode:"cookie",
 persistentLayout:true,
 });

 // ---------------------------------------------------------------------------- 
 // change D/M/YYYY dates to DD/MM/YYYY dates in all columns containing 'date'
 // ---------------------------------------------------------------------------- 
 { var cols = xxxtable.getColumns();
   for(var i = 0; i < cols.length; i++)
   { var colName = cols[i].getField();
     if(colName.indexOf("date") >= 0)
     {  var dateColumn = xxxtable.getColumn(colName);
        for(var cell of dateColumn.getCells()) 
        { var value = cell.getValue();
          if(value && value.length < 10)
          { value = value.split("/");
            cell.setValue(padDate(value[0], 2) + "/" 
                + padDate(value[1], 2) + "/" + value[2]);
          }
        }
     }
   }
 } 
```
Any other way to resolve this issue in the meantime is more than welcome!  =)

**Comment by aklaver** [comment]
Tabulator version?
I am not sure what the issue is:
1) Do you want all visible entries or not?
2) I see nothing in column.js that responds to true. So where are you calling that? Also I see no difference when using getCells here. Tabulator 4.3.0.

Also could the above not be simplified using forEach() over cols? Then you would have direct access to the column.
FYI, virtual DOM is turned on with a height setting. All the virtualDom setting can do is turn it off by setting it to false

**Comment by G-WAN** [comment]
Tabulator v4.3 (latest)

1. YES, we would like to get all Cell entries for the specified Column (and that's most likely what everyone is expecting given your documentation).

2. 'true' is only a suggestion - it is obviously not implemented yet (if it was, I would have not been bothering you).

3. "Could the above not be simplified using forEach() over cols?" Maybe but I don't know how to do it.

Again, even if you know another way to access these Column's Cells (like from getData()) I am welcoming any alternative to my code. My only goal is to make my application work.

**Comment by aklaver** [comment]
Alright I missed the pagination part of the code. In that case col.getCells() only fetches the displayed page cells. Not sure how that behavior can be changed.  The best bet at the moment for would to use table.getData() and iterate over the 'date' column.  Something like:
```
data = table.getData()
data.forEach(function(row){Object.keys(row).forEach(function(ky){if (ky.indexOf("date") >= 0){your_code}} )})
```

**Comment by aklaver** [comment]
Once I started thinking about this I realized  you can't have this and virtual DOM at the same time. Cells are the rendered portion of the table and virtual DOM restricts the rendering(assuming a large enough data set) to a subset of the data. You can see this by setting virtualDom: false in the table constructor. In that case all the cells are available via col.getCells(),  at the cost of the overhead of rendering them all.  So your options are:
1) Don't use virtual DOM if you want col.getCells() to fetch all cells.
2) Use virtual DOM and:
       a) Use table.getData() as shown above.
           OR
       b) Do the date manipulation before you send it to the table.

**Comment by G-WAN** [comment]
I also figured that (about the virtual DOM) but we don't always have the choice of our options.

I can't manage to get access to the Cells via dateColumn.getCells() with your suggested code - could you please complete it or correct my attempt below:

```
  data = xxxtable.getData();
  data.forEach(function(row)
  { Object.keys(row).forEach(function(ky)
    { if(ky.indexOf("date") >= 0)
      { var dateColumn = xxxtable.getColumn(ky); // wrong
        for(var cell of dateColumn.getCells())   // "TypeError: dateColumn.getCells is not a function" 
        { var value = cell.getValue();
          if(value && value.length < 10)
          { value = value.split("/");
            cell.setValue(padDate(value[0], 2) + "/" 
                + padDate(value[1], 2) + "/" + value[2]);
          }
        }
      }
    });
  });

```
Thank you!

**Comment by aklaver** [comment]
The whole point of the code was not to use col.getCells() as it would limit it you to the rendered cells only.  By using tbl.getData() you have access to the complete data set. The forEach loops over that data, which is an array of objects. The Object.keys(row).forEach then loops over the row object keys(field names) so you can search for those have 'date' in their name.  If the ky.indexOf('date') is true then you can change  that fields data. Their is no need to use col.getCells().  The error you are getting is because dateColumn is not a column component. If you want to track that down put in some console logs to see what ky and xxxtable.getColumn(ky) are actually returning.  That being said the best thing would be to avoid that and work on the value directly. So something like:

```
{ if(ky.indexOf("date") >= 0){
   var value = row[ky];
   if(value && value.length < 10){
         value = value.split("/");
         var  new _value = padDate(value[0], 2) + "/" 
                + padDate(value[1], 2) + "/" + value[2];
         xxxtable.updateData([{id: row[id], ky: new_value}]);
     }

}

```
See:
http://tabulator.info/docs/4.3/update#alter-update

For what the id field is for. Basically it should point at whatever you have set as the index on the table.

**Comment by G-WAN** [comment]
My bad, you are absolutely right - and thank you for bringing me back on track. There are so many things about Javascript that are foreign to me (using data as part of the function names(!), thousands of functions that have no reason to exist in other languages like C, etc.) that sometimes there's the temptation not to engage brains and just say "I don't get it". That was my reptilian brain acting this time - during a very busy day. That's great to have a helping hand at such times. Thank you again.

**Comment by aklaver** [comment]
I'm new to Javascript also and I have found:
       https://developer.mozilla.org/en-US/docs/Web
to be a good resource.

**Comment by G-WAN** [comment]
Thanks, but the real issue is how a language is used - or misused, and our few exchanges have demonstrated on which side [Tabulator stands](https://github.com/olifolkerd/tabulator/issues/2274#issuecomment-520168144)... going as far as to DELETE the posts where the project leader was wrong (and edit my prose elsewhere):
![tabulator-leadership](https://user-images.githubusercontent.com/506161/62829828-b12d4000-bc02-11e9-953e-a89355c59127.png)

**Comment by olifolkerd** [comment]
@G-WAN 

In this case this is because you are using the wrong tool, you should be using a [Mutator](http://tabulator.info/docs/4.3/mutators#mutators) if you want to manipulate the data itself.

Formatters are only to be used only as a visual effect that is run at the row is formatted for display.

The whole point of the virtual DOM is that it reduces the overhead on the system during the initial load by only generating elements of the table as they are needed, which means that until a row is first scrolled into view it is not available for manipulation.

I understand there is a bit of overhead to learning how a new library works, but please do not overly your expectations on how the table works to what others think. Tabulator has been around for years and its operation has been heavily guided by feedback from the userbase.

If you have a specific application you need to work towards then please consider posting a request asking "how do i" and experienced users can point you in the right direction. using a new library means adapting to the paradigm in which it is written so please approach it from that point of view. 

and with reguard to your last comment, the code not mis-used at all, the ***thead*** and ***tbody*** tags are specifically designed for delineating the header and footer of the table. which is exactly what Tabulator requires to determine the header and footer of the table. please see documentation [here](https://www.w3schools.com/tags/tag_thead.asp) If you do not format your data to fit the input expectation of Tabulator, that are clearly outlined in the documentation then it is no surprise that it misinterprets your table.

Cheers

Oli :)
