### ISSUE TITLE
Prevent specific columns from being reordered with movableColumns

### ISSUE THREAD

**Issue by rhagstrand** [olifolkerd/tabulator#2296]
**Is your feature request related to a problem? Please describe.**
Im having an issue where a table needs to be "partly" reorganized. So for instance the first 3 columns in my table need to be "locked" and not movable, but the remaining 5 columns should be movable and reordered as the user pleases.

**Describe the solution you'd like**
Maybe a callback event BEFORE a column is about to be moved, so I can check where the column is about to be inserted and something that makes it possible to abort it. Or an attribute on column-level "movable = false" or something.

**Describe alternatives you've considered**
If this can be achieved with the current columnMoved callback please enlighten me :)

**Additional context**
-

**Comment by olifolkerd** [comment]
Hey @rhagstrand 

You are not the first person to ask for this, but i find it a locially odd proposition.

Yes you could lock the column in place, but if other columns can move they could be moved from one side of it to the other, essentially moving that column any way, which is why the feature is not available.

You do have the ability to freeze columns on the left and right of the table but that is the limit of the system.

Cheers

Oli :)
