### ISSUE TITLE
Rendering table on Modal screen doesn't show headers on sub-secuent calls

### ISSUE THREAD

**Issue by sanleong** [olifolkerd/tabulator#230]
Hi,
I'm showing data results in a modal screen like showing in the attachment. But after close the modal window, if I call again the modal view the result doesn't show the header titles. Any idea?

![modal1](https://cloud.githubusercontent.com/assets/1580031/24209590/1831e860-0efd-11e7-9423-be4eb9422c5f.png)
![modal2](https://cloud.githubusercontent.com/assets/1580031/24209599/1d1cb26a-0efd-11e7-85e1-788e54645eda.png)
I'm using jquery jquery-2.1.0.min.js and 1.10.4/jquery-ui.js

**Comment by olifolkerd** [comment]
Hey,

That is because you are populating it when the table is hidden, so it cannot calculate the dimensions of the header correctly as hidden DOM elements have no dimensions.

If you call the ***redraw*** function as soon as the table is visibile it will fix this:
```js
$("#example-table").tabulator("redraw", true);
```

Let me know if that solves your issue.

Cheers

Oli

**Comment by sanleong** [comment]
Owesome!!!
You nailed man! Thanks very much. This was bugging my head for days. By the way, outstanding library you have here.
Best regards
Gilbert

**Comment by olifolkerd** [comment]
Thanks Gilbert!

Always happy to help!
