### ISSUE TITLE
Table data inside model is empty on page load.

### ISSUE THREAD

**Issue by venkatdev22** [olifolkerd/tabulator#2305]
Table data inside model is empty on page load. While i open model, row html getting created, while closing model, again row html are getting disappeared. If I remove the model class in div, table rendering properly on page load.

**Comment by olifolkerd** [comment]
This is happening because you are loading data into the table before it is visible which means it can't render it. You need to call the redraw function on the table after the dialog has been made visible

**Comment by venkatdev22** [comment]
Appreciate your quick response. So with the parent div model hidden, if I have to access the table element on page load, I have to directly access the Tabulator object instead of relying on table html elements. Make sense ? 

Currently, without redraw the table elements, creates, recreates and deletes properly while I open close my model. So when exactly redraw requires ?

**Comment by olifolkerd** [comment]
Because hidden elements have no dimessions untill they are first made visible on the DOM This means that Tabulator cannot correctly draw its contents as it isnt aware how big everything is.

That is why it either has to be visible to start with or ***redraw*** has to be called once it is visible to force it to redraw.

Cheers

Oli :)
