### ISSUE TITLE
Add "latest" option in docs

### ISSUE THREAD

**Issue by BernhardBaumrock** [olifolkerd/tabulator#2322]
Thx for this awesome project!!!

I'm developing a module for the ProcessWire CMS and link to the docs in several locations. It would be nice to have an option to link to the latest docs, for example

```
http://tabulator.info/docs/latest/callbacks
http://tabulator.info/docs/callbacks
```

instead of `http://tabulator.info/docs/4.4/callbacks` which will be outdated on the next update...

Thx in advance :)

**Comment by 805bluebell** [comment]
Of course, it makes sense to use the latest version as more features are added with lesser bugs. @olifolkerd is not very verbose whether older versions are unsupported. That's certainly a user's choice to choose.

**Comment by BernhardBaumrock** [comment]
I don't understand your comment. I'm talking about links to sections in the docs. I'm not talking about referencing latest version of code in some script tag or the like...

**Comment by 805bluebell** [comment]
Sorry to confuse you. I am talking about the documentation part only. 
It just makes more sense to refer docs based on the version you are using. For eg:
`http://tabulator.info/docs/4.0/callbacks`
than
`http://tabulator.info/docs/latest/callbacks`
since a user might not be using the latest version and looking at the latest might be useless for him.

**Comment by BernhardBaumrock** [comment]
Ah, thx, now I get your point :) Yeah, true. I'll close this issue as I'm not sure about it any more myself...
