### ISSUE TITLE
feat: add new cell callback - onDestroy (needed for custom Angular components integration)

### ISSUE THREAD

**Issue by britvik** [olifolkerd/tabulator#2372]
Hi :),

I'm using Tabulator in an Angular 8 application and I would like to render Angular components inside the table.

I'm able to do so thanks to `editor` / `formatter` cell options, but the problem is - I'm unable to unregister the components when the rows/cells get removed or redrawn. I'm afraid of memory leaks.

What I would need is a callback (just like onRendered in formatter/editor) that would be called, when cell gets destroyed (removed from DOM).

**Comment by olifolkerd** [comment]
Hey @britvik 

Once the row is destroyed all DOM elements should be destroyed by the browser garbage collector as long as you arnt trying to reference them in the rest of your app.

Because of the virtual DOM rows/cell elements are created the moment the row is first scrolled into view, and then removed from the DOM when it is scrolled away, the same elements are then readded to the dom when it is scrolled back into view,  it is not a simple matter to define "destroyed" as such

If you feel you are having specific issues please post a link to a JS Fiddle so we can see it in action, we could then provide feedback on the best approach to handle this.

Cheers

Oli :)
