### ISSUE TITLE
Better support for Vue-Components as custom Cell-Formatter

### ISSUE THREAD

**Issue by bertoverflow** [olifolkerd/tabulator#2388]
**Is your feature request related to a problem? Please describe.**
I want to use Vue-Components as a Cell-Formatter. Tabulator does not provide this functionality natively, but there is a workaround: You can create Vue-Components dynamically and return the rendered DOM-Node in the Formatter. See here for example: #2330 

The problem now is: When the Cell with the Vue-Component moves out of the currently displayed Table-Window of the Virtual DOM it gets detached, but the Vue-Component itself does not get destroyed (i.e. the according Vue-Lifecycle-Hook is not called, so you cannot do any cleanup). This will lead to a memory-leak.

I guess the same problem also exists when the value of the cell is changed: Every time a new Vue-Component will be initialised (instead of reusing the old one).

**Describe the solution you'd like**
I guess there are two solutions:
a) Support Vue-Components as "First-Class-Citizens", that is Tabulator will "know" when a provided Custom Cell-Formatter is a Vue-Component and act accordingly:
* call the destroy-Method on it whenever a Cell with a Vue-Component gets removed from the DOM
* update the value-Prop of the Vue-Component, when the Cell gets Updated
* ???

b) Let the use manage the Vue-Components himself. For this to work, a Cell-Formatter would need two additional callbacks (similar to "onCellRendered")
* onCellDetached: should be called when the Cell gets removed from the DOM, so the user can manually call the destroy-Method on the Vue-Compnent
* onCellUpdated: should be called when the value of the cell changed (Note: I guess this can already be done with the current events - I just could not wrap my head around this yet)

**Additional context**
I would be happy to hear your opinion on this topic. Thanks for your awesome table-library.

**Comment by olifolkerd** [comment]
Hey @bertoverflow 

It is the correct behaviour that it is not destroyed when it is scrolled out of view.

The contents of normal cells are created the first time the row is visible, then detached from the DOM, not destroyed, when it is scrolled out of view, so that it is faster and less work for it to be rendered when the row is next scrolled back into focus.

When a row is deleted all its cells and their DOM elements are also deleted, the browsers garbage collector then clears out the unlinked elements

you could use the rowDeleted callback for this.

Cheers

Oli :)
