### ISSUE TITLE
How to have two themes of tabulator in one project

### ISSUE THREAD

**Issue by ajith-om** [olifolkerd/tabulator#2390]
I have a application, where i use tabulator for multiple functionalities. Suppose I have tow tables, I would like to have two themes for two tables. How do i implement this ?

**Comment by olifolkerd** [comment]
Hey @ajith-om,

You would have to add a class to one of the tables to differentiate it for a different style, then update the css in one of the theme css files to select for that class instead of ***.tabulator***

You can actually see this in action on the [Theming Examples](http://tabulator.info/examples/4.3#theming)

Some of the themes do have issues working together so depending on the combination you may need to tweak the CSS in places

I hope that helps,

Cheers

Oli :)
