### ISSUE TITLE
table row text splitting on pages when printing

### ISSUE THREAD

**Issue by dcliffclank** [olifolkerd/tabulator#2401]
**Describe the bug**
when the table is printed the page break sometimes occurs where the top of a sentence
prints one one page and finishes on next. cut in half. illegible on either page.

**Tabulator Info**
- Which version of Tabulator are you using?
- Post a copy of your construct object if possible so we can see how your table is setup

**Working Example**
every single table ive every made.

**To Reproduce**
make any table containing typical text only content.
try to print it.

**Expected behavior**
expect-> css page-break-inside: avoid;

**Screenshots**
![tabulator_printing_cut](https://user-images.githubusercontent.com/56079834/66050472-e6635980-e4f2-11e9-9524-8d9b6c62f455.PNG)

**Comment by olifolkerd** [comment]
Hey @dcliffclank 

Without knowing how your table is setup and which version of Tabulator you are using it is very hard to offer you advice.

The "working example" section of the issue template is asking you to provide a link to a JSFiddle or CodePen so that i can see an example of the table you are having issues with, simply saying "every table" dosnt help me get the bottom of how your table is setup.

If you are having issues it is likely because Tabulator is built of DIV not table elements therefore the browser does not know how to handle it on page breaks.

if you are using version 4.4+ you can use the new [Printing Functionality](http://tabulator.info/docs/4.4/print) to ensure a correctly formatted print experience.

I hope that helps,

Cheers

Oli :)
