### ISSUE TITLE
Updated data after tree child edit not rendered

### ISSUE THREAD

**Issue by roxuss** [olifolkerd/tabulator#2404]
calling updateData in the cellEdited function with a new value for another column in the row (I havent checked on updating another row entirely tho) does not render the new result until the tree expand/collapse is used, or the cell of any tree root is updated.

**Tabulator Info**
v4.4.3

**Working Example**
https://jsfiddle.net/cekbxz6r/2/

**To Reproduce**
If you change the Count of 4. You can force a render by collapse and expand any tree element or put a value in root elements Count (1 or 5)

**Expected behavior**
Change "Count" of 2,3,4 or 6 and expect Value to be updated without further interaction

**Desktop (please complete the following information):**
 - OS: Linux 4.19.58-v7l+ #1245 SMP Fri Jul 12 17:31:45 BST 2019 armv7l GNU/Linux
 - Browser Chromium
 - Version Version 74.0.3729.157 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)

**Comment by olifolkerd** [comment]
Hey @roxuss 

Thanks for getting in touch.

The main issue is your are using the wrong function, you should use the ***update*** function on the row component:
```js
cellEdited:function(cell) {
	var row = cell.getRow();
	var data = row.getData();

	row.update({Value:data.Count * data.Cost})
}
```

Also as an alternative, if the value column is never actually set in the initial data, you could look to use a [Mutator](http://tabulator.info/docs/4.4/mutators#mutators) to generate the contents instead of the cellEdited function,  

I hope that helps,

Cheers

Oli :)
