### ISSUE TITLE
moment is required package but not mentioned in docs anywhere

### ISSUE THREAD

**Issue by niftylettuce** [olifolkerd/tabulator#2422]
We should swap out moment with a pure implementation (it seems to only be used in 4 places in the codebase, specifically in `src/js/modules/format.js`:

```js
	datetime:function(cell, formatterParams, onRendered){
		var inputFormat = formatterParams.inputFormat || "YYYY-MM-DD hh:mm:ss";
		var	outputFormat = formatterParams.outputFormat || "DD/MM/YYYY hh:mm:ss";
		var	invalid = typeof formatterParams.invalidPlaceholder !== "undefined" ? formatterParams.invalidPlaceholder : "";
		var value = cell.getValue();

		var newDatetime = moment(value, inputFormat);

		if(newDatetime.isValid()){
			return newDatetime.format(outputFormat);
		}else{

			if(invalid === true){
				return value;
			}else if(typeof invalid === "function"){
				return invalid(value);
			}else{
				return invalid;
			}
		}
	},

	datetimediff: function datetime(cell, formatterParams, onRendered) {
		var inputFormat = formatterParams.inputFormat || "YYYY-MM-DD hh:mm:ss";
		var invalid = typeof formatterParams.invalidPlaceholder !== "undefined" ? formatterParams.invalidPlaceholder : "";
		var suffix = typeof formatterParams.suffix !== "undefined" ? formatterParams.suffix : false;
		var unit = typeof formatterParams.unit !== "undefined" ? formatterParams.unit : undefined;
		var humanize = typeof formatterParams.humanize !== "undefined" ? formatterParams.humanize : false;
		var date = typeof formatterParams.date !== "undefined" ? formatterParams.date : moment();
		var value = cell.getValue();

		var newDatetime = moment(value, inputFormat);

		if (newDatetime.isValid()) {
			if(humanize){
				return moment.duration(newDatetime.diff(date)).humanize(suffix);
```

If you don't have moment installed client-side then you will get an uncaught error.  Also, we shouldn't be using moment, it's unmaintained and has so many core bugs, we should use dayjs instead <https://github.com/iamkun/dayjs>.

**Comment by olifolkerd** [comment]
Hey @niftylettuce 

Moment.js is not required for normal operation of Tabulator, it is only required if you are using date  or time sorter/filters. if you check the [Sorter Documentation](http://tabulator.info/docs/4.4/sort#func-builtin) you will see it clearly marked under each of the sorter that moment.js is required for the sorter to work.

I would not consider moment JS unmaintained at all, yes it has been a few months since a commit, but that can happen on all libraries when the core developer has to take a step back for a bit to deal with things in life, people cannot expect free libraries to be constantly maintained on a day by day basis.

I would not be looking to make Tabulator handle dates natively, date handling on a global scale is an extremely complicated task (remember Tabulator is used all over the world so it isnt just about handling western date formatting) so i will leave that to those libraries that do it well.

I would be happy to look other date libraries as alternatives, but i only make changed on that scale at major version changes. The next one (v5.0) isnt scheduled till May 2020 at the moment.

Thanks for your feedback

Cheers

Oli :)
