### ISSUE TITLE
Column name containing a dot - doesn't load data

### ISSUE THREAD

**Issue by cezary-z** [olifolkerd/tabulator#2474]
**Describe the bug**
I've tried to create a Tabulator object from a html table and noticed that for the columns that contained a dot in the column name the data was empty. When I removed the dot the data appeared normally.

**Tabulator Info**
- Version 4.4
- var table = new Tabulator(tableId);

**To Reproduce**
1. Create a html table with thead and tbody containing some data.
2. Add a dot to a chosen column name
3. Create a new Tabulator object from that html table
4. The columns that have the dot in the name have empty data.

**Comment by olifolkerd** [comment]
Hey @cezary-z 

This isnt a bug, this is an intentional feature, by default dot notation is used to denote that the field is referencing a nested object, it is extremely bad practice to use dots in object properties, they should be alpha numeric only.

If you need to use dots in your property names you can use the ***nestedFieldSeparator*** option to change this to a different symbol thus making your table treat them as simple properties.

More information on this can be found in the [Nested Data Documentation](http://tabulator.info/docs/4.4/columns#field-nesting)

Cheers

Oli :)
