### ISSUE TITLE
Table doesn't resize correctly when in a css grid

### ISSUE THREAD

**Issue by cfarmerga** [olifolkerd/tabulator#2477]
**Describe the bug**

When inside a css grid, the tabulator table resizes correctly when it's made wider, but not when it's made narrower.

**Tabulator Info**

Tabulator 4.4.3
```
var data = [
    { name: '1', description: 'Description of thing 1', location: 'Location 1' },
    { name: '2', description: 'Description of thing 2', location: 'Location 2' },
    { name: '3', description: 'Description of thing 3', location: 'Location 3' },
];
var cols = [
    { field: 'name', title: 'Name', width: '20%', widthGrow: 1, widthShrink: 1  },
    { field: 'description', title: 'Description', width: '30%', widthGrow: 1, widthShrink: 1    },
    { field: 'location', title: 'Location', width: '50%', widthGrow: 1, widthShrink: 1   },
];

var config = {
    columns: cols,
    data: data,
    layout: 'fitColumns'
};
var mytable = new Tabulator("#mytable", config);
```

**Working Example**
Working example is at https://stackoverflow.com/questions/58793291/tabulator-table-width-problem-using-css-grid.  Also, fiddles that show it both with css grid and without are here:

With grid, showing weird resizing: https://jsfiddle.net/cfarmerga/wtqo65uc/26/
Without grid, showing expected good resizing: https://jsfiddle.net/cfarmerga/wtqo65uc/29/

**To Reproduce**

1. Go to the fiddle at https://jsfiddle.net/cfarmerga/wtqo65uc/26/
2. Make the result window wider, causing the table to correctly grow wider.
3. Then make the result window narrower.  Note that the table remains wide and a horizontal scrollbar appears.

**Expected behavior**
I expected the table to become narrower when the window was made narrower.

**Screenshots**

**Desktop (please complete the following information):**
 - Device: Windows 10
 - Browser: Chrome 77, Firefox 70, Edge 44

**Comment by olifolkerd** [comment]
This appears to be an issue with using the grid display method in combination with a horizontal overflow.

Have a look at this [Modified Example](https://jsfiddle.net/6wojmhvk/11/) In it there is a blue block of a width of 500px; when the width of the containing div is below that width it should show a scroll bar because it has a CSS ***overflow*** value of ***auto***. but for some reason in grid mode it is breaking that basic functionality.

Which is why it is also breaking Tabulator. it appears that that functionality is propagated to any child divs.

I would suggest you have a look into how to prevent that functionality propagating down from your grid div.

Cheers

Oli :)

**Comment by cfarmerga** [comment]
Ah, thanks for the excellent pointer.  That makes sense, and seems trivial now to fix. This link was helpful: https://css-tricks.com/preventing-a-grid-blowout/.

Changing my css from `grid-template-columns: 1fr;` to `grid-template-columns: minmax(0, 1fr);` allows the grid container to get smaller, and the tabulator table now happily gets smaller with it.

**Comment by olifolkerd** [comment]
Fantastic news! Glad I could help 😁
