### ISSUE TITLE
mouseevents of elements inside a cell

### ISSUE THREAD

**Issue by ruggbo** [olifolkerd/tabulator#2503]
Hi Oli,

In a cell i have a text and a button (an icon with a click listener). I put it using a formatter
If i define the column as not editable, the cellclick function receives a mouse event, otherwise if i define the column with an editor (i.e. input) the cell click receives a focus event, so i cant determine which object inside the cell has been clicked
Actually the function associated at the icon listener never fires when the cell is editable, but fires normally when the cell is not editable

I want the cell to be editable, but already want to know if the  user clicks the icon (which correspond to a function that puts a question mark in the cell data and submits the form) or clicks the text, to directly edit it.
How i can achieve it?
Thanks in advance

![image](https://user-images.githubusercontent.com/1107278/69659060-b614e300-107d-11ea-919c-5595c194bda3.png)

**Comment by olifolkerd** [comment]
Hey @ruggbo 

Please ask questions on Stack Overflow, this issues list is reserved for Bug reports and Feature requests only.

In this instance you should be using a [Custom Formatter](http://tabulator.info/docs/4.5/format#format-custom) to add the icons to the cell. in the formatter you can then add listeners to the click event of the icon itself rather than to the cell.

Cheers

Oli :)
