### ISSUE TITLE
printAsHtml not working with rowFormatter:function(row)

### ISSUE THREAD

**Issue by slowsquirrel69** [olifolkerd/tabulator#2509]
When trying to print a report that has a row formatter that changes the background color of a row to red it only displays the row but the print out removes it. See attached img1 what displays on screen and img2 what prints out.

I have the following variables set in my table definition:

printCopyStyle:true,       
printAsHtml:true,

Running Tabulator v4.4.1

<img width="1364" alt="img1" src="https://user-images.githubusercontent.com/14809073/69885059-53a02a80-12a9-11ea-9c1e-82d0a6bca53e.png">

<img width="548" alt="img2" src="https://user-images.githubusercontent.com/14809073/69885058-53a02a80-12a9-11ea-995d-3f8221970fcd.png">

**Comment by olifolkerd** [comment]
Hey @slowsquirrel69 

At the moment row formatters are not called when the print functionality is in use, it regenerates the table from the row data. This is done because the print table HTML structure is completely different from a normal row, therefore a lot of row formatters would error when passed in the print table structure.

I will look at possible solutions for this in a future release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @slowsquirrel69 

I have just pushed some updates to the 4.6 branch to improve formatting in printing and other export scenarios.

Version 4.6 will be released next weekend.

Cheers

Oli :)
