### ISSUE TITLE
CORS Error - Ajax

### ISSUE THREAD

**Issue by pradeepbhardwaj** [olifolkerd/tabulator#2513]
Hi Oli,

I am integrating tabulator with apache solr. I have enabled "cross origin" on solr. But still its giving me CORS error. Please help me to resolve this issue.

![Screenshot from 2019-12-04 13:57:58](https://user-images.githubusercontent.com/14886814/70126059-2df69500-169e-11ea-8f60-2d2aacfcc09b.png)

**Comment by olifolkerd** [comment]
Hey @pradeepbhardwaj 

This is likely not a Tabulator issue, but due to not passing the correct headers in the AJAX request.

Check what headers you need to pass in your request then checkout the [Ajax Cors Documentation](http://tabulator.info/docs/4.5/data#ajax-cors) to see how to configure the request.

Cheers

Oli :)
