### ISSUE TITLE
Add support to row.reformat() between cellEdited and cellEditing events

### ISSUE THREAD

**Issue by molostoff** [olifolkerd/tabulator#2515]
Typical usage (and my case indeed) is to create table with several editable columns and several calculated columns (with calculations via cell formatters)

When cellEdited occured and a Tab key used to process to the next cell, I need before to reformat row with new calculations, so calculated columns will show updated results.

But row.reformat() removes cells and recreate them in a row, so navigating to the next cell fails with exception, and editing fails.

Perhaps a callback after cellEdited and before cellEditing is needed (just before navigating to the next cell, for example ), so navigating after row.reformat could be done without error

**Comment by olifolkerd** [comment]
Hey @molostoff 

This is happening because you are using formatters which are only updated when the underlying data is updated, which is the incorrect approach,

You either be using [Mutators](http://tabulator.info/docs/4.5/mutators) which will generate the values and then trigger the formatters to update.

or use the ***cellEdited*** callback to the trigger the `row.update` function to update the row data and retrigger the format.

It is bad practice to use formatters to alter the data because formatters are visual only, which means those columns will not be sortable or filterabled because they have no underlying data.

I hope that helps,

Cheers

Oli :)
