### ISSUE TITLE
Nested Table

### ISSUE THREAD

**Issue by nasaddis** [olifolkerd/tabulator#2527]
Hello dear, I do really appreciate you for such a nice work thanks !

I have been trying to create a nested table and have succeeded using the code-1 below. I am trying to create a dynamic IOT table and i am updating the table every time a new data is coming from a device, and I used code-2 below for that. but whenever i try to updat, the update is successful but the the nested table is replicating it self so how can I stop this from happening.

================ CODE 1 ==================================
rowFormatter:function(row){

   var holderEl = document.createElement("div");
   var tableEl = document.createElement("div");
   
   const id = row.getData().id;

   holderEl.style.boxSizing = "border-box";
   holderEl.style.padding = "10px 10px 10px 10px";
   holderEl.style.borderTop = "1px solid #d1ddea";
   holderEl.style.borderBotom = "1px solid #d1ddea";
   holderEl.style.background = "#fff";
   holderEl.setAttribute('class', "subTable" + id + "");

   tableEl.style.border = "2px solid #d1ddea";
   tableEl.setAttribute('class', "subTable" + id + "");

   holderEl.appendChild(tableEl);

   row.getElement().appendChild(holderEl);
   
 
 
   var myRowData = row.getData().customFields;

   var subTable = new Tabulator(tableEl, {
       layout:"fitColumns",
       data:myRowData,
       columns:[
       {title:"Name", field:"n",headerSort:true },
       {title:"Value", field:"v"},
       ]
     })    
}, 
============= CODE 2 ===========================
tableAllUnits.updateData([{id:unit.id, speedformatted:data.speed}]);

**Comment by olifolkerd** [comment]
Hey @nasaddis 

Please ask questions on Stack Overflow, this issues list is reserved for bug reports and feature requests.

Please also read the [Community Guidelines](http://tabulator.info/community#help), You should post a JS Fiddle or codepen example of your problem with step by step guide to replicate the issue. it is often impossible to offer advice without seing how the table is fully configured.

In this case the issue is because your row formatter is appending the nested table to the row, but it dosnt check to see if there is already one there first. you should make it so it removes the old table (or updates it) before adding the new one/

Cheers

Oli :)
