### ISSUE TITLE
isNaN space problem ?

### ISSUE THREAD

**Issue by eltomjan** [olifolkerd/tabulator#2531]
There is a problem in validation - you can enter space in number field and it is valid ??
(there is a default JS conversion to 0)

Problem also in current version.

**To Reproduce**
1. Create field with default number or int validator
2. Enter space and leave field
3. Validation succeeds - space can be (default) converted to 0, but it is not number in fact

**Expected behavior**
Valid number input should be empty (null) for nullable DB fields (in relation to required or some nullable flag) or number, but nothing else.

Few demo expressions:
``` JavaScript
var value = ' ' // space
value == Number(value) // true: 0 == 0
value != Number(value) // false: 0 != 0
value === Number(value) // false: ' ' === 0
value !== Number(value) // true: ' ' !== 0
isNaN('') || isNaN(' ') // false: \s* => 0
```

**Comment by aklaver** [comment]
Would be nice to have the full column definition, In meantime depending on what you want to do:
http://tabulator.info/docs/4.5/validate
"Note By default all validators, except the required validator will approve any empty value (ie. empty string, null or undefined). to ensure empty values are rejected you should use the required validator."

The above would reject any empty values.

As alternative:
http://tabulator.info/docs/4.5/callbacks#cell
Cell Edited 

Use above to change value to null.

**Comment by eltomjan** [comment]
Not clear description ? There is missing nullable number cell option (not required number). Only whitespaces in number field are most probably invalid (despite JS understand them as zero). Your suggestion does not help - suppose you cannot delete value of required field, do not want to show/switch empty nor whitespaces to null, do not want to save space(s) as (valid) number. Have a workaround yet, but current logic seems to be incomplete or wrong in my case.

**Comment by aklaver** [comment]
Yes, it is not clear what you want.  You show that JS turns '' into 0 and that JS has varying degrees of strictness for ' ' == 0 or '' === 0.  So it will make an empty string a number and valid more or less. You also want the data to conform to a DB(SQL I presume) NULL type.  So a data type transformation. These are all things that I see as outside of Tabulators control/purview(@olifolkerd  would be the final call on that ).  To me that sort of decision on data transformation should be left to the user not the program. The tools exist for you to deal with what you want. In addition to and probably better then my initial suggestion:
Mutators
http://tabulator.info/docs/4.5/mutators#mutators
and
http://tabulator.info/docs/4.5/validate
Custom Validator Functions

**Comment by olifolkerd** [comment]
@eltomjan 

As per the [Bug Report Guidlines](http://tabulator.info/community#bug) you must submit a working JS Fiddle or Code Pen that replicates your bug so that we can fully understand the issue. Tabulator is made of may interconnected systems and without seeing how your table is fully configured it can be hard to get the bottom of the true source of an issue.

A number editor is simply using a number type input element, any value that the browser considers valid for this input is valid, this is outside the scope of Tabulator, editors provide no validation themselves they are just types of inputs

if you want to restrict entry then you should be using a validator as @aklaver suggests as that is its purpose, and provides a wide range of numeric options.

if you want a more restrictive input element the you can build your own using a [Custom Editor](http://tabulator.info/docs/4.5/edit#edit-custom) that can then behave in any way you like

I hope that helps,

Cheers

Oli :)
