### ISSUE TITLE
Time delay problems with table filter and external chart

### ISSUE THREAD

**Issue by Bambofy** [olifolkerd/tabulator#2532]
Hi,

I'm trying to use ChartJS and Tabulator together, when a table "dataFiltered" callback is triggered, you have to wait a second to use the same table's ".getData('active')" or else you get the non-filtered data.

e.g. This version returns non-filtered data at "newRowsToUse"
```
function myChartUpdateFunction()
{
    var newRowsToUse = TabulatorTable.getData("active");  // non filtered data
}

var TabulatorTable = new Tabulator(this.DivID, {
            selectable: true,
            dataFiltered: function (filters, rows) {
                myChartUpdateFunction()

            },
```

solution is using setTimeout, here newRowsToUse is correct.
```
function myChartUpdateFunction()
{
    var newRowsToUse = TabulatorTable.getData("active");  // filtered data correct
}

var TabulatorTable = new Tabulator(this.DivID, {
            selectable: true,
            dataFiltered: function (filters, rows) {
                setTimeout(() => {
                     myChartUpdateFunction()
                }, 1000);

            },
```

**Comment by olifolkerd** [comment]
This is expected behaviour,

The table filtered function is called while the table is still processing, it just shows the state the table is in. the results of the ***getData*** function will not be available until the table has fully finished processing the data.

As you will see from the [Row Management Pipeline Documentation](http://tabulator.info/docs/4.5/lifecycle#row) row filtering is only the first step in the management process. the results of the ***getData*** function are only stable at the end of the pipeline.

The [Row Components](http://tabulator.info/docs/4.5/components#component-row) for the filetered rows are passed directly into the ***dataFiltered*** function as the second argument, so there is actually no need to call the ***getData*** function on the table. you can just itterate over the rows in the array and call the ***getData*** function on each of them

I hope that helps,

Cheers

Oli :)
