### ISSUE TITLE
On Internet Explorer 11 setting progressiveRender: true causes scrollbar to disappear. 

### ISSUE THREAD

**Issue by bluedog** [olifolkerd/tabulator#255]
[indexnew.zip](https://github.com/olifolkerd/tabulator/files/908167/indexnew.zip)

Works fine with Edge and Chrome on Windows.

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch,

As a general rule I would avoid using progressive rendering with row grouping,

Progressive rendering works by loading the data into the container as you scroll. the grouping system as it currently works assigns rows to groups as they are rendered rather than creating all the groups with their dat in then rendering them, thus progressive rendering when using groups would cause the data to be inserted randomly across the table rather than at the bottom of the table to be scrolled to. which could cause the scroll to jerk about as you load data rather than smoothly scroll.

It seems that this interaction is what is causing the issue on IE.

How many rows are you anticipating using?

Let me know if that helps

Cheers

Oli

**Comment by bluedog** [comment]
Thanks for the quick response. 

The number of rows depends on the time of day: between 1 and a few thousand. Other reports in this system can return up to 30,000 or more rows. 

The users have complained it is too slow without progressive rendering enabled. The users hate pagination. 

Any other suggestions for grouping (I guess without using the build in grouping functionality?)

Thanks.

**Comment by olifolkerd** [comment]
Hey,

The system has run smoothly on many thousands of rows, so i think the jerkyness must either be down to the large number of columns, the column definitions or something to do with the data.

What would really help me isolate the problem for you, would be if you could send over the completed constructor object and that TSV file formatted into a javascript object so i could run some tests on it.

Cheers

Oli

**Comment by bluedog** [comment]
Here is everything in a jsfiddle including a sample dataset. In IE11 it takes about 5 seconds to load about 250 rows of data. In Chrome almost instant. 

https://jsfiddle.net/bluedogisblue/9q3pog0c/10/

**Comment by olifolkerd** [comment]
Thanks for the info, i will investigate further!

**Comment by olifolkerd** [comment]
Hey,

I have just pushed an update to the repo that should fix the IE and smooth scrolling issues.

Have a play and let me know your thoughts.

Cheers

Oli

**Comment by bluedog** [comment]
I do appreciate all of the hard work that goes into this. Thanks. 

Although it seems a little faster it is still much slower in IE11 - takes 4 to 5 seconds to render.  

I updated the jsfiddle to point to 2.12 - https://jsfiddle.net/bluedogisblue/9q3pog0c/15/

**Comment by olifolkerd** [comment]
Hey bluedog,

Im currently working on version 3.0 of Tabulator that will be moving to a full virtual DOM which should be much faster.

This should be released in early May.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, and comes with a full Virtual DOM.

I'm still working on some optimizations for Microsoft browsers, but on the hole you should find it a very smooth experience.

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Let me know what you think :)

Cheers

Oli
