### ISSUE TITLE
Bug on huge data with variable row height on Tabulator 4.5.2

### ISSUE THREAD

**Issue by tomotom** [olifolkerd/tabulator#2555]
With the code inside the JSFiddle, i don't see the last lines on chrome (i should see 1 000 000 lines, then i should see "Task 999999" at the end), when i scroll to the bottom. On firefox, when i scroll to the bottom, sometimes the scrollbar disappears and the content of the tabulator too (or i don't see the last lines, whereas i should see "Task 999999" at the end). On edge and internet explorer (with ie 11, i add `<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>` as suggested), when i scroll to the bottom, i don't see the major part of the last lines.

The jsfiddle of the code : [https://jsfiddle.net/rwnLyk1h/1/](https://jsfiddle.net/rwnLyk1h/1/)

How to correct this bug (except reducing the number of lines and except with pagination)?

**Comment by tomotom** [comment]
Maybe this bug comes from rounded numbers in javascript: between several rows, i see grey horizontal lines. I don't know, this is just an idea.

**Comment by olifolkerd** [comment]
Hey @tomotom 

It looks like a rounding error in the virtual DOM maths that only comes out when you have around a million rows of variable height.

I will certainly look into it for the next release. but tables of this size are rare so im afraid i cant give it top priority at the moment.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @tomotom 

Looking into this further, this issues is arising because you are hitting the physical size limit of a div in chrome, which is 33554428px.

It actually has nothing to do with the variable size of the rows. if you set them all to have the same height as the thick rows then the issue is the same.

To ensure that the scroll bar accurately reflects the position of the elements in the table, the padding used to shift the scroll bar position is calculated in actual pixels. because you have so many tall rows this then exceeds the browser height limits.

While there may be ways to avoid this, i would consider having a million rows in a table to be an extreme edge case and very poor for user experience, both in terms of load time for the table and in terms of usability for the end user, they would not be expected to be able to parse all that data so it should be presented in a filtered fashion.

For this reason i consider this to be a reasonable limitation for the system and do not intend to attempt a solution at this point.

Cheers

Oli :)
