### ISSUE TITLE
variableHeight:true is not working

### ISSUE THREAD

**Issue by boumboum** [olifolkerd/tabulator#2558]
Given the [following jsfiddle ](https://jsfiddle.net/351varuk/) table definition:

I'm expecting a variable row height to fit the data  but instead of that I'm getting a fixed height without seeing the whole data.
What am I doing wrong?

**Comment by olifolkerd** [comment]
Hey @boumboum 

Please can you make sure you fill in the bug reporting template when submitting a bug rather than just deleting it and adding your own content, the template prompts for all the information we need to know in order to resolve your issue promptly.

The issue is because the css for tabulator cells has `white-space:nowrap`. In order to resolve your problem you will need to add the following line to your formatter:

```js
cell.getElement().style.whiteSpace = "pre-wrap";
```

Cheers

Oli :)

**Comment by BillMeyerRSA** [comment]
Cool...
The `cell.getElement().style.whiteSpace = "pre-wrap"; ` solved my problem before I could log an issue. 
Only comment - maybe include in the documentation?

**Comment by wollo** [comment]
I can confirm, that this works. But why is this not added to the included formatters. I was using the built-in html formatter and the variableHeight parameter and it did not work. I head to build a custom formatter with this extra css to make it work.

**Comment by olifolkerd** [comment]
@wollo you misunderstand the purpose of the `variableHeight` property it does not have any affect on the cell at all, it lets the row and column know that changing one dimension of the cell could result in the other dimension changing, so for example if you change the width, it knows the height may change, which tells the table to relayout the cell and the row if needed.

**Comment by olifolkerd** [comment]
@wollo Yeah that could be nice, if you would like to see that added as an option, please create a separate feature request and we can add that to the roadmap
