### ISSUE TITLE
Tabulator IE 11 compatibility issue: more than one tabulator not opening on same html page

### ISSUE THREAD

**Issue by romeshRaghavan** [olifolkerd/tabulator#2559]
We are facing issues for tabulator on IE11, in our application we have dashboard where we trying to display multiple tabulator tables on click of each card.

We are able to view only one table after adding the polyfill scripts but we are unable to view the other tables we're unable to see multiple tabulators on same html page in IE11 the same is working fine in chrome/Mozilla. We tried rearranging the scripts but still the same issue and there in no error on console or the log.

this is the 1st table which is working fine

this are the other tables where tabulator doesn't work.

we've attached the dashboard html page which consists of all the code.

And please refer the stackoverflow issue link that i have already raised [reported stack overflow link](https://stackoverflow.com/questions/59526424/tabulator-ie-11-compatibility-issue-for-more-than-one-tabulator-not-opening-on-s?noredirect=1#comment105254099_59526424)

**Comment by romeshRaghavan** [comment]
And another interesting thing is that when we resize the browser window of IE browser the footer of other tabulator table are getting displayed when opened
![resize browser issue](https://user-images.githubusercontent.com/12832829/71621329-ae081000-2bf4-11ea-83f3-5f5208485d67.png)

**Comment by olifolkerd** [comment]
Hey @romeshRaghavan 

Sorry to hear you are having issue. please do not submit large blocks of code in the issue it is impossible to read them and it blocks out the issue.

Please read the [Bug Reporting Guide](http://tabulator.info/community#bug) you ***MUST*** provide a working JS Fiddle or Code Pen that demonstrates your issue so that we can understand your table setup in action.

Once you have this setup i am sure we can point you in the right direction. It is most likey because your tables are initialized when they are hidden, if you call the ***redraw*** function on the table when it is made visible this should hopefully resolve things for you. (this is not an issue in firefox or chrome because the table can detect when it is made visible in those browsers, but it cant in IE)

Cheers

Oli :)

**Comment by romeshRaghavan** [comment]
Hey Oli,
Thanks for your kind help, your solution worked great!

We used `table.redraw();` with javascript's  `setTimeout(function(){ table.redraw();}, 500);` function and it worked like magic.

Another change that we made is removed the `responsiveLayout:"show"` attribute and the table along with its proper contents and allignment got displayed.

Cheers

Product Exp :)
