### ISSUE TITLE
Tabulator and Pagination Control Element

### ISSUE THREAD

**Issue by benkim-saama** [olifolkerd/tabulator#2568]
The current project I am working on requires us to work with millions of rows.  The product we are creating applies initial filters so the load is not too large for the backend.

The Remote Pagination works like a charm with Tabulator.  I also like the feature that allows the end-user to set the Page Size value.  One item that would be nice to have is a **Jump to Page #** option in the Pagination control.  This way, the end-user can approximate the page and perhaps jump to the middle of the list when searching for a specific item.

I know that I can add a button and add the functionality myself but it seems to be a fairly common thing, at least for Web Apps that we develop for users.

Thank you for your consideration!

Ben

**Comment by olifolkerd** [comment]
Hey @benkim-saama 

Thanks for getting in touch, and thanks for your kind words about Tabulator, it is always great to hear people are enjoying using it!

Thanks for the suggestion. I have actually deliberately left that out of the core library. There are so many different types of additional pagination controls that people have asked for over the years, with each one only applicable to a small subset of usage cases.

Rather than bloat the code base with new control after control, i provided functions to allow the developers to trigger a jump to a page whenever they like and allowed them to put that element in the footer of the table if they choose, or anywhere else on the page if that suits them.

I try to keep tabulator reasonably un-opinionated and very extensible to allow developers to use it how they want.

If you feel that you have added a jump to page footer element that you like then please feel free to share the code here so that others may benefit from it.

Cheers

Oli :)
