### ISSUE TITLE
Hide and Show groups of rows inside the table freezes the screen for few seconds

### ISSUE THREAD

**Issue by gusmattos1** [olifolkerd/tabulator#2599]
**Describe the bug**

When Hiding or showing a group of rows inside the tabulator the screen freezes for 5~10 sec

After checking the code we noticed that on the end of the functions inside Tabulator.js -> Group.prototype.show() and Group.prototype.hide() a call for the function: this.groupManager.table.rowManager.checkClassicModeGroupHeaderWidth()

the function checkClassicModeGroupHeaderWidth() runs a forEach on all rows of the table and this was making the render freezes for few seconds

When this function was removed the render responds almost immediately after the request to hide or show a group.

My table has 20 columns and 350 rows

**Tabulator Info**
Tabulator version 4.5.3

**Example**

https://codepen.io/gusmattos1/pen/povGJro

**Expected behaviour**
When clicking to hide or show a group of rows the render should update just the rows inside that group.

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser chrome
 - Version 79

**Comment by olifolkerd** [comment]
Hey @gusmattos1 

Im afraid the link you posted to your Code Pen, points to a broken pen, the code inside is non functional. it appears to contain part of the Tabulator library. The point of the code pen is for you to provide an example of your issue in action so that we can understand how your table is configured and how it results in the issues present.

The issue you are experiencing is likely because you have not defined a height on your table, and therefore it is running in classic render mode (ie the virtual DOM has not been enabled). It is not advised to run large tables in this way. This is coverd several times in the documentation and in numerous already resolved issues.

While removing the functions you have listed may have resolved the issues you are facing they are necessary for other parts of the system to function (which you may not be using, but without your table definition i cant say)

Cheers

Oli :)
