### ISSUE TITLE
Error in clipboard mutation

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2606]
This [call](https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L11948) 

    output.push(self.table.modules.mutator.transformRow(row, "clipboard"));

is useless because of next condition:

    if (mutator && updatedData) {

the call has no third argument so `updatedData` is false and method does nothing

Actually I come here with different issue. Doc [says](http://tabulator.info/docs/4.5/mutators#mutators):

>Field Required
>For a mutator to work the column definition must have a field property specified, otherwise the muator will not know which field to act on. If you are using the mutator to generate a field that does not exist in the initial data, that is fine but the field must still be specified in the column definition.

But from the [code](https://github.com/olifolkerd/tabulator/blob/master/dist/js/tabulator.js#L20690)

    self.table.columnManager.traverse(function (column) {

a mutator is just called if column defines it

Also this condition (at line 20699):

    typeof value !== "undefined"

prevents mutator to set some default value when user pass `undefined`

**Comment by KES777** [comment]
![_](https://user-images.githubusercontent.com/799021/73257198-facb1080-41cb-11ea-89bc-bed817110712.jpg)

A field mutator knows itself which field **or fields** it needs to mutate.

So this code is not useful. Just makes inconveniences

**Comment by olifolkerd** [comment]
Hi @KES777 


This is totally necessary, it depends on when the mutator is called as to whether there is updated data or not. 

If it is called on the initial data load there is no updated data.

If it is called as a result of an edit then there IS updated data. 

The purpose of the undefined check is to prevent mutators being called on columns that havnt been updated when an edit occurs on other cells in the row, this prevents accidental double mutation.

Cheers

Oli :)

**Comment by KES777** [comment]
>If it is called on the initial data load there is no updated data.

you are not correct. If you call it for initial data you do next:

![_](https://user-images.githubusercontent.com/799021/73260206-1c2efb00-41d2-11ea-9766-17046ad0ffc0.jpg)

**Comment by KES777** [comment]
>is to prevent mutators being called on columns that havnt been updated when an edit occurs on other cells in the row

for this purpose is better to cycle over modified fields and not all fields of the row (see line 20690)

**Comment by olifolkerd** [comment]
ahh, appologies, 

I misread your initial post, you are correct, there is an issue in the clipboard mutator that is not passing in the data it should be. 

There is definitely an issue that the clipboard mutator should being passed in the value. i will look into resolving that in the next release.

The Docs section that you have quoted is still valid, yes the column knows which mutator it is using, but the commutator has to be tied back to actual row data so the column must still have a field otherwise there is no property to mutate in the row data. if you want to be displaying things in columns without a field set then you should be using a formatter not a mutator.

As far as i am concerned an undefined value is unsetting the value in that column, and therefor shouldn't need mutating. at that point if you still want to display something you should be using a formatter.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @KES777 

I have pushed a fix for this to the 4.6 branch that will be released later this weekend.

Cheers

Oli :)

**Comment by KES777** [comment]
Thank you Oli

[comit](https://github.com/olifolkerd/tabulator/commit/84c15c8a7a0d825fae0993598cbcbec706876dbe)
