### ISSUE TITLE
Add Insert Row Form at Bottom of Table

### ISSUE THREAD

**Issue by schmidty1913** [olifolkerd/tabulator#2610]
Table parameter to automatically add an "Add Row" button to the bottom of the table.

![image](https://user-images.githubusercontent.com/24723142/73323014-a6e01c00-420b-11ea-89e7-75b687111098.png)

Clicking on the "Add Row" button adds a row of fields above the pagination controls that utilize the default editors or editors defined in the header. The button then changes to an "Insert Row" button.

![image](https://user-images.githubusercontent.com/24723142/73323029-b0698400-420b-11ea-8047-eb7048ee3b77.png)

Once values are filled in, it uses the validator to make sure the data is valid.
Clicking on the "Insert Row" button inserts the row into the table.

**Comment by olifolkerd** [comment]
Hey @schmidty1913 

Thanks for the suggestion.

I deliberatly keep the footer empty, there are a huge number of buttons that users could want in the footer, and rather than clutter the code base with 100's of options i allow users to set their own [Table Footer](http://tabulator.info/docs/4.5/layout#footer) and then they can add anything specific to their usage case.

It would be very simple for your to add an add row button to the footer that calls the ***addRow*** function.

As for editing the row on the bottom of the table, this is not something i would be looking to add, it is not a standard interface design so i fear it would confuse users. it also would look very messy once there is a scroll bar on the table.

Of course feel free to customise your copy of Tabulator in any way you like.

Cheers

Oli :)
