### ISSUE TITLE
display ajaxLoader when updating or setting table data externally

### ISSUE THREAD

**Issue by afatsoum** [olifolkerd/tabulator#2613]
I couldn't see anywhere how i could display the ajaxLoader modal when updating table data. It seems to only work on the initial data loading.

I am trying to update data subsequently from an external ajax call:
`table.updateData([{id:1, name:"bob"}]);`
or
`table.setData(data);`

Is there any example how I display the ajaxLoader when i update/set table data from external ajax call?

**Comment by AlexanderPD** [comment]
i wanted to do the same thing, but instead of having the standard loader (witch is annoying if you use the option to load data on user scrolling because all the table flashes with the dark loader) i preferred to display and hide a custom loader outside the table.

If your loader is inside a div with id "table_loading" you can use this code inside your tabulator config:

```
ajaxRequesting: function (url, params) {
	jQuery('#table_loading').show();
},
ajaxResponse: function (url, params, response) {
	jQuery('#table_loading').hide();
	return response;
},
ajaxError: function (xhr, textStatus, errorThrown) {
	jQuery('#table_loading').hide();
}
```

**Comment by olifolkerd** [comment]
Hey @afatsoum 

The ajax loader only appears when data is loaded over ajax (due to the time it takes to make an ajax request). There is no need to do it when not updating over ajax as the update should be prety much instantaneous if you have configured your table correctly.

Cheers

Oli :)
