### ISSUE TITLE
Change properties after creation of table

### ISSUE THREAD

**Issue by xola123** [olifolkerd/tabulator#2615]
Hi, maybe I am just too blind to find the answer.

How can I set a property, say "moveableRows", to false when a button was clicked?

I am searching for an function like "table.disableOption("moveableRows")" or "table.disableRowMove()" or such.
Only found the "table.Move(i)" function so far.
Thank you in advance!

Greetings, xola

**Comment by olifolkerd** [comment]
Hey @xola123 

Some properties cannot be changed after the table has been created, due to the complexity involved in changing their configuration.

If you want to change that property i recommend you destroy the old table with the ***destroy*** function and then recreate your table with an updated constructor options object.

```js
table.destroy();
```
I hope that helps,

Cheers

Oli :)
