### ISSUE TITLE
Column width skyrocket outside any bound when resizing - 2° attempt

### ISSUE THREAD

**Issue by AlexanderPD** [olifolkerd/tabulator#2624]
**Describe the bug**
I'm opening again an issue since the old was closed with a solution that, sadly, don't fix the problem. It was suggested to remove textarea formatter from title formatter, but as you can see in the JSFiddle posted here, thats not the cause of the issue.
The problem is, with my configuration, resizing a column makes the next column endlessly enlarge its width

**Tabulator Info**
I'm using Tabulator 4.5.1

**Working Example**
JSFiddle: https://jsfiddle.net/AlexanderPD/149ezabp/19/

**To Reproduce**
1. create Tabulator inside a table's td tag
2. use layout "fitColumns"
3. use at least 2 column: the first with fixed width and the second without any width parameter
4. set the height attribute on tabulator (this step is necessary like the others to reproduce the bug!)
5. try to resize the first column to trigger the problem
6. watch the second column automatically grows endlessly

**Expected behavior**
Resizing the first column should not affect the second column

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Chrome, Firefox, Edge with Chromium
 - Version: Always the latest one

**Additional context**
A partial fix is to replace "width" with "minWidth". This will make the second column grow with the same value of the first one. It doesn't totally destroy the table but still the width grows too much, the second column should not grow with the first one.
Another partial fix is to remove the height attribute from tabulator, but since i want endless scrolling i need to use a fixed height.

**Comment by dcanning** [comment]
work around if you can use it is to set a width on the 2nd column, you can still resize either, but with the width on the 2nd it doesn't expand to infinity when resizing them.

**Comment by AlexanderPD** [comment]
> work around if you can use it is to set a width on the 2nd column, you can still resize either, but with the width on the 2nd it doesn't expand to infinity when resizing them.

Thank you for your reply! Sadly i cannot use that work around because i need the second column to take all the free space and extend until the next column, my JSFiddle was just a (very) simplified version of the table i actually need to use (it has 15 columns with lot of customizations)

**Comment by olifolkerd** [comment]
Hey @AlexanderPD 

Sorry for the delay in getting back to you.

Looking into this further, the issue is not with Tabulator but that you have put the table inside a ***td*** element. Tabulator is setup in a div, so it takes up 100% of the width available to it, when it starts it is at the minimum width the dom will allow which is the fixed width of the first column and the min width of the second.

As you resize the column it forces a change of this, then the td element expands, alowing the table to expand, forcing a redraw of the table with then causes the column to expand because you are using a fitColumns layout, and then it goes into a run away spiral of everything expanding.

to prevent this being an issue, you will need to set a width on the table or the td.

Cheers

Oli :)
