### ISSUE TITLE
DOM elements added using rowFormatter destroyed on create

### ISSUE THREAD

**Issue by billcava** [olifolkerd/tabulator#2637]
**Describe the bug**
Elements added to DOM using rowFormatter appear to be destroyed when redrawing/recreating the table

**Tabulator Info**
- 4.5.3

**Working Example**
A working JSFiddle showing the problem:
https://jsfiddle.net/black_ring_9a/5w9nhc18/

**To Reproduce**

Steps to reproduce:
1. Go to https://jsfiddle.net/black_ring_9a/1ezyp9bv/8/
2. Click on 'Expand All'
3. Notice the group summaries
4. Click on 'Collapse All'
5. Click on 'Expand All'
6. Notice the group summaries are no longer displayed

**Expected behavior**
After Step #5, the expected behavior is that group summaries would be displayed

**Screenshots**
N/A

**Desktop (please complete the following information):**
Reproduced on both Chrome/Safari on Mac OS 10.15.3:
 - Chrome - Version 80.0.3987.116 (Official Build) (64-bit)
 - Safari - Version 13.0.5 (15608.5.11)

**Comment by olifolkerd** [comment]
Hey @billcava 

This is the correct behaviour, redrawing the row will invalidate the rows contents and cause the table to trash the previous contents and call the formatter again.

Because you are storing the setting outside of Tabulator your row formatter can not then cope with the change.

If you want to put an element at the top of a group then you should either look at a custom [Group Header](http://tabulator.info/docs/4.5/group#setup-headers)

Or look at determining if it is the first in a group in a more sustainable way:

```js
//check if element is first in a group
var group = row.getGroup();
if(! group.getRows().indexOf(row)){
    ///first row
}
```

I hope that helps,

Cheers

Oli :)
