### ISSUE TITLE
Changing reactive data does not move focus to the next editable cell

### ISSUE THREAD

**Issue by smiheev** [olifolkerd/tabulator#2639]
Hello!

**Describe the bug**
For example, editing a cell causes other reactive data to change, but the focus does not move to the next editable cell by pressing Tab key or Enter key. Moreover after changing the cell and pressing the ArrowDown key an exception occurs.

**Tabulator Info**
4.5.3

**Working Example**
A working JSFiddle showing the problem:
https://jsfiddle.net/bLt69ncm/

**To Reproduce**
Steps to reproduce:
1. Go to https://jsfiddle.net/bLt69ncm/
2. Change the value of the first row ('Oli Bob').
3. Press the Tab key or Enter.
4. Tabulator does not focus on the next editable cell.

**Expected behavior**
Tabulator focus next editable cell.

Steps to reproduce exception:
1. Go to https://jsfiddle.net/bLt69ncm/
2. Change the value of the first row ('Oli Bob').
3. Press the ArrowDown key.
4. See exception in console.

**Comment by olifolkerd** [comment]
Hey @smiheev 

Thanks for the info, it looks like the data reactivity is blocking the editor transition,

I will have a look into that for the next release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @smiheev 

Looking into this more i would say this isn't a Tabulator issue as such it is more your approach is conflicting with the way tabulator works.

The issue is arising because in your customCellEdited function you are replacing row two, so the moment you have pushed tab, Tabluator moves focus to that row, then by replacing it in the array by splicing it, you remove the row that currently has focus and then replace it, which is why focus is lost because as far as tabulator is concerned you have deleted the old row that had focus and added in a new one.

instead in this instance i would suggest you either call the ***update*** function on the row or update the contents of the object rather than replacing it,

I hope that clears things up

Cheers

Oli :)
