### ISSUE TITLE
movableColumns with a select in a customer headerFilter

### ISSUE THREAD

**Issue by roxuss** [olifolkerd/tabulator#2642]
I created a customer headerFilter that has a &lt;select> in it. When using the &lt;select> on a moveableColumn, unless I stay perfectly still for the 500ms (iirc) timer in the mouseDown event in the column header captured for moving the column, the colmun header will want to move.

https://jsfiddle.net/hsvyc1a8/

You will notice in the code I have commented out a mousedown evebnt handler on the <select> that calls e.stopPropagation(). If I uncomment this, this fixes the issue, but I don't know if this is the "right" thing to do (stop the event bubbling up, or consuming it from everyone).

I *personally think* Tabulator should check the specific target of the event and see if its somehow the area of the column header and not a specific element within the header. I note that this behavior does not come about when clicking in the &lt;input> fields and moving the mouse around. I think it might have something to do with focus() ? IDK

Chromium Version 74.0.3729.157 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)

**Comment by olifolkerd** [comment]
Hey @roxuss 

If you dont want to trigger the move when clicking on the select editor then the stopPropagation is the correct approach to take.

I deliberately don't check the origin because i have no idea what people are going to put in the header, if it is a purely decorative element then there is no reason it should block the move. it is entirely down to you to define the user experience this way.

Cheers

Oli :)
