### ISSUE TITLE
History Does Not Undo All Row Deletes 

### ISSUE THREAD

**Issue by dragmecom** [olifolkerd/tabulator#2676]
**Describe the bug**
When you select and delete more than 5 rows at a time, the history module will not restore all deleted rows

**Tabulator Info**
Latest

**Working Example**
https://jsfiddle.net/pkue7nL2/4/

**To Reproduce**
1. Select Multiple Rows (make sure to skip one row then select it later - ex : 1,2,3,5,4)
2. Click Delete Rows (this just iterates over with a basic for loop and deletes all)
3. Then click undo to try and get all rows back

**Expected behavior**
All rows that were deleted should have reappeared

**Desktop (please complete the following information):**
Chrome - Latest

**Additional context**
If you get the rows all back the first time, try again and delete the same rows, it will give unexpected behavior

**Comment by dragmecom** [comment]
I also noticed this happens with the copy feature as well... I think this comes down to the select algorithm, when selecting any non-sequential items it fails to properly copy or undo/redo etc.

**Comment by olifolkerd** [comment]
Hey All,

Looking into it, the issue was actually to do with the order that the deletes/selects happened. The undo action was trying to reference row components that now longer existed to add the rows back into the table at the right point.

I have pushed a fix for this to the 4.6 branch, which should be released later this weekend.

Cheers

Oli :)
