### ISSUE TITLE
Export / Download Does Not Include New Column Nor Column Edited Titles

### ISSUE THREAD

**Issue by dragmecom** [olifolkerd/tabulator#2682]
**Describe the bug**

This is 2 bugs in one report, I don't want to make a bunch of these reports....

1. Edited Title is not saved upon export (json - didn't check others)
2. Added Columns (and their row values) are not saved upon export (json - didn't check others)

**Tabulator Info**
Latest 

**Working Example**
https://jsfiddle.net/0ucs7arw/6/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Edit Any Title
2. Add Column
3. Export
4. See both errors

**Expected behavior**
Expected editedTitle to update the same way rows did
Expected when a column was edited it would be included in export

**BONUS** - ColumnTitleChanged even with the proper (column) in it based on present documentation, gives error for updateDefinition despite getDefinition() working just above it in the console log.

**Desktop (please complete the following information):**
Chrome / Mac OS

**Additional context**
Done reporting for tonight, feel I may be just be making code mistakes at this point and they might not actually be bugs

**Comment by olifolkerd** [comment]
Hey @dragmecom 

There is no issue with the json output. it dosnt include the column title at any point. the JSON output uses the column ***field*** property as the key not the title, therefore it is unaffected by title changes.

If you add a column to the table then its value will only appear in JSON output once a value has been set for it on that row, otherwise it is undefined and thus not included in the json output

Cheers

Oli :)
