### ISSUE TITLE
4.6 [NEW] updateTitle Removes Column Values / JSON Output Bug

### ISSUE THREAD

**Issue by dragmecom** [olifolkerd/tabulator#2683]
**Describe the bug**
1. When you add a column, add values in that column, and rename it, it deletes all column values
2. When you then output the JSON it will have both the prior column and new column 

**Tabulator Info**
4.6 [Latest]

**Working Example**
https://jsfiddle.net/2uz85rek/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Add Column ( PS : Thanks for that spot on the field FML...)
2. Add Values To New Column
3. Edit New Column Title
4. See Deleting Error
5. Export and see renamed and new column in JSON

**Expected behavior**
Values to not be deleted & json export to only have the renamed column with all values

**Desktop (please complete the following information):**
Chrome OS

**Comment by olifolkerd** [comment]
Hey @dragmecom 

There is a bug in your code. When the column title is changed you are changeing the field name for the column. This dosnt change the row data, it simply changes which field in the row data the column is looking at, which is why it the column empties, the data is still there set on the field of the original column.

If you want to move the data as well as change the field name you will have to do that in that callback as well.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
On a slightly separate note, would you mind clearing out your fiddle a bit, you seem to be including code from old example fiddles which is starting to make it hard to isolate the basic setup in your examples.

Cheers

Oli :)
