### ISSUE TITLE
Deleted Rows (While You Get Them Back - No Longer In Position)

### ISSUE THREAD

**Issue by dragmecom** [olifolkerd/tabulator#2684]
**Describe the bug**
When deleting rows out of sequence (related to the selection bug you fixed), it does restore all rows now, however not to the original place.

For example, deleting 1,3,2 and undo-ing it will result in 1 and 3 being in their proper order but 2 will get added to the bottom of the table not below one.

**Tabulator Info**
4.6

**Working Example**
https://jsfiddle.net/2uz85rek/ 

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Delete Rows 1,3,2 in that order
2. Undo Delete 3 times
3. See error (1 & 3 are in order - 2 is at the bottom)

**Expected behavior**
Upon undo, prior order should be kept

**Desktop (please complete the following information):**
 MAC / OS

**Comment by olifolkerd** [comment]
Hey @dragmecom 

It is not always possible to put them back in the right order, but i can certinly see if i can improve it a bit.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @dragmecom 

Looking into this further, this is not a bug, but is down to the order that your code is deleting the rows. I will explain in more detail:

The ***getSelectedRows*** function returns the rows in the order they were selected, it we track this by using row ids and say that you selected the last 5 rows of the table starting at row 5 so [5,6,7,8,9,10]

the rows are then deleted in that order. when you delete a row it makes a link to the row above it to know where to reinsert it in the table should you undo it.

because of the order in which the rows are deleted they are all binding row 4 as the row above them when they were deleted. so as you are adding them back to the table that order is reversed.

If you were to select them backwards starting from 10 [10,9,8,7,6,5] then this inst a problem because they then bind to the previous row and appear in the correct order.

The delete cant be tracked against their position alone in the table because rows can be deleted even when they are filtered out of the active rows so they have no position at that point.

so the solution to your usage case is to make sure you have sorted the results of the ***getSelectedRows** function before deleting.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have pushed an update to the master branch for the ***deleteRow** function to make it delete the rows in the order the appear in the table to make the undo more predictable.

I will include it in the patch release today.

Cheers

Oli :)

**Comment by dragmecom** [comment]
Great job :) looks like you fixed it! All rows go back in their original order now.

The one thing I did notice is that history wise, it seems that the history length is longer than rows deleted after being restored. So if you delete 4 rows, and restore (undo) it isn't properly calculating history length.
