### ISSUE TITLE
Focus is lost wen navigating vertically through the tables when holding down arrow keys

### ISSUE THREAD

**Issue by Prica25** [olifolkerd/tabulator#2685]
This bug report was already reported here #2665 , but i think that you don't understand well the problem, or maybe not correctly explained.
The problem was not in scrollToRow fail, if you change the given example in the issue from `table.scrollToRow(35, 'top', false)` to `table.scrollToRow(27, 'top', false)`, there is a way to go and yes, it goes. The problem happens next:

Click on line 27, click on up arrow key until focus reach the first line
Click on down arrow key and you will lose focus when tabulator needs to scroll

At the first issue #2665 , the guy responded with a video for the bug: [Link](https://drive.google.com/file/d/1C7mysXAbVoYnp128LPYzXRSBd9zIAscY/view?usp=sharing)

Grateful for your job,
Prica :)

**Comment by olifolkerd** [comment]
@Prica25 

To clarify this has absolutely nothing to do with the ***scrollToRow*** function.

You are saying that if you navigate up and down the table by holding down the arrow keys then occasionally the table looses focus?

If that is the case it is because the table is shifting focus faster than the table is generating new rows so it runs out of rows.

I can look into fixing that if you can confirm that is the case you are trying to report.

Cheers

Oli :)

**Comment by Prica25** [comment]
Yes, that's it!
Its loses the focus faster using scrollToRow to last rows of the table, but it happens without scroll first too.
You are rigth for sure its not a problem with scrollToRow, its just a pattern to find and explain the bug fast.

Cheers,
Prica

**Comment by olifolkerd** [comment]
Hey @Prica25 

Thanks for clarifying, i will look into fixing that in a later release, in the mean time if you look at increasing the size of the [Virtual DOM Render buffer](http://tabulator.info/docs/4.6/layout#virtual-dom-buffer) that should mitigate the issue for you in the short term.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Prica25 

I have pushed a fix for this to the master branch and will include it in today's patch release.

Cheers

Oli :)

**Comment by Prica25** [comment]
Thanks very much!

Prica
