### ISSUE TITLE
Moving Rows Between Tables Bidirectionally

### ISSUE THREAD

**Issue by schmidty1913** [olifolkerd/tabulator#2686]
**Describe the bug**
Only able to move a row from 2nd Table to First Table not visa versa 

It depends on which Table is loaded first.
Table A created
Table B created 
Can move row from Table B to Table A

Table B created
Table A created 
Can move row from Table A to Table B

**Tabulator Info**
4.6.0 and tried on 4.5.

**Working Example**
https://jsfiddle.net/g9w3o6ns/

**To Reproduce**
Try to drag a row from the first table to the second.
If you swap the order the tables are loaded it will follow the order not the table definition

**Comment by olifolkerd** [comment]
Hey @schmidty1913 

Thanks for the fiddle, Just a quick note for the next fiddle you do, you can use the "resources" menu option to pull in the tabulator source from a CDN rather than including it directly in your fiddle. sticking so much code in the fiddle has  slowed it down and makes it really hard to find your code.

Im afraid this is not a bug with Tabulator, this is an issue with your code. In your first table you are setting the ***movableRowsConnectedTables*** property to a value of 'UsersTable' but the user table variable hasnt been defined yet so you are setting it to `undefined` which is why it is unable to link.

In this case you want to be passing in the ID's of the tables you are linking,

so the the UsersInGroupTable table should be 
```js
movableRowsConnectedTables: "#UsersTable",
```

and the the UsersTable table should be 
```js
movableRowsConnectedTables: "#UsersInGroupTable ",
```

I hope that helps,

Cheers

Oli :)

**Comment by schmidty1913** [comment]
Oli thanks.

I read the documentation and it said.

> Connections to receiving tables are established when a row starts being dragged, so the receving tables do not need to exists when the sending table is created

That's why I used the js variable.

**Comment by olifolkerd** [comment]
Hey @schmidty1913 

Yes, but the way you have used the variable is not the way that JavaScript works.

It will pass through the value of the variable at the point it is assigned to the property. at the point you assign it, it is undefined, which is why that dosnt work.

Assigning a value to that variable does not retrospectively change the value of it in functions it has been passed to.

If you passed in a variable containing the DOM node for that table then that would have worked as the pointer would have remained consistent.

I hope that clear things up

Cheers

Oli :)

**Comment by schmidty1913** [comment]
Hello @olifolkerd 
Thanks for the information. I assumed the the JS variables were pointers to the table. My strong suite is not JS... I'm much better in C C++ and goLang.

As for Tabulator I am using it in a personal project of mine, and it is amazing! I am basically using it for everything. I would love to assist in making it better. DM me if you would like some help. I've spent the last 2 months working with Tabulator, I am starting to work with your fullCalendar, and I am looking for a similar graphical JS add on.

As for the JSFiddle, I knew about the CDN add resource. I usually pull the js ones from https://cdnjs.com/libraries/tabulator
but when I looked on JSFiddle, I couldn't find the latest version of tabulator 4.6.x

**Comment by olifolkerd** [comment]
Ahh. I moved to using unpkg as the CDN last year. It pulls directly from npm so is always up to date.

Check out the install docs for the links

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Full calendar is a great library, I use it a lot, but it certainly isn't mine. That is just a fork I was using for my own project work.

It would definitely be worth using the original source for full calendar, they have put in some fantastic new features since I forked it.
