### ISSUE TITLE
Cell Formatter

### ISSUE THREAD

**Issue by annenkovvadim** [olifolkerd/tabulator#2694]
Dear Sir/Madam,

Is it possible to combine the **link** formatter with **textarea** formatter? I mean to have the **labelField** to be multi-line formatted. I think it is useful to be able to put an information  into the link name text.

Best wishes,
Vadim

**Comment by olifolkerd** [comment]
Hey @annenkovvadim 

Please ask questions on Stack overflow.

It is not possible to combine formatters in Tabulator, but you could built your own [Custom Formatter](http://tabulator.info/docs/4.6/format#format-custom) to do the job.

Because formatters can return HTML or DOM nodes, there is not a sensible way to chain them together internally withing Tabulator.

Cheers

Oli :)
