### ISSUE TITLE
Confirmation message in cell editable function

### ISSUE THREAD

**Issue by mats001** [olifolkerd/tabulator#2701]
When confirmation prompt is used before editing the cell in the it does not let you edit if the return is true.
I am able to replicate the same with the latest version 4.6.1 on Js Fiddle. 
https://jsfiddle.net/anilmathew001/zq1xLc9d/4/
I have tried it on both Chrome and Firefox

```
    {title:"Rooms", field:"noRooms", width:150, align:"center", editor:"input",
    	editable:function(cell){
          return confirm("do you want to edit ?");
      },
    },
```

**Comment by olifolkerd** [comment]
The problem is that calling the confirm function causes focus to be taken away from the cell which then cancels the edit.

In this case you should set ***editable*** to `false` and then use the ***cellClick*** callback to trigger the confirmation. If the user then confirms, you can call the ***edit*** function on the [Cell Component](http://tabulator.info/docs/4.6/components#component-cell) to trigger the edit

Also on a separate note you should never try and access any properties with an "_" at the start of the name, it is convention in JavaScript that these are private variables and accessing them could make the library unstable. in your case you just need to call the ***getData*** function on the Cell Component

```js
    {title:"lblNoRms", field:"noRooms", editor:"number",
            editable:false,
            cellClick:function(cell){
                let ids = cell.getData().ids;

                if (cell.getData().ids !== []){
                    if(confirm("do you want to edit ?")){
                        cell.edit(true);  //force cell edit
                    }
                }else{
                    cell.edit(true);  //force cell edit
                }
            },
        },
```

I hope that helps,

Cheers

Oli :)

**Comment by mats001** [comment]
Thank you for your response Oli.  
The solution you have suggested above gives the same result.  The focus seems to change from the cell once the `cell.edit(true)` is triggered and hence the column cannot be edited.  However if you step in to the function using the debugger it lets you do the edit.
