### ISSUE TITLE
View session history of table

### ISSUE THREAD

**Issue by MichaelC77** [olifolkerd/tabulator#2703]
I'm currently setting up some admin tables for a project I'm working on and I want to the ability to make several changes to a table before clicking a save button to process those changes and commit them to a database. 

After reading through the documentation and the History module code I noticed that the history does exist as an array already there is just no functionality to access that array. 

I think being able to access the history of the table for updating the data elsewhere would greatly improve quality of life for me. 

As it stands right now, the easiest way I can see this being done is by using `cellEdited` and store it in an array but I see no easy way to retrieve the original value.

I've forked the repository and added the function in question :
    `History.prototype.getHistory = function () {
        return this.history;
    };`

Which when accessed using:
    `table.getHistory();`

Returns an array like this: 
    
![image](https://user-images.githubusercontent.com/38082474/78676991-be99e780-78c1-11ea-9e6e-d40a25161541.png)

The array could obviously be formatted in a different manner for easier readability but it was more for a proof of concept.

Let me know what you think!

**Comment by olifolkerd** [comment]
Hey @MichaelC77 

The history data is not exposed because there is no meaningful way to present the user with the "details" of what has happened in the history, it tracks a lot more that just editing and not all of it is easy to represent in a format that would be useful to anyone outside of the tables internal functionality.

Each [Cell Component](http://tabulator.info/docs/4.6/components#component-cell) has a ***getOldValue*** function that will return the value of the cell prior to the edit if you need it for any reason, though given your explanation of what you are after i am not sure why you would need the original value?

You could just push the cell component to an array on edit and then iterate over the array of cell components to retrieve the updated values. if you need to work out which row has been edited the each cell component has a ***getRow*** function that returns the [Row Component](http://tabulator.info/docs/4.6/components#component-row) that the cell is in.

I hope that helps,

Cheers

Oli :)
