### ISSUE TITLE
Custom Cell Editor and Multiple Selection, Prevents Editing Rows.

### ISSUE THREAD

**Issue by jmeberst** [olifolkerd/tabulator#2716]
**Describe the bug**
When using Tabulator with selection: true and a custom editor on a column, After triggering a cell edit, some rows become un-editable and instead just get selected/deselected.

**Tabulator Info**
- Which version of Tabulator are you using?
4.6.2

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.
[https://jsfiddle.net/bk5t6eyp/3/](https://jsfiddle.net/bk5t6eyp/3/)

**To Reproduce**
1. Open the custom editor in the bottom row of the example by clicking on dubai, london. The custom editor will open.
2. Click on any other row.
3. The row will be selected instead of the cell edit event triggered.
4. Click the cell again, the row will be deselected and the original cell edit closed. No cell edit event will be triggered.
5. Repeat clicking the cell, no cell edit event will be triggered, only row selection.

6. Cell edits can only be triggered by clicking on a cell in another row.

**Expected behavior**
The cell edit event should be triggered on either the first or second click of the cell. (One click to clear the focus/select and the other to trigger the new cell edit?)

**Screenshots**

**Desktop (please complete the following information):**
Chrome 81.

**Additional context**
I tried adding stop propagation to the cellClick, and that didn't change the issue.

**Comment by olifolkerd** [comment]
If this is only happening on your custom editor it means that you are not handling the blur events correctly.

There is no difference between a custom editor and the built in editors as far as Tabulator is concerned, once the editor function has been loaded on table initialization they function exactly the same way.

I would recommend having a look at the code for the built in editors in `/src/modules/edit.js` and use that as a template for your editor.

It is an added challenge in your example because you have an editor with contents that exceeds the bounds of the cell so will have to manage blur events much more carefully. the select and autocomplete editors face similar challenes.

Cheers

Oli :)
