### ISSUE TITLE
Choose which columns to strech with fitDataStretch

### ISSUE THREAD

**Issue by FuchieSteph** [olifolkerd/tabulator#2725]
Hi,

It would be great to be able to chose which columns to strech with fitDataStrech layout. Then instead of stretching the last column, we would be able to choose the columns we want to strech and how to fill the remaining space. 

I know that the "fitColumn" layout exists, but I find fitData layout more readable on small screens.

**Describe the solution you'd like**
We could use widthGrow property. If there is no widthGrow property we strech the last column. If there is, we stretch the selected columns.

Normal behaviour
![image](https://user-images.githubusercontent.com/54945291/79965039-d362a780-848b-11ea-8aac-24343db27fd1.png)

Desired behaviour 
<img width="1044" alt="Capture" src="https://user-images.githubusercontent.com/54945291/79965059-d8275b80-848b-11ea-99d8-63b6ed90e56e.PNG">

**Comment by olifolkerd** [comment]
Hey @FuchieSteph 

If you want that level of functionality you should be using the ***fitColumns*** layout style. See the [Layout Documentation](http://tabulator.info/docs/4.6/layout#fittowidth) for more info.

Cheers

Oli :)

**Comment by mikekok** [comment]
I came here looking for the exact same thing.
Is there any way to achieve this in the latest version?

```fitColumns``` doesn't seem to be the right solution.

**Comment by noellopes** [comment]
I have the same problem fitColumns does not work for me. This would be a great addition.

**Comment by rframil** [comment]
If anyone is working on this, I simply added a "fitDataStretchFirst" layout option, copying fitDataStretch exactly but making the last step target the first column instead of the last. It seems to work just fine. My javascript is really basic, though, so I don't feel confident enough to suggest a change.

Specifically, I used e[0] instead of n in:

`n ? (o = s - i + n.getWidth(), this.table.options.responsiveLayout && this.table.modExists("responsiveLayout", !0) && (n.setWidth(0), this.table.modules.responsiveLayout.update()), o > 0 ? n.setWidth(o) : n.reinitializeWidth()) : this.table.options.responsiveLayout && this.table.modExists("responsiveLayout", !0) && this.table.modules.responsiveLayout.update()`

**Comment by mbnl** [comment]
> If anyone is working on this, I simply added a "fitDataStretchFirst" layout option, copying fitDataStretch exactly but making the last step target the first column instead of the last. It seems to work just fine. My javascript is really basic, though, so I don't feel confident enough to suggest a change.
> 
> Specifically, I used e[0] instead of n in:
> 
> `n ? (o = s - i + n.getWidth(), this.table.options.responsiveLayout && this.table.modExists("responsiveLayout", !0) && (n.setWidth(0), this.table.modules.responsiveLayout.update()), o > 0 ? n.setWidth(o) : n.reinitializeWidth()) : this.table.options.responsiveLayout && this.table.modExists("responsiveLayout", !0) && this.table.modules.responsiveLayout.update()`

For those using npm, where should I put this?

**Comment by rframil** [comment]
> Where should I put this?

That part is in the fitDataStretch.js file. Instead of targeting `lastCol` when setting the width at the last step, simply target another column. In the end, I decided to add a whole new mode called fitDataStretchTarget, targeting whichever column has "targetStretch" set to true. That required adding a new layout mode (including references elsewhere in the code) and a new column attribute.

**Comment by phnxdgtl** [comment]
My solution here was to edit tabulator.js and modify the `fitDataStretch` function.

Specifically, on line ~7320, I changed the code from this:

`columns.forEach((column, i) => {`

... to this:

`columns.slice().reverse().forEach((column, i) => {`
