### ISSUE TITLE
Editable cell becomes read only when editing value

### ISSUE THREAD

**Issue by chs8788** [olifolkerd/tabulator#2731]
HI,
i have a cell which in which i want to change the color. as soom as i change the color of cell , the cell become non editable.
in blow code i am trying to change of color of cell in prod column

var table = new Tabulator("#example-table", { layout:"fitColumns", history:true,

    columns:[
        {title:"API",field:"name", width:200},
		
		{//create column group
        title:"Vintage",

        columns:[
		{title:"AvailableVintage", editor:true,field:"availablevintage", width:150},
        {title:"DEV", editor:true,field:"dev"},
        {title:"QA", editor:true,field:"qa"},
        {title:"PROD",editor:true, field:"prod",formatter:function(cell, formatterParams){
        //cell - the cell component
        //formatterParams - parameters set for the column

        var value = cell.getValue();

        if(value === "Jan 2020"){
            cell.getElement().css({"background-color":"#f00"}).text("Uregent");
        }

        return value;
    },},
        {title:"PROD Push Date",editor:true, field:"proddate"},
        ],
    },

        {title:"Cycle",editor:true, field:"cycle"},
        {title:"Comments",editor:true, field:"comments"},
    ],
});

**Comment by nrayburn-tech** [comment]
A few things from looking at your code.
cell.getElement() returns an html node.  So there is not any `.css()` method, you need to use `.style.backgroundColor = '#f00';` instead.
Same thing for .text(), you need to use a valid method.  Maybe `.textContent`, but I didn't look into that.
Here is a simplified example that sets the background color if it matches, otherwise it sets the background color back to empty.  If you don't reset the background color, then the cell will change to red and never switch back.
https://jsfiddle.net/emv48wau/2/

If you need any additional help with the valid methods on nodes, I would recommend searching StackOverflow questions, or the MDN documentation.

**Comment by chs8788** [comment]
Thanks for your help and works like a charm
    On Sunday, 26 April, 2020, 06:53:40 am IST, nrayburn-tech <notifications@github.com> wrote:  
 
 


A few things from looking at your code.
cell.getElement() returns an html node. So there is not any .css() method, you need to use .style.backgroundColor = '#f00'; instead.
Same thing for .text(), you need to use a valid method. Maybe .textContent, but I didn't look into that.
Here is a simplified example that sets the background color if it matches, otherwise it sets the background color back to empty. If you don't reset the background color, then the cell will change to red and never switch back.
https://jsfiddle.net/emv48wau/2/

If you need any additional help with the valid methods on nodes, I would recommend searching StackOverflow questions, or the MDN documentation.
