### ISSUE TITLE
wrong Tooltip text for formatted cell data

### ISSUE THREAD

**Issue by kapekost** [olifolkerd/tabulator#2748]
**Describe the bug**
Using a formatter for a cell, is breaking the tooltips function. If you format your data, and set tooltips to true, the tooltip seems to be generated based on the actual object value, and not what the formatter has generated. As a workaround, to get the actual displayed data we can do:             cell._cell.element.firstChild.data

**Tabulator Info**
@4.6.2

**Working Example**
https://jsfiddle.net/6vntejp4/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/6vntejp4/
2. hover on a cell
3. See the tooltip having a date which is the old data

**Expected behavior**
The tooltip function to be able to do a cell.getValue with the actual displayed data of the cell

**Comment by 805bluebell** [comment]
I assume that you need to change the cell data and reflect it appropriately in the tooltip as well.
Why don't you use a custom tooltip function? 
So, instead of just `tooltip: true` in table definition define a custom function to the task. Something like this
```
tooltips:function(cell){
    return cell.getValue() +" formatted data";
}
```
A fiddle for the same here. https://jsfiddle.net/opankajkumar/vxjadz4L/10/

**Comment by kapekost** [comment]
indeed, got a similar workaround at this point, just thought of it better to be as "expected" behavior as 
to avoid having to couple that 'client' side, right?

**Comment by 805bluebell** [comment]
Yeah. Logically, Tooltips and cell content are not supposed to have a common data source. In case they have to then it's a custom case. What do you say?

**Comment by kapekost** [comment]
Hmm indeed they are different things, setting it to true though, defaults to getting that source, therefore any other value (pre-formatted) might be un-needed in most of the use cases I can think of 🤔 
In simple formatters I can see it becoming [object].

**Comment by olifolkerd** [comment]
Hey @kapekost 

The tooltip is working exactly as expected. formatters are visual only and do not affect the underlying data of the cell. Otherwise they would break sorting and filtering ete, as they can return HTML and DOM nodes not just text.

If you want to change the underlying data of the cell then you should look at using [Mutators](http://tabulator.info/docs/4.6/mutators#mutators) as that is their primary purpose.

Cheers

Oli :)
