### ISSUE TITLE
row is not adjusting to content automatically.

### ISSUE THREAD

**Issue by ZalaJaydipsinh** [olifolkerd/tabulator#2762]
[photo of problem](https://drive.google.com/open?id=10lI3EreMt_6tB4ZQXH0e0IwvXS_Iunor)

and i am using **formatter:"textarea"** option.

**Comment by olifolkerd** [comment]
Hey @ZalaJaydipsinh 

If you want to report a bug please use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) it will prompt you to provide all the information we need to help you out.

We will need to see a JS Fiddle that shows how your table is configured in order to offer addvice.

Cheers

Oli :)
