### ISSUE TITLE
Left border should not be set in grouped columns

### ISSUE THREAD

**Issue by dbauszus-glx** [olifolkerd/tabulator#2765]
The first column in a grouped column should not have a left border.

![image](https://user-images.githubusercontent.com/22201617/81398466-25106080-9121-11ea-82eb-2fe99e5d9dde.png)

```
    .tabulator-col-group-cols > .tabulator-col:first-of-type {
      border-left: none;
    }
```

![image](https://user-images.githubusercontent.com/22201617/81398544-4a9d6a00-9121-11ea-9f6d-237994b1befc.png)

Might be hard to see on the screenshots. Not a biggie anyways as I override this in my custom tabulator css.

**Comment by olifolkerd** [comment]
Hey @dbauszus-glx 

Could you confirm which version of Tabulator you are using and which theme?

Could i ask that in future, you use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) when reporting bugs as it will prompt you to provide the info we need in order to help you.

Also it is really helpful if you can provide a link to a JS fiddle so we can see how you have everything setup, it makes it much easier to get to the bottom of the issue,

Cheers

Oli :)

**Comment by dbauszus-glx** [comment]
It's not you, it's me. I had a separate CSS with conflicting rules. Will close this.
