### ISSUE TITLE
cell.getRow().getData()

### ISSUE THREAD

**Issue by cgountanis** [olifolkerd/tabulator#2774]
Is this the recommended way of getting data from the AJAX returned data even if it is not actively used in the table as a column? I need to use data for a hyperlink and the cell part is confusing. Not really the cell but the row of returned JSON data that I am trying to access.

`cell.getRow().getData().[propertyName]`

**Comment by olifolkerd** [comment]
Hey @cgountanis 


If you want to get the value for a cell, you can call the ***getValue*** on the cell:
```js
var value = cell.getValue();
```

If you want to get the value of another cell in the row then there is a shortcut, there is also a ***getData*** function on the cell, which does the getRow bit for you:

```js
var value = cell.getData().propName
```

The cell is one of Tabulators component objects, and is one of the workhorses of the table. each type of component represents a part of the table and allows you to take actions and retrieve data from it. Full details of these can be found in the [Component Object Documentation](http://tabulator.info/docs/4.6/components)

Could you please ask future questions on Stack Overflow as this issues list is reserved for Bug Reports and Feature Requests. Full details can be found in the [Community Guidelines](http://tabulator.info/community)

I hope that helps,

Cheers

Oli :)

**Comment by cgountanis** [comment]
Cool so it is working fine but I had to ask. I am not getting data from the table or any of it's cells. I want to use data that is in the JSON row that is not being displayed in the table. So I assume that is the way. Say you have an id that you want to use in a hyperlink but you do not want it in the table. The name cell is just confusing to me.

**Comment by olifolkerd** [comment]
Im afraid i dont know what you mean by "I am not getting data from the table or any of it's cells. I want to use data that is in the JSON row that is not being displayed in the table."

If you are having issues getting things setup then please post a question on stack overflow with a link to a JS fiddle that shows your table setup, as it can be really hard to provide advice without knowing how things are configured.

The cell component is called "cell" because it represents a cell in the table (this is standard spreadsheet terminology) just like the "row" component represents a row of the table and the "column" component represents a column of the table"

If you want to access a propterty on the row that is not being displayed in a column then this is the correct approach:
```js
var value = cell.getData().propName

Cheers

Oli

**Comment by cgountanis** [comment]
Sounds good thank you and I will ask in SO. Just hard to get moving on that site sometimes.

The documentation has a formatter using `cell.getRow().getData().[propertyName]` so the extra getRow() confused me as well, maybe unneeded in the documentation?

Thanks for the time and effort on this project!
