### ISSUE TITLE
headerFilterParams Sorting by Value and not Text?

### ISSUE THREAD

**Issue by cgountanis** [olifolkerd/tabulator#2775]
Why does the select sort by value/id and not the text?

![image](https://user-images.githubusercontent.com/14899817/81580432-0dc8b180-9373-11ea-8550-82f890c0d0c3.png)

I get the JSON.
```
var url = "/api/flags";
var flags;
$.getJSON(url, function (data) {
    console.log(data);
    flags= data;
});
```

Here is the JSON.
```
{
    "1": "AAA",
    "14": "BBB",
    "4": "CCC",
    "5": "DDD",
    "17": "EEE",
    "15": "FFF",
    "18": "GGG",
    "11": "HHH"
}
```

This is how I implement the headerFilter select using headerFilterParams.
`{ title: "Test 8", field: "test8", minWidth: 100, headerFilter: "select", headerFilterParams: { values: flags } },`

**Comment by cgountanis** [comment]
Wait, I think it is the getJSON that is doing the sort automatically.

**Comment by cgountanis** [comment]
@olifolkerd Are there any examples about the best approach to getting JSON and dynamically populating a headerFilter select? I think I am damn close.

**Comment by olifolkerd** [comment]
Hey @cgountanis 

I really appreciate your enthusiasm for Tabulator, but could i ask you to take a few minutes to get used to using Tabulator and explore the documentation a little more, take time to build out your table, experiment with features and ask Stack Overflow before rasing bug issues on here. 

In the past 2 days you have raised 5 issues on here flagged as bugs and 4 of these have not been bugs at all.

As the first point of the [Bug Reporting Guide](http://tabulator.info/community#bug) says, More often than not the problem is not with Tabulator and you should make sure the problem is not with your code. Stack Overflow is there for general questions, where there are many Tabulator developers that can help you out. This list is ONLY for bugs (with repeatable test cases) and feature requests, and if you want to file one of these you need to use the correct [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) that will prompt you for all the answers you need.

 It is also essential that you provide a link to a JS fiddle that demonstates your issue as it is very hard to offer advice without understanding the context of how your table is setup.

I am very happy to help out new users, but i hope you can understand that tabulator gets downloaded over 15,000 times a week, if every user asked questions on here i would never be able to track any of the actual bugs or updates.

Please take a minute to read through the [Community Guidelines](http://tabulator.info/community), they will only take a couple of minutes to read and will help you in finding the right source of info for your enquieries.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@cgountanis If you have a look at the [Editor Documentation](http://tabulator.info/docs/4.6/edit#edit) for the select editor you will see there is a ***sortValuesList*** for handling list sorting

Cheers

Oli

**Comment by cgountanis** [comment]
I understand, was just not obvious that sortValuesList would work for a headerFilter. Thanks.

**Comment by olifolkerd** [comment]
Hey @cgountanis 

As mentioned yesterday in relation to the header filters, and as the docs say in several places, the header filters simply use editors, they are exactly the same thing, there is nothing special about them.

Any editor can be assigned as a header filter and all of the params available for that editor are also available when it is used as a header filter via the ***headerFilterParams*** property in the column definition

Cheers

Oli :)

**Comment by cgountanis** [comment]
Thanks for all the help, I tried to at least with every created issue have a solution and/or documentation suggestion for others. Not the biggest waste of time but I get it.

Would be nice to have a dynamic example of headerFilterParams with value/text with sorting by TEXT. Sure others would love that in AJAX/ServerSide pagination. If you have a select you kinda want a distinct list of all the options not just the first page.
