### ISSUE TITLE
Datatree scroll to top when expan the rows

### ISSUE THREAD

**Issue by prateeks39** [olifolkerd/tabulator#2786]
Hi Oli,

 If a table has datatree option enabled and height set to '100%' and expanding the row the browser will scroll to top but when I did not use height in options it will give scroll bar in table that I don't want to show (scrollbar) .
I want to show maximum content without any scrollbar within a table.

I have created a sample of issue.

Version :4.6.3
jsFiddle:- https://jsfiddle.net/prateeks39/mu35nda2/

**Comment by olifolkerd** [comment]
Hey @prateeks39 

That is happening because you havnt got a height set on the body so the table isnt properly entering virtual DOM mode, which is resulting in the table being redrawn on tree expansion toggle, which resets t the document scroll

You need to give the containing element a height for your approach to work correctly.

Chers

Oli :)
