### ISSUE TITLE
headerFilterFunc <= showing unwanted rows

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#2792]
I can't recreate the problem with code, so here's a GIF:

https://imgur.com/a/HB9apAp

When I filter for `<= 1`, it works ok, but when I try `<= 2` it works for the first two rows, but then it shows everything beginning with 1 ( 10's, 100's) as seen below the `2`.

If I put `<= 3` it will show 20's, 200's as well...

Here's the column definition:

```js
{
    title: "Категорија",
    field: "rankCategory",
    headerFilter: "number",
    headerFilterFunc: "<=",
    headerFilterPlaceholder: "<=",
    formatter: numberFormatter,
},
```
I have it set to `number`, and it still does weird stuff, I'm going insane. 

What might be the problem?

**Comment by nrayburn-tech** [comment]
It sounds like it is sorting the values as strings and not numbers. Without seeing the actual data, I am going to assume it is being passed in as `{value: “4”}` instead of `{value: 4}`.

I can’t say for certain without creating an example, but that seems to be the most likely issue.

You should check your data is coming in properly. If it needs to remain a string, you could look at using a mutator or a custom filter function.

**Comment by olifolkerd** [comment]
Hey @8483 

If you can't recreate an issue in a JS Fiddle, then it is a strong indicator that it is an issue with your code rather than Tabulator. in that case it should be asked as a question in stack overflow. not as an issue on GitHub.

as @nrayburn-tech says, this is likely because your data is in the wrong format for the filter function, in which case you should look at using a [Mutator](http://tabulator.info/docs/4.6/mutators)

Cheers

Oli :)
