### ISSUE TITLE
dataFiltering/dataFiltered callbacks function(filters) returning empty array

### ISSUE THREAD

**Issue by DhanalakshmiG** [olifolkerd/tabulator#2812]
`dataFiltered(filters , rows) {
    //filters - array of filters currently applied // returns []
  }

<React15Tabulator
              ref={ref => (this.ref = ref)}
              columns={this.state.columns}
              data={this.state.data}
              dataFiltered={(filters, rows) =>
                this.dataFiltered(filters, rows)
              }
              dataFiltering={this.dataFiltering}
              options={options}
>
`
Want to get filter params on column filter

**Comment by olifolkerd** [comment]
Hey @DhanalakshmiG 

Please ask questions on Stack Overflow.

If you think you have found a bug you need to use the [Bug Report Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) and provide a JS Fiddle or Code Pen that demonstrates the issue.

If you want to get the header filter value of a column you should use the ***getHeaderFilterValue*** function. checkout the [Filter Documentation[(http://tabulator.info/docs/4.6/release#filter) for more info.

Cheers

Oli :)

**Comment by ajmichels** [comment]
I am also encountering this issue.

I find it to be incredibly discouraging when project maintainers completely ignore legitimate bug reports just because someone didn't want to jump through your hoops to do so. I understand that it can be frustrating not having all of the details you want when someone reports a bug in your software, but it doesn't make it any less of a bug and ignore it is a disservice to everyone that uses the software. Getting bug reports with limited information is just part of the gig. If you want to have quality software just deal with it, otherwise people to just use something else.

**Comment by olifolkerd** [comment]
@ajmichels Before you post such rude comments i would strongly suggest that you consider how a lot of open source projects are maintained.

Despite tabulator being a Popular table building library downloaded millions of times a year, it is maintained by only **one** developer with minimal contributions from the wider community.

This project is maintained for free alongside my day job, and with 1000's of people contacting me every year, i simply don't have the time to go chasing through every poorly described bug, that quite often is simply a misunderstanding of how to use the table, which is why there is a bug template, and a request to first ask the community on stack overflow for wider feedback before posting on here. Often people find that when the create the requested JS Fiddle that it is actually their code that is the issue and it solves chagsing a phantom bug.

Given the literally 1000's of hours of unpaid work i have dedicated to the creation an maintenance of this library, i do not consider it out of order to ask a developer to spare 5 minutes of their time to fill in a few simple details to make things easier to resolve.

Given that since this bug was originally posted, i have completely rebuilt this library from the ground up it is almost certain that any issue you are experiencing is unrelated to this bug, you may consider rasing an issue of your own. Though i would strongly recommend that you read the [Community Guidelines](http://tabulator.info/community) and check your attitude before posting again if you are looking for any form of assistance.

Oli

**Comment by ajmichels** [comment]
I don't think there was anything rude about the way that I provided you with feedback. I didn't use any aggressive or offensive language and expressed _my_ opinion. I don't think is problem is unique to you, but it is clear you have a sore spot for you. I will work around the issue I am having and find a different solution for future projects. Best of luck to you.

For any who might benefit from the information. What I was running into is that the `dataFiltered` event was firing twice every time the `Tabulator.addFilter()` was called, **or so I thought**. The first time included an empty array for the `filters` argument and the full unfiltered rows. The second time included the populated `filters` array and filtered rows as I was expecting. I realized that the first event call was because I was **clearing** the filters immediately **before adding** new ones.

Some feedback. It would be nice if the events were fired with an `Event` object and/or contained more information about what triggered the event. For example, was the event triggered by the filters being cleared, or by them being added.

**Comment by olifolkerd** [comment]
@ajmichels It isn't just a sore spot for me, it is a sore spot for a huge amount of the open source community. People treating open source community maintained products as if there were something that the developer has paid for.

Community developers freely donate their time to provide a tool for the everyone, there aren't teams of customer support agents waiting to help anyone that has issues. That is literally the purpose of sites like stack overflow, to help share that load.

There is only so much time that open source developers can devote to their libraries, and part of the deal with using that software is that if you want to feedback you participate in the community sharing part of the burden, and especially when it comes to bug reports, that is a tiny burden. Which as i mentioned before are more often that not actually the users own coding mistakes.

In the company where i work, if we come across a bug with a bit of open source software we will always try to submit PR where possible before a bug report to try and share the load.

If you have constructive feedback on functionality then i am absolutely all ears and would love to engauge with you. If all you want to do is complain  that the customer services on this free tool with no paid support and clear community guidelines on how to work is not up to your desired standards, then i suggest that you look for a paid for tool in future.

Cheers

Oli
