### ISSUE TITLE
Slow autocomplete header filter

### ISSUE THREAD

**Issue by zanatoshi** [olifolkerd/tabulator#2815]
First things first, thank you for this nice framework very useful for us.

**Describe the bug**
 Since the 4.6 version, the use of an autocomplete header filter is slower. When you type few characters in an autocomplete header filter you can see : 
- the first character appear in the input
- wait more than 1 second
- the other characters appear in the input and the list is updated

Conditions on the data : more than 60000 objects of 20 attributes.

**Tabulator Info**
4.6+

**Working Example**
[Example](https://jsfiddle.net/eLfbpg89/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Use the first column header by typing oli

**Expected behavior**
the input stay reactive even if the list take time to get updated (can add a loader)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome
 - Version 81.0.4044.138

**Additional context**
I first things it was my fault so I run the chrome profile to try to find out what is happening.
There I found that the keyup event trigger the filterlist function which takes too much time.
As we can see in the joined profile, a lot of gc is called because of the use of a lot of deep clone.

The focus is also taking some times, but this was already happening in previous versions.
Here a screenshot of keyup trigger in the profile : 
![Capture of the profile](https://user-images.githubusercontent.com/3593258/83023299-00771c80-a02d-11ea-991f-0132e5cd3335.PNG)

The profile (you can reproduce it with the fiddle example) : 
[Profile-bug.zip](https://github.com/olifolkerd/tabulator/files/4688973/Profile-bug.zip)

**Comment by olifolkerd** [comment]
Hey @zanatoshi 

This is because you have 60000 rows an are asking Tabulator to build a unique list of values for this, which will take some time.

The reason it is more apparent in 4.6 is because the editor has been updated to allow ajax data returns to populate the list which means the value list is rebuilt each time the search is entered, which in this case means it reparses the rows each time.

I can look to improve this functionality by caching the unique columns list. I will see what i can get in for the 4.7 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @zanatoshi 

I have pushed a fix for this to the 4.7 branch will will be released later this month.

Cheers

Oli :)
