### ISSUE TITLE
If tabulator created without attaching it to DOM then header height is zero

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2816]
**Describe the bug**
Create tabulator object without attaching it to DOM first.
After creation attach tabulator to DOM

**Tabulator Info**
- Which version of Tabulator are you using? 
4.6.3

**Working Example**
Did not complete this yet

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Create tabulator object
2. Attach tabulator to DOM

**Expected behavior**
Headers should have normal size

**Screenshots**
![_3](https://user-images.githubusercontent.com/799021/83037163-222fce00-a044-11ea-9b37-c48f05f7506a.jpg)

As you can see here that if I manually change height size of header cell then it normally displayed.
Problem here is that header height zero when tabulator is not attached to DOM first

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Browser FF v74

**Comment by nrayburn-tech** [comment]
This is expected.  If the `tabulator` instance is created without already being visible in the DOM, then you have to manually `redraw` it after.
The first question here, http://tabulator.info/faq.

**Comment by KES777** [comment]
http://tabulator.info/docs/4.6/layout#redraw

>If the size of the element containing the Tabulator changes (and you are not able to use the in built auto-resize functionality) or you create a table before its containing element is visible, it will necessary to redraw the table to make sure the rows and columns render correctly.

**Comment by olifolkerd** [comment]
Hey @KES777 

If you believe you have found a bug, please create a JS Fiddle that demonstrates the issue

Cheers

Oli

**Comment by KES777** [comment]
I am sorry, Oli. I am not always have a time to create that ((

**Comment by olifolkerd** [comment]
Hey @KES777 

As per the [Community Bug Reporting Guidelines](http://tabulator.info/community#bug) im afraid we need to see a working JS Fiddle in order to progress with this.

I understand that everyone is busy, But I have a full time job as well as writing this library and supporting this community and i simply don't have the time to put together examples of issues for every question that is asked on the list as well as everything else.

Most of the time when i ask people to put together an example they find that it is actually their code that is the issue and then the bug request goes away. it is the first step in the process of tracking down the source of the bug and splits the load between the community and myself.

Cheers

Oli :)

**Comment by KES777** [comment]
Yes, I understand you.

Oli, is it ok if I create and close issue myself. 
And when I investigate into working example then reopen it?
**I just do not want to forget about an issue**
