### ISSUE TITLE
Mutator do not allow to update related fields after mutation

### ISSUE THREAD

**Issue by KES777** [olifolkerd/tabulator#2820]
**Describe the bug**

I try to update field with mutator. After updating other fields are not refreshed

**Tabulator Info**
- Which version of Tabulator are you using? 
4.6.3

**Working Example**
https://jsfiddle.net/KES777/on9p3bua/11/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open link: https://jsfiddle.net/KES777/on9p3bua/11/

**Expected behavior**
When I update field with mutator:
```
    mutator: function( value, data, type, params, component ) {
     ...
      data["valid_from"] =  moment(dates[1], 'YYYY-MM-DD').format("YYYY-MM-DD");
      data["valid_till"] =  moment(dates[2], 'YYYY-MM-DD').format("YYYY-MM-DD");
```
I change values of neighbor fields.
Would be nice if tabulator provide interface to update redraw those fields.

Probably instead of `data` tabulator should provide whole `row`.
So I can do: `row.getCell( 'valid_from' ).setValue( my_value )`
If I want to access `data` I can still do: `row.getData()`

**Screenshots**
Here you can see that after `addData` columns `valid_from`, `valid_till` correct, but after `row.update` are not =(
![image](https://user-images.githubusercontent.com/799021/83161873-a7cd7f80-a111-11ea-8357-328c791724e9.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Browser FF
 - v74

**Comment by olifolkerd** [comment]
Hey @KES777 

That is an invalid use for a mutator. If you want to set data on a column then you need to define the mutator on that column, there is a whole event lifecycle tied into the mutation of data, and by trying to set data in that way you bypass some of the event triggers which is why things update.

In your usage case you want to define the mutator on the ***valid_from*** and ***valid_till*** columns and have them return a value based on the ***app_period*** value.

Cheers

Oli :)
