### ISSUE TITLE
Textarea loses focus on every key press if height is % or auto

### ISSUE THREAD

**Issue by genyded** [olifolkerd/tabulator#2834]
**Describe the bug**
If the table height is set to any percentage value or auto, when editing a textarea the element loses focus on every key press. Changing the height to a literal pixel value works, but that will not allow a 100% height table.

**Tabulator Info**
4.6.3

**Working Example**
https://jsfiddle.net/gbvam5ck/2

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/gbvam5ck/2
2. Click on the TA Test (textarea) field and try to edit it
3. Every key stroke will cell cause focus to be lost
4. Set table height to a literal value as opposed to a % or auto
5. Textarea works

**Expected behavior**
Should be able to edit textarea at 100% height (or any % height or auto height)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome

**Comment by olifolkerd** [comment]
Hey @genyded 

That is because your table is situated in the body element, which does not have a height set, therefore takes up only the space of the table. it will therefor resize every time you change the height of the table triggering a redraw.

In this scenario you wither need to set the body element to a height of 100% or have no height on your table.

Cheers

Oli :)
