### ISSUE TITLE
Performance of getSelectedData() vs getData()

### ISSUE THREAD

**Issue by systek17** [olifolkerd/tabulator#2835]
http://tabulator.info/docs/4.6/components#component-row

I have 500 rows. If I want to perform some operations based on those rows, `table.getRows()` returns the rows faster than `table.getData()`. On each row object within the iteration, I would rather get the data using `row['_row']['data']`

Also when you have the same number of rows selected, `table.getSelectedData()` performs faster than `getData()`. This should be mentioned in the website.

**Comment by nrayburn-tech** [comment]
Can you provide a working example that shows the performance difference?  You should create a new issue using the bug report template and fill in all of the requested information.
https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=

Without a working example from you, we would have to re-create one.  Our example may not result in the same issue as yours.  There are too many different variables that can be involved.

I would expect `row._row.data` to always return faster than `row.getData()` because you are directly accessing the data object.  You are accessing a variable which should be considered private.  https://stackoverflow.com/questions/4484424/underscore-prefix-for-property-and-method-names-in-javascript

 At any time the `row._row.data` may change and not contain the data that you expect.  This can change without notice. Whereas if you use `row.getData()` it will always return the same data OR it will be documented as a breaking change.

**Comment by olifolkerd** [comment]
Hey @systek17 

Thanks for getting in touch.

I would not consider it note worthy that different functions that do different things take different amounts of time time. Nor would i really expect comparative analysis of the performance of each function in the documentation.

The ***getRows*** function returns an array of RowComponents for every row in the table. each of these component objects has to be generated before the function returns.

The ***getData*** function returns the row data object, but this has to be isolated and accessors applied before it is available which takes additional processing.

trying to access the data using the _row variable is strongly discouraged. the `row.getData` and the `table.getData` methods perform vital functions on the data. they run any accessors on the data to convert it as needed, they also use Object.assign to isolate the data and prevent pass by reference issues corrupting the data from outside of Tabulator.

The ***getSeletedData*** function returns only the selected rows on the table, a much smaller subset, so is therefore inherently faster.

The documentation clearly states the output of each function and it is down to the developer to decide which is the best fit for them.

If you have a particular usage case in mind, then please create a question on Stack Overflow asking for community input on the best way to proceed.

If you think you have found a bug then please follow @nrayburn-tech and create a bug issue using the template.

Cheers

Oli :)
