### ISSUE TITLE
Version 4.7 Released

### ISSUE THREAD

**Issue by olifolkerd** [olifolkerd/tabulator#2850]
Hi Everyone,

I am sure you will be happy to hear that the 4.7 release is now live.

Checkout the [Release Notes](http://tabulator.info/docs/4.7/release) for full details.

On a separate note, how would you like notifying about future update availability? 
Is a notice on the website going to reach you? 
do you watch the repo?
is there another platform you follow to keep up to date?

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Great again, thanks a lot.
Fine for me as it is. Checking homepage and github often.
Cheers, Michael

**Comment by R0lin** [comment]
Thanks for this update!
I also don't need any other notification platform to keep me up to date.
Cheers

**Comment by vec2k4** [comment]
Thanks again for the update. 

I'm checking github and the homepage on a regular base to be in sync.

Cheers, Ralf

**Comment by rexxitall** [comment]
Thanks - seems you has fullfilled my whish for drag and drop to any other Element :)

**Comment by jjech** [comment]
In my use case, we have Tabulator pinned to a specific version that is stable for us. I don't actively watch for new releases, since Tabulator "just works" and upgrading to a newer version could potentially break our project. As a result, I sometimes miss out on new useful features because I'm not aware of when a new version of Tabulator is released. (This was the case with the 4.6 release).

Personally I would love to subscribe to an email distribution list for Tabulator. At minimum, the emails distributed via this list could announce new versions of Tabulator and share the release notes, but I wouldn't mind receiving any other announcements you wanted to share with your subscribers.

**Comment by BernhardBaumrock** [comment]
I'm watching the repo and reading the release info - that is a great way to stay up to date, thx! :)

You have some typos:

![image](https://user-images.githubusercontent.com/8488586/85695769-a6738080-b6d8-11ea-9503-c972545cc1e2.png)

![image](https://user-images.githubusercontent.com/8488586/85698243-c86e0280-b6da-11ea-9c4c-251c9247c09e.png)

**Comment by srankgit** [comment]
hello thanks  a lot for this. indeed i could subscribe to a mailing list,  a telegram channel or a discord to follow tabulator updates.

on a side note : i update this issue with regards to fitdatatable,  https://github.com/olifolkerd/tabulator/issues/2644

thx again.

**Comment by olifolkerd** [comment]
Hey @BernhardBaumrock 

Thanks for the headsup, i will get those fixed this evening.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @srankgit 

If you think you have found a bug, please create a new issue, don't add it to old issues, we cant track the new bug  if it is on something already closed.

Cheers

Oli :)

**Comment by sndurkin** [comment]
Thanks for the update! I'm watching this repo for new releases.

**Comment by jodeca** [comment]
Thanks!!!!

**Comment by olifolkerd** [comment]
Hi @srankgit 

Hey @nclemeur 

I'm happy to announce the creation of the new Tabulator community Discord server.

Checkout the [Community Discord Announcement](http://tabulator.info/community/discord) for full details.

Cheers

Oli :)
