### ISSUE TITLE
headerFilter:true results in "input" type editor instead of the new multiselect editor

### ISSUE THREAD

**Issue by jjech** [olifolkerd/tabulator#2853]
**Describe the bug**
Setting headerFilter:true when using the new multiselect editor results in an 'input' type header filter instead of the new multiselect editor.

From the Tabulator documentation:
_Setting this parameter (headerFilter) to true will cause an editor element matching the columns editor type to be displayed in the header below the column title, and will allow the user to filter data in the table by values in that column. The editor will be chosen using the same rules as the editor parameter, for more information on this see the Manipulating Data section._

**Tabulator Info**
4.7.0

**Working Example**
https://jsfiddle.net/jjech/3th28pv0/262/

**To Reproduce**
1. Click on the column header field for the 'Species' column.
2. Observe that no multi-select dropdown appears.
3. Type "Hu" and notice that the header filter is behaving as input type.

**Expected behavior**
Per the Tabulator documentation, the same multi-select dropdown for the cell editor should appear in the column header filter.

**Comment by olifolkerd** [comment]
Hey @jjech ,

The `headerFilter:true` option only duplicates the editor not its params. the reason this is acting as an input  is because there are no prams so the editor has no specified values list. you should see a warning in your console about this.

if you add a ***headerFilterParams*** option you should be all good.

Cheers

Oli :)
