### ISSUE TITLE
Can it be possible for the cell background color to propagate when you create from HTML table element

### ISSUE THREAD

**Issue by criptk** [olifolkerd/tabulator#2859]
So I am using tabulator to create a table of MITRE ATTCK sightings from our data.
We used the number of sightings of a particular technique to color the background of said technique to a value closer to red as it is more used. Say "Account Discovery" is seen 1000 times and "Exploit Public Facing Application" is 500, the former would have the cell background color set to a dark red, whereas the second would be kind of orange.

The thing is i would like to use the information on the <td>  element, and by the looks of it i can only used "tabulator-" attributes if they are on <thead> and <th> element. Since the background of the cell is defined there i believe there is no way to have this propagated.

any ideas ?

**Comment by olifolkerd** [comment]
Hey @criptk 

I would not want tabulator to automatically clone any styling information from the underlying table, it uses it solely as a data source.

If you have the raw data, then i would strongly suggest passing that directly into Tabulator rather than populating it from an HTML table, it would be much more efficient that way.

At that point i would suggest that you use a [Custom Formatter](http://tabulator.info/docs/4.7/format#format-custom) to set the cell colour.

You could use the ***dataLoading*** callback to parse the incoming data and generate a lookup list to pair values with colours, then the custom formatter could use the lookup list for the value to set the background colour on the cell.

Cheers

Oli :)
