### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by AlainEdwards** [olifolkerd/tabulator#2872]
I noticed since the latest release a few days ago (`4.7.1`) the following column definition results in hiding the table header completely (i.e. no column headers); even when there are other columns whose `visible` property by default is `true`.

**Column definition in question:**
`{title:"personData", field:"personData", visible:false}`

My **table settings** are as follows:
```
{
headerSort:false,
                    height:238,
                    layout:"fitColumns",
                    dataTree:true,
                    dataTreeChildField:"items",
                    dataTreeStartExpanded:true,
                    reactiveData:true
}
```

no javascript warnings or errors reported. I checked the docs before submitting this issue but didn't see any special cases. Any ideas?

**Comment by AlainEdwards** [comment]
**Update:**

Invoking `table.hideColumn('personData')` after the table is rendered does work though. 🤔

**Comment by olifolkerd** [comment]
Hey @AlainEdwards 

Sorry to hear you are having trouble

Please use the [Bug issue template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) when rasing issues, it will prompt for all the information to help you.

You must post a link to a working JS Fiddle, it is pretty much impossible to offer help without seeing your table in action, a small snipped of code just inst enough to go on im afraid.

Also could i ask that you are more descriptive in your issue title. the title should outline the issue you face so that it is easy for myself and others to identify, can you imagine if every issue raised had the title "Possible Bug", how would i ever know which issue is which.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @AlainEdwards 

When i build an example based on your code it all works fine.

If you still believe you have found a bug, please post a link to a JS Fiddle or Code Pen that demonstrates the table setup and we cal look into it further.

Cheers

Oli :)
