### ISSUE TITLE
New rows are not added on top when tabulator is grouped

### ISSUE THREAD

**Issue by Mephysto666** [olifolkerd/tabulator#2875]
**Describe the bug**
Even I use

`addRowPos: "top"`

setting, new rows are added at the bottom and not at top.

**Tabulator Info**
4.7

**Working Example**
https://jsfiddle.net/1spgvfw7/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on 'Add row' button
2. See new added row is after all other rows and not as first.

**Expected behavior**
New rows should be added at the top of table

**Screenshots**
Starting table:
![image](https://user-images.githubusercontent.com/3337127/86449259-37b9a700-bd18-11ea-9968-d71044f2218a.png)

Table after two row added:
![image](https://user-images.githubusercontent.com/3337127/86449335-5455df00-bd18-11ea-9840-7649c5ddedcc.png)

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 68.9.0esr (64-bit)

**Comment by olifolkerd** [comment]
Hey @Mephysto666 

This is correct behaviour,

This is because when row groups are enabled, all rows MUST be contained in a group. when you add a blank row in your example it creates a new group which then tied to the current sort order of the table.

If you create a new row with a gender set it will appear at the top/bottom of the matching group

Cheers

Oli :)

**Comment by Mephysto666** [comment]
OK, thank you very much. Is it possible to have a feature to add a row at absolute top?

**Comment by olifolkerd** [comment]
Hey @Mephysto666 

Im afraid not, when row data is grouped a row must appear under a group header, that is just how the table is setup to run.

Cheers

Oli :)
