### ISSUE TITLE
Buggy scroll when scrolling

### ISSUE THREAD

**Issue by BryceBarbara** [olifolkerd/tabulator#2880]
**Describe the bug**
The scroll operation is canceled when dragging the scrollbar to scroll. 

**Tabulator Info**
4.7.1

**Working Example**
https://codesandbox.io/s/leads-search-mockup-v2-mp0bp?file=/src/components/leads-panel/leads-table/TabulatorComponent.vue

**To Reproduce**
It doesn't always happen so be sure to give it a few page refreshes if you don't see it happen the first time.
1. Go to page.
2. Resize the preview window so that the table doesn't have a horizontal scroll bar.
3. Reload the page.
4. Click and drag the table's vertical scrollbar and drag down.
5. See the scroll operation stop prematurely.

**Expected behavior**
The scroll operation should continue as long as the mouse is held down.

**Screenshots**
![93XZPkoqLE](https://user-images.githubusercontent.com/24460210/86661609-bc1e5b00-bfa0-11ea-966c-5ba386e7ba3c.gif)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.116

**Additional context**
It looks like it might also be related to width of the content/screen? I.e: If the content is just barely cutoff but not enough to show the horizontal scrollbar. I've never seen the behavior occur if the horizontal scrollbar is visible on the table.

**Comment by BryceBarbara** [comment]
After doing some more investigating, it looks like the `TableResizer` module is what's causing me grief. The behavior seems to be: 

1. ResizeObserver detects a resize
1. redraw
1. ResizeObserver detects a resize from the redraw
1. redraw again which returns the table to the initial size in step 1.

### Console trace showing the change in sizes
```
ResizeTable.tableElement.onResize(), Existing size = 629x500, New size = 646x500
ResizeTable.tableElement.onResize(), Existing size = 646x500, New size = 629x500
```

Since the size returns to what it was, the behavior repeats as new rows are swapped in and out due to the virtual DOM. The width is changing by 17 pixels which is the exact width of the vertical scrollbar 🤔


P.S: The `autoResize` option isn't listed on the [setup options page](http://tabulator.info/docs/4.7/options). Could it be added there? I can't speak for everyone, but that would've given me a head start on figuring out this odd behavior.

**Comment by olifolkerd** [comment]
Hey @BryceBarbara 

Thanks for rasing this as a separate issue. Im afraid that no matter how may times i refresh i am unable to get the issue to appear in your sample code.

Redrawing the table while scrolling shouldn't interrupt the scroll operation, the table has been built to handle that. 

Looking at your code i think the issue is that you are using the grid layout mode for the element containing the table.  Unless the grid is correctly configured it can fight against Tabulators own resizing system. other users have had similar if not the same issues before #2477

If that is the issue then i would look at the properties of the element containing the table to make sure that it isnt interfering with the resize observer, there are certain layout modes for the container that can cause issues. In which case disabling auto resizing would be a simple solution. I can only apologies for the missing ***autoResize*** option missing from the docs, i think that was probably accidentally removed in an update to the website last year, i will get that fixed in the next docs update.

I can certainly update the notes to include a warning about extra complexities around grid display modes.

One thing i would say is that you have an unusual table configuration there . When pagination is enabled the virtualDOM is usually disabled, because the table is intended to resize to fit all rows on the page.

By forcing a height on a paginated table and setting a page size you are then forcing it to redraw the paginated data. (you would usually either set a height and let the table determine the page size or set a page size and let the number of rows in that page determine the height), this is why it is calling itself multiple times.  having looked at the example on the website i can see how this is confusing.

It seems counter intuitive to have a scroll on paginated data, when the point of pagination is to make the data more accessible. usually the data should be paginated so the whole page is visible without the need for scroll.

I hope that helps,

Cheers

Oli :)

**Comment by BryceBarbara** [comment]
Thanks for the detailed response! You're right about the scroll and pagination being a bit much, my intention was to make sure my component could handle all scenarios first and then pull back. It was a bit of a "kitchen sink" sorta situation.

This is what I ended up with and it works great!
![image](https://user-images.githubusercontent.com/24460210/87098705-cb99e000-c1fc-11ea-8b73-5b8d51373d61.png)
