### ISSUE TITLE
virtual dom rendering incorrectly

### ISSUE THREAD

**Issue by daraHK-test** [olifolkerd/tabulator#2891]
If you run this code in jsfiddle, everything will be OK but if you run it locally on your desktop, virtual dom will not be rendered correctly and table size will be too huge. save the code on your desktop in "index.html" and run it ,then press the blue refresh button at the bottom of the page to see the problem. In codepen and jsfiddle it works normally, my problem is locally on windows.

If you change the  **formatter: "progress"**  to anything else, problem will be solved. 

This is the link to the code https://jsfiddle.net/sjz5fovp/1/

OS is windows 10
Chrome Version 83.0.4103.116 (Official Build) (64-bit)
Firefox 78.0.2 (64-bit)

What is my mistake? same code 2 different behavior

**Comment by olifolkerd** [comment]
Hey @daraHK-test 

Thanks for getting in touch.

If you think you have found a bug, please use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) it will prompt you for all the info we need to help you out

The issue is arising because of the way the elements are contained on the page

Your use of the redraw function is a bit unusual, and im not sure it does what you think it does, could you explain what it is you need to achieve and i can point you in the right direction

Im a bit confused why you have the `table.redraw(true)` line in after the table is built. the table will automatically redraw when you set data on it so there is no need for that to be there.

Also you can pass the initial table data directly into the ***data*** setup property so their is no need for the ***setData*** function either:

```js
 var table = new Tabulator("#example-table", {
    data:tabledata,
    columns: [{
        title: "Age",
        field: "age",
        formatter: "progress",
    }, ],
 });
```
You also seem to be be including the  `jquery_wrapper.min.js` file, which you dont need because you arnt instantiating your table using jquery

Cheers

Oli :)
