### ISSUE TITLE
Row update does not update all columns with the same field

### ISSUE THREAD

**Issue by nrayburn-tech** [olifolkerd/tabulator#2897]
**Describe the bug**
When using row.update(), all columns that share a field name are not updated.  (Note, when creating the initial table data all columns are updated.)

I didn't see anywhere that the column fields needed to be unique, but I could have overlooked it.

**Tabulator Info**
4.7.2

**Working Example**
https://jsfiddle.net/nrayburn/deg5s3rj/5/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open the fiddle
2. See that in the first record, `Name2` contains an updated value for the name, whereas `Name` does not.

**Expected behavior**
When using row.update() all columns are updated, including those that have the same field multiple times.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Browser Brave
 - Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)

**Additional context**
My table has the same field twice.  One uses a lookup to display a more user friendly name, where the other column displays the raw data.  When one of these items are changed, the other should also update.

**Comment by olifolkerd** [comment]
Column field names do need to be unique. If you want to use the same data in two columns, I would suggest making up a unique name for the second column and then using a mutator on the second column to copy the data over from the first

Oli :)

**Comment by nrayburn-tech** [comment]
I can come up with an alternative.  The inconsistency between loading the initial data and using row.update() just confused me.
Maybe a warning can be logged when a table is found that does not use unique fields?  I don't know how unique of a situation it is to try and use the same field twice.

**Comment by nrayburn-tech** [comment]
If you don't think a warning is necessary, then you can go ahead and close this issue.

Thanks!

**Comment by olifolkerd** [comment]
Hey @nrayburn-tech 

It is a fairly unique issue, it has probably only poped in the issues list twice in 5 years.

It basically relates to the way Tabulator uses the field as a key to reference a column when taking actions affecting individual columns. which isnt needed when the table is initially rendered, but is used later on.

I wouldnt want to add console warnings, because for a lot of people that use it they are just using Tabulator as a simple layout tool and in that case it works fine for them. I it is only an issue if you are going to be changing settings on columns or allowing changes to that columns data.

I will add a warning in the documentation to make it clearer.

Cheers

Oli :)
