### ISSUE TITLE
Empty values with autoColumns and column name containing a dot

### ISSUE THREAD

**Issue by Connum** [olifolkerd/tabulator#2900]
**Describe the bug**
When using the `autoColumns` option and a column name contains a `.` (e.g. in the not-so-uncommon case of a column name like `Item No.`), all the row values in that column will just be empty. However, no error is thrown in the console.

**Tabulator Info**
- 4.7.2

**Working Example**
https://codepen.io/Connum/pen/yLeZpKw?editors=1111

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Just open the fiddle and look at the columns
2. Compare what is displayed with the data that is provided via `.setData()`

**Expected behavior**
The values of all three columns are displayed correctly.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/13076806/88188677-761bf500-cc38-11ea-883a-6c46e744079b.png)
![grafik](https://user-images.githubusercontent.com/13076806/88188714-8338e400-cc38-11ea-911a-b4e3f2f4d762.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78.0.2

**Comment by olifolkerd** [comment]
Hey @Connum 

This is not a bug, this is because tabulator uses dot notation to handle data stored in nested objects. More info on this can be found in the documentation [Here](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) . 

This is standard JavaScript practice, as such it is considered bad practice to use dots in property names. for example in a nested object like:
```js
var details = {
    age:22,
    name:"Steve",
    car:{
        color:"red",
        make"ford",
    }
}
```

In order to access the make property of the car you would usual use the code `var make = details.car.make` so to avoid confusion you should not use invalid property names that include dots *(this is why you have to put them in quotation marks for JavaScript to accept them)*.

If you absolutely have to use dots in your field names for what ever reason, then Tabulator provides you with the ***nestedFieldSeparator*** option to change the separation character to something else to allow you to include dots in field names:

```js
var table = new Tabulator("#example-table", {
    nestedFieldSeparator:"|", //change the field separator character to a pipe
});
```

Cheers

Oli :)
