### ISSUE TITLE
mutilselect  headerfilter Problem

### ISSUE THREAD

**Issue by machanrk** [olifolkerd/tabulator#2904]
**Describe the bug**
When using mutilselect  headerfilter , it cannot show the correct filtered data. And when I click the cross inside the input box, it will focus inside and cannot trigger the option unless click other element and click it back.

**Tabulator Info**
- 4.7.2

**Working Example**
https://jsfiddle.net/zos4j01k/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click the headerfilter
2. Choose E and N
![image](https://user-images.githubusercontent.com/59240164/88512231-d0da9580-d018-11ea-9f9c-0e55e1318342.png)

3. No data shown
![image](https://user-images.githubusercontent.com/59240164/88512252-dcc65780-d018-11ea-84f2-6808ebb763e7.png)

4. Click the cross inside, if focused into the textbox and cannot shown the option when click
![image](https://user-images.githubusercontent.com/59240164/88512145-a4bf1480-d018-11ea-8b2d-eb9276fcb0c2.png)

**Expected behavior**
shown the column with E or N 
![image](https://user-images.githubusercontent.com/59240164/88512396-139c6d80-d019-11ea-94a9-03a0212ad4ae.png)

**Desktop (please complete the following information):**
Window 10 Chrome: 84.0.4147.89

**Comment by harshald28** [comment]
Yes, even I face the same problem. So expected behavior is
1. On "multiselect: true", data should be filtered on multiple options.
2. After clearing filter (by clicking on the close button) it should show filter options on click of that filter text box.

I have resolved this issue by adding a custom header filter function.

headerFilterFunc(headerValue, cellValue, rowData, filterParams) {
            if (headerValue.length > 0) {             
              return headerValue.includes(cellValue.toString());
            }
            //  to remove focus from filter.
            document.activeElement.blur();
            return true;
          }, 

Add this code after "headerFilterParams". I have tested on your provided jsfiddle.

**Comment by olifolkerd** [comment]
If you want to filter by multiple options then you need to set the ***headerFilterFunc*** to use the "in" function, which uses array comparison rather than string comparison

```js
{title:"Type", field:"type",  headerFilter:"select", headerFilterParams:{values:true,  multiselect:true}, headerFilterFunc:"in"},
```

The list of available built in filter functions can be found in the [Filter Documentation](http://tabulator.info/docs/4.7/filter#func-builtin)

Cheers

Oli :)
