### ISSUE TITLE
Tabulator rolls down page when I show a modal using @click-row event

### ISSUE THREAD

**Issue by clustersnake** [olifolkerd/tabulator#2905]
I created this example using bootstrap-vue, I tested with quasar framework and the same thing happens. Could you please help me out here?

**Tabulator Info**
- Tabulator-tables  4.7.2
-Vue-tabulator 1.2.2

**Working Example**
[code sandbox](https://codesandbox.io/s/bootstrap-vue-4k89l?file=/src/components/HelloWorld.vue)

**To Reproduce**
1. Go to this [url](https://codesandbox.io/s/bootstrap-vue-4k89l?file=/src/components/HelloWorld.vue)
2. Scroll the page up so you can see the table header
3. Click on the first row to show a modal
4. Close the moda
5. There it is, the page scrolls down by itself

**Expected behavior**
The page should be preserve its vertical position

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser Opera, Chrome

**Additional context**
The Issue doesn't occur in Mozilla firefox, latest version, only Chrome family browsers seem to be affected

**Comment by olifolkerd** [comment]
this is likely due to no height or max height being set on the table. which means the table is in classic render mode.

In this mode, any action that updates the table results in the whole table being redrawn which will cause the scroll shift.

Set a height or max height on the table to prevent this being an issue.

Cheers

Oli :)

**Comment by clustersnake** [comment]
You are absolutely right! It works now. Thank you very much!
