### ISSUE TITLE
Columns don't render if there's a period in the title string.

### ISSUE THREAD

**Issue by andrewbaldock** [olifolkerd/tabulator#2911]
**Describe the bug**
Column title shows up, but the column data itself is blank if there is a period/dot in the column name.

**Tabulator Info**
4.7.2

**Example with single period in the title that fails / triggers the Bug**
https://codepen.io/andrewbaldock/pen/YzwoNaa

**Example with no period in the column title, that works / does not trigger the bug**
https://codepen.io/andrewbaldock/pen/abdgpaw

**To Reproduce**
1. Open the first codepen and see no data in the columns because there is a period in the column title
2. Open the second codepen and see data in the columns because there is not a period in the column title

**Expected behavior**
A period/dot in the column title should not blank the column

**Screenshots**
BAD
![image](https://user-images.githubusercontent.com/1182215/88859400-82f79600-d1ae-11ea-82b1-a5d15a4eaa5b.png)

GOOD
![image](https://user-images.githubusercontent.com/1182215/88859419-8f7bee80-d1ae-11ea-8cf9-d8505c421bae.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: latest chrome

**Additional context**
Tabulator is cool, thanks for making it!!

**Comment by olifolkerd** [comment]
Hey @andrewbaldock 

This isnt a bug, this is an intentional feature, by default dot notation is used to denote that the field is referencing a nested object, it is considered bad practice to use dots in object properties, they should be alpha numeric only.

If you need to use dots in your property names you can use the nestedFieldSeparator option to change this to a different symbol thus making your table treat them as simple properties.

More information on this can be found in the [Nested Data Documentation](http://tabulator.info/docs/4.7/columns#field-nesting)

Cheers

Oli :)

**Comment by andrewbaldock** [comment]
Thanks for the answer Oli!  
We'll cleanse our titles before they hit tabulator.  
-Andrew

**Comment by mikeymckay** [comment]
Would be nice to show a warning like "column field is not alpha numeric" and a flag to disable nested data. It was hard bug to track down why some columns were always empty. My field names are the same as the title names and are just user generated sentences, often with a period at the end. I tried escaping the period, but it seems like it needs to actually be removed. So I had to add to code that checks for periods in field names, then removes it, then loops through all of the data and makes the same change.

**Comment by Podbrushkin** [comment]
I want to leave my feedback too. 
I'm using Tabulator to display tsv and I've spent too much time figuring out why data in columns isn't shown. Tabulator doc provides this simple usecase: 
```
//define some array data
var arrayData = [
  ["Name", "Age", "Likes Cheese"],
  ["Bob", 23, true],
  ["Jim", 44, false],
]

//define table
var table = new Tabulator("#example-table", {
    data:arrayData,
    importFormat:"array",
    autoTables:true,
});
```
There is no such concept as `field referencing a nested object` in this context, task is very simple and common, but behavior is unpredictable, and it was hard to figure out what is wrong.

Also sorry for offtopic, but [this documentation page](https://tabulator.info/docs/5.5/data) has an example of using `autoTables` option in Array section, but [this page](https://tabulator.info/docs/5.5/options) doesn't list such option. Maybe it should be `autoColumns` instead.

**Comment by federiva** [comment]
Came across this issue when passing some column fields with periods in their names.

I think that maybe you can use the [nested_field_separator](https://tabulator.info/docs/5.5/columns#field-nesting) in order to avoid such situations? Either by disabling or defining another field separator.

Btw, the ability of rendering nested fields is awesome and super intuitive the way it is! Thanks @olifolkerd for this amazing package
