### ISSUE TITLE
Rotated table headers

### ISSUE THREAD

**Issue by PythonPhilipp** [olifolkerd/tabulator#2915]
*Is your feature request related to a problem? Please describe.**
Rotated table headers increase the readability of long header-strings in combination with small columns widths.

**Describe the solution you'd like**
There is a greate CSS solution documented on the following url [https://wabain.github.io/2019/10/13/css-rotated-table-header.html](url)

**Additional context**
The existing solution **headerVertical** column definition property [http://tabulator.info/docs/4.7/columns#vertical](url) ist not sufficient, especially in combination with headerFilter = True.

**Comment by olifolkerd** [comment]
Hey @PythonPhilipp 

An interesting proposition, how would you imagine things like [Nested Column Groups](http://tabulator.info/examples/4.7#column-groups) be handled in that layout mode?

Cheers

Oli :)

**Comment by iursevla** [comment]
At our company we created skewed headers

![image](https://user-images.githubusercontent.com/13489488/89134102-1e279d00-d51a-11ea-9bd9-020447f35f02.png)

**Comment by iursevla** [comment]
> _Is your feature request related to a problem? Please describe._*
> Rotated table headers increase the readability of long header-strings in combination with small columns widths.
> 
> **Describe the solution you'd like**
> There is a greate CSS solution documented on the following url [https://wabain.github.io/2019/10/13/css-rotated-table-header.html](url)
> 
> **Additional context**
> The existing solution **headerVertical** column definition property [http://tabulator.info/docs/4.7/columns#vertical](url) ist not sufficient, especially in combination with headerFilter = True.

@PythonPhilipp the links are broken.

**Comment by darshanrampatel** [comment]
@iursevla Are you able to share some sample code of how you achieved this?

**Comment by iursevla** [comment]
@darshanrampatel I can, but now atm. Tomorrow I'll post a js fiddle. I'll update this post. If I don't please send a message again.

**Comment by iursevla** [comment]
@darshanrampatel

Here's  [a working example](https://jsfiddle.net/rr_alves/7yqcb928/91/) with skewed headers.

Basically:
1. With CSS make the header skewed. Header height is 140px and skewed angle is 45 degrees. If you change the degrees you'll have to change things.
2. Since tabulator is not ready to handle skewed headers a javascript class was created (*TabulatorHeaderColumnFixer*). This will listen to style changes and update the styling so that it can keep up with the changes. This will make sure the header and the columns are correctly styled.

The two main functions are:

```js
setFrozenHeaderColumnsPosition()
...
setNonFrozenHeaderColumnsPosition() 
```

See this 
```js

    // TODO: Sort of hack to enable skewed headers. If you comment out this line you'll see the header skrewed up
    this.useHeaderFixer();
```

**Comment by darshanrampatel** [comment]
@iursevla Thank you for the detailed example - I will take a look at this!

**Comment by PythonPhilipp** [comment]
The working example from @iursevla  [https://jsfiddle.net/rr_alves/7yqcb928/91/](url) with skewed headers looks quite good for me.

@darshanrampatel Are you also fine with the proposed solution?

**Comment by olifolkerd** [comment]
Hey All,

As I mentioned earlier i am happy to look into this more, but for this to be implemented in the core library there are a lot more things that need to be considered than simple column titles.

The layout would need to successfully support:
- Editable headers
- Header Filters
- Header Menus
- Sort Icons

If you can provide an idea of how you would see this function i would be happy to look into this further, otherwise i will be closing this feature request.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I am closing this issue due to lack of feedback, if anyone wants to pick up on this again some time feel free to post
