### ISSUE TITLE
Enable/Disable Selection Per Cell

### ISSUE THREAD

**Issue by andy-ziade** [olifolkerd/tabulator#294]
Hi,

First of all congrats for the great job.

How we can disable/enable a cell  ?

Thanks

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, it is always nice to hear people are enjoying using Tabulator!.

what do you mean by disable the cell? do you want to prevent editing, change the styling, prevent a callback from being fired?

Cheers

Oli

**Comment by andy-ziade** [comment]
Dear Oli,

Yes, I need to prevent editing the cell but not the hole column.

Thanks

**Comment by olifolkerd** [comment]
You would need to  create a custom editor to achieve this.

If the custom editor returns false instead of the UI element for the editor element then the edit action is canceled.

Have a look at the editable data section in the documentation [here](http://olifolkerd.github.io/tabulator/docs/#manipulating-data).

let me know if you have any questions.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, the ***editable*** column definition option now accepts a callback to determine if a cell should be editable:

```js
var editCheck = function(cell){
    //cell - the cell component for the editable cell

    //get row data
    var data = cell.getRow().getData();

    return data.age > 18; // only allow the name cell to be edited if the age is over 18
}

{title:"Name", field:"name", editor:"string", editable:editCheck}}
```

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
