### ISSUE TITLE
Need to get data immediately after loading table using ajax json

### ISSUE THREAD

**Issue by swamireddy954** [olifolkerd/tabulator#2940]
Hello, 

I'm having an issue with table.getRows() method. I have created a table and passed the data using ajax call. after setting all teh column and passing data, I'm trying to invoke table.getRows() methods which is returning an empty array instead of data. But when the page is loaded in chrome and trying to fetch data from the console using table.getRows() it is working. 

Can you please let me know how can we get table data while page loading?

Thanks.

**Comment by olifolkerd** [comment]
Hey @swamireddy954 

Please ask questions on Stack Overflow,

This issues list is reserved for feature requests and bug reports only.

When submitting a question you should always include a link to a JS fiddle that demonstrates your problem, it can be very hard to offer advice without seeing how your table is configured.

If you are calling the ***setData*** function to add data to the table, then you need to wait till the table data is loaded before calling ***getData*** otherwise the data may not be there yet (the speed of the load will depend on browsers and network speed). The setData function returns a promise that is resolved when the table is fully loaded, you can use this promise to ensure that your data is available before calling your function:

```js
table.setData(tableData)
.then(function(){
    //run code after table has been successfuly updated
})
.catch(function(error){
    //handle error loading data
});
```

I hope that helps,

Cheers,

Oli :)
