### ISSUE TITLE
Issue Applying Styles To Column Data

### ISSUE THREAD

**Issue by YMPrasad** [olifolkerd/tabulator#2967]
Hello Team,

Trying to apply styles to column data using below code 

![image](https://user-images.githubusercontent.com/69789287/91957911-4b878680-ed24-11ea-85ab-8410512f01aa.png)

but in the browser the result is (one record having this column value "2")

![image](https://user-images.githubusercontent.com/69789287/91957426-a10f6380-ed23-11ea-9902-a75643915908.png)

and noticed a message in browser as below:

![image](https://user-images.githubusercontent.com/69789287/91957615-e59aff00-ed23-11ea-89fe-a7e81b8f1bf2.png)

Am i doing anything wrong or any issue  ? Can anyone please help me out on this.

Thanks,
YMPrasad

**Comment by olifolkerd** [comment]
Hey @YMPrasad 

In future, could you please ask questions on Stack Overflow, this issues list is reserved for Bug Reports and Feature Requests only.


The problem you are experiencing is because you need to set an actual editor on the ***editor*** property, you cannot set it to true when using a custom formatter.

it should be something like:
```js
editor:"input",
```

Cheers

Oli :)

**Comment by YMPrasad** [comment]
Sincere apologies. Will post there.

Thanks for your response on the requested. 

Unluckily, tried above suggested solution but problem remained the same(except no browser console message).

**Comment by olifolkerd** [comment]
The other issue is because you are using a single `=` sign in your if statement, which means you are assigning a value to the variable and will always return true.

you need to be using a `==` which is a comparison operator

Cheers

Oli

**Comment by YMPrasad** [comment]
Thank you, Oli.  Your above suggestion is working.
