### ISSUE TITLE
Unnecessary vertical scroll-bar appears sometimes. 

### ISSUE THREAD

**Issue by h-tendy** [olifolkerd/tabulator#2975]
Hi Oli - One more 'off-by-one' rounding error. I'm using 4.7.2 and without specifying a fixed `height` for the table. (The contents of the table varies and want the table to adjust automatically). 

Sometimes, depending on the row contents, the vertical scroll-bar appears. The scroll-bar seems to not do anything and occupies the full length of the table. Upon closer inspection, it moves up/down by 1px I think. So, I'm guessing that some rounding error when you calculate the row-heights of all the rows and account for the horizontal scroll-bar etc. The fix that worked for me is as below. Again in the `adjustTableSize()` routine. Just do `+ 1` to the `this.element.style.height` style. 
``` js
			this.element.style.height = "";
			// Fix: +1 to correct for rounding errors. This fixes the gratuitous scroll issue.
			this.element.style.height = (this.table.element.clientHeight - otherHeight + 1) + "px";
			this.element.scrollTop = this.scrollTop;

```
Please incorporate if you agree. Thank you so much. 
-Jay

**Comment by olifolkerd** [comment]
Hey @h-tendy 

Thanks for getting in touch,

If you are filing a bug report, please use the [Bug Report Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) it will prompt you to provide all the information we need to help you.

As per your last issue, It is really important that you provide a link to a JS Fiddle or Code Pen that demonstrates your issue. most problems are caused either by user error or on planned interactions between different modules of Tabulator.

I would prefer not adding single pixels like that, it is a work around rather than addressing the problem. using `Math.ceil()` for example would likely resolve the issue if it is to do with rounding math errors at scale, and would not affect the table during normal operation.

Could you please provide a link to a JS Fiddle that demonstrates the issue and i can look at applying a fix.

If you have a minute please read through the [Bug Reporting Guide](http://tabulator.info/community#bug) it will explain the most helpful way to report a bug to us.

Cheers

Oli :)

**Comment by h-tendy** [comment]
Here's the fiddle like for this: https://jsfiddle.net/Lw8hud96/4/

On Chrome, set the zoom level to say, 75%. You should not see any scroll bar in the render. 
![image](https://user-images.githubusercontent.com/40791586/92634384-def72380-f2f1-11ea-8309-dd0a03246109.png)

Now, increase the zoom level to 80% (go higher or lower a bit depending on your screen resolution). Ideally, you should never get a vertical scroll-bar. Sometimes, you get it and it appears to be for 1px paging. 

![image](https://user-images.githubusercontent.com/40791586/92634557-1a91ed80-f2f2-11ea-8e92-f69160ceb507.png)

**Comment by olifolkerd** [comment]
Hey @h-tendy 

Im afraid that demo just worked for me without any scroll bar issues.

I have updated the function to floor out any sub-pixel sizes to prevent these height issues should they arise in future. This has been pushed to the master branch and will be included in this evenings patch release.

Cheers

Oli :)
