### ISSUE TITLE
Error using formatter and bottomCalc in 4.8.1

### ISSUE THREAD

**Issue by MChr1Ss** [olifolkerd/tabulator#2988]
**Describe the bug**
The error is: cell.getValue(...) is undefined
When using formatter and bottomCalc

I think it is because, the cell-row type is "calc".

**Tabulator Info**
- 4.8.1

**Working Example**
https://jsfiddle.net/yeapd01t/

Reference in 4.7.0 https://jsfiddle.net/x7u0g2kp/

**To Reproduce**
1. Go to https://jsfiddle.net/yeapd01t/
2. Compare with (4.7.0) https://jsfiddle.net/x7u0g2kp

**Expected behavior**
See 4.7.0

**Smartphone (please complete the following information):**
 - Browser FireFox
 - Version 68.12.0esr

Thank you Oli :-)

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

This is not a bug with Tabulator, this is an issue with your formatter.

Tabulator will apply the formatter to all cells both normal rows and calculations. The value passed into the formatter on a calculation will be `undefined` therefor your current logic will fail because you cannot get a length of `undefined`

You could either update your formatter to check to see if the value has a type of undefined before checking its length or you could use the ***bottomCalcFormatter*** column definition option to set a different formatter for the calc cell.

Cheers

Oli :)

**Comment by MChr1Ss** [comment]
Hey Oli, thanks for your reply.

I thought that's a bug, because it worked in the previous version. 
And there's the bottomCalcFormatter for formatting the calc cells. 

I'll update my formatter and check for the row-type :-).

Thank you.

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

The bottomCalcFormatter is used to override the standard formatter.

The reason it worked in the previous version is because in 4.7 only the cells containing data were actually formatted, but several users wished to have the ability to format unused calc cells too.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

On further investigation i had misinterpreted your explanation. there was  indeed a bug in the formatting of the column calculations with the default formatter.

I have pushed a fix for this to the master branch and will include it i todays patch release.

Cheers

Oli :)
