### ISSUE TITLE
4.8.1 custom formatters with formula cause custom formatters topcalc / bottomcalc incorrect

### ISSUE THREAD

**Issue by dannykhoo** [olifolkerd/tabulator#2996]
**Describe the bug**
if i put some basic formula in custom formatters, it will cause topcalc / bottomcalc value become incorrect

**Tabulator Info**
4.8.1

**Working Example**
Working Example (4.7.1)
https://codepen.io/dannykhoo/pen/MWyzJNb

Bug Example (4.8.1)
https://codepen.io/dannykhoo/pen/VwaVPBx

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
Just add any formular in custom formatter cell , then the bug will produce.

**Expected behavior**
it should not affected custom formatters in topcalc / bottomcalc ,  example in custom formatters bottomcalc , i just put 'return 88' , but the result is not 88.

**Desktop (please complete the following information):**
 Chrome 85.0.4183.102

**Comment by MChr1Ss** [comment]
It is almost the same problem I've got
See: [2988](https://github.com/olifolkerd/tabulator/issues/2988)

Now I have to use in every formatter:
`if(cell.getRow()._row.type == "row"){...}`
or
`if(cell.getRow()._row.type == "calc"){...}`

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

You should never use the ***_row*** property that should be considered private. you can use `cell.getRow() instanceof RowComponent` to determine if a row is a row or not for that appraoch.

But either way that isnt your issue here  or in your prebious issue. The issue is that your formatters do not correctly handle undefined cell values.

they should check to see if a value is undefined before  attempting any action on their value:
```js
if(typeof cell.getValue() !== "undefined"){
    //do thing
}
```

Cheers

Oli :)

**Comment by MChr1Ss** [comment]
Hey Oli,

thanks for your fast reply.

I think the common problem is: We didn't expect that the formatter is now formatting the top and bottom row, not like in 4.7.  Because there are the bottomCalcFormatter and topCalcFormatter. 
So we're getting strange behavior on the "old implemented formatter" and we have to exclude the calc rows.

In your example is it as well. There is the cross in the bottom (and top) calc-row.
[http://tabulator.info/examples/4.8#calculations](http://tabulator.info/examples/4.8#calculations)
In 4.7 it worked as expected [http://tabulator.info/examples/4.7#calculations](http://tabulator.info/examples/4.7#calculations)

But thanks for your hint to check it with `cell.getRow() instanceof RowComponent` that will probably do it. 

Best regards
Christian

**Comment by olifolkerd** [comment]
On further investigation i had misinterpreted your explanation. there was  indeed a bug in the formatting of the column calculations with the default formatter.

I have pushed a fix for this to the master branch and will include it i todays patch release.

Cheers

Oli :)
