### ISSUE TITLE
copy and paste a single/multiple row from a excel is not working correctly?

### ISSUE THREAD

**Issue by DebaPrasad14** [olifolkerd/tabulator#3000]
when I'm trying to copy some rows from CSV or excel and pasting these to the tabular table, then these are getting pasted in a single editable column, so is there any way we can paste so the data should be pasted in different columns.

For example- suppose I have copied 2 rows from excel having 4 columns and if I copy & paste these to a tabular table (having the same 4 columns) then these copied data should be pasted in 4 different columns in the table but it is getting pasted in only one column. so is there any way to achieve that?

Here is my code.
```
<template>
  <div ref="table"></div>
</template>

<script>
import Tabulator from 'tabulator-tables'; //import Tabulator library
import 'tabulator-tables/dist/css/tabulator.min.css';
import moment from 'moment';

export default {
  data: function() {
    return {
      tabulator: null, //variable to hold your table
      tableData: [
        { id: 1, name: 'Oli Bob', owner: 'bb@gmail.com', start_date: '18/09/2020',  due_date: '20/09/2020'  },
        { id: 2, name: 'Mary May', owner: 'a@gmail.com', start_date: '22/09/2020', due_date: '25/09/2020' },
        { id: 3, name: 'Christine Lobowski', owner: 'a@gmail.com', start_date: '12/09/2020', due_date: '25/09/2020' }
      ], //data for table to display
      columns: [
        { title: 'Name', field: 'name', editor: 'input', validator: ['required', 'maxLength:50'] },
        {title: 'Owner', field: 'owner', editor: 'input' },
        {title: 'Start Date',field: 'start_date',sorter: 'date',editor: 'input',validator: 'required' },
        { title: 'Due Date', field: 'due_date', sorter: 'date', editor: 'input', validator: 'required' },
      ],
    };
  },
  watch: {
    //update table if data changes
    tableData: {
      handler: function(newData) {
        this.tabulator.replaceData(newData);
      },
      deep: true,
    },
  },
  mounted() {
    //instantiate Tabulator when element is mounted
    this.tabulator = new Tabulator(this.$refs.table, {
      data: this.tableData, //link data to table
      reactiveData: true, //enable data reactivity'
      layout: 'fitColumns',
      columns: this.columns, //define table columns
      selectable: false,
    });
  },
  // template: '', //create table holder element
};
</script>
```

**Comment by olifolkerd** [comment]
Hey @DebaPrasad14 

Please ask questions on Stack Overflow. This repo is only for Bug Reports and Feature Requests.

If you are trying to report a bug then you must use the Bug Issue Template and fill in the requested fields as it will help us get to the bottom of the problem.

Cheers

Oli :)

**Comment by DebaPrasad14** [comment]
@olifolkerd isn't it a bug? does this allow us to do the above?

**Comment by olifolkerd** [comment]
Hey @DebaPrasad14 

As per the [Bug Reporting Guide](http://tabulator.info/community#bug) most of the time users experience issues it is likely just a misconfiguration of there table, so we encourage them to check on Stack Overflow first where they can get community feedback onto the configuration of there table.

If you genuinely think you have found a bug, that is fine, but you must use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) as it will prompt you for the information we need to help you out.

If you look at the template you will see it ask for step by step instructions for repeating your error, which version of Tabulator, which browser/os you are using. These are all critical facts that we need to help you out.

It also prompts you to provide a JS Fiddle or Code Pen that replicates the issue. This is very important. we have to communicate with 100s of developers a week and simply dont have the time to put togeather working examples from snippets sent to us. Also 90% of the time we find that when the developer builds out the JS Fiddle they usually find that the problem was in their environment and not actually a Tabulator issue, so it helps reduce the number of invalid issues.

Cheers

Oli :)

**Comment by DebaPrasad14** [comment]
Hey, @olifolkerd I posted this question on StackOverflow already before posting here. but unfortunately didn't get any response as of now.

**Comment by olifolkerd** [comment]
Thanks

I will be working my way through recent unanswered stack overflow questions tommorrow

Cheers

Oli

**Comment by DebaPrasad14** [comment]
thanks @olifolkerd

**Comment by abubelinha** [comment]
>  I posted this question on StackOverflow already before posting here

@DebaPrasad14 would you mind pasting here the StackOverflow link?
Thanks 
@abubelinha
