### ISSUE TITLE
Tabulator Issue: Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by zakipatani** [olifolkerd/tabulator#3003]
We are facing an error while we loaded a data on the page. The error was come at the first time. It means when we reload/refresh the same page then error not come and our code was successfully executed. We apply below steps:

First we load data using ajax call.
then we added a Tabulator js reference below the ajax call.
then we addded Tabulator code. See below Code:

```
<script type="text/javascript">

        var jsonData; //This is called in Tabulator data

        $(document).ready(function () {
            
                $.ajax({
                type: "POST",
                url: "forms.aspx/GetFormDetails",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {

                    var result;
                    if (data.hasOwnProperty("d")) {
                        result = data.d; 
                    }
                    else {
                        result = data;
                    }

                    var item = JSON.parse(result);

                    jsonData = item["NewDataSet"]["Table"];
                    
                },
                error: function (data) {

                }
            });
            

        });

</script>

<script src=".../tabulator.js" type="text/javascript"></script>
<script src=".../tabulator.min.js" type="text/javascript"></script>

<script type="text/javascript">

            $(window).load(function () {
 
                var table = new Tabulator("#example-table", {
                    data: jsonData,           //load row data from array
                    layout: "fitColumns",      //fit columns to width of table
                    tooltips: true,            //show tool tips on cells
                    initialSort: [             //set the initial sort order of the data
        {column: "project_name", dir: "asc" },
        ],
                    groupBy: "form_type",
                    columns: [                 //define the table columns
            {title: "Form Name", field: "project_name", headerFilter: "input" }

        ]
                });
   </script> 
```
Kindly help us to resolve this issue.

![image](https://user-images.githubusercontent.com/49384366/94109699-fcce9780-fe5e-11ea-8f1e-9c3eb715d485.png)

**Comment by olifolkerd** [comment]
Hey @zakipatani 

As has been mentioned on previous issues with you.

Please ask usability question on Stack Overflow first, This issues list is reserved for Bug Reports and feature requests only, and in either case you must use the issue templates that will prompt you for the info we need to help you.

A bug report is for a genuine issue with tabulator that you have checked with the community first.

Posting large blocks of code is unhelpful, we need to see your code in context to help. you  MUST provide a link to a JS fiddle that demonstrates the issue so we can see it in context.

From a quick scan of your code it is likely that the ajax request that you run on page load hasnt returened before you build the table, because ajax requests are asynchronous.

Im also unsure why you are making the request ouside of Tabulator. Tabulator has built in [Ajax Functionality](http://tabulator.info/docs/4.8/data#ajax) and the *** ajaxResponse*** callback allows you to format the returned data into something Tabulator can ingest.

Cheers

Oli :)

**Comment by skanel** [comment]
I have the same problem but i need to remove `table.setData(tabledata);` if you have call it anywhere in your code after declared, and after i removed this works for me.
