### ISSUE TITLE
ES6 modules usage in 4.8?

### ISSUE THREAD

**Issue by hrstoyanov** [olifolkerd/tabulator#3012]
**Website Page**
http://tabulator.info/docs/4.8/install

**Describe the issue**
Not sure if this is an omission in the docs, or it needs to be a new feature:
How can one directly import the ES6 module from UNPKG cdn? Java modules can be imported from URI, for example, something like this:
```
import {Tabulator} from 'https://unpkg.com/tabulator-tables@4.8.2/dist/js/tabulator-tables.js';
```
Is this possible, just not explicitly documented?

**Comment by olifolkerd** [comment]
At the point you are doing that you should be importing it into your
project using npm. Is there a reason you are trying to use a cdn and
import? They seem mutually exclusive

**Comment by olifolkerd** [comment]
Hey @hrstoyanov 

I suppose that would be technically possible as long as you were running your script inside of a `module` type script tag.

You would have to import from the tabulator.es2015.js file though as that is the module compatible table.
So it would be something like:
```js
<script type="module">
import Tabulator from 'https://unpkg.com/tabulator-tables@4.8.2/dist/js/tabulator.es2015.js';

var table = new Tabulator("#table", {
....
});
</script>
```

Let me know how you get on

Cheers

Oli :)

**Comment by hrstoyanov** [comment]
@olifolkerd I guess this would work. Take a look at how Vaadim published their router module here:
https://vaadin.github.io/vaadin-router/vaadin-router/demo/#vaadin-router-getting-started-demos

**Comment by olifolkerd** [comment]
I am unsure the purpose of showing that link


The import works the same, the only difference is they have named exports and Tabulator uses the default export, which is the correct approach for a module with only one export.

In browser ES6 module importing is per the spec supposed to take place inside module type script tags.

So the posted example works as per spec.

If you are not using Tabulator in browser then requiring via CDN would be an antipattern, in those scenarios the correct approach is to import it using a package manager and then use the standard import and require statements.

The breaking apart of the dist files into ES5 and ES6 compatible files is also standard practice so that the package.json can be directed to the correct code base for the correct environment. 


So I'm not sure what you are asking here as the sample code in the previous example does exactly as you have requested

**Comment by hrstoyanov** [comment]
also .. is there a minimized version for the module?

**Comment by olifolkerd** [comment]
There is no minified version of the ES6 module at present no. As it was originally only intended for use through package management importing which prefers in minified source.

I can look at adding a minified example to the roadmap

**Comment by hrstoyanov** [comment]
@olifolkerd why referencing modules through CDN URI in web application is anti-pattern? 
I know of a lot of teams doing it

**Comment by olifolkerd** [comment]
@hrstoyanov I think we are talking cross purposes now.

If the example i posted works for you thats great.

I was unsure as to why you posted the link to their modules documentation, i took it as a request for functionality, but that functionality already exists in Tabulator as was demonstrated in my first comment.

If all you were saying is that they had documented it then thats fine.

I understand you would like to see it documented, which is why this issue is still open and has a documentation flag attached to it.

But i need to consider how best to do this, The module approach is more complex that some other methods and including every possible import method in the docs risks confusing less experienced developers. So while i do agree this could be a benefit this is not something i will be adding to the docs till have had a chance to work it all through. The above example should work suitably for your needs now.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @hrstoyanov 

You will be happy to hear i have just pushed a commit to the 4.9 branch that adds a minified version of the es2015.js file

I have also prepared a documentation update that includes the above method of module importing from the CDN, this will appear in the documentation with the 4.9 release later in the month.

Cheers

Oli :)

**Comment by hrstoyanov** [comment]
Lovely!
