### ISSUE TITLE
Horizontal Scroll header not follwing Chrome Mobile

### ISSUE THREAD

**Issue by darren-trottier** [olifolkerd/tabulator#3014]
**Describe the bug**
Header will not follow Horizontal Scroll on mobile (Chrome)
In firefox it is working, but still is will lag, I think it is a known issue with javascript header scrolling execution on mobile. 

**Tabulator Info**
- Tabulator 4.8.1 

**To Reproduce**
Load any table that is larger than full screen in chrome 

**Expected behavior**
Header should follow horizontal scrolling 

**Screenshots**
![ezgif-2-82196b880a89](https://user-images.githubusercontent.com/57952871/94700523-8f60b200-0309-11eb-8afc-875fcba8d092.gif)

**Smartphone (please complete the following information):**
 - Device:  Huawai P30 Pro, Samsung Galaxy Tab S2
 - OS: e.g. Android 10.1, 7.0
 - Browser:  Chrome
 - Version: 84

**Additional context**

```
var table = new Tabulator("#table_detail", {
            data:tableData,
			columns:Object.keys(tableData[0]).map(obj => {
			return {
				title: obj,
				field: obj,
				sorter: "string",
				align: "right",
				editor: true
				}; 
			}),
                    },
		});

```

**Comment by olifolkerd** [comment]
Hey @darren-trottier 

Please could you include a link to a JS Fiddle or Code Pen that replicates your issue so we can see it in action.

As per the [Bug Reporting Guide](http://tabulator.info/community#bug) and in fact this issue template, we ask you to provide a fiddle or code pen because errors are often linked to the way the table is being used and without seing it fully setup and working we cannot get to the bottom of the issue easily

Cheers

Oli :)

**Comment by darren-trottier** [comment]
Not sure how can I get a JS Fiddle to work, I've done it with the chrome debugger linked on my phone.

**Comment by olifolkerd** [comment]
Hey @darren-trottier 

You dont need any debug tools or anything, a js fiddle should simply show the issue you are experiencing, if you setup your table in the fiddle and then try and access it on your phone, if you cant scroll the header you have successfully replicated your issue and we can then use that to find a fix for you.

If you set up your fiddle and it works on your phone, then this suggests that the issue is with the environment and not tabulator itself *(which happens more often than not)* which is another reason we ask people to do this as is separates the tabulator issues from the site setup issues.

Cheers

Oli 👍

**Comment by darren-trottier** [comment]
You are right, on JSFiddle is seem to work with the same code. Still JsFiddle is not mobile friendly... I've also remark on JsFiddle there is no lagtime on the header. 

Strange that the Xamp setup seem not to performe well compare to JsFiddle.

Issue can be close, I will look on my side.
