### ISSUE TITLE
Can't implement my own spinner

### ISSUE THREAD

**Issue by alainpannetier** [olifolkerd/tabulator#302]
There is something that I can't fathom.

Scenario:
- I want to display a spinner. 
- But I'm _not_ trying to use the built-in spinner ("Loading Data").
- Only for the long running operations. Say after 2 seconds.
- Strategy.
  - Before calling "setData" with my array of rows. I set a timer displaying my own div (pos absolute etc). 
  - Value of the timer: 2000 ms of course.
  - When "setData" returns, it clears the timer and hides any loader. 
  - So operations taking less than 2s never show the timer. Classical.

Precisions:
  - my spinner is not a DOM child of the tabulator home div (css class tabulator).
  - for instance 1000 rows, less than 10 columns for now.
  - if I delay setData a bit, spinner displays as expected. But _all_ loads display the spinner.

Problem:
 - Once setData starts, no kind of timeout works.   
 - GUI is irresponsive.

Is it a jquery queue problem? A browser issue? A known issue?
Many days of research. No hair left. Surrounding walls in rubble.

**Comment by olifolkerd** [comment]
Hey,

There is already an option for custom loader elements, simply set them in the ***loader*** option.

```js
$("#example-table").tabulator({
    loader:$("<div style='display:inline-block; border:4px solid #333; border-radius:10px; background:#fff; font-weight:bold; font-size:16px; color:#000; padding:10px 20px;'>Custom Loading Data</div>"),
});
```
If you wanted to have control over the loaders contents then i would suggest passing a selector to an object that is outside of the table, that you can manipulate the contents of.

The beta version of Tabulator 3.0 will be coming out later this week, and has enhanced loader functionality, it also uses a virtual DOM so has zero loading time for large table (aside from the time needed for a ajax request if loading remotely) so that should speed things up for you.

Let me know if that helps,

Cheers

Oli

**Comment by alainpannetier** [comment]
Thanks Oliver for the super-flash answer. 
I did see that loader option. 
The thing is, my idea was to display the loader selectively - only for the long running operations.
Hence the timer play. Which I seem to be unable to implement.
I'm eager to try tabulator 3.0 - especially considering ignorant (and now bald) me has no idea what a virtual DOM is...  
I have to deliver tomorrow. So I can wait a bit and compromise for now.
Don't close yet. I'm so puzzled, I'll get to the bottom of that one.

**Comment by olifolkerd** [comment]
Hey,

Well if you need to have something out by tomorrow, lets get to the bottom of this now.

Are you loading data over ajax? Could you post a copy of your tabulator constructor so i can see how your table is set up. it is likely you just need to use another callback.

A virtual DOM means that the rows are created and destroyed as they enter and leave the visible section of the table, it means it only ever has to display a small number of the rows, so can instantly load massive data sets. it also means it doesn't slow the browser down trying to move thousands of rows every time you scroll.

Cheers

Oli

**Comment by alainpannetier** [comment]
Don't worry Oli. The things I have to deliver is yuge - way beyond a few tables ( over 100kloc) and I was just being unreasonably perfectionist on one point. I'll follow your more reasonable suggestion in the short term.  So no need to change your plans for me. Let's keep 3.0 as your target.
I'm sure I've messed up too much and I just need to step back and re-start from a clean version.
Many thanks for your generous offer.
Otherwise: here is the context. No Ajax. Constructor and calls are wrapped into javascript "classes". So it's not easy to reduce to a small case. I'll do that over the WE though. Or migrate to 3.0 :+1:

**Comment by olifolkerd** [comment]
So the issue you are having is that rendering all those rows is hogging the all the processing power which is killing the timeouts you are setting.

This will be completely fixed in version 3.0, but until then i would suggest you use the progressive rendering option, which will render sections of the table as you scroll to them making it load much faster.

Check out the documentation for this feature [here](http://olifolkerd.github.io/tabulator/docs/#progressive-render)

Cheers

Oli

**Comment by alainpannetier** [comment]
Thanks Oliver. I'm OK with progressive rendering. I did try it. Works nicely  (modulo issue #296). 
So far I did not come arround implementing the update of the table in the background (without scrolling). yet.
Also, since, in my wrapper class, I expose that  progressive-rendering option, I wanted to have both progressive and non progressive rendering to work smoothely. 
That will be for a bit later.

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release, with its new virtual DOM there should be no long loading times :)

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
