### ISSUE TITLE
Avergage function does not work

### ISSUE THREAD

**Issue by blue-urban-sky** [olifolkerd/tabulator#3025]
average function is not functional maybe only using html importer 

v 4.8.2

https://codepen.io/blueUrbanSky/pen/rNLBQvy

**Expected behavior**
should average correctly

**Additional context**
src/js/modules/calculation_colums.js:L457 - the reduce function needs to initialise the accumulator with 0

```
output = values.reduce(function(sum, value){
				value = Number(value);
				return sum + value;
			}, 0);
```

**Comment by olifolkerd** [comment]
Hey @blue-urban-sky 

Thanks for the headsup,

I will get a fix out for this in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @blue-urban-sky 

I have pushed a fix for this to the master branch.

The issue wasn't to do with initializing the accumulator, this always starts as the first value. The issue was that the sum was beig read in as a string not a number from the table so it was concatenating the numbers instead of adding them.

The fix will be included in the next patch release.

Cheers

Oli :)
