### ISSUE TITLE
Layout property with Frozen

### ISSUE THREAD

**Issue by mark-zarandi** [olifolkerd/tabulator#3029]
**Website Page**
http://tabulator.info/docs/4.8/layout#frozen-column

**Describe the issue**
I was having trouble getting this to work and then noticed that your example for frozen columns dictated no "layout" property, so commented mine out.  For sure, I see now i think why frozen columns won't take a layout property, but i think the expectation from this module is that it will accept a layout property.  I had "fitDataTable".  Loving everything else so far tho, thanks.

**Comment by olifolkerd** [comment]
Hey @mark-zarandi 

the frozen columns system will work with any of the layout modes, the exception to this is the ***fitDataTable*** layout mode, because in this mode the table is designed to change the width of the table to fit the columns, and never to produce a scroll bar. with no scroll bar ever being created in this layout mode, frozen columns make no sense.

Cheers

Oli :)
