### ISSUE TITLE
Cannot input value in custom control created in column formatter function

### ISSUE THREAD

**Issue by EfimKR** [olifolkerd/tabulator#3037]
**Describe the bug**
You can create input in column formatter and it will be used in tabulator. I did it because I need custom behaviour in input (allow only number input, etc.) In 4.2.7 all worked fine, but in 4.8.2 I cannot input value. This bug exists in Google, in Firefox all works fine. In Chrome it may be fixed by prevent propagation 'click' event on input.

**Tabulator Info**
Tabulator v4.8.2

**Working Example**
https://jsfiddle.net/EfimKR/dw2bpq31/15/

**To Reproduce**
We have simple table. Two colums are input. You can input in field2 but cannot in filed1 if you open example in Chrome. In Firefox you can input both.

**Expected behavior**
Can input without call stopPropagation() on 'click' event.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  86.0.4240.75

**Comment by olifolkerd** [comment]
Hey @EfimKR 

This is because you have row selection enabled on row click, when the row is selected it triggers a redraw of the row and loose focus.

It is bad practice to allow rows to be selectable like that while also containing editors/editable formatters as it creates a poor user expereience as the row selection is toggled as they click into the cell.

In your setup I would move to using a row selection tickbox formatter, as it will improve user experience:
```js
var table = new Tabulator("#example-table", {
    columns:[
        {formatter:"rowSelection", titleFormatter:"rowSelection", align:"center", headerSort:false},
    ]
});
```

In this scenario the correct approach is to stop the click event propagating down to the row, so using the `stopPropagation()` is not a bug but the correct approach.

I am a bit unclear why you have used formatters to handle editing tasks. the idea would normally be that you use a custom editor rather than a custom formatter for this. as your formatters will not actually update the value of the cell in the data.

Cheers

Oli :)
