### ISSUE TITLE
Row doesn't get resized after formatting a cell

### ISSUE THREAD

**Issue by LancerRevX** [olifolkerd/tabulator#3053]
I put a code for creating a nested table into a formatter of a cell, which has a 'field' property filled in, so I don't have to call row.reformat() every time I update it's data, I also return a nested table's DOM element from the formatter function. The nested table gets built properly, but the row doesn't get resized, so the table happens to be hidden inside it. The solution I came up with is to call row.normalizeHeight() in setTimeout callback with 0 milliseconds delay.

Tabulator version: 4.8

Bug illustration: https://jsfiddle.net/u27Ladn5/
My solution: https://jsfiddle.net/svk8rmg7/

To reproduce:
1. create a top-level Tabulator table
2. add a formatter function for one of it's columns
3. create a nested table inside this formatter function
4. use nested table's DOM element as a return value

Expected behavior:
I expect a row to be resized after creating a nested table in a cell formatter function, as it happens if a nested table is created in a rowFormatter function.

Windows 10 1909, Firefox 81.0.2 x64

**Comment by olifolkerd** [comment]
Hey @olifolkerd 

This is because you are trying to render the table before the element that holds it is visible which is causing layout issues.

You need to put your subtable definition inside the ***onRendered*** formatter passed into the formatter:
```js
formatter: (cell, formatterParams, onRendered) => {
    	let nestedTableElement = document.createElement('div');
      
      onRendered(() => {
        new Tabulator(nestedTableElement, {
          layout: 'fitColumns',
          data: cell.getValue(),
          columns: [{
            title: 'ID',
            field: 'id'
          }, {
            title: 'Name',
            field: 'name'
          }]
        });
      })
      
      return nestedTableElement;
    }
```

Though it is odd that you are doing it inside of a cell. most people use the ***rowFormatter*** to achieve this instead. see the [Nested Table Example](http://tabulator.info/examples/4.8#nested-tables) for more info

Cheers

Oli :)
