### ISSUE TITLE
replaceData causes scrolling to stop

### ISSUE THREAD

**Issue by wildcat-cs** [olifolkerd/tabulator#3056]
**Describe the bug**
Updating the table using replaceData causes the scroll bar to stop if the user is actively scrolling during the update causing the user to release the mouse button, re-click on the scroll bar and continue.   

**Tabulator Info**
4.8.2 (https://unpkg.com/tabulator-tables@4.8.2/dist/js/tabulator.js)

**Working Example**
fiddle: https://jsfiddle.net/2xsu7o8c/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Run fiddle
2. Continually scroll by dragging the scroll bar up and down 
3. Scroll bar will stop scrolling when replaceData is called (interval is set at 1 second so could a few drags to see issue)

**Expected behavior**
Scrolling should not be interrupted while replacing data.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome/Edge
 - Version: 86/85

**Additional context**
Documentation says replaceData should be used to silently replace the data without alerting the user to the data change without alerting the user, however with many items in the grid scrolling through them becomes an issue when the scroll bar keeps pausing whenever data is changed.

**Comment by olifolkerd** [comment]
Hey @wildcat-cs 

Thanks for getting in touch, this isnt a bug, more a limitation of the browser.

There is no way to track scroll momentum so there would be no way to interrupt the scroll and then let it continue. the replaceData causes a full redraw of the current view of the table so the scroll bar essentially disappears and is rebuilt in the same position which will abort any scroll.

This is a bit of a neiche issue and not something i would be looking to change. the vase majority of uses of the replace data function are for static dashboard displays of which this has no impact.

If you are worried about this you could always add a scroll listener to the table and then only call the ***replaceData*** function if it has been 300ms since the last scroll.

Cheers

Oli :)
