### ISSUE TITLE
Column Calc Error - No such calculation found when using custom calculation

### ISSUE THREAD

**Issue by johnpitchko** [olifolkerd/tabulator#3077]
Tabulator throws warning `Column Calc Error - No such calculation found, ignoring:  myCountCalc` when integrating a custom calculation in a table. Confirmed that custom calculation is defined above the table where it is being implemented.

Oddly enough, when I follow the same steps to create an implement a different custom calculation on a different page, it works fine.

**Tabulator Info**
4.8.2

**Working Example**
See [JSFiddle](https://jsfiddle.net/johnpitchko/fjLwzch1/1/)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 82.0.3

**Comment by olifolkerd** [comment]
That is because you are referenvig it as a string in the column definition, but you are using a custom function

Strings can only be ued to load built in functions, if you are using a custom function then it should be assigned as any other function would in JavaScript by passing the function into the property:

```js
 bottomCalc: myCountCalc, //no quoatation marks
```

Cheers

Oli :)

**Comment by johnpitchko** [comment]
Wow thanks @olifolkerd. Geez I feel dumb now! Got it fixed now, thanks again. Sorry to waste your time.
