### ISSUE TITLE
Ability to create from CSV

### ISSUE THREAD

**Issue by sdraper69** [olifolkerd/tabulator#3079]
Firstly, great work on Tabulator, it's exaclty what I needed and very powerful.

**Describe the solution you'd like**
The ability to create a tabulator table directly from a CVS file.

**Additional context**
I believe this could be really useful as people could save out from Excel and other applications (for example engineering and CAD applications) and then import and have a table easily.

**Comment by h-tendy** [comment]
Yeah, I had a similar need. But stepping back, you also need a full backend/frontend usually to support this kind of "data grooming". I've started a project towards this end using @olifolkerd 's wonderful component. 

https://github.com/h-tendy/datagroom-gateway and https://github.com/h-tendy/datagroom-ui

But this is in very very early stages and it hasn't been announced anywhere and might have some initial kinks of course. See the readme file in the first repo.

**Comment by olifolkerd** [comment]
Hey @sdraper69,

At the moment Tabulator dosnt handle data in a simple array format, but this will be coming in the 5.0 release so i will look into this functionality then

@h-tendy great to hear you are working on a Tabulator based tool, it is always great to see Tabulator in action. but could i ask that you promote your tool on the {Tabulator Ideas Repo](https://github.com/olifolkerd/tabulator-ideas) rather than in feature requests. the ideas repo is specifically there for people to showcase off their great work. If you make a Pull Request with a link i would be happy to accept it.

Cheers

Oli :)

**Comment by sdraper69** [comment]
hi @olifolkerd , thanks for getting back to me. I'll keep an eye out for V5!

Keep up the great work.

**Comment by olifolkerd** [comment]
Hey All,

I have just pushed an update to the 5.2 branch which includes the new `import` module.

This will allow you to import any type of data into the table and then tell Tabulator how to interpret it.

This will be included in the next release.

Cheers

Oli :)
