### ISSUE TITLE
Unable to extendModule to reference headerMenu by string in Tabulator 4.7.2

### ISSUE THREAD

**Issue by andrew-phil-bell** [olifolkerd/tabulator#3080]
**Describe the bug**
When trying to extendModule to create a different "headerMenu", I receive an error when clicking on the header menu.  When I don't use extendModule, things work as expected.

**Tabulator Info**
4.7.2

**Working Example**
https://jsfiddle.net/abfiddler/9sj1ahqc/

**To Reproduce**
1. Go to https://jsfiddle.net/abfiddler/9sj1ahqc/
2. Scroll down to bottom right quadrant and click on the ellipses menu beside "project"
3. Notice the "script error" in the console.

**Expected behavior**
I expect that extendModule would allow giving strings for headerMenu lookups.  Since the data source is coming from JSON, this extendModule approach has proved invaluable for formatters/mutators already.

**Screenshots**
![image](https://user-images.githubusercontent.com/61638998/99455260-770a1e00-28dc-11eb-8494-4f44a74eaf33.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome
 - Version 86.0.4240.198

**Additional context**
N/A

**Comment by andrew-phil-bell** [comment]
As I look at the code, this looks like a feature request now since the menu module doesn't seem to support this lookup.

**Comment by olifolkerd** [comment]
Hey

You are correct,this is not supported.

Only modules that have built in options allow extension in this way.

There are no built in defaults for the menu system because every use case would be unique, therefore it wouldn't be appropriate as a feature.

If you explain your usage case in a bit more detail I may be able to offer a solution.

Cheers

Oli
