### ISSUE TITLE
Question on stopping cell editing

### ISSUE THREAD

**Issue by wp4nuv** [olifolkerd/tabulator#309]
Hello!  This is a separate issue than my last:  On issue #294 you mention that the editor must return false for the edit event to be stopped.  My editor varies depending on the value of another field:

    switch (data.requires_date) {
        case 'y':
            var input = $("<input type='text' pattern='(?:19|20)[0-9]{2}' placeholder='yyyy' length=4/>");
            break;
        case 'my':
            var input = $("<input type='text' pattern='(0[1-9]|1[012])/(?:19|20)[0-9]{2}' placeholder='mm/yyyy' length=7 />");
             break;
        case 'fd':
             var input = $("<input type='text' pattern='(?:(?:0[1-9]|1[0-2])/(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])/(?:30))|(?:(?:0[13578]|1[02])-31))/(?:19|20)[0-9]{2}' placeholder='mm/dd/yyyy' length=10 />");
        break;
        default:
        break;}`
This arrangement works as I expected, with the placeholder and pattern updating according to the value of the switch statement.  
Since my data is not in a form, I'm triggering validity using `checkValidity()`:
```    
input.on("change blur", function(e){
        e.target.checkValidity();
                cell.trigger("editval", input.val());
        }).bind('invalid',function(e){
                 alert("incorrect format");
                 e.preventDefault();
                 return false;
         });
```
The binding works because the alert is triggered, but the cell edit still goes through even with preventDefault() or return false.

This is the constructor:
```
// Define Table
		$("#table-bln-tabulator").tabulator({
			responsiveLayout: true,
			dateFormat: "mm/dd/yyyy",
			fitColumns: true, //fit columns to width of table (optional)
			columns:[ //Define Table Columns
    <?php echo $this->element( 'Loans.general_tabulator_user_documents_columns' ); ?>
			],
			groupBy: function(data){ //group document by class (mandatory)
				return data.doc_class;
			},
			cellEdited:function(id, field, value, oldValue, data, cell, row){

				// Store key vars for later use
				$("#loan_app_id_store").val(data.loan_application_id);
				$("#property_id_store").val(data.property_id);
				$("#editor_prior_store").val(oldValue); // Save prior value of this field
				$("#editor_cellcheck_store").val(1); // This value identifies an edit as a Cell edit vs Filter edit.
				var docid = data.doc_id;

				if(field === 'pertains_to'){
					var formValues = {"doc_id":docid,"field_type":field,"value":value,'type':row.doc_class};
				} else {
					var formValues = {"doc_id":docid,"field_type":field,"value":value};
				}
				var request_url = "/loans/user_documents/update";
				console.log(data);
				$.ajax({
					url: request_url,
					data: formValues,
					type: "POST"
				})
					.done(function(d){
						if(d == 1){
							cell.addClass("success")

						}
					})

			},
		});
```
_This is using CakePHP which explains why there's embedded PHP calls.  It works fine as is._

**Comment by Paraplegix** [comment]
Hi

I guess what you want to do is to no accept the modification made by the user until your `checkValidity()` function agrees ?

First the Issue n°284 is to prevent the cell from being editable, not from rejecting modifications.

What trigger the acceptation of the modification is `cell.trigger("editval", input.val());`. This line tell tabulator to take in the current content of the cell and apply the modification to the row data so you could change `checkValidity()` to return false when the current data inside your cell is not valid (and true otherwise) and change the lines to :

```
input.on("change blur", function(e){
       if (e.target.checkValidity())
                cell.trigger("editval", input.val());
        })
```

also i'd add `return false` after the `default:` statement in your switch case :) to prevent error if by chance `data.requires_date` was not defined or incorrect

**Comment by olifolkerd** [comment]
Hey,

if you can hold on till the weekend version 3.0 is going to be released with a whole new editor system, it even has a specific callback you can use to check that a cell is editable

Cheers

Oli

**Comment by wp4nuv** [comment]
@Paraplegix thanks for your comment.  I tried your suggestion but unfortunately it halts user entry completely since the first keystroke is always going to be incorrect.  

Here's the full editor function:


````
date_format = function (cell,value, data) {
				var input = $("<input type='text' />");
				if (data != undefined){

					switch (data.requires_date) {
						case 'y':
							var input = $("<input type='text' pattern='(?:19|20)[0-9]{2}' placeholder='yyyy' length=4/>");
							break;
						case 'my':
							var input = $("<input type='text' pattern='(0[1-9]|1[012])/(?:19|20)[0-9]{2}' placeholder='mm/yyyy' length=7 />");
							break;
						case 'fd':
							var input = $("<input type='text' pattern='(?:(?:0[1-9]|1[0-2])/(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])/(?:30))|(?:(?:0[13578]|1[02])-31))/(?:19|20)[0-9]{2}' placeholder='mm/dd/yyyy' length=10 />");
							break;
						default:
							return false;
							break;

					}

				}

				input.css({
					"padding":"4px",
					"width":"100%",
					"box-sizing":"border-box",
				})
				.val(value);

				if(cell.hasClass("tabulator-cell")){
					setTimeout(function(){
						input.focus();
					},100);
				}
				//submit new value on blur
				input.on("change blur", function(e){
					if(e.target.checkValidity()){
						cell.trigger("editval", input.val());
					} else {
						alert("incorrect format");
						return false;
					}
				});

				//submit new value on enter
				input.on("keydown", function(e){
					if(e.keyCode == 13 ){// Enter hit
						if(e.target.checkValidity()){
							cell.trigger("editval", input.val());
						}
					} else {
						alert("incorrect format");
						e.preventDefault();
						return false;
					}
				});

				return input;
			}; // date Formatter

My next approach is to use a library called `inputmask` that we've used before. Hopefully it will work with Tabulator

**Comment by wp4nuv** [comment]
@olifolkerd, thanks for your reply. I look forward to version 3!

**Comment by Paraplegix** [comment]
@wp4nuv I think this is what you wanted to manage ? https://jsfiddle.net/jwzvtee3/
It is based on the simple pattern that take years only, but i've replaced both input.on by something simpler :
```
input.on("change blur", function(e){
  if(/(?:19|20)[0-9]{2}/.test(input.val())){ // Place your custom validation here ("e.target.checkValidity()")
    cell.trigger("editval", input.val());
  } else {
    console.log("pas ok");
    cell.focus();
  }
});

```

In your code i think its the second input that prevent the user from doing anything, because as you said, each time he press a key, you check if he as enter a good input, wich is impossible. Then the `e.preventDefault()` prevent the key from being added into the input and the user can never escape this input :smile: 

Also, inside the switch statement, you shouldn't need the `var` keyword in front of each `input` as it is already declared just before the switch statement. 
If you are using recent browsers, you could take a look at [`<input type="date">` ](https://developer.mozilla.org/en/docs/Web/HTML/Element/Input/date) which could be a good help :wink:

**Comment by olifolkerd** [comment]
Hey,

You will be happy to hear that version 3.0 is now in beta release. There is now an improved ***editable*** option that you can pass a callback too to check weather a cell should be edited:
```js
var editCheck = function(cell){
    //cell - the cell component for the editable cell

    //get row data
    var data = cell.getRow().getData();

    return data.age > 18; // only allow the name cell to be edited if the age is over 18
}

{title:"Name", field:"name", editor:"string", editable:editCheck}}
```

Head over to http://olifolkerd.github.io/tabulator/news/ to see the latest features!

Cheers

Oli
