### ISSUE TITLE
Conditional rowSelection (checkbox) display i.e show/hide cell value based on a condition

### ISSUE THREAD

**Issue by asadsahi** [olifolkerd/tabulator#3100]
I am struggling to find an option with which I can add `rowSelection` on certain rows based on condition. e.g only display checkbox (or make row selectable) if row's certain field has a value or a certain condition to be true for that row.
![image](https://user-images.githubusercontent.com/3470892/100484503-9d0d9a80-30f4-11eb-9f20-ef1bd46c337b.png)

Possible suggestion:
Perhaps a display function as input to columns definition that is run to return true or false to show/hide cell value.

**Describe alternatives you've considered**
One possible solution I thought of was to override rowSelection implementation by copying it from tabulator source, like any formatter function, but there is a bit of complexity in that function. Is there an easy option or possibility?

**Comment by olifolkerd** [comment]
Hey @asadsahi 

This is a bit of a niche feature so i would not be looking to include this in the tabulator library, but you could easily implement it your self using a [Custom Formatter](http://tabulator.info/docs/4.9/format#format-custom)

You could base it off of the existing ***rowSelection*** formatter that can be found in the `/src/js/modules/format/js` file at line 689.

Cheers

Oli :)

**Comment by asadsahi** [comment]
@olifolkerd do you suggest overriding the rowSelection formatter or create a custom formatter you mean?

Creating a custom one will require copying rowSelection logic and change it I guess?

**Comment by olifolkerd** [comment]
Hey @asadsahi 

Either approach will work. In either case you will need to copy the existing formatter and tweak it to meet you rneeds.

Cheers

Oli :)

**Comment by EZWrighter** [comment]
FYI, I had the exact same need and assumed selectableCheck:function(row) would handle the display/disable the checkbox in a row.  However, this does absolutely nothing for the checkbox interaction.  I might suggest a documentation update or at least note that selectableCheck does not address the RowSelection formatter.

**Comment by EZWrighter** [comment]
Adding another note here as to how I made this work in version 4.9 - Used Customer RowFormatter as Oli suggested, but had to change "row instanceOf RowComponent" to check row for toggleSelect function since RowComponent is not accessible outside the modules.  Also added to that same conditional -  && this.table.options.selectableCheck.call(this.table, row)  which will check if you want this row selectable.

I also wanted the titleFormatter: "rowSelection" to work with selectableCheck, so I modified select_row.js "_selectRow" function to also do this same selectableCheck at the same time it checks if it's a row.

These few modifications made selectableCheck actually work with the checkbox selections and selecting/deselecting all, only selects selectable rows.

Hope that helps someone, probably not baked enough for production, but got the job done for my prototype.

**Comment by asadsahi** [comment]
@EZWrighter is it possible to share the working prototype or the complete custom formatter code?

**Comment by Deepakeon** [comment]
@asadsahi possible solution 
![image](https://github.com/olifolkerd/tabulator/assets/92251781/17964bbf-d337-49f9-9d06-8deaf83c72ee)

**Comment by awdorrin** [comment]
I am running into an issue where using selectableRowsCheck is not having any impact on the checkbox column
Programmatically, the checkbox is having no impact, but visually, the user can select/deselect the checkbox, even though
 'tabulator-unselectable' is applied to the row

```
<div class="tabulator-row tabulator-unselectable tabulator-row-odd" role="row">
  <div class="tabulator-cell tabulator-row-header" role="gridcell" style="text-align: center; height: 28px; width: 46px;">
    <input type="checkbox" aria-label="Select Row">
  </div>
```

Really need for the 'tabulator-unselectable' class to impact the input element and disable it.
