### ISSUE TITLE
Cells fail to display when a column field is a decimal number

### ISSUE THREAD

**Issue by j-madden** [olifolkerd/tabulator#3135]
**Describe the bug**
Unusual behaviour displaying cells when a column field is set to a decimal number. The table fails to display all data.

**Tabulator Info**
- v4.9.1

**Working Example**
https://jsfiddle.net/aLku5d24/

**To Reproduce**
1. Go to https://jsfiddle.net/aLku5d24/
2. See that all values not being displayed
3. In your console run `table.getData()`
4. See that values are in fact set correctly

**Expected behavior**
Table should display all data.

**Screenshots**
![image](https://user-images.githubusercontent.com/36580322/102601542-989b3700-4120-11eb-98f5-0e0616e66bdf.png)
![image](https://user-images.githubusercontent.com/36580322/102601627-b8caf600-4120-11eb-9645-c11738acc968.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.0.1
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (x86_64)

**Comment by olifolkerd** [comment]
Hey @j-madden 

This is not a bug, and there are at least 5 other issues already that deal with this and another 5 stack overflow questions.

Tabulator uses dot notation to allow users to specify that a column is to be built from a field that is nested in a set of objects. This is standard JavaScript practice, and it is therefore considered bad practice to use full stops in property names, and is in fact why you have to include them in quotes when you do this, because otherwise JavaScript would treat it as an object property reference.

You can use the ***nestedFieldSeparator*** option to change this character to another character so that you can use a period in your field names.

```js
var table = new Tabulator("#example-table", {
    nestedFieldSeparator:"|", //change the field separator character to a pipe
});
```
Full details on this can be found in the [Nested Table Data Documentation](http://tabulator.info/docs/4.9/columns#field-nesting)

Cheers

Oli :)
