### ISSUE TITLE
Download & Remote Pagination

### ISSUE THREAD

**Issue by Darkseal** [olifolkerd/tabulator#3154]
**Describe the bug**
As of Tabulator 4.9, there is still no built-in way to download all data when using remote pagination. The downloadRowRange option only works for the data already present within the table (i.e. current page only if remote pagination is enabled).

**Tabulator Info**
4.9

**Working Example**

```
var table = new Tabulator("#example-table", {
    pagination:"remote", 
    ajaxURL:"http://testdata.com/data", 
    paginationSize:5,
    downloadRowRange:"all" 
});
```

**To Reproduce**

1. Instantiate tabulator
2. Click on 'download CSV data'
3. Watch output

**Expected behavior**
When pagination is set to `remote` and downloadRowRange is set to `all`, the downloaded data should contain all rows and not the current page rows only.

**Screenshots**
None applicable.

**Desktop (please complete the following information):**
 - OS: Windows and Linux
 - Browser All browsers
 - Version All versions

**Smartphone (please complete the following information):**
 - Device: All devices
 - OS: All OSes
 - Browser: All browsers
 - Version: All versions

**Additional context**
See issue #935 for a suggested workaround (NOTE: HerveEmagma 's answer doesn't work for remote pagination, since the download method and the setPageSize/setPage will be executed asynchronously and independently between each other.

**Comment by olifolkerd** [comment]
This isnt a bug.

This is a physical limitation of the remote pagination methodology,

The table only stores the current page in memory, the rest is on the server, so there is no way to create a download from all the data because it simple is not there.

Remote pagination is specifically designed to only pull down the needed data, if a table has 10,000 pages for example then it could take many minutes to pull all that data down before the table was ready to be downloaded.

If you wish to download in this fashion you should either generate the doc on the server and transfer it, or pull all the data down to the client and then load it into the table for generation

Cheers

Oli :)

**Comment by Darkseal** [comment]
Hi Oli,

as a matter of fact, I found a way to implement a full-data download with remote pagination and native Tabulator methods, thanks to the fact that the setSize returns a promise that can be used to fix HerveEmagma's answer for good.

Here's how you (and anyone else) can do that:

```
function downloadData() {
        var page = table.getPage();
        var pageSize = table.getPageSize();
        table.setPageSize(table_rowCount);
        table.setPage(1).then(function () {
            table.download("csv", "data.csv");
            table.setPageSize(pageSize);
            table.setPage(page);
        });
}
```

The `table_rowCount` global variable can be retrieved using the Tabulator's native `ajaxResponse` callback in the following way:

```
        ajaxResponse: function (url, params, response) {
                table_rowCount = response.row_count;
        },
```

Alternatively, one can pass a value of `0` or `false` and implement the server-side pagination to return all data in such scenario. 

Could you open the #935 issue for replies so that I can add this workaround there as well before closing it for good?

**Comment by olifolkerd** [comment]
Hey @Darkseal Im glad you have managed to find a work around for your usage case, though for the exact reason listed above i would not be looking to include such functionality in the core library.

This issue is the correct place to post the solution, the original issue you posted on was for a very old legacy version of Tabulator. so it makes more sense for it to be posted here.

Thanks

Oli :)

**Comment by Darkseal** [comment]
Sure Oli, I understand your reasons, I'm just glad that I found a way to support this much needed feature using your awesome library's native methods :)

Keep up the good work!

**Comment by wergio** [comment]
@Darkseal the hack you propose [here](https://github.com/olifolkerd/tabulator/issues/3154#issuecomment-757484523) is not working with very big dataset (like 500.000 records). Your [previous hack](https://github.com/olifolkerd/tabulator/issues/935#issuecomment-401787365) was working perfectly with tabulator 3.* even with big dataset. But i cannot make it work with 4.9, the problem is the deprecation of downloadDataMutator and downloadDataFormatter. Do you have any fix? or you could post a working example? thanks.

**Comment by Darkseal** [comment]
@wergio are you sure that downloadDataFormatter is deprecated? It should work in 4.9:

http://tabulator.info/docs/4.9/callbacks#download

**Comment by wergio** [comment]
Maybe an error in documentation? Unfortunately with 4.9 downloadDataFormatter does not trigger anymore on download, and a DEPRECATED message appears in console. 

In 4.7 upgrade guide is specified:
"The downloadDataFormatter option has been depricated and is no longer available.
Where you used to use the downloadDataFormatter option to alter data being downloaded, you should now use the accessorDownload on the columns to be altered."
See http://tabulator.info/docs/4.7/upgrade#download

And I don't think could be done the same thing with accessorDownload

**Comment by olifolkerd** [comment]
@Darkseal that looks like a documentation fail on my part, that callback should have been removed from the docs

**Comment by Darkseal** [comment]
@wergio , given your scenario maybe you should just bypass Tabulator as a whole and just bind the "download" button to an AJAX request that fetches a (huge) JSON file and then convert it to a worksheet using SheetJS.

You can find a decent guide explaining how to do that here:
https://redstapler.co/sheetjs-tutorial-create-xlsx/

Bypassing Tabulator will probably help you because you will avoid having to render those 500.000 rows in a single page within the tabulator interactive table, which is probably too much to ask for a typical client/browser/PC.

**Comment by marhyno** [comment]
@Darkseal i am building XLSX export using tabulator within angular 17 and in the latest version of tabulator "tabulator-tables": "^5.5.2", your hack doesnt work if used **table.blockRedraw();** If I dont use it, it works but all the rows are drawn so it degrades the performance and I dont recommend to use it (I have 35 thousand rows table)
