### ISSUE TITLE
Column freeze is not working in nested tables

### ISSUE THREAD

**Issue by Danyshman** [olifolkerd/tabulator#3156]
**Describe the bug**
Column freeze is not woking in nested tables

**Tabulator Info**
- I am using Tabulator 4.9.3 version

**Working Example**
Here is the demonstration https://jsfiddle.net/L6swvnd0/1/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the link https://jsfiddle.net/L6swvnd0/1/
3. Scroll the nested table to right
4. See error, the column date should be frozen, but it is not

**Expected behavior**
Column freeze feature should work in nested tables

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
That example is working correctly. The date column in correctly frozen on the left in the nested table.

The issue that you have is that you have not set a width on the CSS table so expands to take up as much space as needed, meaning the horizontal scroll is never engaged and so the frozen column is meaningless.

The frozen column in the nested table is frozen only with respect to the table it is declared it, scrolling the parent table will have no effect on a column in a nested table, that would result is some very weird user experience otherwise

Cheers

Oli :)
