### ISSUE TITLE
dataTreeChildColumnCalcs and groupBy do not work together

### ISSUE THREAD

**Issue by wailay** [olifolkerd/tabulator#3165]
**Describe the bug**
When both options `dataTreeChildColumnCalcs : true` and `groupBy : "field"` are active the table does not render and throws an error.

**Tabulator Info**
latest 4.9

**Working Example**
https://codepen.io/wailay/pen/OJRdrBw?editors=1111

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. uncomment dataTreeChildColumnCalcs: true
2. Table will not render

**Expected behavior**
There should be a sum calculations of every children of every group

**Screenshots**
This is a screenshot of the expected behavior
![image](https://user-images.githubusercontent.com/24802037/104970722-78c68f80-59ba-11eb-8860-d3f077161475.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version : Latest version

**Additional context**
When using only either `groupBy : "name"` or `dataTreeChildColumnCalcs : true` the table render and works as expected

**Comment by olifolkerd** [comment]
Hey @wailay 

Thanks for the information, you have definitely found a bug there.

I will stick it on the list to fix for the next release.

Cheers

Oli :)

**Comment by wailay** [comment]
@olifolkerd Thank you for your awesome work !

**Comment by olifolkerd** [comment]
Hey @wailay 

I have pushed a fix for this to the master branch, and will include it in the next patch release.

Cheers

Oli :)

**Comment by verdonfly** [comment]
Hey @olifolkerd @wailay 
you need to reopen this ticket. The reported (fixed) issue is also present when editing a child cell.

**Tabulator Info**
latest 5.1.7

**Working Example**
https://jsfiddle.net/verdonfly/3g4udm5k/3/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

- right click on the first column to add a child to the row
- change the total column of the new child.

![image](https://user-images.githubusercontent.com/49061831/158610072-d53170a2-2db7-404e-ad06-fc9d08a27c9a.png)

**Expected behavior**
the first total should be 103.


**Additional context**
if you comment the groupby the total works correctly.

![image](https://user-images.githubusercontent.com/49061831/158610794-1843341c-f2fe-4765-a94e-b83048e3579d.png)

**Comment by olifolkerd** [comment]
@verdonfly This is unrelated to the original issue, please raise a new issue detailing your problem, the original issue was correctly resolved.
