### ISSUE TITLE
No data showed in table when using browser print function

### ISSUE THREAD

**Issue by fbenedetti06** [olifolkerd/tabulator#3166]
Hi Oli

Congratulation for this amazing library! I can't stop using it!

I experiment an issue and I really tried all possible to resolve it before to bother you...

Browser screenshot (3 tables side by side):
![image](https://user-images.githubusercontent.com/49648330/105020487-a574b880-5a47-11eb-8971-5c7b6afa23ac.png)

Printer (different positioning du to page size):
![image](https://user-images.githubusercontent.com/49648330/105020611-ce954900-5a47-11eb-96a4-676961687b9f.png)

As you can see center table do not show data!

Tables have exactly same setup.

Data are present because they are showed if I use printAsHtml:true

Thanks for your support.

This issue could be related to #951

**Comment by olifolkerd** [comment]
Hey @fbenedetti06 

If you wish to raise a bug please use the [Bug Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) as it will prompt you for all the information we need to help.

without a JS fiddle to show how your table is setup it is almost impossible to offer you advice. I would wager that the issue is to do with your heavily customised styling. FOr a start you should check that your `printStyled` property has been set to `true`

```js
var table = new Tabulator("#example-table", {
    printAsHtml:true, //enable html table printing
    printStyled:true, //copy Tabulator styling to HTML table
});
```

You should also make sure that the custom stylesheet you have applied to the Tabulator element is also applied to the print table classes as these are different from the standard table.

Information on these can be found in the [Print Styling Documentation](http://tabulator.info/docs/4.9/style#css-print)

It is almost certainly unrelated to issue #951 as that issue was created two years before the table print functionality was added to Tabulator

Cheers

Oli :)

**Comment by fbenedetti06** [comment]
Thanks for taking time to respond to me.

I understand well
My code is quite complicated because I use many possibilities offered by tabulator. 

I have to simplify and isolate the concerned portion then I will use bug report template!

Best regards
