### ISSUE TITLE
Scroll bouncing problem on mobile when using fixed column

### ISSUE THREAD

**Issue by idringvard** [olifolkerd/tabulator#3170]
Hello. Thanks for awesome work on this library. It is really amazing.

Sorry, if that bug already was reported before. It could be similar or related to #1451

**Describe the bug**
When use fixed column in table and start scrolling table body left/right/up/down, then table body begins bouncing and not
synced with table header. See screenshot below, it fully describes problem. This issue only appear on mobile devices
or in desktop Chrome when Developer tools in mobile emulation mode

**Tabulator Info**
4.9.1

**To Reproduce**
1. Create table with one fixed left column and normal columns
2. Open table on mobile phone or in desktop Chrome with Developer tools in mobile emulation mode
3. Start touch scrolling table body

**Expected behavior**
When scrolling table is in synch with header and no table body bounces.

**Screenshots**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/31104386/105168011-2acc9b80-5b22-11eb-9d66-8de0ad939008.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Developer tools Mobile emulation mode
 - Version: 87.0.4280.141

**Smartphone (please complete the following information):**
 - Device: iPhone XI
 - OS: iOS 14.3
 - Browser: Safari

What can be done to fix this kind of problem? Is this issue can be fixed in 5 version of Tabulator?

**Comment by olifolkerd** [comment]
Hey @idringvard 

Thanks for your kind words about Tabulator, it is great to hear people enjoy using it.

Ive flagged this as a duplicate because it has been brought up before and it is a limitation the way mobile browsers interact with Tabulators structure.

As part of the 5.0 rebuilt that is currently happening the strucutre of the table will be changing which should hopefully mitigate this issue.

Cheers

Oli :)
