### ISSUE TITLE
Retrieval of data via a "DataManager"

### ISSUE THREAD

**Issue by nl095059** [olifolkerd/tabulator#3172]
Hi Oli,

  As you know, I had been looking into asynchronous querying and feeding that data and "in-progress" counts of results into tabulator using it's API.

What has occurred to me is that there several places in the codebase where loading/imports of data is performed. i.e. Loading from file, loading from AJAX, loading from HTML, etc.

It did occur to me that if this loading was abstracted behind a data manager, then you would be able to plug and play a variety of different loading mechanisms without core tabulator needing to have any knowledge of this. All these loaders could then be nicely tested in isolation. I know that the AJAX module and htmlTableimport modules go someway towards this, but I figured a formalised interface would make writing "loaders" easier?

Obviously this would need a fair bit of planning as a simple getColumns/getCount/getResults(start, end) on the DataManager won't cut the mustard, but I was wondering what your thoughts are on the concept?

Cheers,
  Nathan

**Comment by olifolkerd** [comment]
Hi @nl095059 

Im afraid i dont really understand the need for what you are proposing, that being said i would like to continue the discussion and hear more from you.

Tabulator has a very clear data format for loading data into the table. which is the only point at which data needs to be loaded in, so a simple conversion function written by the developer at the point the load the data into the table should be sufficient. so i dont really understand what you are gaining front sticking another layer in front of this. in most cases developers need only call a simple map function on an array to convert their data into something that Tabulator can process.

The existing Ajax system is very detailed and handles all request/response mechanics (most other data sources wouldn't be able to handle sorting/filtering/pagination etc server side) and it has a promise that can already be replaced (see [ajax promise override docs](http://tabulator.info/docs/4.9/data#ajax-promise)) with anything you like so you can load data in from any asynchronous source using that and it would fit into the data straight away. This is what most developers use when making async queries to JS based databases etc...

There are already modules in place that handle loading in data from an HTML form which encapsulates that data totally and it has specific functionality because of the need to replace the element when the table has been.

So i dont really see how this would bring greater functionality to Tabulator when each method of data ingest has some very specific usage cases around it.

Could you explain your usage case in more detail to start with, we can then talk about broader abstractions once i understand the reasons for this.

Cheers

Oli

**Comment by olifolkerd** [comment]
If you are talking about importing files through the `setDataFromLocalFile` function then i was looking as part of the 5.0 upgrade to add importers for this so that you could load in from multiple different file types. with build in ones matching the equivalent downloaders in the download module.

**Comment by olifolkerd** [comment]
I am specifically avoiding creating constructs, types of classes or objects that people can pass into the table at setup to manage different things. 

I much prefer the approach of allowing people to bind specific use case functions where needed which is provided by the current module extension operations that allow people to register their own handlers.

When I first set out to build Tabulator one of my first mandates was to ensure users didn't have to insatiate lots of components and objects just to get a table working. You look at slick grid for example, to do anything complex you end up having to import and initialize numerous objects and while that approach has some benefit on the whole it makes the table cumbersome to use for most simple use cases.

At current the way users add custom functionality to the table is to extend a module to add built in custom functionality or to set a callback for one of use cases. I would want any additional systems to fit into this usage patter so that developers have an intuative understanding of how to customise the table and dont need to take a different route for every sort of customisation

**Comment by nl095059** [comment]
Hi Oli,

  Thanks for the really prompt reply. I have taken a little longer to try and explain in detail the reasons for the proposed change, I hope it gives a better context?


> Could you explain your usage case in more detail to start with, we can then talk about broader abstractions once i understand the reasons for this.

When I started looking at extending tabulator to handle asynchronous fetching of results I needed to find 3 things.

1. Was there a logical place to initialise my query
2. Where does tabulator ask for results and how to extend this to make the call onto my datasource with sort/filter/page params.
3. How to call the pagination module to update the pagination control


What became quite clear is that the concerns appear to be a little blurred between the modules I started looking at to answer these questions. 

I realised that the core module has lots of business logic to determine where it gets its results from and how to set up the page module to be ready for these results. It dawned on me that core should really ask for results and have no knowledge of how it is fetching data as the modules should have responsibility for this.

I then started looking at the AJAX module and realised that it was updating the pagination module to tell it to optionally handle progressive loading. The AJAX module also makes calls to the rowManager and pagination which feels like they should be outside the concerns of this module.

Looking at the page module I realised that the trigger function also has logic to determine whether the data is local/remote/progressive or not, as well as calls to AJAX to blockRequests and rowManager to set data. 

Conversely, filter and sort modules look spot on, they purely get the information they need and supply this information to the modules that need it without knowing anything about where this data is coming from, or how to perform these operations on it.


I felt that omitting ajax urls and pushing data directly into the table was a little clunky as retreiving and setting information on the page module was still calling functions on the AJAX module. I appreciate that you can provide your own promises to override some of this functionality, but it still felt like that is sidestepping the issue in this instance.

I also started writing some tests to make sure that I wasn't breaking any existing functionality, but realised that the mixing of these concerns does make testing of AJAX/progressive loading and pagination more difficult as more code needs to be stubbed than is really necessary. 



So, I started thinking about how I would personally go about separating back out these concerns while still allowing for testing and to not break existing functionality or changing the table options API. The following is what I concluded:

- The AJAX module to me feels like it should fetch the data it is told to and not need to worry about how to update the table with it. 

- All modules that fetch data also need to be provided with information about page/sort/filter, but shouldn't need to go fishing for it by referencing the modules themselves. If a data loader module is asked for data it should be provided with all relevant params from the (page/sort/filter modules)

- The page module should tell the core that it has done something noteworthy that requires the core to get a new page of data or update the table, so essentially using trigger but just making the core act on it, not page. This could then ask for more data if needed, triggering the retrieval via the relevant data mechanism (Ajax, websocket, etc)

- The _create in tabulator that loads data from html feels like it is in the wrong place. The same goes for setDataFromLocalFile (To a much lesser extent), as it feels like it's just adding another loading mechanism onto core. I feel like both functions should go somewhere more "common" and relating to loading data.


I started thinking more about abstracting this data retrieval into a manager just like the rowManager and columnManager. This would move all data/loading business logic off to the side of tabulator core, which would keep core nice and clean as a library for the display/manipulation of data. The dataManager would be called by core to retrieve/update(Kicking this conversation down the road!) data, but it would have a formal interface so could then be tested in isolation.

Getting back to my use case, I could then add my own module for async querying that would have an initialise (Called at the same time as all other modules and can initialise my query). I could provide a getData/getResults method that would take the (sort/filter/page) data and fetch this data from my datasource. I could also provide a onCountUpdated callback that could be used to update the count of results from my datasource and update this in the table.

At this point it occurred to me that if this pattern was employed by all data loaders, then core becomes much cleaner.

The html loader module does all the html processing already it just needs to sit behind a getData call? 
Similarly setDataFromLocalFile feels like the start of a FileLoader module, that also exposes a getData method?
A CSV loader module would be similar but would need to expose the columns as well as the data.



The dataManager would be responsible for parsing the table options to determine where it is getting the data from, at that point it should instantiate the relevant module (html/ajax/file/csv/json, etc)
Each of those modules would have an:

initialise (To do any required setup)
getData (Called with all view related params - page/sort/filter)
getCount (Gets the number of results)
onCountUpdated (Optional callback for updating table counts - async)
getColumns (Optionally defined, useful for csv/html loading)
...


When the table is initialised it calls dataManager.initialise, which parses the options, instantiates the relevant loader and calls initialise on the loader module.
When the table needs to obtain it's columns it can either use the table options or if a getColumns method exists on the loader it uses that instead.
When the table is ready for data it calls dataManager.getData which calls through to the loader module with all the view params.
When the table needs more data (triggered via a page.trigger, etc) it calls onto the loader module getData again.


Hopefully this gives you a better context of where I am coming from, and these ideas/observations are in no way meant to be a criticism of Tabulator at all. I wouldn't have recommended tabulator to my team if I didn't think it was the best library out there for our requirements. I can try and put some UML diagrams together if it would help, or put a PR up with a rough hack and slash code rejiggle just to give a clearer picture of what I am proposing. 






### As for your questions/concerns in the comments above, I have tried to answer all of them below:


> Tabulator has a very clear data format for loading data into the table. which is the only point at which data needs to be loaded in, so a simple conversion function written by the developer at the point the load the data into the table should be sufficient. so i dont really understand what you are gaining front sticking another layer in front of this. in most cases developers need only call a simple map function on an array to convert their data into something that Tabulator can process.

I'm not proposing that any of this changes from a users viewpoint, only changing where the code lives that handles the determination of what type of data it is. This logic already exists in _loadInitialData, _setData, _create and setDataFromLocalFile. I am just proposing moving these into more specialised classes/functions to make it clearer as to their function.


> The existing Ajax system is very detailed and handles all request/response mechanics (most other data sources wouldn't be able to handle sorting/filtering/pagination etc server side) and it has a promise that can already be replaced (see ajax promise override docs) with anything you like so you can load data in from any asynchronous source using that and it would fit into the data straight away. This is what most developers use when making async queries to JS based databases etc...

Agreed, I am not proposing this changes from a user perspective either, maybe a few of the internal method names and purely the code that calls onto it.


> There are already modules in place that handle loading in data from an HTML form which encapsulates that data totally and it has specific functionality because of the need to replace the element when the table has been.

This can happily stay where it is in the existing module, at most I am proposing a few method name changes to align with an interface that datamanager uses to call onto it.


> If you are talking about importing files through the setDataFromLocalFile function then i was looking as part of the 5.0 upgrade to add importers for this so that you could load in from multiple different file types. with built- in ones matching the equivalent downloaders in the download module.

Exactly! I am proposing this kind of change, but just stepping back a bit and looking at all Data sources (Local and Remote)


> I am specifically avoiding creating constructs, types of classes or objects that developers need to pass into the table at setup to manage different things.

While specifying the data "source" with a pattern such as

dataSource: {
  type: 'ajax',
  url: 'http://example.com'
}

in the table options would be preferable with this approach (To avoid relying on the existance of multiple keys to determine type). I completely agree that the existing options should not be moved/removed as this gives an easier route to entry for most users.


> I much prefer the approach of allowing people to bind specific use case functions where needed which is provided by the current module extension operations that allow people to register their own handlers.

I personally think this would open it up more, it pushes all the loading business logic into modules and out from core. And most of those loaders could/will be tree shaken out of the picture post v5.0


> When I first set out to build Tabulator one of my first mandates was to ensure users didn't have to instantiate lots of components and objects just to get a table working. You look at slick grid for example, to do anything complex you end up having to import and initialize numerous classes and while that approach has some benefit on the whole it makes the table cumbersome to use for most simple use cases.

I completely agree, this dataManager would sit alongside the rowManager and columnManager and wouldn't be seen by most of the tabulator users.


> At current, the way users add custom functionality to the table is to extend a module to add built in custom functionality or to set a callback for one of use cases. I would want any additional systems to fit into this usage patter so that developers have an intuative understanding of how to customise the table and dont need to take a different route for every sort of customisation

This change does fit in with this pattern I feel, it just tidies up some existing functionality to make it cleaner.



As far as adding something extra that developers need to instantiate, I see this as something that lives in core, just like the rowManager/columnManager and would only need understanding if you wanted to do something a little more bespoke.

It's more about tidying, seperating concerns and adding the ability to request data from all datasources in pages and testing.
I am 100% with you on keeping the options for table instantiation the same/minimal as to not scare off people with simpler use cases.


Cheers,
  Nathan

**Comment by olifolkerd** [comment]
Hi Nathan,

Thankyou for your detailed reply.

I think that if you will see that some of your proposed functionality is already coming in the 5.0 release,  but could I as that you hold of for a couple of months until I am finished with the rebuild and we can talk from there.

I certainly appreciate your enthusiasm, and you certainly have many valid points, but as with your last PR, your desire to contribute to Tabulator has come at exactly the wrong time, as the underlying foundation of the library is undergoing significant changes `(which will address a lot of the concerns layout out in your post)` at the moment making it very hard to have these discussions in a meaningful way. 

Quite a lot of your proposals are based off of the 4.0 architecture and I feel we will be talking at cross purposes. if we can pick this discussion up once the core architecture of 5.0 is in place I feel we can have a more meaningful discussion.

In response to some of your queries.  As I mentioned above the ability to manage importing data from different sources is already on the roadmap for the 5.0 release, and a new module will be created to contain this functionality. it will allow people using any of the `setData` type functions to specify how that data should be interpreted and this could easily be applied to the AJAX responses too.

I can certainly see the benefit in having a data module that abstracts away some of the loading functionality from the core, but this could just was well be situated in the planned import module

The ajax and page modules are specifically linked to allow progressive loading into the system, it uses the pagination system behind the scenes to load data in one page at a time, hence there is a necessary feedback loop between the two, though I take your point about where some of this logic resides inside the ajax module, it could be moved into the module that makes the request for the data.

The filter modules and sort modules work very differently from the ajax and pagination modules because they sit lower down in the row management pipeline, and are not specifically involved in the making of requests in that fashion, the nature of the pagination module managing the async loading in progressive mode makes this link necessary, calling to a data manager module would still require an external dependency just a different module.

A lot of Tabulator modules make calls to other modules specifically because they can all need to trigger refresh actions at certain points, and the rowManager is in fact called from several modules, as there are general functions that are called on it whenever the row management pipeline is updated (there is a need to differentiate between data being set an updates being triggered), though i do take your point onboard about the resulting action of the ajax call needing to be abled outside of the module.

Actions like row counts happen in the row Manager and that is exactly where it should stay. no module looks at the count of unprocessed data, it is the responsibility of the row manager to take raw data and transform it into the row components and various display management row arrays that are then used by the rest of the system.

I am happy with where the processing of data currently sits / will site with the planned updates, all exporting of data happens in the export/download modules, all importing of data will happen in the new import module and they will have matching defaults set to handle both actions. in this scenario I feel the data manager is just a different approach to the same thing, and so at present I would not be looking to change the way it works. I totally understand your point of view, and your suggestion to group things by type rather than actions is perfectly valid, but in this case i want to stick with the current paradigm. 

I am strongly against adding any configuration classes that would need to be passed into Tabulator at initialisation time, and I have no intention of changing that in the 5.0 release, at present all updates to existing table defaults are carried out by the registration of simple call backs against existing modules, a pattern which your current proposal does indeed break.

Version 5.0 will come with an optional core version that allows you to attach the modules to it offering considerable tree shaking savings as it is, at this stage I am not looking to add any further tree shaking functionality to the library beyond this as I feel the benefits of the tiny optimisation to code size it offers are offset by the increase in complexity in table configuration

For now let us hold this discussion of the full data manager till the 5.0 release is out. I will certainly take on board your feedback as part of the refactor and will look to clean up some of the extraneous functionality in the ajax module. Once that release is out and you have a chance to fully explore the new system architecture i would be very happy to pick this up again.

Cheers

Oli :)

**Comment by nl095059** [comment]
Hi Oli,

  I was going to give a more detailed response to your comments, but as you say until I have visibility of the 5.0 code base we will probably be talking cross purpose which just confuses things.


However, I would like to just clarify a few little points:

- I am not proposing changing the existing table options at all, I think that this work can be done without changing any options which have already been well documented and utilised by your user base.
- I was not proposing removing the 'simple callbacks against existing modules' as the import/data modules can still utilise these.
- The name import to me does suggest a one time operation, surely if you step back a bit you have a "data" module that can interrogate the data to a finer level and fetch data in chunks, i.e. progressive, paged, etc?
- I completely understand that there needs to be communication between the ajax and page modules, I just feel that it shouldn't be direct. I am also a little hung up on the fact that AJAX as a technology should probably be distinct from progressive loading which is a function in it's own right (I need to get out more :-) )

Is there already a rough design for this import module, as from what I understand it is not a million miles from what I have been describing here? I would very much like to help in any way I can with this excellent library, just let me know when you are ready to open up the 5.0 code base for review/testing.

Cheers,
  Nathan

**Comment by olifolkerd** [comment]
Hi Nathan,

I understand that you feel the progressive load functionality should be unrelated to the ajax functionality, but that may be more down to naming convention than anything. the ajax modules function has extended well beyond its its initial ajax functionality and is in fact largely a data loading module, it just comes with built in ajax functionality that can be overridden by users. And yes there is already a design for the import module but it will be made available with the rest of the library when the 50 release is made available to the community in march

I maintain a trello board that outlines the plans for each release, but i do not publicly release any of the internal designs, It takes enough time maintaining the library and the website without making public plans available and handling the resulting discussion. The work up to version 5.0 has been years in the planning *(there has been a roadmap to this point since version 2.0 and I already have plans for 6.0, with each update incrementally updating the exposed API and functionality so as not to overwhelm users with massive migration tasks)* and sadly I find that with so many different developers having very different and opinionated approaches it invariably turns into a squabble of developers fighting to have things "their way" and it distracts from actually getting the job done, there are always pluses and minus's to each approach and I try and balance these to consider all users.

I am always happy to have people contribute towards Tabulator, but please understand that is is a passion project of mine, it is my way to be challenged by the developer community, to overcome a range of challenges thrown at me and to give something back to the community as a whole, and while I am happy for people to add a function here or there, or even modules with prior planning, I am not looking for developers to collaborate on large scale refactors or the core design behind it, that is the area that interests me most. 

If you would like to make a significant contribution to Tabulator then one area that i am definitely looking for help is unit testing. as part of the 5.0 release i have restructured every module to use ESM exports to allow for easier unit testing. With all the work i will be doing updating the core i have little time to build out unit tests.  I am currently looking at using the karma test runner to achieve this and would welcome any help that could be lent in this direction.

The [Community Page](http://tabulator.info/community#contribute) on the website also lists other areas where i would appreciate additional help

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @nl095059 

Tabulator 5.0-alpha has been released today for community feedback. and you will be happy to hear that with the inclusion of the new internal event system the data loading process has been decoupled from the modules.

There is now a DataLoader that is responsible for coordinating data ingest into the table and modules can subscribe to its event to provide it with data or provide params for data requests.

Head on  over to the [Release Notes](http://tabulator.info/docs/5.0/release) for more info

Cheers

Oli :)
