### ISSUE TITLE
Tabulator textarea losing focus on every key press

### ISSUE THREAD

**Issue by Danyshman** [olifolkerd/tabulator#3176]
**Describe the bug**
Tabulator textarea losing focus on every key press

**Tabulator Info**
- 4.9.3

**Working Example**
https://jsfiddle.net/3L56u79a/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Try to edit column TA Test
2. Every time you will try to edit the cell, it will lose focus from cell

**Expected behavior**
Do not lose focus when editing textarea and when pressing enter it shouldn't lose focus too.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olifolkerd** [comment]
This is because your table is misconfigured.

if you want the table to resize to the data, do not set a height on the table and disable the virtual DOM in the setup options:
```js
var table = new Tabulator("#example-table", {
    virtualDom:false, //disable virtual DOM rendering
});
```
This is happeneing because you have the table set to 100% height, but by default the body/html elements of a page match the size of the elements they contain not the page.

Cheers

Oli :)

**Comment by Danyshman** [comment]
Thank you!
