### ISSUE TITLE
Cell size computed wrong when the Table is initialized while hidden

### ISSUE THREAD

**Issue by vmsh0** [olifolkerd/tabulator#3193]
**Describe the bug**
If the table is hidden (e.g. descendant of an element with `style="display:none"`) while it is initialized, the cells are computed wrong: when the table is finally displayed, each cell simply takes the width of its content, and, in the header, all the columns that come before the first hidden column have `height: 0px` in their style (and are thus completely hidden).

As a dirty workaround, after showing the table, I'm toggling all the columns twice, which forces everything to re-compute.

**Tabulator Info**
4.9.3

**Working Example**
https://jsfiddle.net/k9564jb0/3/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click on "show table"
2. See that the cells are not rendered with the correct size
3. Click on "fix table"
4. See that everything gets fixed

**Expected behavior**
I'm not sure on how the issue should be addressed. Computing the cell sizes correctly while the table is hidden doesn't sound like a promising strategy. Maybe there should be a method to re-compute the whole table without going through toggling each column? (or maybe there already is, and I just can't find it)

**Comment by olifolkerd** [comment]
This is not a bug, this is a limitation of using a virtual DOM and browser inconsistencies and is covered extensively in the documentation.

Because tabulator uses a virtual DOM it has to calculate cell dimensions in order to layout the table properly. Elements that have not been added to the DOM yet do not have a height *(this is a standard browser limitation)* so it is not possible for Tabulator to calculate how to layout the DOM.

Some browsers implement the `ResizeObserver` functionality which allows Tabulator to know when it has been made visible and so it recalculates it sizes and redraws itself.

But if you are looking for full cross browser compatibility you will need to call the redraw function on the table when it is made visible, this will resolve any layout issues:

```js
table.redraw(true)
```

Cheers

Oli :)
