### ISSUE TITLE
When switching a table out of view then back the column widths are not restored

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3198]
@olifolkerd Sorry for another one. I think this might be easier, as it might just be a regression? I've definitely seen this before.

**Describe the bug**
When having a table hidden then shown, the cell column widths don't get reset, and the table looks 'collapsed'

**Tabulator Info**
Latest 4.9.3

**Working Example**
https://jsfiddle.net/rathboma/jtnmcuLr/39/

![Peek 2021-02-05 20-26](https://user-images.githubusercontent.com/279769/107106301-7f456b80-67f0-11eb-96a0-5607635eb616.gif)

Original report from Beekeeper Studio: https://github.com/beekeeper-studio/beekeeper-studio/issues/524
gif from but report:
![gif](https://user-images.githubusercontent.com/884882/107065816-e0b40d00-67e5-11eb-846e-3978bacbb301.gif)

**To Reproduce**
1. Open jsfiddle
2. click 'switch table'
3. observe

**Expected behavior**
Table contents shouldn't be garbled

Browser:
- Firefox (confirmed), chrome (confirmed)

**Comment by rathboma** [comment]
Ok, so it might be because I'm not forcing a redraw, I'm calling redraw(), but calling redraw(true) seems to fix it?

**Comment by rathboma** [comment]
Is that right? Why would it have this behavior? Also this behavior is new

**Comment by rathboma** [comment]
It seems to only happen when I open the same table twice, if I open different tables, it doesn't seem to happen, even without the redraw. Investigating. Not sure anything is shared between the two

**Comment by rathboma** [comment]
Ok, I've figured it out in Beekeeper at least. I don't know why it happens in the fiddle.

In Beekeeper it happens when `setColumns` and `refreshTable` are called while the table is in the background. Figuring out a workaround.

**Comment by olifolkerd** [comment]
That is expected behaviour if you are going that while the table is hidden. Because elements that are hidden don't have any size on the DOM Tabulator cannot lay them out correctly, so you have to redraw the table when you make it visible (it won't happen in some browsers, if the support they Resize observer feature, because Tabulator can use that to detect its visibility change and redraws itself automatically)

It didnt happen when u used the hoz v Dom because the column widths were recalculated as you scrolled

Cheers

Oli
