### ISSUE TITLE
Virtual DOM rendered callback

### ISSUE THREAD

**Issue by vmsh0** [olifolkerd/tabulator#3205]
*Is your feature request related to a problem? Please describe.**
Columns are not fitted to data in non-rendered rows, when the table is rendered in _virtual_ mode. This is of course the sensible thing to do, but I need to work around that. More context: https://stackoverflow.com/questions/66151521/fit-column-to-data-for-unrendered-virtual-dom-rows-in-tabulator 

**Describe the solution you'd like**
Have a callback for when a virtual DOM rendering action (i.e. added/removed/changed rows) happens

**Describe alternatives you've considered**
Couldn't think of any viable alternative. Suggestions welcome! :)

**Additional context**
JsFiddle example (also posted in the SO question): https://jsfiddle.net/tsqL3ju7/

**Comment by olifolkerd** [comment]
There are already callbacks for all of these actions in the [Callbacks Documentation](http://tabulator.info/docs/4.9/callbacks)

The not changing width is intentional as it would result in a jarring user experience.

Cheers

Oli :)

**Comment by vmsh0** [comment]
> There are already callbacks for all of these actions in the [Callbacks Documentation](http://tabulator.info/docs/4.9/callbacks)
> 
> The not changing width is intentional as it would result in a jarring user experience.
> 
> Cheers
> 
> Oli :)

Could you point them out to me? The only interesting one I found is `renderComplete`, which however isn't triggered when rows are added to the virtual DOM.

**Comment by olifolkerd** [comment]
dataChanged

**Comment by vmsh0** [comment]
Surely I'm missing something, but from what I see the `dataChanged` callback is not called when the virtual DOM renders a new row. It is only called when a new row is actually added to the data (or deleted/updated).

I probably did a poor job explaining my request. I apologize. My issue is that I would like to update the column width when a new row gets rendered by the virtual DOM (i.e. when the table is scrolled vertically and `RowManager.scrollVertical()` is called) - not when the data in the table is updated.

**Comment by vec2k4** [comment]
As described in your StackOverflow post, the only way I think it is possible is to hook the scrollVertical and to set the column width here.  No need to patch tabulator since there is a callback you can use. I've modified your example to show a simple and unoptimzied solution: https://jsfiddle.net/vec2k4/wdu65avk/

![scroll](https://user-images.githubusercontent.com/9272347/107657419-738cf580-6c85-11eb-8363-71278b67b08e.gif)

Please be aware that this solution can have a massive performance impact since it is re-setting the column widths for every scroll event.

**Comment by olifolkerd** [comment]
It would be extremely unsafe to add that call-back in for when the virtualDOM is in the process of redrawing itself. it relies on uninterrupted access to carry out the necessary calculations.

Allowing access at that point would only encourage developers to carry out actions that would very likely slow the render process down to a crawl at best or at worst completely corrupt the table layout.

You certainly shouldn't be binding to the scroll event of the table, specifically because of the performance issue that will cause.

The solution you are looking to achieve is fundamentally incompatible with the current design of the render system, and is really not something I would be looking to include in Tabulator. I would consider it extremely bad UI design to have a column resize while the user is scrolling, it looks very jarring and would not be expected by the user, which is why Tabulator behaves as it currently does

This is not a feature i would looking to add to Tabulator,

Cheers

Oli :)

**Comment by vmsh0** [comment]
@vec2k4 thank you for providing that snippet. From the documentation, I thought that particular callback was out of the game due to performance reasons, but upon further inspection I found that it is actually called in the same code path as the virtual DOM rendering.

@olifolkerd thank you for addressing this in so much detail. I agree that it would make for very poor user experience, however in our case it is not really acceptable (and thus even worse UX) to have ellipsis in our cells. For this reason, I'm going to provide at least a mock with the resize-while-scrolling functionality to the client, and let them decide.

As pointed out above, the `scrollVertical` is called in the same code path as `RowManager.scrollVertical()`, which handles adding and removing rows from the virtual DOM. Since the event is already being triggered after `RowManager.scrollVertical()`, and then the Tabulator code terminates, I really don't see any architectural or re-entrancy issues with adding a second callback in the same code path that are not already there for `scrollVertical` (in fact, this new event would simply be a filtered version of `scrollVertical`.)

I still understand why you wouldn't want to add it to Tabulator tho. I do agree that it would probably encourage writing bad code. So, of course, if your position is still that you are not interested in adding it, I will have to do with either filtering the `scrollVertical` events myself, or patching the code.

Thank your for your help! It is much appreciated.
