### ISSUE TITLE
Tabulator displays the "expand" icon for rows that have no actual children

### ISSUE THREAD

**Issue by sthkn** [olifolkerd/tabulator#3211]
*Is your feature request related to a problem? Please describe.**
I use C#.NET as the backend for my application, and have Tabulator setup to use ajax data filter. The data model returned by the server always includes a `_children` field - even if it is an empty array. Tabulator then displays all rows as if they have children - which appears to be working as intended based on the documentation. This will be confusing for end users. 

**Describe the solution you'd like**
In the `DataTree.prototype.initializeRow` function, it would be nice if there was a check to make sure that the children array actually has any elements. I modified the local copy of tabulator.js to be:
`var children = (isArray && childArray.length > 0) || !isArray && (typeof childArray === 'undefined' ? 'undefined' : _typeof(childArray)) === "object" && childArray !== null;`
and it works as expected.

**Describe alternatives you've considered**
I've considered trying to make the backend not provide the `_children` field if there are no children, but could not find an acceptable solution. 

Thanks!

**Comment by olifolkerd** [comment]
Hey @sthkn 

This was a deliberate choice, because some people use this as a way to asynchronously load child data to the table when the row is expanded.

In your case you should set the `_children` field to `false` or `undefined`. you could either do this on the server side. or if you prefer to do it in the browser then you can use the `ajaxResponse` callback or a mutator to change the data as it is  loaded into the table.

Cheers

Oli :)
