### ISSUE TITLE
Add cellClick events to the Collapsed data Model

### ISSUE THREAD

**Issue by sololegends** [olifolkerd/tabulator#3240]
*Is your feature request related to a problem? Please describe.**
It is inconsistent behaviour when you have a `cellClick` event registered but it isn't not fired on click when clicking on collapsed data

**Describe the solution you'd like**
I would like to have the registered `cellClick` events which run on rendered cells, to also be fired when you click on a "cell" within the collapsed data list.

**Describe alternatives you've considered**
The alternative I've considered, is writing a handler for each instance of the table to trigger the desired function manually by overwriting the `formatCollapsedData` function locally.

**Additional context**
N/A

**Comment by olifolkerd** [comment]
Hey @sololegends 

As of version 5.0 the cellClick events work correctly on all rows in nested data tree including on child rows.

If you are talking about not triggering the cell click when the expand element itself is clicked, then this is consistent with the behaviour of other in cell control elements, the deliberatly do not trigger the cellClick event because the purpose of the click was an interaction with the control not the cell.

If you need to track that as well, there are already [Data Tree Events](http://localhost:8080/docs/5.1/events#tree) that handle this.

Cheers

Oli :)

**Comment by giacomok** [comment]
I write here cause I have the same behaviour but I do not know howto handle it.  
I have a column defined in this way:

    await table.updateColumnDefinition("info", {formatter:"html", minWidth: 100, cellClick:function(e, cell) {
            //e - the click event object
            //cell - cell component
            clickInfo(cell.getRow().getData().id);
        },
    });

with `responsiveLayout` attribute set to `collapse`.

When the cell is collapsed (and shown below the row), the `cellClick` event is not fired. How can I handle this?
