### ISSUE TITLE
CORS fetch request ignoring set headers

### ISSUE THREAD

**Issue by alexanderluiscampino** [olifolkerd/tabulator#3245]
Using the ajaxProgressive loading with an endpoint set up using AWS gateway, the request keeps getting blocked due to CORS.

Somehow, tabulator adds headers to my request, which are unnecessary. Strictly setting the headers to empty does nothing

```js
var ajaxConfig = {
    mode: "cors", //set request mode to cors
    credentials: "same-origin", //send cookies with the request from the matching origin
    headers: {
        // Accept: "application/json", //tell the server we need JSON back
        // "X-Requested-With": "XMLHttpRequest", //fix to help some frameworks respond correctly to request
        // "Content-type": "application/json; charset=utf-8", //set the character encoding of the request
        // "Access-Control-Allow-Origin": "*", //the URL origin of the site making the request
    },
};

var table = new Tabulator("#example-table", {
    ajaxURL: url, //ajax URL
    ajaxProgressiveLoad: "load", //sequentially load all data into the table
    ajaxConfig: ajaxConfig,
});
```
Tabulator checks for empty headers and adds in its best guess, I don't need that. I can use fetch with the above ajaxConfig, and I get my data back
```js
fetch(url, ajaxConfig)
    .then((response) => response.json())
    .then((data) => console.log(data));

```
why is it that with tabulator, it doesn't work?

**Comment by olifolkerd** [comment]
Hey @alexanderluiscampino 

I use Tabulator extensively for CORS and with AWS and have not run into any issues, the default configuration of Tabulator without any config should handle CORS requests just fine.

Cheers

Oli :)

**Comment by srikanthmeenakshi** [comment]
I have a similar issue - I am trying to load a json file from a cdn, and it's getting blocked by cors despite trying  many ajaxconfig combinations. The issue is "blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.". I need to *unset* that particular header field from the default header sent by Tabulator. As OP mentioned, setting it to empty or removing it from the header set does not stop tabulator from setting it. The value set does not seem to matter - the problem is that it is getting set at all.

Any way to work around this?

**Comment by srikanthmeenakshi** [comment]
Just FYI - I had this issue with Bunny.net CDN and I worked with them to set up an edge rule to avoid this situation.

thanks,

Srikanth
