### ISSUE TITLE
Contenteditable elements inside table cells cannot be edited when doing text selection after double click/tap

### ISSUE THREAD

**Issue by handhikadj** [olifolkerd/tabulator#3270]
**PLEASE DON'T CLOSE THIS ISSUE SOONER THAN I EXPECTED AS MY EARLIER POST WAS CLOSED WITHOUT CLEAR SOLUTION. SEE https://github.com/olifolkerd/tabulator/issues/3267 FOR EXAMPLE**

**Describe the bug**
I notice I can't type when some texts are selected after double click/tap

**Tabulator Info**
- Which version of Tabulator are you using? v4.9.3

**Working Example**

https://codesandbox.io/s/tabulator-tables-sandbox-forked-7z8fl

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the provided link
2. Double click/tap on one of text in age column to do text selection. don't ctrl + shift when doing text selection
3. Type something. you should notice you cannot type anything

**Expected behavior**
Can type during text selection

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Browser: Mozilla Firefox v87.0 & Google Chrome v89.0.4389.114

**Comment by olifolkerd** [comment]
You shouldn't be using content editable to edit cells, this is an incorrect approach.

When using Tabulator you should use the built in editor functionality.

Also please don't use all caps to try and gain attention, your issue was closed because it was not a bug nor an acceptable suggested feature. Which is also the case here. If you have questions on the correct approach for something, please ask on Stack Overflow

Please read the documentation for more info.

Cheers

Oli

**Comment by handhikadj** [comment]
okay. sorry if i was rude

so the conclusion for all this is contenteditable element for table cells is not supported and discouraged on Tabulator

One should update this on Tabulator docs

**Comment by Elstermann** [comment]
Dear @handhikadj,

as Oli suggested: ask on StackOverflow. I'm pretty sure you could be satisfied at the end of the day. Also you should focus on your goal instead of your current strategy, imho...

**Comment by olifolkerd** [comment]
Hey @handhikadj,

Given the number of features available in HTML and JS it would be a never ending task to compile a list of what is and isn't advised.  

When you use a 3rd party plugin to complete a task then part of that processes is accepting the design paradigm of that library. In this case Tabulator provides extensive [Built in Editing Functionality](http://tabulator.info/docs/4.9/edit) that covers the needs of pretty much every usage case, and allows for extension for customised usage cases.

It is mentioned in several places in the documentation, and the interactive examples that if your want to edit cell data then you should use an editor.

If you want to work in a different way that is totally your call, but you have to accept that you are then working against the framework which you have included which will likely result in issues.

In this case i would recommend following @Elstermann advice. Rather than approaching your issues with a solutions in mind, look for an existing solution to the bigger goal by reading through the documentation and trying out some of the demos.

Cheers

Oli :)

**Comment by Elstermann** [comment]
"Rather than approaching your issues with a solutions in mind, look for an existing solution to the bigger goal by reading through the documentation and trying out some of the demos." is exactly what I meant, @olifolkerd. I'm pretty sure @handhikadj easily could achieve what he is after just using what Tabulator offers right now out of the box!

**Comment by handhikadj** [comment]
Have you guys checked stackoverflow at tabulator tag? I've addressed https://github.com/olifolkerd/tabulator/issues/3267 5 days ago but no one can answer until now. you can check this link out: https://stackoverflow.com/questions/66903756/text-wrapping-on-tabulator 

<img width="255" alt="image" src="https://user-images.githubusercontent.com/22522638/113735325-59701080-9726-11eb-8f52-4d6c8a9f482b.png">

Maybe I'm the one who's at fault the most here cos I gave less detail on this. here's the detail as to what I'm achieving for: I should be able to render img tag inside the table cells which aligned with the text like the image above.

The main problem: I'm getting stuck and can't find this on the docs
