### ISSUE TITLE
How Can I add a a href button tag in td last column? 

### ISSUE THREAD

**Issue by khurshed52** [olifolkerd/tabulator#3327]
**Describe the bug**

**Tabulator Info**
- Which version of Tabulator are you using?

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khurshed52** [comment]
![image](https://user-images.githubusercontent.com/26027515/120171431-19537880-c213-11eb-9620-4c6f0e62f2da.png)
like this

**Comment by bornova** [comment]
Hi @khurshed52,
You can do this by defining a [custom cell formatter](http://tabulator.info/docs/4.9/format#format-custom) for the last table column.
Here is an example: https://jsfiddle.net/zgyp43wm/

I also think this question may have been more appropriate for Stack Overflow since it's not a bug.

**Comment by khurshed52** [comment]
Thanks for your quick response. @bornova 

How can I translate the columns? any help would be really appreciated
