### ISSUE TITLE
Table scrolls top when unfolding a collapsed column with table height 100%

### ISSUE THREAD

**Issue by tsteinwen13** [olifolkerd/tabulator#3343]
**Describe the bug**
Using tabulator table with `responsiveLayout: "collapse"` and `responsioveLayoutCollapseStartOpen: "false"` without a **fixed container height** causes **scroll to top issues**. When scrolling down and clicking to unfold or collapse a row, the window scrolls top.

**Tabulator Info**
- 4.9.3

**Working Example**
Resize the preview window so it is scrollable and some columns are collapsed. Then scroll down and click at `+` to unfold a row.
[JSFiddle](https://jsfiddle.net/thyrasia/ztfnyugv/) 

**To Reproduce**
1. Go to [JSFiddle](https://jsfiddle.net/thyrasia/ztfnyugv/)
2. Resize the preview that the table is scrollable and some columns are collapsed
3. Scroll a bit down
4. Click on `+` to unfold or collapse a row

**Actual behavior**
The window scrolls up to top when unfolding or collapsing a row.

**Expected behavior**
The window stays at the current scroll position.

**Desktop:**
 - OS: Ubuntu
 - Browser Firefox (also in chrome v 91.0.4472.114)
 - Version 89.0.2

**Smartphone:**
 - Device: iphone x
 - OS: IOS 14.6
 - Browser safari

**Comment by olifolkerd** [comment]
This is because you have not defined a height on the  element containing the table.

This means that Tabulator is taking up the full height of all its data, and the scroll is happening on the page not the table (you can tell this because the headers are moving with the scroll.

The resize causes all the table to be redrawn which makes it momentarily zero height and so the documents scroll is reset.

If you want the table to manage the scroll, and thus not reset the scroll position of the page, you will need to maksure its containing element cannot exceed the height of the page.

Cheers

Oli :)
