### ISSUE TITLE
Tabulator for VSCode 🤔

### ISSUE THREAD

**Issue by RandomFractals** [olifolkerd/tabulator#3344]
Hi, Oli and contributors,

I wanted to reach out and see if you would be open to collaborate with me on exclusive Tabulator vscode extension for devs using that IDE and new native notebooks.

I plan to start working on that MVP this week. Will do it in this repo: https://github.com/RandomFractals/vscode-tabulator

I would like to use your library name and branding for that data grid view extension and open to transfer it to your domain for maintenance later if you'd prefer to keep such tools here in one place.

You can preview some of my work in that space here: https://marketplace.visualstudio.com/publishers/RandomFractalsInc

My intent is to make viewing data in vscode native notebooks easier with your library.

I took it for a spin on my last client project and really liked the docs and features you created, and I think it could be a good fit for the default data grid view in vscode for some devs.

I also run vscode-dev-community slack with a few other experienced vscode extension authors.

This effort will require nothing from your end. Just permission to use your library name and branding for MVP, and repo transfer to your domain is up to you. I am open to maintain it too if you don't have the bandwidth for it.

Please consider it and let me know if you or your users are interested in such a plugin to exist in vscode.

Thanks for creating and maintaining this excellent data grid library.

Taras

**Comment by RandomFractals** [comment]
@olifolkerd we should probably add it to the https://github.com/olifolkerd/tabulator-ideas doc under dev tools if you are up for it

**Comment by RandomFractals** [comment]
done! https://github.com/olifolkerd/tabulator-ideas/pull/2

**Comment by RandomFractals** [comment]
@olifolkerd: Oli, after chatting with some extension devs, and no word from you, I've decided to rename my extension to DataTable, so we don't have any name/branding conflicts and I can move forward with that extension dev and publishing.

I'll provide credits and links to your lib.

**Comment by olifolkerd** [comment]
Hey @RandomFractals 

Sorry for the delay in getting back to you, ive had a bit of a hecktic week at work.

It is great to hear you  are enjoying Tabulator and looking to make an extension with it. 

I am happy for people to use Tabulator in any of their projects, but i do have to insist that the Tabulator branding stay with the library and not with any of the projects that use it, because i dont want the name diluted, and i have no control of the quality of external libraries..

That being said i am happy for people to create libraries that incorporate the name, just not the branding, for example the vue-tabulator and react-tabulator wrapper libraries that other devs have created.

I would add a word of caution against using "DataTable" as that is also the name of another popular JS table library.

What i would say is that i am happy to collaborate with you  on your project, if there are any specific features you may need from Tabulator i would be happy to look at adding them to the roadmap,

And i would love to feature your plugin on the website when you have something ready.

Cheers

Oli :)

**Comment by RandomFractals** [comment]
Hi Oli,

Thanks for the followup.

I might go with ObservableHQ Inputs table for that data table renderer for now. see: https://github.com/RandomFractals/vscode-data-table/issues/12

We can chat more later if you want to see one using Tabulator too.

Taras

**Comment by RandomFractals** [comment]
> I would add a word of caution against using "DataTable" as that is also the name of another popular JS table library.

mine is clrearly names vscode-data-table. unless that other library has some trademark on such a generic name, I don't plan to rename that vscode extension for the 2nd time :smile:

**Comment by RandomFractals** [comment]
@olifolkerd btw, are you referring to [Data Tables](https://datatables.net/) in that note? I looked at it too and liked yours more.

There is only R [data.table](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html) which is really good too, but it's different from what I am after.
