### ISSUE TITLE
tabulator and bootstrap 5 somehow break each other when using popover

### ISSUE THREAD

**Issue by xtlc** [olifolkerd/tabulator#3381]
**Describe the bug**
When adding a button in a popover the wrong code is created
I suspect this is due to some parsing errors. The parsed code looks like this:
```

<button type="button" 
        class="btn btn-danger btn-lg"
        data-bs-toggle="popover"
        data-bs-placement="right"
        title=""
        data-bs-content="<button class=" btn="" btn-danger"="" 
        data-bs-original-title="headline">hello</button>NOT WORKING
          <div class="tabulator-col-resize-handle"></div>
          <div class="tabulator-col-resize-handle prev"></div>

```
it is easy to see that the `<button class ="btn="" btn-danger"=""` does not represent valid HTML code.

**Tabulator Info**
4.9.3

**Working Example**
https://jsfiddle.net/93gLyha2/15/

In this fiddle when you switch `return a` instead of `return b` in the `pContent` function the generated html is broken.

**Expected behavior**
both fields should work fine.

**Desktop (please complete the following information):**
 - OS: win10
 - chrome & safari on current versions

**Comment by bornova** [comment]
Hi @xtlc,
You have couple issues.  One, you need to use single quotes for the class property of the popover button returned by the `pContent` function. Because you are inserting this into the `data-bs-content` attribute which is already wrapped with double quotes. Use this instead:

```javascript
let a = `<button class='btn btn-danger'>hello</button>`;
```

Second, don't wrap the `tooltipsANDpopovers()` function call in another function in the `dataLoaded` callback of tabulator.  Just call it directly as such:
```javascript
dataLoaded: tooltipsANDpopovers()
```

Here is your example updated:
https://jsfiddle.net/h7uLvjdm/
