### ISSUE TITLE
Redraw method fails in Tabulator v5

### ISSUE THREAD

**Issue by dbauszus-glx** [olifolkerd/tabulator#3436]
Version 5.0+ ; Tested with v5.0.1 and v5.0.6

Works with v4.9.1

Creating a table, setting the data with setData(), then redrawing the table with .redraw() fails due to the layout mode being null.

```js
layout(){
 Layout.modes[this.mode].call(this, this.table.columnManager.columnsByIndex);
 this.dispatch("layout-refreshed")
}
```

The layout() method in the [layout module](https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/Layout/Layout.js) is called prior to the initialize method when setData() & redraw() are used instead of providing the data as parameter when the table is created.

![image](https://user-images.githubusercontent.com/22201617/139059366-78797868-7fa5-4ffc-9e38-95e1d7121b1a.png)

You can replicate the issue in this codepen.

https://codepen.io/dbauszus-glx/pen/WNEjmOG

**Comment by olifolkerd** [comment]
Hey @dbauszus-glx 

This is happening because you are calling functions on the table before it has been initialised. you should see a warning in the console telling you that you are trying to call `setData` on an uninitialized table.

This happens because Tabulator now initializes asynchronously, this happens for two reasons, the first is to allow consistent initialization between async and synchronous data sources, the second is to allow binding of  events to the table before initialization is completed, to catch things like the `tableBuilt` event.

If you want to continue to use the `setData` to initialize the data in your table *(which is unnecessary if you correctly initialize the data in the table using the `data` setup option)* then you need to call it in the `tableBuilt` event which is fired after the table has been fully initialized
```js
table.on("tableBuilt", function(){
    table.setData(data);
});
```

As for the `redraw` function, there is no need to call it in your usage case, the table will automatically redraw itself after the table data has changed.

i will add a console warning to the redraw function as well incase it is called on an uninitialized table.

I hope that clears up the confusion.

Cheers

Oli :)

**Comment by dbauszus-glx** [comment]
Thanks. Much appreciated that you explain the behaviour in more detail here.
