### ISSUE TITLE
column header resize missaligns row-cells

### ISSUE THREAD

**Issue by jaguarxii** [olifolkerd/tabulator#3445]
When the table has many columns that shows a horizontal scroll bar, when you interact with the header (width, sorter) the rows of the table resets its horizontal offset to ZERO causing the headers and the content cells do not match any more.

It realigns after scrolling in any direction using the horizontal scroll bar.

This behavior is consistent since previous versions (4.9.3).

**Tabulator Info**
- v 5.0.7 (also happens in previous versions 4.9,3)

**Working Example**
https://codepen.io/jaguarito/pen/oNezjoZ

**To Reproduce**
1. scroll all the way to the right using the horizontal scroll bar
2. hit the sorter button of any visible column header (age or favourite color)
3. the content cells reset its offset to ZERO showing the contents of the name column (which was hidden after scrolling)

optional: it show the same result if you filter (header filter) by favourite column

**Expected behavior**
The cells should retain its original offset after applying the sort order

![20211101_missaling](https://user-images.githubusercontent.com/8013436/139682248-1ae38dc1-3ebd-47fe-afb2-87274fa5e98a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Waterfox (latest), Chrome (latest)

**Comment by uaturk** [comment]
Hi Olie,
I did not realised that the previous topic which I wrote a comment on, is too old and closed. I am sorry for that.
I have similar issue. I use tabulator with tabulator.js v5.0.6. If there are some columns out of view port, a horizontal scroll bar appears.
When you scroll to the right, to see the other columns, and, when you
issue(1) click column header in order to sort the table data or,
issue(2) type something in the header filter input box
makes the table data - data rows' columns: really the first column displayed in the left of the view port but, header columns did not reflect any change. So misalignment occurs. When you scroll a little to the right misalignment resolves.
I could fix the issue(1) by
`table.on( "headerClick", function( e, column ){`
	`table.columnManager.scrollHorizontal( 'left' ); // new line to restore header scroll position`
	`table.scrollToColumn( column.getField(), "middle", false ); //scroll column which is clicked to the middle if not already visible`
`} );`
but issue(2) remains unresolved.
Thanks for your effort.
Initial screen:
![initial](https://user-images.githubusercontent.com/39532292/139708790-ac799189-ab4a-4d88-a768-6612207ec5bd.jpg)

issue(2):
![issue-2](https://user-images.githubusercontent.com/39532292/139708934-cab66e41-1758-47fe-865e-d154851f8053.jpg)

**Comment by jaguarxii** [comment]
> `table.on( "headerClick", function( e, column ){`
> `table.columnManager.scrollHorizontal( 'left' ); // new line to restore header scroll position`
> `table.scrollToColumn( column.getField(), "middle", false ); //scroll column which is clicked to the middle if not already visible`
> `} );`

thanks, works like a charm

**Comment by olifolkerd** [comment]
Thanks for the info,

I will look at getting a fix out for this in the next patch release

Cheers

Oli:)

**Comment by thephoton** [comment]
In my case, it just seems that the rowManager forgets its position - reapplying the scrollLeft from the columnManager fixes the issue:

`this.table.on("headerClick", (e, column) => {`
`    this.table.rowManager.scrollHorizontal(this.table.columnManager.scrollLeft);`
`} );`

**Comment by olifolkerd** [comment]
Hey All,

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

OlI :)
