### ISSUE TITLE
Issue with ajax progressive load and remote filters

### ISSUE THREAD

**Issue by edwbaker** [olifolkerd/tabulator#3453]
**Describe the bug**
With scrolling progressive load and ajax filtering enabled, when a filter is applied the results appear below what has already been progressively loaded, rather than replacing them. The ajax requests follow sequentially from what has already been loaded (i.e. if progressive loading has already loaded two pages when the filter is applied it will request page 3 of the filtered data - which might not exist).

**Tabulator Info**
- 5.0.6

**Working Example**
https://audioblast.org/demo.html

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://audioblast.org/demo.html
2. Type 'Baker' into author filter
3. See filtered results appended to end of already loaded data.

**Expected behavior**
Filtered results replace existing results, and are requested from page one.

**Comment by plataux** [comment]
I can confirm that the same issue exists with remote sorting with progressive (scroll) loading as well. Say you scroll two pages down, then you click on a header to sort. The existing data remains and newly AJAX data is appended underneath the currently loaded rows, rather than replace them.

The work around that I came up with is to replace the whole table each time filtering or sorting takes place, but that is not an optimal solution

**Comment by olifolkerd** [comment]
Hey @edwbaker 

I have pushed a fix for this to the master branch and will include it in the next patch release,

Cheers

Oli :)
