### ISSUE TITLE
Bootstrap 5.1+ CSS

### ISSUE THREAD

**Issue by cgountanis** [olifolkerd/tabulator#3472]
Just wondering if there was a plan on getting a bootstrap 5 CSS for tabulator I noticed there's like three and four but nothing for the current build and a few things did change and it would be nice to normalize that throughout our bootstrap 5.1 site.

**Comment by stvowi** [comment]
Bootstrap 4 will soon be deprecated. I also miss a SCSS/ CSS - theme for Bootstrap 5.

**Comment by cgountanis** [comment]
Right now we've reverted back because the HTML created tables rowclicks do not work so hopefully I can circle back in a couple of months and we're back to where we were 😁

**Comment by olifolkerd** [comment]
Hey All,

I would love to add this as a feature, but i don't have the time myself right now as im focusing on other parts of Tabulator, but i would be happy to accept a pull request for this.

It would be simple enough for anyone to build out a PR for this, simply base it on one of the existing Bootstrap themes in the `/src/scss/themes/bootstrap` folder.

The [Build Docs](http://tabulator.info/docs/5.0/build) contain all the details you need to get started building for Tabulator

and the [Pull Request Guide](http://tabulator.info/community#contribute-pr) explains our PR process.

If someone is willing to take this on, could you post below so that everyone can cooridinate.

Cheers

Oli :)

**Comment by cgountanis** [comment]
I can't promise anything but I can always try to take a look at it myself maybe in a week or two.

**Comment by olifolkerd** [comment]
Hey @cgountanis, Im about to start work on the 5.2 release, with the aim to have it released around mid april. Any chance you fancy doing the Bootstrap 5 theme?

**Comment by cgountanis** [comment]
> Hey @cgountanis, Im about to start work on the 5.2 release, with the aim to have it released around mid april. Any chance you fancy doing the Bootstrap 5 theme?

You know I would love to I just have to find some time between now and then. I'm assuming I could probably take the old one and just update it for the new syntax as far as styles and CSS goes shouldn't be too bad. I've been working with bootstrap 5 for a while so I kind of know the before and after start versus left XY they change stuff for no reason really... I'll keep you posted unless you have somebody that wants to rain man it overnight you know what I mean 😂

**Comment by olifolkerd** [comment]
Yeah you can certainly base it of the previous version no probs 👍👍👍

**Comment by cgountanis** [comment]
@olifolkerd Don't think it's going to happen. New to some of this NODE build stuff. Forked, branch, started getting things ready. Failed right on npm install. I figure if I can not get past that first step, best not to waste any time. Tried with Node Current & LTS. Best not relay on me man, lol...

**Comment by olifolkerd** [comment]
You will be happy to hear someone has just contributed the bootstrap 5 theme, it will be included in the 5.2 release later this month.

Cheers

Oli :)

**Comment by cgountanis** [comment]
Well that's awesome news! Is there a PR or something maybe I could learn from the steps and the change files?
