### ISSUE TITLE
Check if Cell is Editable

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#348]
When clicking on a cell, how do I determine if that cell is editable?
I don't see any class changes that I could test for.

Note: Still looking for solutions to #341 & #347 
Thanks,  Bill

**Comment by olifolkerd** [comment]
Hi Bill, with regards to #341 im happy to help you, but i need you to post your tabulator constructor object in that issue so i can replicate the problems you are having.

**Comment by olifolkerd** [comment]
Hi Bill,

Tabulator uses the ***editable*** function in the column definition array to check if a cell is editable when the user clicks on it. This is done the moment the user clicks on it because it could be dependant on anything (other values in the row, values outside of tabulator, etc...) so there is no safe way for tabulator to know when to add/remove an "editable" class, it just performs the calculation when the user clicks on the cell. It does this all automatically, you should not need to manually change this.

If you want to know this for other reasons, there is nothing to stop you from calling the editable callback yourself if you have the cell component, for example dong this on click:

```js

var editCheck = function(cell){
    //cell - the cell component for the editable cell

    //get row data
    var data = cell.getRow().getData();

    return data.age > 18; // only allow the name cell to be edited if the age is over 18
}

$("#example-table").tabulator({
    columns:[
        {title:"Age", field:"age"},
        {title:"Name", field:"name", editable:editCheck,  cellClick:function(e, cell){
            var editable = cell.getColumn().getDefinition().editable;

            if(typeof editable  === "function" && editable(cell){
                //cell is editable
            }else{
                //cell is not editable
            }
        }}
    ]
});
```

**Comment by stack-its** [comment]
I'm trying to combine various things you've said, so if I am checking if cell is editable on click:

```
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", cellClick:globalCellClick}
   ]
});
```
Then a script outside of tabulator:
```
function globalCellClick(e, cell) {
    console.log('Cell: ' + cell);  // getting undefined
    var cellf = $(cell).attr('tabulator-field');
    console.log('Selected cell field: ' + cellf); // getting undefined
    var celledit = $(cell).getColumn().getDefinition().editable; // determine if editable
    console.log('Editable cell: ' + celledit); //  getting undefined
    var  celltxt = $(cell).text(); // getting undefined
}
```
