### ISSUE TITLE
cell click or cell double click not working in version 5.0.7

### ISSUE THREAD

**Issue by agilent21** [olifolkerd/tabulator#3508]
![Screenshot from 2021-12-16 14-00-01](https://user-images.githubusercontent.com/96267138/146455370-426fb750-37ab-4273-b8ae-0019e45e4050.png)

**Comment by GreenX5** [comment]
I have the same
`https://cdnjs.cloudflare.com/ajax/libs/tabulator/5.0.7/js/tabulator.min.js`
```
rowClick: function (e, row) { //trigger an alert message when the row is clicked
		alert("Row " + row.getData().id + " Clicked!!!!");
	},
```
=>
`Invalid table constructor option: rowClick`

**Comment by olifolkerd** [comment]
@GreenX5 that is because it is now an event, checkout the [Upgrade Guide](http://tabulator.info/docs/5.0/upgrade) for full details.

@agilent21 If you feel you have found a genuine bug then please resubmit this using the Bug issue template, it is impossible to offer help from a simple console error, we need to see  a JS fiddle that demonstrates the issue and step by step guide how to reproduce it.

Cheers

Oli :)
