### ISSUE TITLE
Error row resize

### ISSUE THREAD

**Issue by FrantzUml** [olifolkerd/tabulator#3524]
Using the JavaScript - Feature Rich Table example [(http://tabulator.info/)], an error 'this.dispatchExternal is not a function' when rsizing any row, appears.

Using the latest version from CDN : src="https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js"
Using Firefox 95.0.2
Error dispatched on console : Uncaught TypeError: this.dispatchExternal is not a function

Thanks

**Comment by olifolkerd** [comment]
Hey @FrantzUml 

Thank for the headsup, i have pushed a fix for this to the5.1 branch and will include in in the next release.

Please can you use the [Bug Reporting Issue Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) next time you report a bug, it will prompt you for all the information we need to help you out.

Cheers

Oli :)

**Comment by asadsahi** [comment]
@olifolkerd this bug is causing some serious issue in my app. There is some global error handling which this bug raises too many errors to raise without any indication of the real issue. Is there a way to use the fix earlier by using some beta version of this? When are you planning on releasing 5.1? Is it worth to keep this issue open until the release? Thanks

**Comment by asadsahi** [comment]
Just to point out I am having this issue on `rowClick` as well, all the 5.x versions have this issue. Reverting back to 4.9 version to get round this issue. Looking forward to 5.1 fix 🤞
