### ISSUE TITLE
column.updateDefinition() creates new column

### ISSUE THREAD

**Issue by cimenta** [olifolkerd/tabulator#3528]
**Describe the bug**
column.updateDefinition() creates new column when called from  table.on("cellEditing", function(cell)

**Tabulator Info**
- 5.0.10

**Working Example**
(https://jsfiddle.net/radek/us79t2hj/49/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:

test scenario #1
1. load table. click column 'contract'
2. new column is created

test scenario #2
1. click column "id"
4. columns title is update as it should be. see the code

**Expected behavior**
columns title should be updated as per scenario #2

**Additional context**
I was testing proof of concept to update autocomplete data/values after the cell is clicked. I need the autocomplete data for column contract be different for each cell based on value selected in the column name

Please also note the error "Uncaught (in promise) TypeError: t.classList is undefined"

**Comment by doublehrajput** [comment]
Use `cellEdited` event

`
       
    table.on("cellEdited", updateTitle);
      
    function updateTitle(cell) {
        var field = cell.getField();
        if (field == "contract" || field == "id") {
          window.column = cell.getColumn();
          var name = cell.getData().name;
          column.updateDefinition({ title: "Updated Title" });
      }
    }
`

**Comment by olifolkerd** [comment]
Hey @cimenta 

You cannot update a column while you are actively using it, the `updateDefinition` function actually destroys the current column and replaces it when you trigger an update like that.

Since the cell is being edited at the time, the it cannot be destroyed, so the new version is added along side it.

as @doublehrajput mentions, the correct approach would be to use a different event.

Cheers

Oli :)
