### ISSUE TITLE
Grouping cause issue with site position

### ISSUE THREAD

**Issue by Eloar** [olifolkerd/tabulator#3564]
**Describe the bug**
Using groups with data set after table initialization causes weird behavior. Window position is changed each time group is toggled. Also in simple example it "jumps up" every few seconds.

**Tabulator Info**
Version 5.0.10

**Working Example**
JsFiddle: https://jsfiddle.net/eyhmn47q/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. wait 3 seconds when interval loads data into Tabulator
2. open few groups
3. scroll down, open group - window position will change
4. optionally scroll down on table with few open groups and wait, it should 'jump' randomly in few seconds

**Expected behavior**
Expected groups to open in place.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser:
  - Chromium 95.0.4638.54 (Official Build, ungoogled-chromium) Ubuntu (64-bitowa)
  - Firefox 96.0.2

**Additional context**
Found that problem when migrated from 4.9.1 to 5.0.10. I use Tabulator to present data acquired from server and bit manipulated. There is single level grouping using multiple parameters. Those params are just concatenated into text. Quite effective.

So thing work as expected on 4.9.1 and doesn't on 5.0.10. In 5.0.10 could get closest to

**Comment by olifolkerd** [comment]
Hey @Eloar,

The issue is happening because you have defined a height on the table in percent but haven't set a height on the tables containing element so it has no reference and will grow indefinitely.

In virtual render mode *(enabled by default when the table has a height)*, the table is full redrawn each time something in the DOM changes *(only the visible area)*. In this case because the table is uncalculatable, when the group is toggled, the table is redrawn, meaning it momentarily has a height of 0 which causes the scroll position of the page to shift as it no longer has a table to accommodate.

The two options to resolve this are either, don't set a `height` on your table if you want it to show all data it holds, in which case tabulator engages `basic` render mode and has a special function to stop this scroll jitter. or define a height on your table, but if that is in percent then the containing element also must have a specific height for the table to display correctly.


On a side note you don't need to call the `redraw` function after calling the `setGroupBy` function, it will do this automatically, also you don't need to call the `setGrouby` function after loading data into the table, it will automatically group data by the existing group by settings

Cheers

Oli :)

**Comment by Eloar** [comment]
There are two problems. I was experimenting with height in different configurations and it changed little to none. Also When grouping and not setting height table height is set to height of groups and second scroll appears each time group is open. In 4.9.1 there were no scroll, there is in 5.0.10. Only way to get rid of it is to set height to 100%, but... then there is issue with jumping. How may I get rid of scroll on table when using groups?

Also jumping happens by itself. Even in fiddle I provided on other machine I noticed it jumped by itself around 2s after table was scrolled into view.

**Comment by Eloar** [comment]
Tried version 5.1.0, no luck.
I've set `renderVertical` to 'basic', height already set on table, and vertical scroll appears when opening group (documentation states it should not happen). Set height to `100%` along `basic` renderer. Unfortunate "jumping" is still there. Shouldn't `basic` renderer disable VirtualDOM?

**Comment by olifolkerd** [comment]
THere wanst any chance in 5.1 that would affect this.

The full redraw of the table happens in all render modes, in basic, it is more apparent because the height of the table changes which is what causes the jumping.

The issue is because the table container has no height.

Cheers

Oli

**Comment by Eloar** [comment]
so how may I achieve effect like in 4.9 when I don't declare height and table is as long as needed and it gets longer when group is extended? Idea of second scroll on page is part of bad user experience.
