### ISSUE TITLE
Using setData with POST and ajaxContentType json, turns array into json object.

### ISSUE THREAD

**Issue by langebangen** [olifolkerd/tabulator#3579]
**Describe the bug**
When using `setData` with a json post request with a body of a json array, that json array is turned into a json object in the request that is sent.

`table.setData("/echo/json/", [1,2,3], "POST")`

This was not the behaviour in tabulator 4.9, the json array would not be transformed to a json object.
It is also important that `ajaxContentType` is set to `json` on the tabulator object.

**Tabulator Info**
- Which version of Tabulator are you using? 5.1 (It was working in 4.9)

**Working Example**
Here is a jsfiddle were the issue occurs: (v5.1): https://jsfiddle.net/L5d4vsje/17/
Here is an example where it is still working as expected (v4.9.0): https://jsfiddle.net/4etsvdrz/6/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open chrome developer tools
2. Go to network tab
3. Press ctrl+s in the jsfiddle window so the code reruns
4. Open the json network request seen in the developer tools and inspect the payload.
5. You will see that the payload is a json object instead of a json array

**Expected behavior**
I expect the sent in json array to be sent as an json array and not transformed into a json object.
This was how it worked previously in v4.9

**Screenshots**
![image](https://user-images.githubusercontent.com/11957324/152932583-e2b0ea74-0b8c-4944-acdf-e4162a3caf1d.png)
![image](https://user-images.githubusercontent.com/11957324/152932624-55fa7224-ea50-4494-b9d1-210033323f7f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 98.0.4758.82

**Comment by olifolkerd** [comment]
Hey @langebangen 

That is because it is standard practice to send data back to servers as a series of props. In the case of Tabulators module system, each module can add additional data to the props that are sent over ajax, for example the pagination system would add page numbers etc, if there is an array passed in, it would have no way to handle this.

I would consider it extremely bad practice to send back an array in a request without attaching it to the contextual information or a prop. it makes your request unextendible in future if you need to send additional data. i will update the docs to make it clear this is the case.

Cheers

Oli
