### ISSUE TITLE
Cannot edit cells if Chrome Virtual Keyboard is enabled

### ISSUE THREAD

**Issue by tcrussell** [olifolkerd/tabulator#3583]
**Describe the bug**
When using the Google Chrome browser with the Virtual Keyboard extension enabled, you cannot edit cells. When you click on a cell you cannot get an insertion bar to appear. The virtual keyboard does not have to be active, you just have to have it enabled in the extensions screen. The same issue occurs when using Chromium on an Raspberry Pi. 

**Tabulator Info**
Noticed this behavior in Node Red, but you can observe it right on the tabulator page: [(http://tabulator.info/examples/5.1?#editable)]

**Working Example**
Launch Google Chrome with Virtual Keyboard extension.
Enable the extension in the extension manager.
Restart Chrome.
In the Chrome tool tray you can have the virtual keyboard either on or off - it does not matter.
Go to tabulator website:
[(http://tabulator.info/examples/5.1?#editable)]
Click on the cell for Mary May and cursor will appear and then disappear

**Expected behavior**
You should be able to edit the cell.

**Screenshots**
![image](https://user-images.githubusercontent.com/6455830/153010474-d369c548-b38b-420d-b48c-060f56361a37.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 98.0.4758.81 (Official Build) (64-bit)
- Browser Chromium
- Version Version 92.0.4515.98 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)

**Comment by olifolkerd** [comment]
Hey @tcrussell 

This is because the chrome virtual keyboard extension (not made by google) simply adds a keyboard to the DOM of the page, so every time you click a button on the keyboard it moves focus from the editor element.

Tabulators elements consider a loss of focus(blur) to mean the user has finished editing and therefor close the editor and save the value.

Most browsers built in keyboards do not append to the DOM, and therefor do not steal focus when used.

Cheers

Oli :)
