### ISSUE TITLE
getParentColumn() fails with Uncaught ReferenceError: Column is not defined

### ISSUE THREAD

**Issue by micrology** [olifolkerd/tabulator#3585]
**Describe the bug**
getParentColumn() applied to a column component fails with the error:
```
Uncaught ReferenceError: Column is not defined
    at Proxy.value (tabulator.min.js:2:6696)
    at n.<anonymous> (pen.js:51:35)
    at tabulator.min.js:2:94519
    at Array.forEach (<anonymous>)
    at e.value (tabulator.min.js:2:94488)
    at n.value (tabulator.min.js:2:4871)
    at n.value (tabulator.min.js:2:283488)
    at n.value (tabulator.min.js:2:282688)
    at tabulator.min.js:2:96696
    at Array.forEach (<anonymous>)
```
**Tabulator Info**
- Which version of Tabulator are you using? 5.1

**Working Example**
https://codepen.io/micrology/pen/RwjpGeK

The relevant section is
```
table.on("cellClick", function (e, cell) {
  console.log(`Cell ${cell.getValue()}
  Column ${cell.getColumn().getField()}
  Parent ${cell.getColumn().getParentColumn().getField()}
        `);
});
```

**To Reproduce**
To show the bug, click on any table cell.  Nothing will visibly happen, but if you open a DevTools inspector window, you will see the error above.  If  you now delete line 52: ` Parent ${cell.getColumn().getParentColumn().getField()}`, open the codepen console, and click a table cell, you will see the expected output: the cell value and the column field name. 

**Expected behavior**
The codepen console should show the field name of the parent column (or false if none)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Browser Chrome
 - Version 98

**Comment by olifolkerd** [comment]
Hey @micrology 


Thanks for the info, there was an issue in the `getParentColumn` function that resulted in it always returning `false` even if there was a parent column. I have pushed a fix for this to the master branch and will include it in this weekends patch release.

I should point out that in your example it will always throw an error when you click on the name column, even with this fix, because the `getParentColumn` will return a value of `false` if the column has no parent and you are calling the `getField` function on it without checking if there is actually a parent first.

Cheers

Oli :)
