### ISSUE TITLE
Background Cell

### ISSUE THREAD

**Issue by neorm5** [olifolkerd/tabulator#361]
Hi, my table have nulls in the cell, i want a color instead of a null, is possible?
I try with cell.css and formater but i dont do anything

Thanks
 PD: I used the 3.0 version of tabulator

Thanks #

**Comment by olifolkerd** [comment]
Hey,

you could create a custom formatter to do this:

```js
var nullFormatter = function(cell, formatterParams){
    var value = cell.getValue();
    if(value  == null){
       cell.getElement().css("background-color","#f00");
       return "";
    }else{
        return value;
    }
};

$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", formatter:nullFormatter}
    ]
});
```

Let me know if that helps

Cheers

Oli

**Comment by neorm5** [comment]
Work perfect! Thanks

**Comment by midhunp6** [comment]
But when I used this got TypeError
**Uncaught (in promise) TypeError: cell.getElement(...).css is not a function**
![capture](https://user-images.githubusercontent.com/35056568/48544109-f6794700-e8e8-11e8-85ec-4d2c69c9ad24.JPG)


`var color_mamnager = function(cell, formatter_params){
    var value = cell.getValue();
    return value;
    if(value > 90){
        cell.getElement().css("background-color","red");
        return value;
    }
}`

**Comment by olifolkerd** [comment]
Hey @midhunp6 

Please do not post comments on old posts that have been closed for over a year, please raise a new issue if you are having trouble and use the issue template as it prompts you to answer questions that help us fix your issue.

If you are using version 4.0+ then this is because Tabulator no longer uses jQuery. so the ***getElement*** function now returns a DOM node so the correct code to set the background colour would now be:

```js
cell.getElement().style.backgroundColor = "red";
```

I hope that helps,

Cheers

Oli

**Comment by midhunp6** [comment]
Hi @olifolkerd 

Thank you for the solution, I will keep your advice for the next time issue. 
Now your solution is working fine 😍😍 
Thank you so much

Cheers ❤
Midhun 😍
