### ISSUE TITLE
Virtual horizontal dom still going bananas.

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3627]
After testing 5.1.2 in Beekeeper Studio, the horizontal vdom is still going crazy...

https://user-images.githubusercontent.com/279769/155914484-3054b666-efae-4b88-bd7a-d1ec44b66909.mp4

It seems to only happen when the tab is first loaded, if I resize the window it behaves itself.

However, if I trigger a data load (like sorting by a particular column) it ends up back in the broken state.

When inspecting the table, it has insane padding, like 3000px:

![image](https://user-images.githubusercontent.com/279769/155914783-fcf68822-8b47-4824-b467-19768cfbc4a4.png)

@olifolkerd Any idea how to debug this?

**Comment by rathboma** [comment]
Here's a better video, with voiceover:

https://drive.google.com/file/d/1hBCF5APlmN8yejPb2q1C0OVMc24Rm6xX/view?usp=sharing

**Comment by rathboma** [comment]
This might be limited to ajax'd data?

**Comment by rathboma** [comment]
Ok, so my guess is that whenever something calls `this.table.rowManager.setData(...)` it causes this problem.

This calls a function called `resetScroll`, which might not actually reset the scroll properly? That's my best guess because:

- It happens with AJAX and paging
- It doesn't happen with a non-ajax table, even when sorting columns
- Only ajax and paging call `rowManager.setData`.

**Comment by rathboma** [comment]
Here is it replicated:

https://github.com/beekeeper-studio/tabulator/tree/horizontal-dom

clone
yarn install
yarn web:dev
browser: http://localhost:5678/examples/hoz-dom.html

Things to notice:
- On first load horizontal scroll is broken, same as in Beekeeper
- If you resize the window, it works better
- Sort by any column, it's broken again

**Comment by rathboma** [comment]
This is on master!

**Comment by rathboma** [comment]
Here's a video of the demo in the tabulator fork

https://user-images.githubusercontent.com/279769/156030769-2e9bf5e0-9807-4ec6-bc45-93f512f113f7.mp4

**Comment by olifolkerd** [comment]
Hey @rathboma 

Thanks for all the details, that is very helpful. Sorry i missed your message about pair programming, unfortunately i was busy Friday eve.

Thankyou for the example, i can now replicate it on my machine, so will have a look at it over the weekend and see what i can do.

Interestingly it doesn't seem to happen with my randomly generated column and data combos, but i can reliably replicate it with the data/columns you provided, so i will investigate things a bit further and see what i can dig up.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma 

I have just pushed a couple of commits to the master branch that fix the issues i have have observed. i will include them in todays, patch release. Have a play and let me know how you get on.

There were two different issues i found:

The hozVirtualDom was trying to render the cells of the row before the row was flagged as initialized which was resulting in elements on the DOM becoming orphaned from their components and not being removed properly which resulted in the header falling out of sync with the body on scroll and additional duplicated cells.

When the table is in `fitData` layout mode the hozVirtualDom requests a sample row from the modules to correctly work out the column widths, in this case the fallback row lookup function was returning a row instead of an array of rows so the the renderer didn't have the correct information to calculate the row widths which was resulting in the blank table while scrolling.

A key learning for me was that in my example data all my randomly generated data was the same width therefor all  my columns were the same width, in that circumstance the effects of the issue were masked. Thankyou for the more realistic data set, that made it very obvious where the issues where.

I will have the 5.1.4 release out in the next hour or so.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma, The patch has now been released :)

**Comment by rathboma** [comment]
Legend. :rocket:
