### ISSUE TITLE
Incorrect Row object when sending / adding a row from one table to another

### ISSUE THREAD

**Issue by verdonfly** [olifolkerd/tabulator#3639]
**Describe the bug**
When trying to add the **same row** from a Sender table to the Receiver table, this creates a problem when changing the row on the Receiver and trying to add the same row from the Sender.
The problem occurs not only with linked tables, but also with a simple addrow.
Tabulator Info

5.1 >
**Working Example**

https://jsfiddle.net/verdonfly/46dg5upv/12/

**To Reproduce**

**Test1:**

1. Drag "Oli Bob" to the Receiver Table
2. Change "Oli Bob" to "Oli Bob2" in the Receiver Table
3. Drag Oli Bob back to the Receiver Table

I expect "Oli Bob" to be added to the Receiver Table

**Test2:**

1. Double click on "Oli Bob" in the Receiver Table
2. Change "Oli Bob" to "Oli Bob2" in the Receiver Table
3. Double click on "Oli Bob" in the Receiver Table

I expect "Oli Bob" to be added to the Receiver Table

Desktop (please complete the following information):

OS: Windows
Browser chome

@olifolkerd

**Comment by olifolkerd** [comment]
Hey @verdonfly 

This is happening because javascript objects are passed by reference. and is the correct default behaviour, In most usage cases the row would be removed from the parent table before being added to the child table, preventing duplication.

In the case of the `addRow` function. If you want to break the reference then you should use `Object.assign` before passing the value to the function:
```js
 table2.addRow(Object.assign(row.getData()), false);
```

You can acheive a similar result in the drag drop by defining your own `movableRowsReceiver` function in the table constructor object:
```js
movableRowsReceiver:function(fromRow, toRow, fromTable){
    this.table.addRow(Object.assign(fromRow.getData()));
    return true;
}
```

Cheers

Oli :)

**Comment by verdonfly** [comment]
@olifolkerd thk.
The correct use of the Object.assign () function for this case is:
table2.addRow (Object.assign ({}, row.getData ()), false);

**Comment by olifolkerd** [comment]
@verdonfly Quite right, i have corrected my answer
