### ISSUE TITLE
pagination scrolls to top with remote pagination

### ISSUE THREAD

**Issue by s-cork** [olifolkerd/tabulator#3644]
**Describe the bug**
When using remote pagination and clicking next page, the table scrolls to the top on each click to next.

**Tabulator Info**
- Which version of Tabulator are you using? 5.1.2

**Working Example**
https://codepen.io/s-cork/pen/vYWMmQr

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Make sure the window is small enough so that the tabulator component goes off the screen vertically
2. scroll down to the pagination footer
3. click next
4. observe the window jumps back to the top

**Expected behavior**
The scroll position remains at the pagination footer

**Desktop (please complete the following information):**
 - Browser Chrome
- MacOs

**Additional context**
I'm using a variation of the database example module to demonstrate the issue.
Without the remote pagination mode I don't see this behaviour.

**Comment by olifolkerd** [comment]
That is because you are using a table that has no height defined, when it loads each page it clears out the rows and then rebuilds the table with the new rows, during this the scroll will reset because the table does not take up as much height.

You either need to set a height on the table or its container to avoid this.

Though i would say it is a massive antipattern to have a paginated table bigger than the page it is displayed on, the whole point of pagination is to break a big data set into chunks that are digestible by your user.  If they are having to scroll to view the data then you have rather lost the point of paginating the data in the first place.

Cheers

Oli :)

**Comment by s-cork** [comment]
Sure, I was just surprised that the same approach worked fine without the use of remote pagination. 

I think massive anti-pattern is a bit of an overstatement.
