### ISSUE TITLE
GroupContextMenu pops up in wrong place

### ISSUE THREAD

**Issue by proautodinc** [olifolkerd/tabulator#3647]
Describe the bug
Right click to view GroupContextMenu pops up in wrong place.

Tabulator Info

version 5.1.4
Working Example
https://jsfiddle.net/dnyg2jor/

To Reproduce

Open fiddle above
Click on Run
Expand the right paenl view to max
Right click in one of the table groups
Expected behavior
Context menu show be showing in the same location as the row
Context menu pops in wrong place way to far below the grouped row position

Desktop:

OS: Windows
Browser: reproduced in Chrome, Opera and Brave
Versions 98, 83 and 1.35

**Comment by olifolkerd** [comment]
Hey @proautodinc 

This is happening because the menu elements are positioned absolutely in the parent container, in your case because the body is not set to a min height of 100% and is position static it is throwing off the calculations.

The documentation does stat that a position needs to be set on the menu container, so if you set the body to `position:relative` it should resolve the issue. to be safe for Tabulator to alter the position of the body element itself so i will have to look into this further in a later release as it certainly could handle this default scenario better.

In the mean time, as a workaround set the position as outline above or use the `menuContainer` option to append the menu to a relative or absolutely positioned parent.

Cheers

Oli :)
