### ISSUE TITLE
Horizontal vdom - column headers out of sync and disappearing data (replicated)

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3653]
Hey Oli,

After chatting with a BKS user I figured out how to replicate it, at least in one specific way.

This shows two things:
- Column header sync issues
- Performance drops when scrolling back to the left

I'm using this demo repo / branch:

https://github.com/beekeeper-studio/tabulator/tree/hoz-dom-3646

I took the same data and made 10 copies of each column, so it's a very wide table -- although this is not an unrealistic size

## How to replicate

1. Use either firefox or Chrome, doesn't matter
1. Scroll all the way to the right
2. Scroll slowly back to the left
3. At like duplicate 5 or 6 you'll see the headers mis-align
4. During this scrollback you'll notice performance tank and a lot of stuff starts failing to render

It actually performs better in FF. I'm using a Ryzen 3600 with 32gb RAM, which is pretty beefy.

## Video:

https://user-images.githubusercontent.com/279769/157499348-74e7cd65-ea45-49d9-a2d2-27360372fef2.mp4

**Comment by rathboma** [comment]
Not sure if this helps, but a performance capture from chrome dev tools shows it's spending all of it's time in `addColLeft`:

![image](https://user-images.githubusercontent.com/279769/157500426-b1ddc1f3-a015-4c79-8946-078f6954a441.png)

**Comment by olifolkerd** [comment]
Hey @rathboma 

Thanks, that was perfect info.

There are a few issues going on here which this highlights:

#### Scroll Behaviour
The functionality that manages the scroll has two different modes, for small scroll movements it add the columns but for bigger movements it redraws things to stop the performance overhead you saw there.

The issue was that the scroll wasn't taking account of the new adaptive buffer width, and that i wasn't taking account of the absolute value of the scroll movements so scrolling in one direction were triggering the full re-render and scrolling the other was triggering the incremental update

I have just pushed a fix for this to master and will look at including it in the next patch release.

#### Performance bottle necks
Looking at the column management functions it is layout thrashing when it has to add/remove multiple columns. I have already optimized this behaviour in the vertical virtual renderer, so i will look at making the same improvements here, though this will probs take a day or so to do. i will give you a shout when the changes are in.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
In addition to the above the reason for the header mis-alignments was due to the calculations used to work out the width of the table.

When `fitData` mode was enabled, the renderer only used the actual widths for the visible columns and then worked to an average width for the non visible columns *(i believe this was done to improve table load times on the 4.9 renderer)* which meant that as you scrolled right it had to recalculate the width of the columns as you scrolled and it added new columns, this was no issue because the columns were ahead of the scrollbar.

If you scroll right it skips some of these columns to make the render faster, which means that when you scroll left again you encounter uninitialized columns, because the columns change width and are to the left of the current scroll position it then changed the columns relative to the current scroll and broke the alignment.

I added some corrective maths for this to prevent the misalignment, but because it also adjusted the rows relative to the scroll bar, in order to keep the table scroll smooth it had to programmatically shift the scroll position of the table, which caused a lot of jitter in the render.

To avoid the worst of it, I have also tweaked the renderer to render an entire first row of the table including all columns, so there is less deviation from the average when scrolling which seems to have smoothed things out. In my simulation with 1000  columns this hasn't resulted in any disenable increase in loading time that i could see, but if you notice anything let me know and i can see what i can do, same goes for if you notice any scroll jitter.

I have also thrown in a few more optimizations to the render process to smooth things out a bit further. The hoz vdom demo on the examples site is now running buttery smooth so i hope the same works for you

I have just released v 5.1.6 so these are live for you to try now.

Cheers

Oli :)

**Comment by rathboma** [comment]
Oli you are a machine! :-D.

**Comment by rathboma** [comment]
Really interesting write-up. Wish I'd had time to sit with you and watch you figure it out!

The incremental update waterfall makes sense to me, that's what it looked like in the performance charts, although I would not have been able to figure out how to fix it myself unless I had a week or two I think.

The one-row approach seems super smart and makes a lot of sense.

I'll play around with this in my test bench and in BKS. But I think we're at a point where this can go into BKS master. :tada:

**Comment by olifolkerd** [comment]
Hey @rathboma 

I would happily give you a guided tour of the hoz render some time if you would like, drop me an email if you want to arrange a time. Your detailed issue really helped, I could tell a couple of the issues just from looking at the performance graph.

I had a couple of thoughts on the renderer while I was sleeping, and i think the updates might cause issues if data is loaded into the table multiple times, so i will do a quick patch for that this eve and let you know when it is out.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@rathboma v5.1.7 has just been released that should fix the data reload issue, it could also have result in errors after sorting and filtering so deffo worth including in your update.

Cheers

Oli :)

**Comment by rathboma** [comment]
Awesome, I'm on a mini-vacation next week, but I'll email you!

I'll test 5.1.7 tomorrow. Good stuff!
