### ISSUE TITLE
Add Tabulator in the Data Grid Performance Comparison

### ISSUE THREAD

**Issue by nclemeur** [olifolkerd/tabulator#3662]
I think it would great to see how tabulator is comparing against the other grid libraries. For example this article is comparing bryntum grid to other grid solution.

So I have forked their github repo and added a test for tabulator. You can find it [here](https://github.com/nclemeur/grid-performance).

Could anyone from the team review the code in  the tabulator folder to make sure I haven't missed anything?

My first results suggests that tabulator is quite performant for the unlocked case, but there is really a big performance hit when using the locked columns module (mostly for the initial rendering which goes from about 50ms to about 2200ms on my computer).

**Comment by olifolkerd** [comment]
Hey @nclemeur 

That is a great idea, i would love to see that in there, i will take a look at the code this weekend and give you a shout.

As for your initial results, if by "locked" you are referring to frozen columns, they yes Tabulator is very inefficient there, especially since the 5.0 rebuild as it hasn't been fully migrated to the new internal event structure yet.

It is part of my plan for the 5.2 release to have a rebuild of that module as there are many inefficiencies that can be improved upon.

Cheers

Oli

**Comment by nclemeur** [comment]
Yes, locked is the equivalent of frozen in tabulator world. Maybe it's worth waiting for 5.2 before asking to integrate tabulator in the tests suite. Anyway, I'll wait for your feedback.

**Comment by nclemeur** [comment]
I used the `setData` so that I have a callback to know when tabulator has finished the updated and then stop the timer. Maybe I can use the `data` prop and then use the `tableBuilt` to stop the timer (assuming that's the right event to know when tabulator is done). I'll try that tomorrow.
Thank you for the info about the block/restore functions.

**Comment by olifolkerd** [comment]
yes, i can see why you did that, which is valid. if you went for the `data` prop then you would need to listen to the `dataProcessed` event.

see which approach is faster, i would love to know the results.

**Comment by nclemeur** [comment]
I did try the approach with the data as a prop and it was slightly faster, but the difference were not huge. By curiosity I ran the tests for ag-grid and extjs-classic on my computer,and got the following results:
![image](https://user-images.githubusercontent.com/7132890/158742520-7c9268e2-d8b0-4535-a14d-d75e0a0fa321.png)

So unlocked version is really extremely good, but the locked (frozen) is extremely bad too...

**Comment by olifolkerd** [comment]
Very interesting numbers. Great to hear it outperforms ag grid on the standard render!

Hold off untill after the 5.2 launch and the frozen column score should be much better.

I'm aiming to have 5.2 released by mid April

Cheers

Oli :)

**Comment by nclemeur** [comment]
For completeness I should probably add a link to the original [article ](https://dzone.com/articles/data-grid-performance-comparison)

**Comment by olifolkerd** [comment]
Hey @nclemeur 

I have just pushed some updates to the 5.2 branch to address some of the frozen columns efficiency issues.

They will be included in the 5.2 release later this month.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @nclemeur 

Version 5.2 has just been released. Any chance you could run your benchmarks again and see how we get on?

Cheers

Oli :)

**Comment by nclemeur** [comment]
Hello,

I have just ran the tests with 5.2 and indeed what an improvment for locked/frozen columns. Please see table below
![image](https://user-images.githubusercontent.com/7132890/164565616-204a0a96-1274-4fbc-a4a1-c07b4c9b99b2.png)

**Comment by olifolkerd** [comment]
Awesome news. Would you be ok to add these values to the comparison repo?

**Comment by nclemeur** [comment]
I have created a PR to integrate into the main repo (see https://github.com/bryntum/grid-performance/pull/3), but I don't have access to the same computer as the one they ran their test suites. So my numbers would not be really comparable. Hopefully they'll do it when they integrate that PR...

**Comment by olifolkerd** [comment]
Hey @nclemeur 

Turns out the bable transpilation was slowing down the UMD versions of Tabulator hugely, If you were running the tests against the tabulator.min.js file then it may be worth running them again on the latest release, it is about 8 times faster at loading data.

I have also completely rebuilt the frozen columns module so it is based on `sticky` positioning so it is much more performant too.

Cheers

Oli :)
