### ISSUE TITLE
pagination row counts incorrect whne using groups

### ISSUE THREAD

**Issue by DuredhelFinceleb** [olifolkerd/tabulator#3672]
**Describe the bug**
I'm using a custom footer to display pagination information like: "Rows 50 to 60 out of 100"
It works very well including when using filters.

But it breaks with grouped data. Let's say I've got 20 rows in 10 groups of 2 rows, the table will display 30 rows
But since the group headers are not counted as rows by Tabulator API, my pagination information quickly become wrong with things like "Rows 21 to 30 out of 20"

**Tabulator Info**
- version 4.9.3

**Working Example**
https://jsfiddle.net/r9kzd5p4/11/

**To Reproduce**
Just run the fiddle and look at the custom footer in the lower left of the table

**Expected behavior**
I expected group header rows to be counted out
So intead of getting "Rows 21 to 30 out of 20" I would have gotten "Rows 14 to 20 out of 20"

**Screenshots**
![image](https://user-images.githubusercontent.com/9292585/159330597-aa5562d8-b4bd-4ee0-a2ca-6ec6f651c45a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browsers: FF 98, FF developer Edition 99, Chrome 99, Egde 99

**Smartphone (please complete the following information):**
 - Not tested on smartphones

**Comment by olifolkerd** [comment]
Hey @DuredhelFinceleb 

You are using a rather old version of Tabulator there, the 5.1 release comes with the built in ability to add the counters at the bottom of the row.

This isn't an issue with Tabulator because it is rendering correctly, this issue is with how you are counting the rows that are available, which is a complex issue when pagination and grouping are run together.

I would suggest you look at the [Pagination Counter Docs](http://tabulator.info/docs/5.1/page#counter) for how to handle this correctly.

Cheers

Oli :)

**Comment by DuredhelFinceleb** [comment]
Thanks for your answer.
I've tested with v5.1.7 and indeed there is a working counter here.
Currently I'm stuck with 4.9.3 though, migrating to 5+ will have to wait. 
So for the time being, I'll postpone this for when we migrate to 5+
Currently we use a custom equivalent of v5+ paginationCounter:"pages" that works very well so we'll live with that.
Thanks again!
