### ISSUE TITLE
Custom Buttons on tabulator footer

### ISSUE THREAD

**Issue by arelbernardo** [olifolkerd/tabulator#368]
Hi Oli,

I just want to ask if there's a feature that can add a custom button on tabulator footer like on this image highlighted by red box:

![image](https://user-images.githubusercontent.com/22093815/27174714-9f469afa-51ef-11e7-82d1-841b5fd22da9.png)

Thanks!

**Comment by olifolkerd** [comment]
Hey,

I have just added the ***footerElement*** config option to the 3.1 branch.

This will give you the option to define a custom footer element and add your own controls to it (or to define it else where in your document and have it pulled into the table):
```js
$("#example-table-demo").tabulator({
    columns:[...],
    pagination:true,
    footerElement:$("<div class='tabulator-footer'><span>Custom Span With Stuff In</span></div>"),
});
```

There will be a production release of 3.1 by the end of the weekend, but feel free to have a play with the 3.1 branch in the mean time.

Cheers

Oli

**Comment by Praveene7** [comment]
Hi  oli
![tabulator](https://user-images.githubusercontent.com/20556109/30029166-bad119ee-91a5-11e7-911f-144224235ae6.JPG)
,
I want to show sum of value on footer.
please give some example for footer element

**Comment by olifolkerd** [comment]
Hey Praveene,

You want to use column calculations to acheive that, have a look at the [Column Calculations Example](http://olifolkerd.github.io/tabulator/examples/#calculations) on the website.

Cheers

Oli

**Comment by Praveene7** [comment]
Hi Oli,
I have used column calculation but didn't show the column calculation row bottom or top on tabulator.
This is my tabulator code 
[tabulator.txt](https://github.com/olifolkerd/tabulator/files/1276220/tabulator.txt)

**Comment by olifolkerd** [comment]
which version of Tabulator are you using?

**Comment by Praveene7** [comment]
3.2

**Comment by BillMeyerRSA** [comment]
Using version 4.4
The code above 
`    footerElement:$("<div class='tabulator-footer'><span>Custom Span With Stuff In</span></div>"),
`
does not work. Actually table disappears. 
Would like to do a custom button at the bottom that can take filtered table and launch a chart window using button at the bottom. 

In online documentation I get this 
`footerElement:"<button>Custom Button</button>"`
but cannot get a function to be launched with it.

**Comment by pickleboy0214** [comment]
I know this is closed but thought I would post anyways since this came up on Google first. Here is one way to do it using version 6.3 but I think it could work all the way to at least version 5.0.

if you update the online doc version to include the id attribute, then you can assign the click event to the button after the table is built.

HTML:

`footerElement:"<button id='myButton'>Custom Button</button>"`

Then add your javaScript:


```
table.on("tableBuilt", function () {
  //Grab button and assign a click
  const button = document.getElementById("test")

  button.addEventListener("click", function () {
    // Code to execute when the button is clicked
    console.log("Button clicked!")
  })
});
```

Here's a [JS Fiddle](https://jsfiddle.net/bsunderland/m25zvqsa/41) . 

Note: I haven't tested it with any other versions, I just remember 5.0 being a big change for events.

**Comment by pickleboy0214** [comment]
I know this is closed but thought I would post anyways since this came up on Google first. Here is one way to do it using version 6.3 but I think it could work all the way to at least version 5.0.

if you update the online doc version to include the id attribute, then you can assign the click event to the button after the table is built.

HTML:

`footerElement:"<button id='myButton'>Custom Button</button>"`

Then add your javaScript:

```
table.on("tableBuilt", function () {
  //Grab button and assign a click
  const button = document.getElementById("test")

  button.addEventListener("click", function () {
    // Code to execute when the button is clicked
    console.log("Button clicked!")
  })
});
```
Here's a [JS Fiddle](https://jsfiddle.net/bsunderland/m25zvqsa/41) .

Note: I haven't tested it with any other versions, I just remember 5.0 being a big change for events.
