### ISSUE TITLE
Conflict checkbox to select row and selectable Check property

### ISSUE THREAD

**Issue by verdonfly** [olifolkerd/tabulator#3684]
**Describe the bug**
By selecting the rows using the checkbox in the header of the table, the rows that do not meet the condition in the "selectableCheck" property are also selected, selecting all the rows anyway

**Tabulator Info**
latest 5.1.7

**Working Example**
https://jsfiddle.net/verdonfly/mjptn98d/6/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1) press the checkbox in the header to select the rows
2) you will see that the rows that do not respect the rule of the "selectableCheck" property are selected, then the rows with "age" <18 are also selected

**Expected behavior**
I expect the defined rule to be respected also by selecting the rows with the checkbox

**Screenshots**
![image](https://user-images.githubusercontent.com/49061831/161264735-ec44bc37-7a07-4ca8-be5e-e3d4c41658ca.png)

![image](https://user-images.githubusercontent.com/49061831/161264496-e7faa0d9-a8e1-4170-bacb-531f9c7ea22b.png)

**Additional context**
if I activate the "selectable: true" property, it allows me to select the rows by clicking on the row and the rule is respected.

**Comment by olifolkerd** [comment]
I would consider this to be a mis use case, when presenting  checkboxes to a user all rows should be selectable otherwise it makes for terrible UI.

The primary purpose of the selectable check is for when there are no checkbox columns and you are doing row selection by click.

Without explanation as a user i would get the impression the table was broken if i clicked the select all option and all the rows werent selected.

Cheers

Oli :)

**Comment by verdonfly** [comment]
@olifolkerd I understand what you mean, in fact in my case I use the rowformatter to hide the row checkbox according to my condition.
