### ISSUE TITLE
rowMouseLeave event emits incorrect row when moving between cells on 

### ISSUE THREAD

**Issue by ajrnz** [olifolkerd/tabulator#3689]
(Great library - thanks!)

Reproduction: 

https://jsfiddle.net/ajrnz/kxyej64o/6/ (check the console)

* Hover on a cell - the enter event fires correctly
* Now move up or down without exiting the table - the leave event fires on the destination cell, not the one we are leaving

Exiting the table works as expected

v5.1.8

**Comment by blankbadge** [comment]
I encountered the same issue upon upgrading from 4.6 to 5.1.8 yesterday.  Here is my fiddle, it shows the exact same issue.  When mousing from one row to the next, rowMouseLeave is operating on the row that I'm entering instead of leaving.  If moving the mouse from a row to an area off the table (not another row), it works as expected, operating on the row that I'm leaving.

https://jsfiddle.net/blankbadge/1r75vzsy/10/

**Comment by olifolkerd** [comment]
Hey @ajrnz 

Thanks for the headsup.

I have pushed a fix for this to the 5.2 branch and will include it in the release later this month.

Cheers

Oli :)
