### ISSUE TITLE
Add responsiveCollapse event to allow for control of formatting when table layout changes

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3691]
**Describe the bug**
use layout fitDataStretch doesn't work when responsiveLayout: "hide" is active

**Tabulator Info**
5.1.8

**Working Example**
https://codepen.io/lekoalabe/pen/JjMLLgb

**To Reproduce**
Click on the link and check the console

**Expected behavior**
The table loads

**Desktop (please complete the following information):**
Chrome Windows (latest)

Note: this is not a big issue, just stumbled upon it when testing various options and reported it while at it ;-)

**Comment by olifolkerd** [comment]
This happens because the layout is only triggered when the data in loaded into the table, not on every update as this would be inefficient.

I would not be looking to change this behaviour, but i can look at adding a ***responsiveCollapse*** event to the table so that you could trigger a redraw when the column configuration changes if that is your desired behaviour.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @lekoala 

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)
