### ISSUE TITLE
Header filter autocomplete dropdown list open direction

### ISSUE THREAD

**Issue by bornova** [olifolkerd/tabulator#3711]
**Describe the bug**
Header filter autocomplete dropdown list opens to the top of filter input box instead of bottom.

**Tabulator Info**
- Which version of Tabulator are you using? 5.2.1

**Working Example**
https://jsfiddle.net/09mn3cxL/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/09mn3cxL/
2. Click inside Name header filter input box
3. The dropdown list opens to the top of filter input box

**Expected behavior**
The dropdown list should open to the bottom of filter input box

<img width="753" alt="Screen Shot 2022-04-22 at 2 25 37 PM" src="https://user-images.githubusercontent.com/35872220/164797300-7e851245-ac3a-47d5-a33d-f4b6abc3c61b.png">

**Comment by olifolkerd** [comment]
This is happening because of in propper setup of the containing element for the table and the use of margins.

The phenomenon is known as [Collapsing Margins](https://www.sitepoint.com/collapsing-margins/) and is happening because of the way that margins are calculated by the browser. By adding a margin to the top of the first element in the body the margin is collapsed and moved to above the body. this breaks the calculations that determine if the element can still fit in the space as it cant then accurately determine the available space left in the containing element. essentially detecting the top margin from the bottom of the element.

By default Tabulator uses the page body element to calculate the position of the modal relative to the body, which in this case works but then because of that top margin the calculation is then broken because it cannot correctly detect the available space in the container because the collapsed margin takes the space that should be inside the body and moves it outside.

In reality i dont think this scenario will come up very often ass the body would usually have padding, and the table would very rarely be the first element in a page nor have that much artificial margin above it.  it is just a artifact of the demonstration.

The correct procedure in this instance would either be to prevent the margin collapse on the container element, or to change the container element for the popups, in your usage case changing it to be the table itself would work best:

```js
var table = new Tabulator("#example-table", {
    popupContainer:true
});
```

Cheers

Oli :)

**Comment by bornova** [comment]
Thank you for the detail explanation! `popupContainer:true` does what I need.
