### ISSUE TITLE
Replace Data Causes memory leak

### ISSUE THREAD

**Issue by sakib1361** [olifolkerd/tabulator#3714]
Replacing 100 elements from 500datas in the grid causes high memory usage over time. It also has a high cpu usage. 

**Tabulator Info**
5.2.2

**Working Example**
https://jsfiddle.net/937hmzwf/
[tabulator_bench.zip](https://github.com/olifolkerd/tabulator/files/8552845/tabulator_bench.zip)

**To Reproduce**
Run the html code and observe in task manager. 

**Expected behavior**

**Desktop (please complete the foll
 - OS:Windows 11
 - Browser Chrome
 - Version 100.0.4896.127

**Comment by olifolkerd** [comment]
The issue is you are using the wrong function there,

for replacing data in situe like that you should be using the ```replaceData``` function, which will prevent any memory leaks.

Also for your own debugging in future, cosider using the performance tab of the browser debug tools, it give more accurate info per  browser process than the windows task manager.

Cheers

Oli :)
