### ISSUE TITLE
Is it possible to hide arrows and still sort?

### ISSUE THREAD

**Issue by dakuwan** [olifolkerd/tabulator#372]
I have a pretty packed table, lots of columns, and if i cut sorting off and make the sorting arrows disappear the whole table fits in the area i need it.  If i leave the arrows (sorting) in then some columns get cut off the end.  Is it possible to still have clicking the headers sort but not show the arrows next to the header text?

Thanks

**Comment by scooterbelasco** [comment]
Did you try just doing it via css?

```
.tabulator .tabulator-header .tabulator-col[data-sortable=true] .tabulator-col-title {width: 100%;}
.tabulator-arrow {display: none;}
```

**Comment by dakuwan** [comment]
Good idea.  I had thought of digging into the css but was hoping maybe it was a setting so that I could turn it on and off depending on the page/table.  This does work though so will do that for now. 

Thanks for the suggestion.

**Comment by olifolkerd** [comment]
@scooterbelasco has the correct idea there, CSS is the only way to remove the arrows and keep the header click sorting functionality

**Comment by E3V3A** [comment]
@scooterbelasco  
I just tried this, and the arrows doesn't go away.
Any ideas?

**Comment by olifolkerd** [comment]
There have been updates since this, please have a look at the answer to your original question in issue #861

**Comment by mspinaci** [comment]
Sorry to reopen this many years later, but while the proposed solution indeed removes the triangle, I think it doesn't solve the original issue: now there is just an empty space where the triangle should be. The text is still replaced by ellipses for a much shorter width than it could use. This is the default image, with width manually adjusted so that the "upselling" text on the second line just fits. Looks good because you need that space for the triangle:

<img width="119" alt="Screenshot 2024-06-13 at 13 25 50" src="https://github.com/olifolkerd/tabulator/assets/32176505/dbf74249-dc7c-4b7d-8c85-8fe0ed713063">

Adding the proposed CSS changes indeed the triangle is not there anymore, but the space is just the same (again, I've manually set the width to adjust for the second row; you can see that the first one gets truncated at the same place, leaving lots of space where in fact the whole "KDDCup09" word could fit)
<img width="121" alt="Screenshot 2024-06-13 at 13 23 07" src="https://github.com/olifolkerd/tabulator/assets/32176505/d67f2c2c-e160-4703-b21c-f9612772dba6">

Is there a way to make it fit more adequately?

(sorry if this is just a matter of a simple CSS options, I'm really not into web development...)
