### ISSUE TITLE
Unstable clientHeight cut off rows

### ISSUE THREAD

**Issue by chumaltd** [olifolkerd/tabulator#3720]
**Describe the bug**

Hi, when I use PageModule under Preact / Redux framework, not all rows are rendered.

With `paginationSize: 100`, it shows only 20 rows on a typical case.
I think 20 comes from `vDomWindowMinTotalRows`.

After I tried several workarounds, 
it looks that `clientHeight` from actual DOM returns unreliable value at timing:

* Additional operation like switching to next page recovers full rendering.
* If I set CSS `height` to root DOM for the table, it renders more rows like 52.
* RowManager sets `height: 1px` to `.tabulator-tableholder` in the same context,
  which `<style>.tabulator-tableholder { height: auto!important }</style>` can override.

Without PageModule, full rows are rendered.

**Tabulator Info**
v5.2.2

**Working Example**

The following patch works for me:
https://github.com/chumaltd/tabulator/commit/2efb6a26e4424ac5bd0670bcff10d1185d9a07dc

Paging module handles rows precisely, so skip additional check solves this issue.
I don't think this covers all configuration.

My configulation is as follows:

```
Tabulator.registerModule([FormatModule, InteractionModule, PageModule, ResizeColumnsModule, SelectRowModule, SortModule, TooltipModule]);

        const table = new Tabulator(node.current, {
            rowHeight: 30,
            pagination: true,
            paginationSize: 100,
            selectable: true,
            columnDefaults: {
                resizable: "header",
            },
```

**To Reproduce**

I just rebuilt dist. You can compare.

https://github.com/chumaltd/tabulator/tree/master/dist/js

Note: I upgraded node-sass and rollup-plugin-postcss for newer Node compatibility.

**Expected behavior**

All rows supplied by PageModule should be rendered.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium
 - Version 100

**Additional context**

For my case, patched version above works well.
It's not urgent.

Thanks!

**Comment by olifolkerd** [comment]
Hey @chumaltd 

The issue is likely that you DOM layout is not fixed before the table is rendered, ie, fonts are loading that change the size of the rows after the render is started, or that the relationship between the table and its container element is not setup correctly.

Your proposed solution may fix your particular render issue but would totally break the virtual render when in virtual DOM mode which is the vast majority of usage cases.

In order to help you with this i would need to see a working JS fiddle that demonstrates the issue, without seeing it in action with the original Tabulator code it is not possible to pin point the issue. but in most cases this is due to layout issues outside of the Tabulator element that cause the layout calculations to fail.

Cheers

Oli :)
