### ISSUE TITLE
Key binding issue with Alt key combination

### ISSUE THREAD

**Issue by rakshithns** [olifolkerd/tabulator#3734]
Bug Description:

The key binding events associated with the combination of any key with alt key tries to trigger the event even with any one of the key in the combination is pressed after holding the alt key for some time. So once the alt key is released the tabulator remembers that the alt key is still pressed even though the key was released.

Tabulator version:
5.2.3

Working Example:
https://jsfiddle.net/42v1umsj/

Steps to Reproduce:

1. Create a key binding with a combination with alt key. In above example its alt key + arrow up key("test": "18 + 38").
2. Click on the table and press alt key plus arrow and hold the alt key for some time (5-10 seconds) and release it. You can see the the event "test" is getting triggered.
3. Once you release the alt key, try pressing the arrow up and you see the event "test" is still getting called and it seems like tabulator still remembers the alt key pressed even though it is released.

Desktop Details:
OS: Windows 10
Browser: Chrome

**Comment by olifolkerd** [comment]
Hey @rakshithns 


That is not a vaild Tabulator keybinding. Tabulator only supports use of the `ctrl`, `shift` and `meta` keys with the `+` syntax, because these are passed into the keydown event with a normal key press. The keybinding does not have the functionality to look for a combination of other keys.

I will clarify this in the documentation.

On the whole i would advise against using alt key combinations in the browser, these keyboard combinations are usually used to control app level functionality and in the context of a website that usually means the browser itself rather than the site it is showing.

Cheers

Oli :)
