### ISSUE TITLE
some rows not displayed with height: 100% and remote pagination

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3735]
**Describe the bug**
When navigating between page, if the height is fixed to 100% (as recommended here http://www.tabulator.info/docs/5.2/layout#height-fixed) large space will remain empty (where actual rows should be)
This only happens if you need to scroll to actually see the table footer content (=> if paginationSize is set to a high number)

**Tabulator Info**
5.2.3

**Working Example**
https://codepen.io/lekoalabe/pen/PoQPYVp

**To Reproduce**
scroll down and navigate to a page

fun fact: if i'm zooming (eg 90%, when i tried to take a screenshot), it's working fine. so maybe it's because the browsers try to be smart and does not paint anything or it's the vdom acting strange?

commenting height: 100% also fixes the issues with no noticeable change so maybe these options are not compatible

tested with chrome & edge

**Expected behavior**
all rows being drawn or document height:100% not being compatible/being useless with remote pagination

**Comment by lekoala** [comment]
@olifolkerd and while at it, I added some new styles in the codepen. I know taste is a personal matter, but you can check if some of it make sense to be added for all.
i think things like cursor:pointer for responsive toggle for example
i also quite like my solution for the loading alerts, i fade the background to show activity and delay the alert a little bit. if the server respond swiftly, it's a much nicer experience imho (but i know that's up to everyone personal taste)

**Comment by olifolkerd** [comment]
@lekoala Thanks for the info, i will look into that this weekend.

With regard to the styling, the whole point of the bootstrap theme is that is uses the standard bootstrap styling and classes so that it matches in with the framework. And while i agree that your styling looks nice, that is not the purpose of the theme, in order to be effective it must exactly match the bootstrap default styles.

And by all means customize the styling of the alerts for your usage case, but the default styling and functionality of Tabulator tries to be as unopinionated as possible to allow developers to customize their apps to meet their needs, i would far rather provide a simpler option by default that developers can then customize, than add a complex solution that needs to be worked back.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
@lekoala 

This is happening because you have specified both a table height and a page size, you should only specify one or the other, as you are using remote pagination i suggest leaving out the height on the table.

Could i ask that when you create a bug report, you make your JS Fiddle with a [Minimal Reproducible Example](http://www.tabulator.info/community/mre), The one linked to from this issue had so many setup options it was hard to wee the wood for the trees.

Cheers

Oli :)

**Comment by lekoala** [comment]
@olifolkerd ok so maybe the issue is just that it's not compatible^^ the solution is probably some clear indication in the docs or even a console warning saying these options do not work well together
