### ISSUE TITLE
Issue at selectRow

### ISSUE THREAD

**Issue by heliocj** [olifolkerd/tabulator#3757]
I'm trying to implement that selectRow but that doesnt working even with the example on your Tabulator documentation. 

When you click on Select Oli Bob that's console the error: "Selection Error - No such row found, ignoring selection:1". If you click on that Select All that gonna work.

Tabulator 5.2

https://jsfiddle.net/nzb9425w/1/

**Comment by olifolkerd** [comment]
That is because you do not have an index field set in your row, by default this is the `id` field. so it is correct in saying there is no matching row, have a look at the [Row Range Lookup Docs](http://tabulator.info/docs/5.2/components#row-lookup) for full details of acceptable values.

Cheers

Oli :)
