### ISSUE TITLE
headerFilter = true not supported anymore ?

### ISSUE THREAD

**Issue by MarcFlynn** [olifolkerd/tabulator#376]
With Tabulator 2.11 I was using headerFilter = true.
This is still in the documentation but don't seems to work anymore.
headerFilter = "input" is working, but does not support the "select" filter behaviour.
Is there a way to get back the  "select" filtering ?

**Comment by olifolkerd** [comment]
The headerFilter = true system should definitely still be working.

Could you post a copy of your Tabulator constructor object so i can test against it.

Cheers

Oli

**Comment by MarcFlynn** [comment]
A part (the list of columns) is generated dynamically from a DB, so this is not easy to extract.
Time to sleep... (Belgium) I'll try this tomorrow.
Good night
Marc

**Comment by olifolkerd** [comment]
If ***headerFilter*** is set to true it will use the same editor that is defined in the ***editor*** option. if an editor isn't set then it wont work.

There is no inbuilt ***select*** editor in Tabulator, you would need to define your own custom editor. see [Editing Data Documentation](http://olifolkerd.github.io/tabulator/docs/3.0/#manipulating-data) for more info.

If you look in your browsers dev console Tabulator should be producing warnings that will let you know where the issue is.

Im afraid without an example of a column definition i wont be able to diagnose your issue.

**Comment by MarcFlynn** [comment]
Hi Oli,
I found my mistake.
My selectEditor was old fashion.
I realign to the new specifications and my issue is gone.
Thank you for the hints.
Kind regards,
Marc
