### ISSUE TITLE
List Editor multiselect blur issue and Bulma CSS

### ISSUE THREAD

**Issue by mikeciz** [olifolkerd/tabulator#3762]
**Describe the bug**
The built-in list editor does not fire the cellEdited consistently when 'multiselect' is true. See the "Cheese" column in the jsfiddle.  After you select one or two cheeses, clicking outside the input cancels the edit from the looks of it. 

(bonus minor bug -- the bulma css has some issues with list style. The input background is missing)

**Tabulator Info**
Tabulator v5.2.4

**Working Example**
https://jsfiddle.net/mikeciz/w07tdjqz/6/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to the "Cheese" column
2. Click on an empty cell to select one or two cheese
3. Click outside the input to confirm your edit and close the dropdown
4. Most, but not all the time, the edit is cancelled.  I assume this is due to a blur?!

**Expected behavior**
I would hope that a multiselect = true would fire the cell edited once you were complete

**Screenshots**
Bulma CSS issue:
<img width="290" alt="Screen Shot 2022-05-20 at 12 11 00 AM" src="https://user-images.githubusercontent.com/3874665/169450433-6028a280-8c05-4b31-ad88-8ffa78b95d93.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: Monterray

**Comment by olifolkerd** [comment]
Hey @mikeciz 

Thanks for getting in touch, sorry to hear you are having trouble, there were some issues with the list editor and multiselect that should hopefully be fixed in this evenings release.

I will also include a fix for the bulma styling issue in this release.

Could i ask that you report multiple issues in separate github issue, it is very hard to track progress fixing issues if people combine them.

Cheers

Oli :)

**Comment by mikeciz** [comment]
Thanks Oli!  My apologies for reporting two items in a single issue.  Love the work you are doing my friend!!
