### ISSUE TITLE
Responsive collapse toggle show unwanted scrollbars

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3771]
**Describe the bug**
When the table has no fixed height, there should be no vertical scrollbar. With the responsiveLayout: "collapse", clicking on the toggle will show a vertical scrolbar
(and sometimes, also show a horizontal scrollbar)

**Tabulator Info**
5.2.4

**Working Example**
https://jsfiddle.net/3jL4gt2s/1/

**To Reproduce**
- Click on the toggle
- There is a vertical scrollbar that appears

Bonus issue:
- There is a horizontal scrollbar as well

**Expected behavior**
As there is no fixed height, the whole table should simply expand when clicking on the toggle.

Bonus behaviour:
- There is no need for the horizontal scrollbar

**Additional context**
Related PR
https://github.com/olifolkerd/tabulator/pull/3752#issuecomment-1132922771

Probably related issue
https://github.com/olifolkerd/tabulator/issues/3768

**Comment by olifolkerd** [comment]
Hey @lekoala 

Can you confirm that you are saying that when you expand the element and the vertical scroll bar appears that you are unhappy that the horizontal scroll bar appears too?

This is because the width of the table has not changed, therefor the columns have not resized, which means that part of the columns is hidden by the vertical scrollbar therefore there is horizontal space behind the vertical scroll bar and so a horizontal scroll bar is needed. If it was to resize the columns to accommodate the scroll bar you could end up in a resize loop where columns flicker in and out of responsivity collapse as the scroll bars come and go, which would be extremely undesirable.

Just as a quick headsup, you dont need to include both the tabulator.css and the tabulator_bootstrap5.css. you only need the one CSS file for your theme.

Cheers

Oli :)

**Comment by lekoala** [comment]
@olifolkerd I've updated the jsfiddle, and I don't think this quite solve the issue

https://jsfiddle.net/3ohz710a/1/

Clicking on the data should simply expand the table, there is no need for scrollbars in the first place since i don't want a fixed height. I've tested again with height 100% and it seems fine (no scrollbars).

I don't think it's really related to the collapse toggle itself, it's rather the fact that a height is set even if I didn't set one, and there is no way to avoid that (both renderers use the fill mode which set a height).

In the meantime setting height 100% seems to do what I need so I'll go with that :)

**Comment by olifolkerd** [comment]
Hey @lekoala 

Thanks for the clarification, when it has no height it uses a different renderer from standard. I can have a look into this further, it will just need to be a small tweak to the formatter. which i can include in the next patch release.

What i would say is that the "classic" render mode doesn't use a virtual DOM and so all rows are handled in the browser, if you are dealing with a lot of rows this will result in a performance hit for your application and i would recommend setting a height or maxHeight.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @lekoala 

Following on from the PR merge this will be resolved in the 5.3 release in a couple of weeks time. Sorry for the mixup, i had got really confused what that PR was fixing.

Cheers

Oli :)
