### ISSUE TITLE
List editor with freetext not retaining existing data when clicked

### ISSUE THREAD

**Issue by shinseiryu** [olifolkerd/tabulator#3776]
Prior to updating to v5.x from 4.8, the select (now list) editor retained data in the cell when the user clicked into the cell as if to being editing it.  Now, when using autocomplete, freetext, pre-defined values, if the data in the cell is not a member of the pre-defined values, the data is cleared out once the user clicks into the cell.  Sometimes we click into the cell so that we can copy a portion of the data to paste elsewhere.  Location field in the example below has been setup to mimic this behaviour

Using version 5.2.4

https://jsfiddle.net/5ztaL890/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Click any of the location cells.
2. Change the location to one that is not in the list like "freetextexample"
3. Exit the cell by tabbing or clicking another cell.
4. Click the location cell with "freetextexample" to enter editing mode of the field.

**Expected behavior**
Data is not cleared from the field when entering edit mode of a list cell with freetext enabled.

**Screenshots**
Screenshots uploaded here:
https://imgur.com/a/7qaoUZb

**Desktop (please complete the following information):**
 - OS: MacOS 12.4 and Windows 10
 - Browser: Chrome
 - Version 102.0.5005.61 (Official Build) (arm64) as well as x86 chrome on windows 10

**Comment by christianitis** [comment]
This is happening to me as well

**Comment by creativecontrol** [comment]
I also have the same issue. I have found that if you press ESC the data returns. However, if you remove focus from the field by clicking somewhere else on the page the data is erased.

My use case is a dynamic list of available IP addresses. Since a selected address is removed from the autocomplete list it now seems to be erased when reselecting the cell since it doesn't match something in the list. This is not the same behavior as in version 4.*

**Comment by olifolkerd** [comment]
Hey All,

I have pushed a fix for this to the master branch and will include it in sundays patch release.

Cheers

Oli :)
