### ISSUE TITLE
Tabulator logs errors like crazy when Vue Devtools is used

### ISSUE THREAD

**Issue by rathboma** [olifolkerd/tabulator#3778]
I think Vue Devtools pokes at objects to see if they are Vue components, but doing so triggers the `handle` function in tabulator that listens for method calls and dispatches to plugins.

The result is two fold:
1. The console fills up with errors
2. Tabulator performance tanks as it spins on this while you interact with the table

Screenshot:

![image](https://user-images.githubusercontent.com/279769/170726970-ec3bdee2-00d1-465f-a8d1-c1c08baecb6a.png)

**Comment by olifolkerd** [comment]
Hey @rathboma 

Is this a vue 3 thing? i use vue 2 all the time and have never come across this one.

I specifically added exceptions to the warnings for functions that started with an "_" when 5.0 was launched because it caused these issues with vue 3 but when i made that changed the community told me it was fixed. so it would appear that something else is happening now.

Is there a way to setup a JS fiddle that replicates this (im not a vue3 user), has changed in the way vue works in a recent release, i would find it very odd if this has been happening since the 5.0 release 5 months ago and no one had brought it up by now if it slows things down and fills the console with errors, i know tabulator has a lot of Vue users, and quite a few on Vue 3 because i have addressed other issues related to vue.

Not much has changed in the proxies since the 5.1 release so i would find it odd that something has just sprung up.

If we can get to the bottom of the route cause im sure there will be a way to handle it, either by detecting the vue or allowing exceptions to the messaging for those props. Im reticent to remove the functionality as it has certainly helped out users since the move to 5.0 because Tabulator now comes without modules as standard and i have recevied many responses that this warning has helped people out.

Cheers

Oli :)

**Comment by rathboma** [comment]
This is Vue 2 actually. It only happens when I inspect a component containing a Tabulator stored as a data field in the component

**Comment by olifolkerd** [comment]
Oh I know it is from 5.0 that is where the component proxies where added which contain the error.

I use Tabulator and Vue 2 loads and have never come across this. What steps do I need to take to trigger these messages?

Are you talking about the Vue debug tools chrome extension? I can't seem to replicate this in my browser. Any chance you could do a video what u do to trigger the error.

And yeah I can certainly add an option to disable the messages as I have for other warnings. That won't be an issue

Cheers

**Comment by rathboma** [comment]
Yes, it's with the vue debug tools, let me record a screencast quickly

**Comment by rathboma** [comment]
https://user-images.githubusercontent.com/279769/170774044-39fcdf59-094f-47f2-96f1-362cc298c061.mp4


https://user-images.githubusercontent.com/279769/170774062-98a29414-c8f7-4393-9079-47060b9a98a2.mp4

**Comment by olifolkerd** [comment]
Hey @rathboma 

Do you have an example of your table constructor, i cant seem to get this logging to happen?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @rathboma 

I have pushed the new `debugInvalidComponentFuncs` option to the 5.3 branch to hide these warnings, this should be out in a couple of weeks.

Cheers

Oli :)
