### ISSUE TITLE
sync `downloadReady` and `Blob` data

### ISSUE THREAD

**Issue by reviewher** [olifolkerd/tabulator#3784]
**Is your feature request related to a problem? Please describe.**

The `downloadReady` callback function receives a `Blob` and is expected to return a `Blob` or `false`.  For browser-side post-processing of the export, the methods to recover an `ArrayBuffer` from the `Blob` are not synchronous: either a `FileReader` must be used with callback or a promise-based method like `await blob.arrayBuffer()`.

**Describe the solution you'd like**

Since the underlying download libraries generate `ArrayBuffer`s or `Uint8Array`s or strings, make `downloadReady` receive an `ArrayBuffer` with the contents.  The `Blob` generation should be moved to the actual download action.

**Describe alternatives you've considered**

Alternatively `downloadReady` could be made async (return a promise that resolves to `false` or the `Blob`) or callback-based (pass a callback that the function would have to call).

**Comment by olifolkerd** [comment]
Hey @reviewher 

Could you explain a little more about why this feature would be needed? in your usage case it suggests you should be using a custom downloader function. Which is where the responsibility for generating file contents resides

Cheers

Oli :)

**Comment by reviewher** [comment]
The custom downloader function would effectively repeat the exact implementation of the existing downloader function with some minor adjustments at the end.  That's *a* solution but it seems brittle and non-DRY to reimplement the functionality that exists in the library.

**Comment by olifolkerd** [comment]
Hey @reviewher 

Sorry maybe i wasn't clear in my last response. could you explain why you need the feature you have requested, what actual purpose are you trying to achieve, what data are you trying to transform?

The reason I ask is that from your explanation it looks like you my be trying to use a function for a purpose other than its intended use. if that is the case it would be better if I could then explain the intention for how the download system should be used so that you can adapt to Tabulators paradigm rather than me forcing a function to do something it wasn't intended to.

As I mentioned above, within Tabulator it is the downloaders that are responsible for generating content for files, and the `downloadReady` function allows for intercept primarily if you want to override the default download behaviour and route the content elsewhere. If that is not how you intend to use that function then there is probably a better approach that will get you what you need.

If you have found a usage case that is not covered by the existing mechanic then i would of course be happy to make a change, but i cant do that unless i understand why the requested change is needed with a practical example.

Cheers

Oli :)

**Comment by reviewher** [comment]
For example, [you can override the DSV separator for Excel using the `sep=` pragma.](https://en.wikipedia.org/wiki/Comma-separated_values#General_functionality)

Adding that pragma is not supported by Tabulator's CSV export.

If `downloadReady` actually provided an `ArrayBuffer`, it would be easy enough to fix the output before generating the download.  But the shape of the function precludes an easy solution.

FWIW the downloaders and the actual download action are "simple" to reimplement, but they may change over time.

**Comment by olifolkerd** [comment]
Hey @reviewher 

I have just pushed an update to the 5.3 branch (released in a few weeks) that adds the new `downloadEncoder` callback that will function as discussed above.

Cheers

Oli :)
