### ISSUE TITLE
Fixed Table Headers Transparent with Bootstrap 5.2

### ISSUE THREAD

**Issue by VictorioBerra** [olifolkerd/tabulator#3785]
**Describe the bug**
When using tabulator and fixed headers with Bootstrap 5.2, the headers are transparent and overlap.

**Tabulator Info**
5.2.6

**Working Example**
https://codepen.io/SloppyCoder2745/pen/eYVKpXz

**Resize your window so that the table has a horizontal scrollbar.**

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://codepen.io/SloppyCoder2745/pen/eYVKpXz
2. **Resize your window so that the table has a horizontal scrollbar.**
3. Notice headers are behind eachother

**Expected behavior**
Headers should have a solid background.

**Screenshots**
![image](https://user-images.githubusercontent.com/2934507/171686301-696630cb-b19b-4cd5-86c3-f22a5c07ce0e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lekoala** [comment]
probably the same issue, but with sticky headers, i need to set a background because it's transparent as well

**Comment by olifolkerd** [comment]
Hey @VictorioBerra 

This happened because the default table background colour in bootstrap is transparent. i have updated the theme to default to using the built in grey shades that do not use transparencey to resolve this issue.

I have pushed this fix to master and will include it in the patch release tomorrow.

Cheers

Oli :)
