### ISSUE TITLE
Not working in modal div

### ISSUE THREAD

**Issue by VidhyaApple** [olifolkerd/tabulator#38]
![selection_015](https://cloud.githubusercontent.com/assets/7392482/16232928/12fc3eda-37ea-11e6-85c9-28708d7641d7.png)
Am trying to populate table into the bootstrap modal, but it is not working out. Without bootstrap modal, it is working fine. 

```
$("#tabulator_table").tabulator({
       	fitColumns:true,
      	columns:[ //Define Table COlumns
	        {title:"name", field:"name",sortable:"false"},
	  ],
	}); 
	//load sample data into the table
	$("#tabulator_table").tabulator("setData",[
    {id:1, name:"Billy Bob", age:"12", gender:"male", height:1, col:"red", dob:"", cheese:1}, ]);
```

```
<div class="modal fade">
    <div class="modal-dialog">
         <div class="modal-body" id="tabulator_table"></div>
    </div>
</div>
      
```

**Comment by olifolkerd** [comment]
That is because you are building the tabulator while the modal is hidden and so tabulator cannot calculate its widths and heights properly as the element has no size.

To fix this, call the ***redraw*** function when you display your dialog:
```js
$("#example-table").tabulator("redraw")
```

[full documentation on this can be found here](http://olifolkerd.github.io/tabulator/docs/#layout)
