### ISSUE TITLE
hiding groups does not work properly

### ISSUE THREAD

**Issue by maku** [olifolkerd/tabulator#3821]
**Describe the bug**
When I iterate over the groups of a Tabulator instance and call the "hide" function for every group ALL groups should be hided. But it only effects the first group.

**Tabulator Info**
Version 5.2.7

**Working Example**
https://jsfiddle.net/maku/8eush3tp/7/

**To Reproduce**

1. Go to https://jsfiddle.net/maku/8eush3tp/7/
2. Click on 'Hide groups" button
3. Onyl the first group is hidden

**Expected behavior**
All groups should be hidden

**Comment by olifolkerd** [comment]
Hey @maku 

The issue you are having here is because the hide function triggers a table redraw which cause a regeneration of the group components which invalidates the old ones.

It is also inefficient because it will trigger the redraw of elements of the table multiple times.

If you want to trigger a bulk update of the table, the correct approach is to call the `blockRedraw` function first, which will prevent the table being redrawn until the update is complete, then make your updates, then call the `restoreRedraw` function to trigger a single redraw of the table to make all the updates:

```js
table.blockRedraw();

table.getGroups().forEach((c) => {
      console.log('group key', c.getKey(), c.isVisible());
      c.hide();
});

table.restoreRedraw();
```

I hope that helps.

Cheers

Oli :)

**Comment by maku** [comment]
@olifolkerd thank you for clarification (and also for your great work). I definitely need more knowledge of how tabulator works
