### ISSUE TITLE
cell.isEdited() cleared on tree expand/collapse event

### ISSUE THREAD

**Issue by harpsdev** [olifolkerd/tabulator#3831]
First a big thank for the work done on the component, it is brilliant!

**Describe the bug**
When using the tree option on an editable table, expanding and collapsing a node clears the isEdited status on the whole table.

**Tabulator Info**
- Which version of Tabulator are you using? —> 5.2.4

**Working Example**
https://jsfiddle.net/rk23ad0y/2/

**To Reproduce**
Steps mentioned in the jsfiddle

**Expected behavior**
The isEdited status to persist tree node collapse and expand events.

**Screenshots**
If applicable, add screenshots to help explain your problem. —> Nope

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 101.0.1

**Smartphone (please complete the following information):**
N/A

**Additional context**
It looks like the edit module context disappears from cells, not only isEdited prop to turn false.

**Comment by harpsdev** [comment]
I just forgot to mention that cell.getInitialValue() returns the modified value then.

**Comment by olifolkerd** [comment]
Hey @harpsdev 

Thanks for getting in touch,

This is a known limitation of the tree system at present.

This happens because child rows are not true rows in the table like the top level rows, they are recreated every time the contents of the `_children` array is updated, so they dont persist state on update.

This is something that will be fixed when the data tree module is rebuild in one of the upcoming releases, but is not something that can be patched around in the mean time.

Cheers

Oli :)
