### ISSUE TITLE
this.cell.getTable is not a function

### ISSUE THREAD

**Issue by JAIC-be** [olifolkerd/tabulator#3849]
Dear,

We are in the process of upgrading tabulator on our website from v4.9.1 to v5.3.0 but are having issues with the 
editor:"autocomplete", editorParams:{
    valuesLookup:true,  //lookup all unique values
    valuesLookupField:"people", //lookup all unique values from the people column
}
and 
editor:"list"

Both of these are giving the console error; this.cell.getTable is not a function

`Uncaught TypeError: this.cell.getTable is not a function
    at i.value (List.js:53:14)
    at new i (List.js:41:8)
    at s.list (list.js:4:13)
    at s.value (Filter.js:389:28)
    at s.value (Filter.js:294:8)
    at s.value (Filter.js:190:9)
    at InternalEventBus.js:119:25
    at Array.forEach (<anonymous>)
    at e.value (InternalEventBus.js:118:21)
    at s.value (CoreFeature.js:78:30)`

https://codepen.io/JAICbe/pen/gOerWKm

**Comment by olifolkerd** [comment]
Hey @JAIC-be 

Looks like you have found an issue there, which i will get a patch out for this evening.

The good news is that is totally possible to work round this, it is only occuring because you are using the deprecated `sortValuesList` option, if you replace it with the `sort` option it should stop causing issues.

Cheers

Oli :)
