### ISSUE TITLE
No option to filter with lookups instead of value

### ISSUE THREAD

**Issue by stickylp** [olifolkerd/tabulator#3864]
Hello,

I'm trying to filter my rows using the "like" operator 
`table.setFilter([
        {field:"name",type:"like", value: name},
        {field:"surname",type:"like", value: sname}]);`
and i have my values (IDs in my database) visually replaced with names by using the `formater:"lookup"` parameter, now when i try to filter, there is no option to filter with the replaced names. A workaround that i tough of is doing a custom filter but the only data you get with the custom filter is the rows and their values so it can't be done this way too.

The code was working before i changed it so it works with lookup and IDs isntead of plain text.

If there's a way to do it, please tell me.

Thank you,
Sticky

**Comment by olifolkerd** [comment]
Formatters are visual only, because they are intended as a layout option and can generate Dom elements, you cant filter or sort on them because they do not effect the underlying data.

This is intentional, for example if you have a formatter that creates a progress bar or image element there is no meaningful way to sort or filter that.

If you want to change the underlying data instead of a visual only change then you need to use a mutator instead of a formatter

Cheers

Oli
