### ISSUE TITLE
Bug: Header ignores Padding when using Grid

### ISSUE THREAD

**Issue by Emporea** [olifolkerd/tabulator#3881]
The header (col-content) ignores padding when using `grid` and `autoResize: true` as seen on this screenshot:
![image](https://user-images.githubusercontent.com/21969523/181130522-5423729f-b6d8-42d5-bada-b0ec2f68396d.png)

If `autoResize: false` the header gets displayed correctly on first load but is wrong again after a column sort.
Desired view:
![image](https://user-images.githubusercontent.com/21969523/181130689-b0c99299-5e15-4294-ad2a-70ee36a3f8e5.png)

I made a reproducible example on [codepen.io](https://codepen.io/emporea/pen/xxWXgad)

Edit:
This is somewhat of a duplicate of #3871 and #3874 (possible more) but maybe a new code example helps investigating.
Also I am not sure anymore if it has even something to do with grid, but i keep this issues as it is since its a duplicate anyway.

**Comment by farnoosh-wzzx** [comment]
Of course, the issue that I have registered is related to the RTL mode (#3874)

**Comment by olifolkerd** [comment]
Hey @farnoosh-wzzx 

This is unrelated to your issue, that issue is due to the scrollbar compensation mechanism built into the header, its maths is currently only set up for ltr and needs adjusting for rtl.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Emporea 

Tabulator does not like being inside flex or grid elements when `resizeTable` is enabled, because the resizeObserver that tabulator uses and the flex/grid layouts end up fighting with one another and it creates visual corruption. This is not limited to tabulator, but a lot of other JavaScript libraries that auto resize also face the same issue.

When working with flex the solution is to put Tabulator into an absolutely positioned element inside the flex, thus preventing the layout battle.

There is also a solution for the gird approach which i have answered in a couple of previous questions, but cant remember off the top of my head. i will have a didd through the previous issues and see if i can point you in the right direction.

I will also look to update the `tableResize` docs to explain these limitations and work arounds ahead of time.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Emporea 

The issue here is that you are trying to apply padding directly to the Tabulator element. If you need spacing around the table you should do this outsite the table element. Tabulator requires there to be no internal padding on its element inorder to do the layout calculations correctly.

Cheers

Oli :)
