### ISSUE TITLE
Double clicking cells to edit blocking input

### ISSUE THREAD

**Issue by ATapia24** [olifolkerd/tabulator#3895]
**Describe the bug**
Double clicking an cell with editor set to "input" to highlight text does not allow for keyboard input.

**Tabulator Info**
- Which version of Tabulator are you using?
- 5.3.1

**Working Example**

Present in documentation examples
http://tabulator.info/examples/5.3?#editable

**To Reproduce**
1. Double click a cell in the name column to highlight the text
2. Attempt to type to clear text and enter a new value

**Expected behavior**
The highlighted text should be replaced by new keyboard input.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Tested on Chrome & Edge
 - Version [e.g. 22]: Chrome 103.0.5060.134

**Comment by ATapia24** [comment]
Seems like the same focus issue in #2262 (https://github.com/olifolkerd/tabulator/issues/2262)

This seems to work as a temporary fix, same as mentioned in #2262 but inside a setTimeout function call.
`
table.on("cellDblClick", function(e, cell) {

    setTimeout(function() {
        try {
            let input = cell.getElement().childNodes[0]
            input.focus()
            input.select()
        } catch (e) {
            // empty - do nothing
        }

    }, 0);
});
`

**Comment by olifolkerd** [comment]
Hey @ATapia24 

Thanks for the info, i have pushed a fix for this to the master branch and will include it in the next patch release.

The issue was in the interaction manager, in the `cellContentsSelectionFixer` function that prevents selection of more than a cells contents on non-editable cells. there was a flaw in the logic that was copied over from the old cell component and it was not correctly checking when it was being called on the currently edited cell.

Cheers

Oli :)
