### ISSUE TITLE
UMD dist file tabulator.js seems to have significant performance slowdown relative to the ESM file

### ISSUE THREAD

**Issue by welford** [olifolkerd/tabulator#3928]
**Describe the bug**

i switched from 4.2 to 5.3 recently and noticed that page loading has gotten noticably slower.

https://jsfiddle.net/cz1ovdqk/ 4.9    ~500 ms
https://jsfiddle.net/zp7cLae4/ 5.3   ~2800 ms 

Roughly 5 times slower to load the same data. 300,000 entries paginationSize:50.

**Tabulator Info**
- 5.3

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/zp7cLae4/ 
2. Click run with the browsers performance tools on
3. see results and compare with https://jsfiddle.net/cz1ovdqk/

**Expected behavior**

**Screenshots**
nothing really stands out from tabulator in the 4.9 capture in either the evaluate script or the function call segments.
![image](https://user-images.githubusercontent.com/4590399/188512518-f22359a3-8e0b-4d98-96ce-4f0382cac8b4.png)

in the 5.3 version one callstack seems to take up 1447ms of the total time.
![image](https://user-images.githubusercontent.com/4590399/188512537-2d977c9d-b637-4cfb-a97f-5225f95b2ada.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
- Version 105.0.1343.27 (Official build) (64-bit)

**Additional context**
using the full fat version of the js this seems to be the offending callstack.

![image](https://user-images.githubusercontent.com/4590399/188512862-b94c70cd-e2d9-4d74-a976-acbd3643894a.png)

**Comment by welford** [comment]
[4.9.zip](https://github.com/olifolkerd/tabulator/files/9492042/4.9.zip)
attached two perf captures if they are useful.

**Comment by welford** [comment]
Similar profiles on chrome : Version 105.0.5195.102 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/4590399/188515019-9ac76668-98a2-43df-8001-5839be4e0c34.png)

**Comment by olifolkerd** [comment]
Hey @welford 

Thanks for getting in touch,

Interestingly when i run your code locally on my local instance of 5.3.3 then i get a loading time of 500ms for the table which is what i would expect.  I ran extensive benchmarking when building it and it outperforms 4.9 on most counts. 

Having looked into this a bit, this is actually only a problem on the UMD build of Tabulator (tabulator.js), if you import the ESM module (tabulator_esm.js), which is how most of Tabulators users use it then it works as expected with a load time in the 500ms range. In this case most users import the Tabulator library via npm and then include it in their project with an import statement.

This is interesting as they are both based off exactly same src files, they are just different builds of the library for different environments.

As a demo, i have rearranged your JS Fiddle to pull in the code from the ESM module version of the library and you can see in builds in 500-600ms. I have added `console.time` and `console.timeEnd' statements to the code so you can see in your dev console the render time output.  Please forgive the messyness of the code, to do a ESM Module Import via CDN i had to add a module type script tag which JS Fiddle does not seem to support in the script window.

As such i will rename this issue to refer to a build issue in the UMD module.

In the mean time i would suggest as a work around if it is possible, import the code into your source rather than pulling it from a CDN, defails can be found in the [Install Guide](http://tabulator.info/docs/5.3/install)

Cheers

Oli :)

**Comment by welford** [comment]
Thanks for the response! I'm pulling in the tabulator.min.js from a local copy without running any server (for ease of dev reasons) Will have to take a look at what is possible wrt importing (immediately hit some CORs issues ;s)

thanks again,
James

**Comment by olifolkerd** [comment]
Are you using any build tools like webpack or gulp with your project to manage your JavaScript, if so then you can just build it into your main JS file via the import statement without having any issues with cors as it will be embedded in your code

**Comment by olifolkerd** [comment]
Hey @welford 

I have gotten to the bottom of the performance issue.

In the UMD package the babel transpiler was used in the build chain to convert the code to ES2015 so that it would work on older browsers like IE 11. This resulted in a massive performance hit as it converted all the class syntaxes and chaining logic to use a series of complex reflector functions which really ate up a tone of processing resource.

The good news is that actually the use of babel is now a bit redundant, as IE is no longer supported by Tabulator. So i removed it from the build chain and i get much more efficient render times, on a par with the ESM module.

I have pushed this fix to the 5.4 branch which i will be releasing around the end of September.

Thanks for the bug report, it was very helpful.

Cheers

Oli :)
