### ISSUE TITLE
An option to retain topCalc values in collapsed group header.

### ISSUE THREAD

**Issue by welford** [olifolkerd/tabulator#3930]
An option to retain topCalc values in collapsed group header.

**Describe alternatives you've considered**

the topCalc values are really useful when looking at collections of data, but when you collapse them you lose most of that information by default:

![image](https://user-images.githubusercontent.com/4590399/188746410-31939734-04c8-459b-9e70-5469f02e77a0.png)

I understand you can write a custom header with a [callback](http://tabulator.info/docs/4.0/group#setup-headers), but it would be nice to be given the option to keep the totals/sums as they are - no user side code needed.

for example something like this:
![image](https://user-images.githubusercontent.com/4590399/188746775-5612ac9c-0171-4f35-98ff-aed311c44a63.png)

**Additional context**
I've definitely found the default collapsed header a little limiting when i am looking at data that includes 10000s of rows split between a 10s of groups. Maybe my recall is just bad, but i find myself having to re-expand them to check sums of data sizes.

Thanks,
James

**Comment by olifolkerd** [comment]
Hey @welford 

This has been a requested feature, but if i am allowing top calcs to be retained i would also need to allow bottom calcs, and no one has as yet come up with a suggestion of how to do this in a non confusing way, if they do i would be happy to implement it.

I would not be looking to merge the values into the header as you have suggested in your graphic because as soon as you have event a slightly long group title it would interfere with the column layout, they would have to be in a row under the group.

So i would be happy to look at including this as keeping the calc rows in the closed group but i would need a suggestion as to how to maintain the bottom calc rows in a nested group scenario before i could proceed.

Cheers

Oli :)

**Comment by welford** [comment]
> I would need a suggestion as to how to maintain the bottom calc rows in a nested group scenario before i could proceed.

Could you perhaps have an option like "retainedCalcs" with options "none" (current behaviour) "top", "bottom", & "both"

or maybe i am misunderstanding the issue?

**Comment by olifolkerd** [comment]
@welford I think you are mis understanding the issue there.

I can certainly add an option for it.

The issue is the visual layout, with nested groups, the bottom calcs stack directly on top of each other making it hard to see which row is for which closed group/

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @welford 

When looking into this further, the existing `groupClosedShowCalcs` option seems to already offer the functionality you need:
```js
var table = new Tabulator("#example-table", {
    groupClosedShowCalcs:true, //show column calculations when a group is closed
});
```

Cheers

Oli :)

**Comment by welford** [comment]
Thanks Oli, will check it out.
