### ISSUE TITLE
Sort table for selected rows.

### ISSUE THREAD

**Issue by dbauszus-glx** [olifolkerd/tabulator#3994]
Is it possible to sort a table to show all selected rows on top?

I can add a rowSelection formatter to the table as [shown in the documentation](https://tabulator.info/docs/5.4/format#formatter-rowselection). 

However changing the headerSort to true doesn't make that row sortable.

```
{
  formatter:"rowSelection",
  titleFormatter:"rowSelection",
  hozAlign:"center",
  headerSort:false
}
```

Is it possible to manually create a sorter for selection?

I created a codepen with the example from documentation and headerSort set to true.

https://codepen.io/dbauszus-glx/pen/gOKYJge

**Comment by olifolkerd** [comment]
Hey @dbauszus-glx 

That wouldnt be possible out of the box because Tabulator sorters only work on row data, and the selection functionality is handled by a seperate module.

But there is a simple way you can implement this yourself. You could use the `rowSelected` and `rowDeselected` events to set a boolean selected field on that rows data.

If you then assign that field to the rowSelection column and set a `boolean` sorter on it it should sort just fine.

I hope that helps

Cheers

Oli :)
