### ISSUE TITLE
Cell focus lost after a table.updateData() on nested data (_children)

### ISSUE THREAD

**Issue by francoisrousseau** [olifolkerd/tabulator#4016]
Describe the bug
First of all, awesome table control, thank you very much.

I have a table with editable nested data.
I want to navigate through a child row using the tab button and change the values.
On each edition, I need to update the tooltip value of the cell.

To update the cell tooltip, I use table.updateData() like so 
let updateData = { id: row.id, _children: childData };

The update works but I lose the cell edition focus. 
I can't use the tab button to navigate to the next cell, which is what I would like to do.

I did not find a way to update "_children" without passing the entire object.
Something like the following would be awesome to specify only the desired change.
let updateData = { id: 1, _children: [ { id: 2, tooltip: 'My new tooltip' } ] };

Any help?
Thank you !

Tabulator Info
5.4.2

Working Example
https://jsfiddle.net/frousseau/ceg9m5sq/73/

To Reproduce
1. Click on the cell of row ID 3 and column "Name"
2. Change the value of 1 to 2
3. Press the Tab button to end edit and navigate to the next cell
4. The cell tooltip was successfully updated **but the cell focus was lost**

Desktop (please complete the following information):

OS: Windows 10
Browser: Google Chrome
Version 99.0.4844.82 (Offizieller Build) (64-Bit)

**Comment by olifolkerd** [comment]
Hey @francoisrousseau 

Thanks for getting in touch, and thanks for your kind words about Tabulator, im glad to hear you are finding it useful.

This seems more like a question for help rather than a bug report, so could i ask that if you have complex usage cases and need advice that you ask on the Discord server or Stack Overflow first to get community feedback before reporting it as a bug.

In this case the issue is that you are calling `updateData` from within an editor which will definitely result in unstable operations, as it will cancel any edit in progress. You are also trying to access some of the internal logic of the row component using the _row and _children props, This is STRONGLY discouraged, by standard JS convention underscore variables should be treated as private, attempting to directly manipulate internal variable is pretty much guaranteed to make the table unstable. As a general rule if you are trying to use an _variable then you have missed something in the docs.

Tabulator has a full component API that provides safe access to all functionality and provides functionality to update individual rows without triggering a redraw of the table. Checkout the [Component Object Docs](https://tabulator.info/docs/5.4/components) for full details.

If you just want to update the tooltip value on the row that is currently being edited you can just call the `update` function on the row component
```js
cell.getRow().update({tooltip:"potatoe"})
```

Cheers

Oli :)

**Comment by francoisrousseau** [comment]
Wow, thank you very much for that detailed answer !
It is now working perfectly fine :)
