### ISSUE TITLE
Multiline title in export as PDF

### ISSUE THREAD

**Issue by peterprvy** [olifolkerd/tabulator#4028]
my solution for multi-line subtitles

		...
		title = options.title ? options.title : "";

		if(typeof title === "string") { // title is string or Array,  after split always array
			title = title.split("\n");
		}
		....
		var doc = new jspdf.jsPDF(jsPDFParams);
		
		const dim = doc.getTextDimensions('Text');
		const lineHeight = dim.h + 2;
		let marginTop = 40;
		let topOffset = 30;
		let leftOffset = 40;

		if (Array.isArray(title)) {
			marginTop = topOffset + title.length * lineHeight;
		}

		....
		autoTableParams {
		....
			margin: { top: marginTop, left: leftOffset },
			
			didDrawPage: function(data) {
					for (let i = 0; i < title.length; i++) {
						let lineTop = (lineHeight) * i;

						// (text, x, y, options, transform)
						doc.text(title[i], leftOffset, topOffset + lineTop);
					}
				}
		}

My PDF:

	let title =
	options.title || [
	"Testovací titulok s diakritikou:",
	"a, á, ä, b, c, č, d, ď, dz, dž, e, é, f, g, h, ch, i, í, j, k, l, ĺ, ľ, m, n, ň, o, ó, ô, p, q, r, ŕ, s, š, t, ť, u, ú, v, w, x, y, ý, z, ž",
	"A, Á, Ä, B, C, Č, D, Ď, DZ, DŽ, E, É, F, G, H, CH, I, Í, J, K, L, Ĺ, Ľ, M, N, Ň, O, Ó, Ô, P, Q, R, Ŕ, S, Š, T, Ť, U, Ú, V, W, X, Y, Ý, Z, Ž."
	];
			

![image](https://user-images.githubusercontent.com/36068077/202857949-800b1087-6979-4fc0-9576-64177fc8edae.png)

**Comment by olifolkerd** [comment]
Hey @peterprvy 

Looks like you managed this with the built in autotable params extension which is what that function is there for.

Given the bespoke nature of a multi line title, and the probability that people would want to format each line differently, i would prefer to let them code that themselves for their usage case rather than forcing a generic solution on people.

Thanks for your suggestion though.

Cheers

Oli :)
