### ISSUE TITLE
tebulator stuck in infinite loop if formetter is set

### ISSUE THREAD

**Issue by Alex-Github-Account** [olifolkerd/tabulator#4040]
sometimes, usually after third or forth tabluator.redraw(), console is getting spammed with infinite messages like this
![image](https://user-images.githubusercontent.com/60236507/204749949-8f1f99e9-14ba-42c8-8561-cb5aec1d8949.png)
there is no way to debug this on user-side since it is unclear from where exactly from inside a tabulator this message is generated
The value is my ID column value, and it has formatter, but it's code is irrelevant since is not even getting called (it has console.log('called') as very first string of function)
eventually this spamming results in unresponsive page
currently I am solving this by not using tabulator in production
but is it possible to have something at least like 
if (columnAlreadyProcessed OR amountOfMessagegesGenerated > 1000000000) then
stopGeneratingMessagesFinally()
to control the infinite loop?

**Comment by olifolkerd** [comment]
Hey @Alex-Github-Account 

As per my response to issue #4039 please make sure you fill out a bug template when rasing a bug, without providing a replicatable example of how your table is setup it is impossible to offer advice.

What i would say is that there is no scenario when using the table in which you should need to call the `redraw` function that often. it is a catch all function only intended to cover very rare edge cases. this suggests that what ever feature you are using you might be using things incorrectly. If you can provide a working fiddle that demos the issue i can point you in the right direction.

At this point, given the number of these sorts of issues raise, could i please ask that you checkout the questions channel on the Tabulator discord server and ask the community for help, i can pretty much guarantee you will have a much smother experience.

Cheers

Oli :)

**Comment by Alex-Github-Account** [comment]
Sorry? Like, in very first words I mentoined that It takes about 3 redraw calls to let tabulator go crazy and do infinite updates, then you saying I am calling redraw "that often"?? 3 times is too often or you didn't read the bug report? Also, closed as completed? Infinite loop that hangs out the browser and you dont want to solve? Facepalm

**Comment by olifolkerd** [comment]
Hey @Alex-Github-Account 

Dude, dial down the attitude, im trying to have a polite conversation with you and at every point from the moment you raise questions to your replies all i get is attitude, you need to reassess the wording of your issues or you will be blocked from this repo. please read the community guidelines or do not participate in this project.

Also as i clearly mentioned above the issue is not that you didn't provide a description, the issue is that you didn't use the bug template, missing half the info needed to solve the issue, and that you haven't included a link to a JS Fiddle. without this it is not possible to get to the bottom of the issue because i cannot see how your table is configured and how and when you are calling the redraw function. There are so many permutations of your description it is impractical to replicate.

Im here to help and happy to resolve this but im not going to play 20 questions to get to the bottom of your issue. If you want help then you follow the community guidelines and engage with the process providing the info we need to help you.

And yes as i mentioned the fact that you are calling redraw even three times suggests that you may be using the function in th wrong place, but i cannot help you further with this without seing a fiddle that demonstrates the issue. As i said i am very happy to offer you help and guidance but i cannot do this without seing how you are using tabulator, without the context of how your table is configured the issue is not helpful at all.

There is a simple guide to creating a js fiddle in the [Community Section of the Website](https://tabulator.info/community/jsfiddle)

When you have an example setup, please re raise the bug with the issue template or post the link here and we can pick things up again.

Cheers

Oli :)
