### ISSUE TITLE
Remove :hovered state on devices that do not support hover functionality

### ISSUE THREAD

**Issue by Alex-Github-Account** [olifolkerd/tabulator#4047]
when user scrolls tabulator on mobile device (or do long-press on a row), row would acquire :hover state (background highlighted),  and it would stuck in that state: it wont go away as user releases the finger or scrolls the page, using browser controls, switch the apps, etc. 
Since some hater there just closes all the bugs I found as "completed" (a sign to you, potential user, to not repeat my mistake and keep leg away from this hobby project), here is my solution for anyone here from google:
`@media (pointer: coarse),  (hover: none)  {
   div[class~="tabulator-cell"]:hover {
        background-color: initial !important;
    }
    div[class~="tabulator-cell"]:not(div[class~="tabulator-selected"]):hover{
        background-color: white !important;
    } 
}`
replace the "white" color with background color of your tabulator. There maybe actually better solution which requires no specific color to be set.
 (note that if bug is closed, this does not mean it is fixed, and you still in need of some walkaround like my)

**Comment by Alex-Github-Account** [comment]
For anyone here from google, this bug is closed but not fixed, there is someone who closes my reports simply to keep issues count low.
Thus my walkaround is still the way to have issue solved.

**Comment by olifolkerd** [comment]
@Alex-Github-Account  As was clearly stated in your previously closed issues, they were closed because you were not using the issue template and not provided examples to demo the problem so it was not possible to resolve your issues without further information

Things were not closed to keep the issue count low but to indicate that no further action would be taken on that issue until you provided more information.

**Comment by olifolkerd** [comment]
This has been applied to the 5.5 branch and will be included in the next feature release in march

Cheers

Oli :)
