### ISSUE TITLE
Add Row does not appear to add to "top" when initial sort specified

### ISSUE THREAD

**Issue by python3Berg** [olifolkerd/tabulator#4049]
[https://jsfiddle.net/python3berg/qmwxz6jn/7/](url)

Upgrading from 4.9 to 5.4. I always add rows from websocket updates to top to show users progress without scrolling. This is not working for me right now when testing 5.4. 

If rows are added with initialSort commented out...all good. When it is in place, it appears the virtual renderer is not receiving the target position and always doing a clearRows and redraw. This would explain why things are always sorted. Attempting to be compliant with code same with first jsfiddle :)

**Comment by olifolkerd** [comment]
@python3Berg 

Thanks for getting in touch.

And thanks for the the fiddle that is very helpful 

Please could I ask that you use the bug issue template when reporting a bug instead of a blank template. It will prompt you for the small amount of info we need to help you out and makes the process much easier to manage.

I'm building out a patch release over the weekend so will have a look at resolving this then.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @python3Berg 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by python3Berg** [comment]
Thanks Oli.

**Comment by python3Berg** [comment]
New rows are added to top correctly. They are however missing some concepts of ordering. All new rows have a class of tabulator-row-even which will lead to formatting problems for those with alternating row colors...

![image](https://user-images.githubusercontent.com/73388511/205661906-c5cd9b9e-56c5-442b-9d1c-5e3e549c86cd.png). See same jsfiddle above for illustration.
