### ISSUE TITLE
Deleting a row inside cellClick callback in column definition throws an error

### ISSUE THREAD

**Issue by thearchitect3344** [olifolkerd/tabulator#4055]
**Describe the bug**
Deleting a row inside cellClick callback in column definition throws an error 

**Tabulator Info**
- Which version of Tabulator are you using? 5.4.3

**Working Example**
[https://jsfiddle.net/zgadr34L/2/](url)

**To Reproduce**
1. Click on any row in the delete row column
2. Open the inspect window 
3. See error "Uncaught TypeError: Cannot read properties of undefined (reading 'add')"

**Expected behavior**
deleting happens without error. This worked in the previous versions.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge, Chrome

**Additional context**
Problem was not there on version 5.4.0

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

That is because you have an editor in the cell and you are trying to delete the cell at the same time as editing it. which is causing the editor to fail out.

While i don't know your full usage case, this does not seem like a realistic configuration of the table. Do you have a practical example of when this would be an actual issue?

Cheers

Oli :)

Do you h

**Comment by Jojoshua** [comment]
@olifolkerd I didn't author this issue but in my case it was that I had a delete icon in a cell so that the user could delete the row. Maybe @thearchitect3344 could provide their use case. There is probably some more code that needed to happen along with the delete. 

Looks like the original post got a few thumbs up so I can assume its a fairly common pattern & issue. Thank you for taking a look at this one!

**Comment by olifolkerd** [comment]
Hey @Jojoshua 

Sorry for the confusion there, in that case do you have an example of the issue from your delete button. I can see the thumbs which is why i want to get this one sorted. but when i dont use an editor i dont get the issue. 

Are you not using a formatter to ad the button? do you have an example of the column definition that causes the issue, even a single line snippet would be really helpful.

Cheers

Oli :)

**Comment by Jojoshua** [comment]
@olifolkerd It will take me some more time to find where this happened to me but overall I think https://jsfiddle.net/zgadr34L/2/ is likely the same scenario. Are you saying the code can use a formatter instead of an editor and it will work fine?

**Comment by Jojoshua** [comment]
Testing the original fiddle and using formatter:"buttonCross" instead of editor:"input" did seem to work.

https://jsfiddle.net/jojoshua/yvpef38m/

**Comment by olifolkerd** [comment]
@Jojoshua  Yeah, i think this is a case of people using the wrong type of element of that sort of interaction.

I will add a console warning there instead of an error to prompt people to use the formatter instead.

Cheers

Oli :)

**Comment by thearchitect3344** [comment]
@olifolkerd Awesome, thanks for this update Oli! Great support. @Jojoshua Thanks for taking a look at this as well.
