### ISSUE TITLE
action is being called 50k times

### ISSUE THREAD

**Issue by inecjcorreia** [olifolkerd/tabulator#4062]
**Describe the bug**
 when loading the tabulator, we have a problem when the tabulator function "addColumn" calls the formatter function "visitBaseLineFormatter" since it is called about 50,000 times, what causes the page to take a long time to load.

**Tabulator Info**
- we are using the 4.9.3 version.

**Working Example**
we made a quick demo on VisualStudio, you can download the files via https://we.tl/t-6IyvCvwPkr

**To Reproduce**
to reproduce the problem, open the HTML file in the link above and see that the tabulator takes about 1min to load.

**Expected behaviour**
we are expecting this action to be called several times but by the count, we were expecting it to be called about 2000 times  instead of 50,000

**Screenshots**
![image](https://user-images.githubusercontent.com/32265471/207558255-810a5fe0-cdf0-4ede-8a89-e66f96a54273.png)

**Desktop (please complete the following information):**
 - Chrome

**Additional context**

**Comment by olifolkerd** [comment]
Hey @inecjcorreia 

Sorry for the delay in getting back to you, i was dealing with a family emergency over the xmas break, and things are only just starting to get back to normal now.

Please create a JS fiddle that demonstrates the issue, without example code im afraid we cannot help you.

Im afraid we are unable to allow downloads of source as there is no way to be sure what the payload of the file may be.

Depending on how the data is structured, the number of rows, and how many columns the formatter is applied to 50,000 is an eniterly possible number.

Though i would say that suggest that you havnt set a height on the table, so all the rows are being rendered at once. if you set a height so that scrolling is needed, it will enguage the virtual DOM and only render the currently visible rows, dramatically improving table performance.

If you can post a link to a fiddle i would be happy to reopen this issue and help you out.

Cheers

Oli :)
