### ISSUE TITLE
When loaded as ESM, table data disappears

### ISSUE THREAD

**Issue by megatron0000** [olifolkerd/tabulator#4066]
**Describe the bug**
I have a static table element in the HTML. Then I import Tabulator and try to new Tabulator(table, {}). 
If the import is ESM, this causes the table data to disappear from the HTML. But if the import is not ESM, everything works as it should.

**Tabulator Info**
5.4.3

**Working Example**
JSFiddle that imports tabulator as ESM (bug): https://jsfiddle.net/3vqdfg0z/1/
JSFiddle that imports tabulator globally (works as expected, no bug): https://jsfiddle.net/whmzjdky/

Both fiddles have a setTimeout in the js code, which is there just to let some time pass since page load, to make it easier to see when the Tabulator instance is created.

**To Reproduce**
1. Open the JSFiddle (ESM version). There will be a table element on the HTML
2. Wait for 1 second. Then the js will instantiate a Tabulator from the HTML table
3. Notice that the table disappears from the HTML (bug)

**Expected behavior**
I expected that the ESM fiddle would have the same behavior as the non-ESM fiddle. Which is to load Tabulator correctly without destroying the table data that was already there in the HTML.

**Screenshots**
ESM fiddle, on page load:
![image](https://user-images.githubusercontent.com/8161576/208252145-afb396af-2874-4515-abba-60e6097edbb0.png)

ESM fiddle, when Tabulator is instantiated:
![image](https://user-images.githubusercontent.com/8161576/208252182-e8b73007-d08f-4c44-9f2d-477a8ac55d94.png)

Non-ESM fiddle, on page load:
Same as the ESM fiddle

Non-ESM fiddle, when Tabulator is instantiated:
![image](https://user-images.githubusercontent.com/8161576/208252198-0bbf651c-826b-46a5-9acb-386029b65d60.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave, Chrome, Edge (bug happens on all of these)
- Version: Brave Version 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit) ; Chrome Version 108.0.5359.125 (Official Build) (64-bit) ; Edge Version 108.0.1462.46 (Official build) (64-bit)

**Comment by colemannugent** [comment]
Running into what appears to be the same issue with a slightly different setup. Instead of importing the ESM via a CDN I've got it bundled via esbuild.

Once Tabulator is initialized my HTML table disappears. Poking around in the HTML that is left behind reveals that all the content is missing.

OS: Linux (Ubuntu 22.04.1 LTS)
Browser: Firefox 109.0

I've tested a few versions of tabulator to see if they were affected:
|Version|Affected|
|---|---|
|5.4.3|Yes|
|5.4.0|Yes|
|5.3.4|Yes|
|5.2.7|Yes|
|5.1.8|Yes|
|5.0.0|Yes|

Pre 5.0.0 versions failed to bundle with an error:
>✘ [ERROR] No matching export in "node_modules/tabulator-tables/dist/js/tabulator.es2015.js" for import "Tabulator"

**Comment by olifolkerd** [comment]
Hey Eeveryone, 

This is because the UMD version is the equivalent of using Tabulator full, it pulls the whole library down because there is no optional module loading with the UMD version.


With the ESM version the default Tabulator that you are importing is the Tabulator Core which does not include any modules, in order for the Tabulator to be built from a table the HTMLImport module needs to be included.

You could either include the core and the module, or the `TabulatorFull` option which includes all modules. so changing your import statement to the following will work:
```js
import {TabulatorFull as Tabulator} from 'https://unpkg.com/tabulator-tables@5.4.3/dist/js/tabulator_esm.min.js';
```

A full explanation of this can be found in the [Setup Docs](https://tabulator.info/docs/5.4/install#setup-basic)

Cheers

Oli :)
