### ISSUE TITLE
Tree-shaking not working

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [olifolkerd/tabulator#4070]
Copying this over from #1447 as I also asked around.

The installation docs have a section [Core With Optional Modules](https://tabulator.info/docs/5.4/install#setup-basic), but following the example does not lead to a tree-shaked bundle.

Having a file tabulator_rollup.js pointing to tabulator_esm.js like so:

```
import {Tabulator, FormatModule, EditModule} from './tabulator_esm';

Tabulator.registerModule([FormatModule, EditModule]);

var table = new Tabulator("#example-table", {
  //table setup options
}); 
```

and running

`rollup tabulator_rollup.js --file tabulator_bundle.js --format iife`

leads to a bundle containing all the modules. Same result, if running Rollup with `rollup -c` against Tabulator installed from npm with a config file like

```
import resolve from 'rollup-plugin-node-resolve';

export default {
  input: 'tabulator_rollup.js',
  output: {
    file: 'tabulator_bundle.js',
    format: 'iife',
  },
  plugins: [
    resolve({
      browser: true,
    }),
  ],
};
```
 
I also tried with Parcel, asked a question in their discussions and got [an answer](https://github.com/parcel-bundler/parcel/discussions/8708) saying it does not seem possible due to how tabulator_esm.js is structured.

**Comment by diervo** [comment]
I spent a couple of hours trying to see if there was an easy way to make the code tree shakable, but many issues will require changes to the API and the way the imports are set.

To give a concrete example, tabulator fully uses an `export *` binding with most modules, making the code non-tree-shakeable:

```
//tabulator with all modules installed
import {default as Tabulator} from './Tabulator.js';
import * as modules from '../core/modules/optional.js';
import ModuleBinder from './tools/ModuleBinder.js';

class TabulatorFull extends Tabulator {}

//bind modules and static functionality
new ModuleBinder(TabulatorFull, modules);

export default TabulatorFull;

```

If the team wants to get the ESM mode tree-shakeable (so the library doesn't weight ~420kb) and is willing to change some APIs, I'm happy to make a proposal and a potential PR.

**Comment by olifolkerd** [comment]
Hey @diervo 

I would love to hear your feedback on the tree shaking in more detail.

When running locally i was able to successfully pull down only the modules i needed so i would love to know more about the issues you have faced. But i will be honest and say that i have only really followed guides for the tree shackability side of things so would welcome any advice.

As for the `TabulatorFull`, the whole point of that export is that it includes ALL of the modules, there shouldn't be anything to shake there, if you are saying you want `TabulatorFull` you are saying you want everything, it is a short cut import for people who dont mind the size and dont want to have to manually import everything.

It is only if you are importing `Tabulator` that it should import the core of the library and then you should import each module individually as per @ilmari-lauhakangas example above.

Cheers

Oli :)

**Comment by diervo** [comment]
My example was unfortunate due to the `TabulatorFull` appearance, but the problem is the same for any module.

Check out this example: We only import `ResizeColumnsModule`, yet ~95% of `tabulator-table` is being included on the build (almost zero tree-shaking).

https://codesandbox.io/p/sandbox/stupefied-frost-mdqibd?selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A2%7D%5D&file=%2Fsrc%2Fmy-element.ts

There are a lot of reasons why the code is non-tree-shakeable: The use of `export *`, the use of eager bindings for some of the modules, ... 

If this makes sense, I'm happy to take a stab at fixing it correctly, but the changes are highly likely to be non-backward compatible (some module imports will have to change), so I would like to first get to an agreement and consensus on changes and expectations.

**Comment by olifolkerd** [comment]
Hey,


That is for getting back to me.

I'm not keen on any action that would change the import requirements in the short term as this would certainly only be possible on a major version change which won't be happening for another year.

It is clear from your example that the tree shaking isn't working as expected, but i would say that when I first added the tree shaking functionality I did extensively test it and it was working as anticipated so it is very likely that some changes I have made since that point have broken it. Which more suggests that this is due to one or two changes that have occured than due to a holistic issue.

Could you explain a little more on the details of your last two bullet points. Are there any specific actions or causes that I could investigate further. At this point I really just want to understand the cause of the issue more than anything else. I'm certainly not looking for a wholesale refactor of the code as that will likely cause more problems that it solves in the short term. And if needed would form part of the next major version upgrade.

Cheers

Oli :)

**Comment by wpk-** [comment]
I used the exact example in the OP and compiled with rollup using 5.1, 5.2, 5.3, 5.4 and master branches. In all cases the compiled bundle included all modules, not just the imported modules. This seems to confirm the original finding and that it exists for quite some time.

**Comment by wpk-** [comment]
Rather than importing from the ESM bundle, I worked around the issue by importing from src instead. The following, when compiled with rollup, gives me a much reduced file. Hope this helps.

```
import Tabulator from './tabulator/src/js/core/Tabulator.js'
import LayoutModule from './tabulator/src/js/modules/Layout/Layout.js'
import LocalizeModule from './tabulator/src/js/modules/Localize/Localize.js'
import CommsModule from './tabulator/src/js/modules/Comms/Comms.js'
import FormatModule from './tabulator/src/js/modules/Format/Format.js'
import EditModule from './tabulator/src/js/modules/Edit/Edit.js'

Tabulator.registerModule([
    LayoutModule,
    LocalizeModule,
    CommsModule,
    FormatModule,
    EditModule,
])
```

**Comment by diervo** [comment]
Interesting, that matches with the explanation from @olifolkerd, seems that the changes are much more trivial that I though if is just due to the current dist esm issue.

Will try to take a stab at it shortly.

**Comment by devicious** [comment]
Any update on this issue?

**Comment by olifolkerd** [comment]
Hey Everyone,

Great News!

Ive just started work on the 6.0 release, that im hoping to get out in the next month or so, and the first thing i have fixed is the ESM tree shaking, which I can now confirm is working on the 6.0 branch.

For those that are interested there were a three main issues that were preventing the tree shaking algorithm from being able to trace the dependency graph correctly:

- There were a couple of circular dependencies, these have now been restructured
- The modules made use of properties defined on the class prototype, these seemed to upset the tree shaking algorithm and have been moved to static properties on the class
- The module binder handled module classes dynamically which the tree shaking algorithm couldn't track, this functionality has now been rebuilt to allow for a fully static setup.

when v6.0 is released, i will remove references to tree shaking from the 5.x docs to avoid confusion

Cheers

Oli :)
