### ISSUE TITLE
headerSortElement can get wrong with Ajax Progressive Loads if the user clicks too fast on the header column

### ISSUE THREAD

**Issue by MetallianFR68** [olifolkerd/tabulator#4074]
I use remote sort with ajax progressive loading

If my users click two times on the same column header very fast, the headerSortElement can get wrong.
(Yes my users are stressed people !)

As I understand, it happens if the click happens before the previous ajax request was fullfilled.
In this case, i get this error in the console : 
![image](https://user-images.githubusercontent.com/6049266/209425582-beb18286-8c69-476a-a62e-6d31a0e1a73c.png)
Nevertheless, the headerSortElement is updated

So it happens that the headerSortElement show an ASC order while the data is still displayed DESC order

Very minor issue but worth mentionning

**Comment by MetallianFR68** [comment]
Here's a JSFIDDLE to demonstrate
https://jsfiddle.net/MetallianFR68/3gbv4yt6/2/
Try double clicking fast on first column header

**Comment by olifolkerd** [comment]
Hey @MetallianFR68 

The console warning is correct, it is saying that it has blocked the response from the orginal sort request because there is a new request sorted in the other order.

Cheers

Oli :)

**Comment by marcfal** [comment]
Hi,

I'm getting the same issue : data load is triggered for both sorts, but the displayed data corresponds to the first sort.
The problem is that in the table, the sort indicator displayed does **not** match the sorting of the data (for example the table is showing a sort by Name ascending, while the data is sorted by Name descending).

I'm using `progressiveLoad: "scroll"`, which seems to trigger multiple ajax calls, so while the first page has finished loading and the sort controls are enabled, the next pages are still being loaded in the background, triggering the "Data Load Response Blocked" warning if the user clicks on a header to sort. The only way I've found to avoid the issue so far has been increasing the page size to a high number so that only one page is loaded initially.
