### ISSUE TITLE
dataTree:true and table.getDataCount() combo return an incorrect number of visible rows

### ISSUE THREAD

**Issue by SmileSoftSr** [olifolkerd/tabulator#4077]
Version: 5.4.3 (linked from CDNJS)
Browser: Firefox 106
OS: Windows 10

When using `dataTree: true` and checking for the number of rows **shown** / **visible** in the table, I'm always getting the number of main rows, and the sub-rows are not counted.

For example:

```
+ Alice (main row)
+ Bob (main row)

table.getDatacount(); // 2
```

Then, when expanded:

```
- Alice (main row)
  ... (1) Alice (sub-level)
  ... (2) Alice (sub-level)
+ Bob (main row)

table.getDatacount(); // 2
```

It should be 4. This happens with `table.getDatacount(true);`, as well.

The fiddle can be found [here](https://jsfiddle.net/ncog5he6/).

Are there any other **native** ways of properly counting the rows?

**Comment by olifolkerd** [comment]
Hey @SmileSoftSr 

This is because Tree children dont count as full rows in Tabulator, only the top level rows do.

The child rows are injected by the tree module after the data has been processed.

In this case i would suggest using the `getRows` function and passing in the `visible` option as the first argument, then looking at the number of rows in the returned array.

Cheers

Oli :)
