### ISSUE TITLE
clearHeaderFilter stops working after column definition is updated

### ISSUE THREAD

**Issue by toneb** [olifolkerd/tabulator#4079]
**Describe the bug**
If column definition of column with header filter is modified, then ```clearHeaderFilter``` stops working.

**Tabulator Info**
5.4.3

**Working Example**
JSFiddle: https://jsfiddle.net/3tzvnru8/1/

**To Reproduce**
``` javascript
// update column definition of a column having header filter
await table.updateColumnDefinition("name", { title: "Name2" });

// fails, either after being called immediatelly or if called later
await table.clearHeaderFilter();
```

Error:
![image](https://user-images.githubusercontent.com/616279/210411008-8c6af047-124f-46d4-ba80-0cc221e2c707.png)

**Comment by olifolkerd** [comment]
Hey @toneb 

This is because the `updateColumnDefinition` function is asynchronous and returns a promise, you are trying to clear the header filters while they are in the process of being rebuilt.

Wait for the promise returned from the `updateColumnDefinition`  to resolve before calling your next function and all should work as expected.

Cheers

Oli :)

**Comment by tumblewader** [comment]
This bug is still there and is also affecting us.
