### ISSUE TITLE
Column Setup: Headerfilter potentially interferes with editor setup

### ISSUE THREAD

**Issue by JLGarber** [olifolkerd/tabulator#4085]
**Describe the bug**
When the`headerFilter` property is set on a column definition, the `editorParams` object passed to `_initializeParams()` is empty.<https://github.com/olifolkerd/tabulator/blob/c09c538169847ec31bcc9529fe4b20bdaa741e79/src/js/modules/Edit/List.js#L164>
This causes a spurious warning for a missing values definition. Note that this doesn't seem to have any impact on actual functionality, as the list will still populate. However, it is slightly annoying to have spurious warnings, and it's possible this indicates some other problem that hasn't affected me personally.

**Tabulator and Browser Info**
Tabulator 5.4.2 and 5.4.3.
Windows 10/11 desktop
Chrome 108.0.5359.125 and Firefox 108.0.1.

**Working Example**
Issue demonstration with spurious console warning: <https://jsfiddle.net/k47rxthy/2/>

Same setup, no `headerFilter`, no spurious warning: <https://jsfiddle.net/rems0f1o/3/>
-->

**To Reproduce**
Open each fiddle and run with the JSFiddle console open

**Comment by olifolkerd** [comment]
Hey @JLGarber 

This is because you are not passing the params to the `headerFilterParams` option. Setting the `headerFlter` option to `true` only tells the system to use the same type of editor as the cell, but does not pass the params for that editor as well.

If you set the params to the same as the editor you will see it all functions correctly.

Cheers

Oli :)
