### ISSUE TITLE
ContextMenu does not register on upclick dragged

### ISSUE THREAD

**Issue by simon1tan** [olifolkerd/tabulator#4090]
**Describe the bug**
context menu does not register a upclick when being dragged. Often times, I'll hold down the left mouse button, and change my mind and move to another item and release the left mouse button(mouseup) but nothing happens. I guess I am used to doing this and most programs that I have used get it right.

**Tabulator Info**
5.4.1, 5.4.3

**Working Example**
https://tabulator.info/docs/5.4/menu 
The first tabulator under Menu

**To Reproduce**
1. Right click on "Oli Bob" to activate contextmenu
2. hold down leftclick on "Change Name"
3. drag-move mouse over to "Select Row"
4. release leftclick

**Expected behavior**
It is expected that the menu where I let go of the leftclick is activated

**Desktop (please complete the following information):**
 - OS: Windows 10Pro
 - Browser: Chrome and Firefox
 - Version: Latest versions

**Comment by olifolkerd** [comment]
Hey @simon1tan 

Thanks for getting in touch

This is because the menu selection is triggered on the context click event rather than mouse up.

This is a bit of a niche usage case and has not gained any community feedback, given the amount of effort needed to manage this VS the single affected user at present, I'm afraid I will not be looking to change this behaviour.

If more members of the community want to register an interest in this issue then i will happily look at revisiting it.

Cheers

Oli :)
