### ISSUE TITLE
Is remote validation possible?

### ISSUE THREAD

**Issue by argo-uka** [olifolkerd/tabulator#4098]
I've been trying to validate some data. I need to do it on the server because the cell depends on some other data in the database. Some complex logic that can only be run on the server, because it involves too many tables.

I've tried this simple example, with a custom validator
```jsx
var validateRemote = async function (cell, value, parameters) {
    await client({
        method: "users@validate",
        params: {
            field: "xxxx",
            value: "xxxxx"
        }
    })
    return false;
}
```

and I setup a column with this definition
```jsx
...
{
  title: "Name", 
  field: "name", 
  editor: "input", 
  sorter: null,
  headerFilter: "input",
  validator: [{ type: validateRemote, parameters: {} }]
}
....              
```

So, the `await client({})` is just our interface, on top of axios, to our RPC server. The RPC request is made correctly. But the cell never get highlighted, even tough `validateMode: 'highlight'`. Everything works as expected if remove the `await/async` and the `client({})`.

It there anything, I'm missing? It just seens that the validator doesn't await for the `return false` nor it gets the `return false`.
In fact, when the RPC requested has endend, if I try in the console `table.getInvalidCells()`, it returns an empty array.

**Comment by olifolkerd** [comment]
Hey @argo-uka 

Remote validation is not possible, because Tabulator uses the browsers focus event logic to move between cells it must be able to synchronously determine the validity of the edit in order to cancel the focus event if the edit is invalid.

It couldn't do this asynchronously because then the user would already have focus on the next cell and be editing.

Cheers

Oli :)
