### ISSUE TITLE
updating row with parent does not work

### ISSUE THREAD

**Issue by j-lim-sigma** [olifolkerd/tabulator#4114]
**Describe the bug**

When the table is displaying tree structure, it is not possible to update the child data.

**Tabulator Info**

Tabulator version: 5.4

**Working Example**

JSFiddle: https://jsfiddle.net/jlimfiddle/k2pwvyt0/3/

**To Reproduce**

1. expand all row (click on "expand" button)
2. Click on 'frame' (child of 'desk')

**Expected behavior**

'frame' should be updated to be: 'frame updated'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.1
 - Browser: safari
 - Version:  16.2 (18614.3.7.1.5)

**Comment by olifolkerd** [comment]
Hey @j-lim-sigma 

This is because child rows are not full rows in their own right. they are generated from the parent row data when the row is rendered and injected into the DOM.

In this case the correct approach would be to update the data in the `_children` array on parent that will trigger a redraw of the table with the updated data.

A rebuild of the Tree module to make the child rows, fully functional in their own right has been requested, and will be looked into for a later release.

Cheers

Oli :)
