### ISSUE TITLE
Horizontal scrollbar appears with fitColumns in Chrome

### ISSUE THREAD

**Issue by Andrisa1** [olifolkerd/tabulator#4130]
**Describe the bug**
Horizontal scrollbar appears with fitColumns in Chrome

**Tabulator Info**
5.4.4

**Working Example**
https://jsfiddle.net/9bostkwe/1/

**To Reproduce**
Click multiple times on "add row"

**Expected behavior**
Horizontal scrollbar shouldn't appear as fitColumns is used.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 109.0.5414.119 (Official Build) (64-bit) 

**Additional context**
It seems there is a workaround to call table.redraw() after table.replaceData() as in https://jsfiddle.net/r4msz8dk/

**Comment by olifolkerd** [comment]
Hey @Andrisa1 

This is happening because the vertical scroll bar is added which causes the columns to no longer fit in the space.

This is because the layout system is not called when a row is added, only when the `setData` function is called or the table is resized. The `replaceData`  function is intended for in situ data replacement, It could be jaring for the user for the columns to suddenly resize in this manor. it may not in your example because it is simple text, but if there are visual formatters like images or wrapping text this could cause the vertical position of the table contents to shift.

For this reason I would not consider this to be a bug.

If you want the table to behave as described, then you are correct in saying you can call `redraw` after the update

Cheers

Oli :)
