### ISSUE TITLE
editor:"time" not allows editing the time correctly in a browser with 24hour format

### ISSUE THREAD

**Issue by surfNicolas** [olifolkerd/tabulator#4141]
**Describe the bug**
the value of the field time is "18:00:00", the display format: 06:00 PM. 
By clicking in the time field  it shows: 06:00. 
It should show 18:00 to allow a correct editing.

**Tabulator Info**
5.5.4

**Working Example**
the fiddle:
https://jsfiddle.net/surfnicolas/0c7f8gd3/

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - german windows 10
 - Chrome, Version 110.0.5481.178 (

**Comment by simon1tan** [comment]
why is your outFormat hh?

**Comment by simon1tan** [comment]
I confirm the issue. 

Also, "Because this editor uses the default time type input element, it is up to each browser to choose how the time picker will function and be styled, which may lead to an inconsistent look and feel. If you need consistent functionality across browsers then it recomended that you make a [custom editor](https://tabulator.info/docs/5.4/edit#edit-custom) using an external time picker library." 
Based on this, I'm not sure this is a bug, more of a known problem.

**Comment by SultanOrazbayev** [comment]
Just to add that I ran into this issue also, with slightly different behaviour, but long story short using 'time' editor doesn't work as expected.

**Comment by wp666666** [comment]
I encountered the same issue and I believe it's due to inaccurate format conversion at line 40 in the datetime.js file. The code "newDatetime.toFormat("hh:mm")" converts the time format into 12-hour system instead of 24-hour system, i think it should be "newDatetime.toFormat("HH:mm")" instead.
![image](https://user-images.githubusercontent.com/63539380/233897350-b3a98415-6576-412f-a6fa-bbed1c5ed23e.png)

**Comment by surfNicolas** [comment]
It depend on the browser. Like this you find out, if the browser has 12 or
24 hour format:

function getLuxonLocaleTimeString(){
  var mydate=new Date(2000,12-1,31,10,0,0);
if(mydate.toLocaleTimeString().indexOf('AM')==-1){
  return "HH:mm";
  }else{
  return "hh:mm a";
  }
}

mit freundlichen Grüßen
Klaus Eisert
Bechhausenerstr. 8
51399 Burscheid
Tel: 02174 748999
Email: ***@***.***
Web: https://tom24.info/


Am Mo., 24. Apr. 2023 um 06:02 Uhr schrieb wp666666 <
***@***.***>:

**Comment by olifolkerd** [comment]
Hey all, 

Thanks for the headsup, i have pushed a fix for this to the master branch and will include it in todays patch update.

Cheers

Oli :)
