### ISSUE TITLE
Download HTML example not working

### ISSUE THREAD

**Issue by riziles** [olifolkerd/tabulator#4146]
**Website Page**
<https://tabulator.info/docs/5.4/download#overview>

**Describe the issue**
Nothing happens when I click the "Download HTML" button. Chrome developer tools says that there is no `click` event listener, but all the other buttons (e.g. CSV, JSON, etc) have one. Would try to troubleshoot deeper, but I wasn't sure where the source code for the docs were.

**Comment by AmolPawar7181** [comment]
Hi @olifolkerd , I can see the above mention issue #4146 happens because the **document.getElementById("download-html").addEventListener** is nested inside callback function of **document.getElementById("download-pdf").addEventListener**

```
document.getElementById("download-pdf").addEventListener("click", function(){
        example_table_download.download("pdf", "data.pdf", {
            orientation:"portrait",
            title:"Dynamics Quotation Report",
        });

        document.getElementById("download-html").addEventListener("click", function(){
            example_table_download.download("html", "data.html", {style:true});
        });
    });
``` 
I would love to contribute to your project, let me know.
Thanks.

**Comment by olifolkerd** [comment]
Hey @riziles @AmolPawar7181 

Thanks for the headsup, I have pushed a fix for this to the website and will include it with the 5.5 release site update later today.

Cheers

Oli :)
