### ISSUE TITLE
table.addRow() does not work as expected

### ISSUE THREAD

**Issue by scry-UrjitDesai** [olifolkerd/tabulator#4152]
I am using tabulator-tables in angular. I want to be able to add new empty rows above or below a specific row that has been right clicked. Currently the implementation is buggy. It sometimes adds a new row correctly and sometimes it does not. Here it the link to the demo.
https://stackblitz.com/edit/angular-ivy-srtlwq?file=src%2Fapp%2Fexample-table%2Fexample-table.component.ts 

To replicate the issue, try right clicking on a populated row and add a row above twice. 
Any help is appreciated. Thank you!

**Comment by arpsmack** [comment]
Unfortunately, row indexes don't work the way you think they do. See https://tabulator.info/docs/5.4/data#row-index

The "index" of a row is actually its "id".

Try this slight modification of your example that assigns an auto-incrementing id to each row, and passes the row object into `addRow` instead of its position:

https://jsfiddle.net/54pm0j62/2/

If you don't like that the row isn't completely empty, you could always make `id` a hidden field and not assign a view column to it.
