### ISSUE TITLE
Extra column end the end of the table

### ISSUE THREAD

**Issue by szszabolcs** [olifolkerd/tabulator#4167]
Hi Everyone,

Could you please help how can I remove the extra column added by tabulator?
Layout settings are not working for this purpose and I checked documentation and forums previously but I did not find solution.
This is neither in the tabulator-col class and nor in the tabulator-row class  
Thank you,
Szabolcs
![Extra_column](https://user-images.githubusercontent.com/26326382/233111573-4123562a-741f-4874-aa9f-6380ffb45a7f.PNG)

**Comment by olifolkerd** [comment]
Hey @szszabolcs 

There is no extra column there, this is because the table is taking up the full with of the container.

If you think you have found an issue, please start by asking a question on the Discord server.

If you still think you have found a bug, please create an issue, using the issue template and include a link to a JS fiddle that demonstrates your issue, without siding your setup it is not possible to advise.

Cheers

Oli :)
