### ISSUE TITLE
XSS vulnerability?

### ISSUE THREAD

**Issue by nirhu** [olifolkerd/tabulator#4168]
**Describe the bug**
When using formatter for a cell, it is possible to execute script contained in the value.

**Tabulator Info**
5.4

**Working Example**
https://jsfiddle.net/o7p48fv5/

**To Reproduce**
Observe an alert on top of page.

**Expected behavior**
The script should not be executed. Value should be in the table.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: newest

Not sure if i should handle this in the formatter (e.g. escape string) or it is something tabulator should do. I welcome your suggestions. Thanks :)

**Comment by ferulisses** [comment]
Hi,

I'm not sure if this is really a XSS vulnerability, since these kind of vulnerability consist of data been passed by an external source, like a query string or inputted by a third party without user intent, it's not the case here.

About the code been executed, you are using a raw formatter that return the cell contents, it's the formatter obligation to render it in a safe way, if you remove your formatter, the original tabulator formatter will skip the dangerous code.

But, since the data rendered usually comes from an API request, it's embedded on page or it's inputted by user, there is no need to do the filtering, but if it's your use case (receive data from untrusted sources), you can use a sanitize function.

About tabulator handling the output of a formatter, I think that it's not a good idea, we don't know that someone will code, it's useful to render any HTML and even some Javascript into columns.

I modified your code just to include a formatter that needs to be rendered the way it is, I also used a simple sanitizer to avoid running the dangerous input:

https://jsfiddle.net/7t26ofmj/3/

**Comment by olifolkerd** [comment]
Hey @a
