### ISSUE TITLE
cellClick stopPropagation does not work

### ISSUE THREAD

**Issue by jinchris** [olifolkerd/tabulator#4174]
**Describe the bug**
stopPropagation() on a cellClick event listener does not prevent bubbling.

**Tabulator Info**
- 5.4.4

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

https://jsfiddle.net/u0cjyq7a/2/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/u0cjyq7a/2/
2. Open the browser developer tools > console
3. Click on one of the rows
4. In the console, we should only see the log for "CELL CLICK" but "ROW CLICK" appears as well despite the presence of e.stopPropagation() method in the cellClick event listener

**Expected behavior**
We should only see cellClick event fire

**Screenshots**

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Browser: Chrome
 - Version: 112.0.5615.165 (Official Build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @jinchris 

This is the expected behaviour. This is because Tabulator does not put the event binding on the element itself but on the table container, it then traces back the event to its element and they triggers the event.

The reason this is done is to improve table efficiency, if you have a table with 100,000 rows, that is a huge number of event bindings if you are listening to every cell on every row. This would cause a significant increase in memory usage and processing time.

I will update the docs to make it clear that this isnt possible.

Cheers

Oli :)
