### ISSUE TITLE
minMax filter i.e. number is between range

### ISSUE THREAD

**Issue by 8483** [olifolkerd/tabulator#4186]
**DISCLAIMER:** I am well aware that you want to keep the library free of such implementations. I believe it's worth hearing me out. :)

*Is your feature request related to a problem? Please describe.**
It's really convenient to filter number columns, where the values are between a range.

**Describe the solution you'd like**
A default header filter for numbers (going both ways), as it is such a common use case.

**Describe alternatives you've considered**
I've previously had to choose between smaller/greater than or equal filters.

**Additional context**
Here's how my solution looks like.

![minmax](https://github.com/olifolkerd/tabulator/assets/16456606/8a99b7d6-adb0-46e3-bc05-6f412d59b329)

Here's the column definition:

```js
{
    title: "title",
    field: "field",
    headerFilter: minMaxFilter,
};
```

Here is the filter function code:

```js
function minMaxFilter(cell) {
    let min = -Infinity;
    let max = Infinity;

    function filterFunc(data, filterParams) {
        let value = data[cell.getField()] || 0;

        min = min ? min : -Infinity;
        max = max ? max : Infinity;

        return value >= parseFloat(min) && value <= parseFloat(max);
    }

    let wrapper = document.createElement("div");

    let inputMin = document.createElement("input");
    inputMin.placeholder = ">=";
    inputMin.style.cssText = `
        width: 48%; 
        margin-right: 4%;
        padding-left: 5px;
    `;

    inputMin.addEventListener("keyup", (e) => {
        min = e.target.value;
        cell.getColumn().getTable().removeFilter(filterFunc);
        cell.getColumn().getTable().addFilter(filterFunc);
    });

    wrapper.appendChild(inputMin);

    let inputMax = document.createElement("input");
    inputMax.placeholder = "<=";
    inputMax.style.cssText = `
        width: 48%; 
        padding-left: 5px;
    `;

    inputMax.addEventListener("keyup", (e) => {
        max = e.target.value;
        cell.getColumn().getTable().removeFilter(filterFunc);
        cell.getColumn().getTable().addFilter(filterFunc);
    });

    wrapper.appendChild(inputMax);

    return wrapper;
}
```

**Comment by olifolkerd** [comment]
Hey @8483 

Thanks for your suggestion, Im it clearly represents very good value for your usage case.

Though you are correct in saying that i am not looking to add this type of filter to the library, dual value filters are very context specific and how they need to be rendered to make sense to the user will depend on usage case. For this reason i will not be looking to include it in the library.

That being said, if you head over to the discord server, i would recommend posting a link to your code on the "look what i made" section, so that others can see what you have built.

Cheers

Oli :)
