### ISSUE TITLE
Expanding a group near the bottom of the table scrolls the page to top 

### ISSUE THREAD

**Issue by lukecotter** [olifolkerd/tabulator#4187]
**Describe the bug**

When expanding a group the page is scrolled up 

**Tabulator Info**
- Which version of Tabulator are you using?
v5.4.4

**Working Example**
https://jsfiddle.net/1fmw57ep/3/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/1fmw57ep/3/
2. Scroll down to the bottom 
3. Expand the very bottom row (or any near the bottom)
4. The page is scroll up / to the top

**Expected behavior**
Focus stays where it is so the expanded row can be seen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3 
 - Browser: Chrome v113.0.5672.92

**Comment by olifolkerd** [comment]
Hey @lukecotter 

This is happening because you have the height of your table set to 100% in a container (ie body) that has no height itself. as the group is expanded it changes the size of the table, which changes the size of the body which triggers a redraw.

Either set a fixed height on the table, or ensure that there is enough space in the body for the table to grow.

Cheers

Oli :)

**Comment by lukecotter** [comment]
Thanks for the response.
My case is a little different to the one I shared but I can not replicate in a fiddle.
I am sure I will resolve it :)
