### ISSUE TITLE
Setting paginationElement loses all pagination styles

### ISSUE THREAD

**Issue by jonatanschroeder** [olifolkerd/tabulator#4241]
**Describe the bug**

While a `paginationElement` can be set to an element outside the table, the styles (both for default style and Bootstrap, I haven't tested other themes) rely on the element being inside the footer. Setting a pagination element loses all styling effects.

**Tabulator Info**
- Which version of Tabulator are you using?

Tabulator 5.5 with Bootstrap 4 theme.

**Working Example**
YOU MUST include a link to a JS Fiddle or Codepen that demonstrates the problem, it is very hard to diagnose an issue from a simple description.

https://codepen.io/jonatanschroeder/pen/wvQpNxq

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. If in the JS code paginationElement is set, the pagination controls go to the placeholder, but without styles.
2. If in the JS code paginationElement is not set (default), the pagination controls use the footer with proper styles.

**Expected behavior**

I believe the styles for pagination should be independent of the location of pagination controls (inside or outside the tabulator or the footer). A viable alternative would be to set up a specific CSS class that can be applied to the placeholder for appropriate styles to be used.

**Screenshots**

If set: 
<img width="233" alt="image" src="https://github.com/olifolkerd/tabulator/assets/1004907/b92df937-0f6c-48a8-b3f7-40d98f3c5b4b">

If not set:
<img width="637" alt="image" src="https://github.com/olifolkerd/tabulator/assets/1004907/341f7021-2354-4297-b76d-0610ca8bdc2a">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version 114.0.1823.67

**Additional context**

**Comment by olifolkerd** [comment]
Hey @jonatanschroeder 

Tabulator only styles elements within its containing element, to do otherwise would risk breaking the styling of the rest of the document, this is standard practice.

If you want a pagination element outside of Tabulator then it is a bespoke addition to your project and Tabulator has no idea what your intentions are and you are therefor responsible for styling it.

All the same classes are applied so you could simply copy the styling CSS that already exists and simplify the selectors yourself.

Cheers

Oli :)
