### ISSUE TITLE
Objects added via onRendered appear as undefined when collapsed

### ISSUE THREAD

**Issue by mitchray** [olifolkerd/tabulator#4256]
**Describe the bug**
Objects added via onRendered appear as undefined when collapsed - ```responsiveLayout: "collapse"```

**Tabulator Info**
5.5.1

**Working Example**
https://jsfiddle.net/70o9nc4v/

**To Reproduce**
1. onRendered output as expected in the table cell
2. Resize the window to trigger the "onRenderer Example" becoming collapsed
3. The Sparklines object is not rendered, instead you see 'undefined'

**Expected behavior**
The returned value from onRendered should also appear in the collapsed view

**Screenshots**
Shows as expected in normal cell
![firefox_hGxWbh4SCM](https://github.com/olifolkerd/tabulator/assets/5735900/8800fad1-1780-44d7-a529-48aa0fe4370a)

```undefined``` in collapsed view
![firefox_vdRlpigIHi](https://github.com/olifolkerd/tabulator/assets/5735900/2db205cb-16fa-4d5b-8546-4b81eeba3c3e)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [115.0.3]

**Comment by olifolkerd** [comment]
Hey @mitchray 

The issue you are seing here is happening for two reasons,

The first is that you are not retutning anything from the formatter, therefor the value is undefined, which is what is causing the text to appear.

The second is that a sparkline fomatter will not work on the responsive view, because that view uses a pusdo cell component to render which does not behave the same as a normal cell.

To resolve both of these i would suggest returning a div from the formatter with height and width set. that should resolve both issues.

Cheers

Oli :)
