### ISSUE TITLE
rowSelected event callback runs twice when used inside of renderComplete event callback

### ISSUE THREAD

**Issue by Deepakeon** [olifolkerd/tabulator#4348]
**Describe the bug**
when i use rowSelected event inside of renderComplete event callback, than rowSelected event callback runs twice

**Tabulator Info**
- Which version of Tabulator are you using?
- v5.5.2

**Working Example**
- https://jsfiddle.net/zolt_eon/zxj3qu1s/31/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. sort or filter the name column once
2. than click on the checkbox of any row
3. in console the selection text will be visible twice for only one selection

**Expected behavior**
- the rowSelected event callback should only once

**Screenshots**
- refer to jsFiddle

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] edge
 - Version [e.g. 22] 120.0.2210.61 (Official build) (64-bit)

**Comment by olifolkerd** [comment]
Hey @Deepakeon 

This is happening because you are trying to register a callback inside of another callback, therefore very time the table renders you are registering an additional row selected callback, the more times the table is renderered the more console logs you will see.

You need to register the callbacks one after the other, not inside eachother.

Cheers

Oli :)
