### ISSUE TITLE
General

### ISSUE THREAD

**Issue by 500Foods** [olifolkerd/tabulator#4371]
It might be an idea to add an extra bit to some of the topic titles that indicate when the feature being documented was added or significantly upgraded in Tabulator? 

For example, the "Validation Mode" functionality is something you referenced in one of the posts you responded to during today's patch release. I don't recall running across it before. Nice feature, btw. But it seems it has been around since well before v5 and I've just never known about it. Somehow. 

It may not be worth the trouble to go back and add it for all topics, but something to maybe add as new features roll out? So If I'm looking at the docs for a future v5.7 or something, I can see that whatever feature I'm reading about was added in v5.2. 

I can of course read the release notes, but often when looking at those, it's easy to overlook items that aren't relevant at the time.

Another example is that I see that the "unique" column calculation finally made it out (you added this a while ago, but is just now in the 5.5 release notes). Yay, thanks!

**Comment by olifolkerd** [comment]
Hey @500Foods 

I did actually used to do this but it became a bit of a nightmare and got very cluttered, the problem comes that features evolve over time and so trying to track every change just results in a messy UI.

The release notes cover every single feature and change that happen in each release, so if you are interested in finding out about the latest features in each release, just check out the release notes.

Cheers

Oli :)
