### ISSUE TITLE
Tabulator ESM with Sveltekit and Vite

### ISSUE THREAD

**Issue by tadmi** [olifolkerd/tabulator#4378]
Tabulator 5.5.4
Sveltekit 2.5.0 (built with Vite 5.0.12)

Possible problem
![image](https://github.com/olifolkerd/tabulator/assets/63556979/b3a257bb-9b5f-44b1-9e2c-3a540f5508f5)

and solution: add in tabulator-tables package.json **type: module**.

The problem appeared with Vite 5.0.8:
specific change — fix(ssr): check esm file with normal file path (#15307) (1597170), closes #15307

**Comment by olifolkerd** [comment]
Hey @tadmi ,

The challenge with your proposed solution is that Tabulator is not just a module, it offers both ESM and UMD options, which is why you will see in the package.json that it offers both a `main` and a `module`.

This works by allowing your task runner to pick whichever version is correct depending on whether you are running as a module  or not.

You may need to update your projects package.json to handle this. If i add your proposed solution, it will break it for all UMD users.

I use tabulator in many ESM projects with the current package.json without any issues.

Cheers

Oli :)

**Comment by novecento** [comment]
sorry: what does it mean "You may need to update your projects package.json to handle this." ?

**Comment by novecento** [comment]
If I use 
import * as TabulatorFull from 'tabulator-tables';
const { Tabulator } = TabulatorFull;

Tabulator doesn't work well (ie tree not works)

If I use 
import {TabulatorFull as Tabulator} from 'tabulator-tables';

Error when evaluating SSR module /src/lib/components/common/Tabulator.svelte: failed to import "tabulator-tables"
|- SyntaxError: [vite] Named export 'TabulatorFull' not found. The requested module 'tabulator-tables' is a CommonJS module, which may not support all module.exports as named exports.

apologies if it's a stupid question..

**Comment by thisjt** [comment]
I think we need to reopen this issue. Here's a minimum reproducible repo of the issue using SvelteKit.

(File is in `src/routes/+page.svelte`)
https://github.com/thisjt/tabulator-import-issue

Here is the result on dev run
![image](https://github.com/olifolkerd/tabulator/assets/64672207/b35330ad-7466-431c-8a78-76f453441869)

I didn't have this issue when I was on Vite 4, but when I was forced to update to Vite 5 as it is a requirement for SvelteKit 2.0 due to Vercel recommending me to migrate from SvelteKit 1 to 2, this issue started showing up on my imports.

**Comment by thisjt** [comment]
For those wondering what my workaround for this one is, this is how I was importing the `TabulatorFull` variable from `'tabulator-tables'`

```
	import * as Tabulator_Import from 'tabulator-tables';
	const { TabulatorFull: Tabulator } = Tabulator_Import;
```

**Comment by olifolkerd** [comment]
@thisjt This only happens with the latest version of sveltKit and literally nothing else. I use tabulator in many projects with many different build tools and not a single one throws an error.

Given the 1000s of users of Tabulator if this was a package configuration error of significant size this issues list would be inundated.

If I change the package.json as suggested it will literally break the UMD importing of the package.

I'm not a vite user myself, so don't have the setup to test this one. But if a member of the vite using community wants to come up with a fix and submit a PR then I would be very happy to do a patch release as long as it doesn't break the package for everyone else.

Cheers

Oli :)

**Comment by thisjt** [comment]
Instead of the suggested fix, maybe a wrapper specifically for SvelteKit 2 would be a better (temporary) suggestion. However, it would be kind of a waste of time making it. Let me try raising a ticket on the Vite repo and see what they can find with this issue.

Is it also potentially possible that this issue started showing up because of Svelte 4 removing support for cjs bundling as per PR https://github.com/sveltejs/svelte/pull/8613? This could be why the issue is only showing up specifically on SvelteKit and not on any other Front-end Frameworks.

**Comment by thisjt** [comment]
@olifolkerd we have received some answers with regards to the issue with SvelteKit compatibility. You may check on the linked bug above for some info.

![image](https://github.com/olifolkerd/tabulator/assets/64672207/faf5c224-1870-49a1-a186-4f0a728cb248)

I'm currently in the process of creating a repo for reproducing the issue not existing in SvelteKit@1, a barebones project in Vite@5, and fixing the SvelteKit@2 sample repo not working in Stackblitz. He has a different advise with changing the filename of `/dist/js/tabulator_esm.js` to `/dist/js/tabulator_esm.mjs`, but not sure how that will affect the entire project.

If this is too much of a risk for a change, maybe the aforementioned SvelteKit wrapper of tabulator would be viable, or honestly I would just document it on the website on my suggested workaround with importing the table specifically for SvelteKit users. At least they won't be left out.

**Comment by gatewaynode** [comment]
Just ran into this as well, I tested adding `"type": "module",` after the "module" declaration on line 8 of the tabulator `package.json` and this does seem to fix the import issue in SvelteKit 2.  Seems this additional K/V here might be fairly safe, or at least worth testing more, want a PR for it?

**Comment by olifolkerd** [comment]
@gatewaynode as described several times above if I did that it would break cjs/umd importing.

There are two different ways to import a package. And the current configuration of the package.json is the approved way to structure a package.json that allows for both cjs and esm importing.

I will not be making any changes that break the importability of this library to resolve an overly strict change in one build environment that is used by a small subset of users.

I'm happy to give the mjs approach outlined above a shot of that resolves things. But again will only include this if it does not break others access

Cheers

Oli

**Comment by olifolkerd** [comment]
@thisjt have you tried the .mjs extension change in your setup? And does it work? (You will need to change the file and possibly update the path in the package.json)

If that does work, then that would also work my end without breaking things. So could be a good opinion.

Cheers

Oli

**Comment by thisjt** [comment]
@olifolkerd I'm glad to say that it worked on my end. Here's what I did. Maybe you need to do some modification on your bundler as you need to build the ESM module as a `.mjs` extension.

```
  "module": "dist/js/tabulator_esm.mjs",
  "exports": {
    ".": {
      "require": "./dist/js/tabulator.js",
      "import": "./dist/js/tabulator_esm.mjs"
    }
  },
```

Changing `module` only and adding the `.mjs` extension did not work. We need the `exports` field in the `package.json` so that we can properly direct require and import. https://antfu.me/posts/publish-esm-and-cjs

I tried `tabulator_esm.js` on the import and module field but it throws an `Unexpected token 'export'` issue, so the rename to `.mjs` is really needed.

![image](https://github.com/olifolkerd/tabulator/assets/64672207/be570786-132e-4ad9-a597-f7d69bde2621)

I'd be happy to submit a PR for the changes in the `Bundler.mjs` and `package.json` if you're fine with that.

**Comment by thisjt** [comment]
@olifolkerd I have made the PR for the changes to `package.json` and `build/Bundler.mjs`. I'll let you do the building so that you can properly manage the versioning.
