### ISSUE TITLE
Copy Paste does not work when cell is represented by an object.

### ISSUE THREAD

**Issue by scry-UrjitDesai** [olifolkerd/tabulator#4426]
**Describe the bug**
When a cell is represented by an object, the copy-paste feature does not seem to work.
It works fine when the cell content is represented by a plain string.
It works fine when copying data from a cell represented by an object into a normal cell.

**Tabulator Info**
- 5.6.1

**Working Example**
https://jsfiddle.net/prdufj3v/1/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Try selecting a range of cells from the gender column and pasting it into the favorite color column. It does not work
2. Try selecting a range of cells from the gender column and pasting it into ratings or progress column. It works.

**Comment by olifolkerd** [comment]
Hey @scry-UrjitDesai 

That is the correct behaviour because the clipboard has no way to represent raw JS objects.

I(f you want that field to be able to be copied, you need to define an accessor on the column that can transform the data into something compatible with the clipboard.

Checkout the [Accessor Documentation](https://tabulator.info/docs/5.6/clipboard#accessors) for more details

Cheers

Oli :)
