### ISSUE TITLE
The highest security compatibility of Content Security Policy(CSP)

### ISSUE THREAD

**Issue by JunqiaoDuan** [olifolkerd/tabulator#4532]
*Is your feature request related to a problem? Please describe.**
I tried using this component to configure a strict CSP (Content Security Policy), but it caused functionality errors, prompting me to enable 'unsafe-inline'. Security is becoming increasingly important. Will this issue be addressed? What‘s the highest security compatibility of Content Security Policy(CSP)?

**Describe the solution you'd like**
Tell me the  highest security compatibility of Content Security Policy(CSP)?
And how to solve it?

**Describe alternatives you've considered**

**Additional context**

**Comment by olifolkerd** [comment]
Hey @JunqiaoDuan 

The CSP determines what scripts can be loaded from where, it would not be something specifically implemented in Tabulator but on the headers of your site.

If errors are being thrown it will be because you have setup your policy in such a way that either dependant files of Tabulator cannot be loaded, or actions the table is trying to perform have been  blocked by your policy.

Cheers

Oli :)
