### ISSUE TITLE
Rows don't appear correctly since upgrade to v3

### ISSUE THREAD

**Issue by shayo** [olifolkerd/tabulator#457]
Even on your website.
see http://olifolkerd.github.io/tabulator/quickstart/3.1/, at the bottom of the page.

**Comment by olifolkerd** [comment]
Hey,

Thanks for pointing that out, i wasn't linking to the correct source files on the quick start page, i have now fixed it.

If you are having the same issue on your site it will be because you aren't pointing at the correct source files. From 3.0 onwards they are located in the ***/dist*** folder.

If you are still running into trouble after you have changed your js and css files, post a copy of your constructor here and i can point out any changes you need to make as a number of the functions changed name as part of the overhaul from 2.12 to 3.0

Cheers

Oli
