### ISSUE TITLE
Is there a way to filter on blank values?

### ISSUE THREAD

**Issue by venkatrams** [olifolkerd/tabulator#465]
Hello

Is there a way to filter the column on blank values?

I have an email column which needs to be filled in always so I should be able to find all the records that dont have the email addresses?

Thanks in Advance.

**Comment by olifolkerd** [comment]
You can use the ***setFilter*** function for this:

```js
$("#example-table").tabulator("setFilter", "email", "=", "");
```

Cheers

Oli

**Comment by venkatrams** [comment]
Can I use the header filter to implement this functionality?

**Comment by olifolkerd** [comment]
how would you want this to behave, if you made it so it filtered like this when the header filter was empty you would never be able to view all the rows in a table.

If you could outline how this would work i can suggest a solution

**Comment by venkatrams** [comment]
Is there a way to use formatter or mutator to cushion the data to special value like "EMPTY" and by typing the empty can pull up only the data with empty columns
I tried this using formatter but when I try typing empty the filter doesnt work as the data is not altered.

When I try the same function with mutator the empty word doesnt show up.

Please let me know if this isnt clear enough

**Comment by 1manfactory** [comment]
Had the same problem. Solved it like this.

SQL

`IF (email IS NULL, '--', email) AS email`

HTML

`<option value='--'>{none}</option>`

**Comment by JustinGOSSES** [comment]
Not obvious to me how the last comment solves the problem. Maybe it does?

There are situations where people want to see all the rows that have one column that is blank. You currently can't add an input field above a column that filters on the input and filter on blanks. Nothing in the input field doesn't work. "" doesn't work. NaN doesn't work. 

Would be nice to let users do this in the header: http://tabulator.info/examples/4.0?#filter-header

**Comment by olifolkerd** [comment]
Hi Justin 

with a custom header filter function you can filter in any way you like. Checkout the filter documentation for more details.

On a side note if you are looking for assistance I would recommend asking on stack overflow. Posting on a 3 year old closed issue will rarely result in your getting the assistance you are hoping for.

Cheers

Oli

**Comment by mikeymckay** [comment]
I realize this issue is closes, but just wanted to share my findings since this is the place users will end up when searching:

$("#example-table").tabulator("setFilter", "email", "=", "");

This didn't work for me, because my value was undefined, so replacing "" with undefined solved it. 

Not very elegant but since you can't use the header filter field to do this, you could add a button to your page that adds the above filter, so that users can search for empty values.

Also, I think what @1manfactory was suggesting was to change empty strings (or undefined) to something searchable like "---" when creating the data for your table. That way you can search for the string that represents empty values in the header filter.

**Comment by JustinGOSSES** [comment]
Thanks @mikeymckay , this approach would have worked and I'll try it on next project. I don't control the incoming data, so the other suggestion to use "--" or similar wouldn't work in my case.
