### ISSUE TITLE
Layout: 

### ISSUE THREAD

**Issue by GerritKnippschild** [olifolkerd/tabulator#467]
Hi Oli,

I would be really glad, if you could help me with those two questions:

We were trying to use following combination:
**formatier:"textarea", formatter:fontSizeFormatter**

Code of fontSizeFormatter:
function fontSizeFormatter(value, data, cell, row, options, formatterParams){
var block = $("<span>" + value + "</span>");
block.css({
"font-size":14,
"cursor":"pointer",
});
return block;

But it seems, that Tabulator is only accepting one formatter and ignoring a second formatter when specified in combination.

Second question: Is it possible to specify a customized tool tip when using Tabulator.js, like jQuery ui tooltip format:
$("#tabulator_objektkinder").tooltip({ track: true, });

Cheers Gerrit

**Comment by Paraplegix** [comment]
Hello Gerrit,

As far as i know, you can't apply directly two formatter to one column. You will have to extend a bit more your custom formatter functions to achieve what you want. 
If the only thing you want for your cell is to be a textarea and control the fontsize, adding `"white-space":"pre-wrap"` in your `block.css` should be enough.

For the second question, you can define custom tooltip on a per column basis by using the tooltip param on column definition : see [Formatter](http://olifolkerd.github.io/tabulator/examples/3.1/#formatters) (scroll a bit for the tooltip section), adding `tooltip:true` will display the current value of the cell, or you can pass a custom function instead of true to display whatever the passed function will return.

**Comment by GerritKnippschild** [comment]
Hello Oli,

thank you very much. We could implement the tooltip and also used your "pre-wrap" tipp, as we just wanted to control the fontsize in an textarea.

Cheers,
Gerrit

**Comment by olifolkerd** [comment]
Hey Gerrit,

You seem to be using the old version of Tabulator, have you considered moving over to 3.1.5, it has a much improved rendering system. (version 3,2 is being released tommorow)

You will need to use a custom formatter to do this, in Tabulator 3.0+ it would be
```js
var fontSizeFormatter= function(cell, formatterParams){
    //cell - the cell component
    //formatterParams - parameters set for the column

    cell.getElement().css({
    	"font-size":14,
    	"cursor":"pointer",
    	"white-space":"pre-wrap",
    })

    return cell.getValue(); //return the contents of the cell;
}
```
For version 2.12 and below it would be:
```js
function fontSizeFormatter(value, data, cell, row, options, formatterParams){

	cell.css({
		"font-size":14,
		"cursor":"pointer",
		"white-space":"pre-wrap",
	});

	return value;
}
```

The tooltips specified through the cell definition array use the elements title attribute and so can only accept plain text (this is done to improve accessibility for people using screen readers etc)

You could also include this in your formatter, to add the jquery tooltip to the element.

for 3.0 +
```js
var fontSizeFormatter = function(cell, formatterParams){
    //cell - the cell component
    //formatterParams - parameters set for the column

    var element = cell.getElement();
    element.css({
    	"font-size":14,
    	"cursor":"pointer",
    	"white-space":"pre-wrap",
    })

    element.tooltip({ track: true, });

    return cell.getValue(); //return the contents of the cell;
}

```

for 2.12and below:
```js
function fontSizeFormatter(value, data, cell, row, options, formatterParams){

	cell.css({
		"font-size":14,
		"cursor":"pointer",
		"white-space":"pre-wrap",
	});

	cell.tooltip({ track: true, });

	return value;
}
```

Let me know if that helps,

Cheers,

Oli
