### ISSUE TITLE
scrolling Problem with overflow:visible

### ISSUE THREAD

**Issue by cschnelting** [olifolkerd/tabulator#495]
Hi Oli,

I have a Bootstrap DropDown-Element as Table Header-Filter. If it opens, the DropDown is visible behind the Table-Data, caused by "tabulator-col"- and "tabulator-header"-Element CSS Property "overflow: hidden". So I changed the CSS-Property from "tabulator-col"- and "tabulator-header"-Element to "overflow: visible". Now the DropDown is shown fine, but the horizontal Tabulator-Scrolling is not possible: I can scroll the table-data fine, but the Header-Elements doesn't scroll with the table-data. Can you help me to fix the scroll-Problem?

Thanks!

**Comment by olifolkerd** [comment]
Hey, Thanks for getting in touch,

Do you have a copy of your table constructor object and the dropdown filter you are using.

Cheers

Oli

**Comment by cschnelting** [comment]
Hi,
the scrolling-problem is independent from the dropdown-element. I can re-produce the error in your example-grid: http://olifolkerd.github.io/tabulator/examples/3.2/#frozen-col
When I only change the CSS-Property from "tabulator-col"- and "tabulator-header"-Element to "overflow: visible", I'm not able to scroll horizontal. The data can be scrolled, but the headers aren't scroll with the data-columns.

**Comment by olifolkerd** [comment]
Hey,

Changing the overflow will result in a malfunction of the table because it is needed for a variety of calculations and styling reasons.

The reason I asked if you could post your dropdown element code was so i could run some test against it and post a solution to your issue.

Without it i would be unable to ensure that the solution would be right for you.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @woxcab 

Yes that is expected behaviour when overflow is hidden, and im afraid that cannot change in the header as it is needed for the correct function of the table.

Most library's with pop up elements have an option that allows you to set where the popup sits in the DOM, to cover situations exactly like this, allowing it to be appended to the body rather than next to the element itself.

You will notice that in Tabulators built in ***select*** editor it appends the list to the DOM rather than the cell to get round exactly this issue.

Just so you know, multi select functionality will be coming to Tabulator in the next release.

Cheers

Oli :)

**Comment by dbauszus-glx** [comment]
@olifolkerd I am having the same problem after trying to implement a multi-select dropdown filter. You mention multi-select functionality in the last post. Is this available in the current release?
