### ISSUE TITLE
If tabulator starts inside a <DIV> with style ="Display;None;" Virtual Dom scroll bars are not visible

### ISSUE THREAD

**Issue by bluedog** [olifolkerd/tabulator#514]
If tabulator starts inside a DIV style = "display;none;" - after show(), setData and redraw the virtual dom scroll bars never appears. This is in context of a single page app with several tables with only 1 or 2 shown at a time. 

[tab_displaynone.zip](https://github.com/olifolkerd/tabulator/files/1220019/tab_displaynone.zip)
![display_none_2](https://user-images.githubusercontent.com/71191/29243788-bdfda412-7f75-11e7-9228-1a1f76b74b63.png)

**Comment by bluedog** [comment]
Also, if you change the field "seq" to visible=false the virtual dom scroll bar appears but the header is missing the two previous columns. 

![display_none_headers](https://user-images.githubusercontent.com/71191/29243877-36ef4810-7f78-11e7-84e9-effa9adf0d0e.png)

**Comment by olifolkerd** [comment]
Hey,

If you create your table on a hidden element you will need to call the ***redraw*** function when the table becomes visible to ensure it is displayed correctly:

```js
$("#example-table").tabulator("redraw", true); //trigger full rerender including all data and rows
```

This is because elements have no height or width until they are made visible in the DOM so Tabulator cannot calculate the values needed to render the table correctly unless it is visible.

Cheers

Oli
