### ISSUE TITLE
Field names with full stop no longer accepted

### ISSUE THREAD

**Issue by TomWhitson** [olifolkerd/tabulator#517]
I have some data in json with keys containing full stops. In the prior version this worked well by simply setting the field of the column to data.with.full.stops. However in the latest version the field name appears to be split based on the . in the string and my json data gets mutated as if each . was a new nested field of the json.

Do we have the possibility to still use field names with . characters in them

**Comment by olifolkerd** [comment]
Hey,

At the moment this is not possible as the ***.*** character is now used to denote child objects as standard dot notation when accessing multi-dimensional arrays.

I should say that it is considered very bad practice to us dots in your object keys, specifically because they are not valid JavaScript variable names and convention would usually dictate either snake_case or camelCase.

If you must use these keys then i can provide an example function to convert them into something usable by Tabulator.

Cheers

Oli

**Comment by TomWhitson** [comment]
Hi,

Fair enough, agree that yours is the normal usage of the dot notation, I was using Sequelize to get data and by default it provides all associations with dots rather than nesting so didn't really have an option. Anyway fair enough I can always change the data before giving it to tabulator.

**Comment by c-dante** [comment]
Follow up to this issue -- I don't expect it to be changed/addressed, but this puts some serious restrictions on data driven tables.

A better solution would be allow the `field` property to be a getter as opposed to a flat string, if the intention is getting data from a nested structure. See how `d3` handles this.

Another alternative is flagging out if you're working with nested data in the first place. Having this be opt-in or opt-out is a better answer than "No. Just never use '.'".

That, or being able to disable this functionality is very useful. This is quite a serious "gotcha" if you're generating tables based off data, since you need to map `.` to some other character, which might collide with other data.
