### ISSUE TITLE
Horizontal Scrollbar

### ISSUE THREAD

**Issue by tranquochuy29** [olifolkerd/tabulator#53]
Hi there,

I hope you're still fine.
I have just found out new issue. We will lost the horizontal scrollbar if we have no data.

You can have a check at the below image.
1. We have no data
2. We resize column to make it bigger
=> We have no scrollbar to resize the column again.

![scrollbar issue](https://cloud.githubusercontent.com/assets/4382757/18161573/b18d055c-705c-11e6-9607-fbf8df914c92.png)

Thank you so much

Cheer,
Tony

**Comment by olifolkerd** [comment]
Hi Tony,

At present the horizontal scroll bar is tied to the width of the data not the header. i will have a look at it this week and put in an update to fix the issue.

Cheers

Oli

**Comment by olifolkerd** [comment]
i have just pushed a fix to resolve this.

**Comment by woxcab** [comment]
@olifolkerd 
Good afternoon! Is this bug really fixed?  There's example https://jsfiddle.net/dveb5Lhr/ where horizontal scrollbar does not appear for an empty table.

**Comment by olifolkerd** [comment]
Hey @woxcab 

Sorry to hear you are having issues,

This issue was closed over two years ago (during which time the entire code base has been rewritten twice) so if you are experiencing a similar issue it is almost certainly entirely unrelated to this one. (please do not comment on old closed issues as it will only confuse new users)

Can you please create an issue using the correct bug template and i can look to resolve any problems ASAP.

Cheers

Oli :)

**Comment by woxcab** [comment]
Created https://github.com/olifolkerd/tabulator/issues/1608
