### ISSUE TITLE
Need one example of the following...

### ISSUE THREAD

**Issue by jkathir** [olifolkerd/tabulator#535]
Could you please kindly consider adding one more example html file with the following features...Please kindly attach to the project examples folder as it would be helpful for many as well..

1. read only grid as above without edit, delete and save option.
2. the grid should have huge export options - pdf, csv, excel, word etc.,
3. When the pagination is enabled - goto page option to navigate to particular page
4. Copy to clipboard and print option
5. Support quickest rendering for alteast 5,000 rows with page size as 10, 100, 500, 1000, 5000

example grid
http://institut-de-genomique.github.io/Ultimate-DataTable/
https://w3lessons.info/2015/07/13/export-html-table-to-excel-csv-json-pdf-png-using-jquery/

Reference
http://2.bp.blogspot.com/-yTiytux2848/Vcj-b5FjyUI/AAAAAAAAdQk/8rzPAsyU4Dw/s1600/jQuery%2Bdatatables%2Bexport%2Bto%2Bpdf.png
2 . https://www.phpflow.com/wp-content/uploads/2015/09/export-table-data-toexcel-png-pdf.png
https://i.stack.imgur.com/XeCzz.png

**Comment by olifolkerd** [comment]
Hey,

The good news is there are already examples of these on the tabulator website:

1. http://olifolkerd.github.io/tabulator/examples/#fittodata
2. http://olifolkerd.github.io/tabulator/examples/#download
3. http://olifolkerd.github.io/tabulator/examples/#pagination
4. Im not sure what you mean here, you can select items you want to copy to clipboard and print a page in the normal way
5. The virtual dom will render any number of items http://olifolkerd.github.io/tabulator/examples/#virtual-dom

Im happy to post examples of each of the individual functions of Tabulator, as you will find on the examples page, adding them together is simply a matter of combining the options from the different examples.

I don't include examples of a "fully featured table" because there are so many available options with Tabulator you would never use them all at once, and the definition of "Fully Featured" would be different from person to person based on their usage case,

The  [Tabulator Website](http://olifolkerd.github.io/tabulator) has over 30 [examples](http://olifolkerd.github.io/tabulator/examples/#virtual-dom) and an extensive set of [documentation](http://olifolkerd.github.io/tabulator/docs/3.2/) that covers every feature available in the table.

Examples are not included in the repository itself, I have deliberately taken this step as i feel that the website offers a greater context around the code and allow me to maintain the examples and documentation in the same place.

If there is an example of a specific feature you feel is missing please let me know, and if you have a specific issue you are having trouble with i will be happy to point you in the direction.

Cheers

Oli

**Comment by jkathir** [comment]
Thanks for your detailed explanation. Is it possible to create an example with the following?

**Comment by olifolkerd** [comment]
Hi @jkathir,

While i am happy to provide you with help on areas you are stuck on, im afraid this is not a free coding service. If you are looking for someone to build a site for you i suggest you hire a web developer, there are thousands of great developers out there, i would be happy to point you to some freelance developer sites if you are in need.

Cheers

Oli

**Comment by jkathir** [comment]
sure and work on it and update you if i am struck..thank you...
