### ISSUE TITLE
setData will not work on a div with display:none

### ISSUE THREAD

**Issue by distraub** [olifolkerd/tabulator#542]
I am using tabulator on a table that is in a hidden div, the idea being that you select a menu item then the table shows. If I setData when the table is showing it works fine, but if I setData when the table is hidden, it does not render into the div.

Here is a jsbin to explain.

[http://jsbin.com/serugosebi/edit?html,css,js,output]()
if you uncomment the first line of the javascript it will render because the div was shown before the tabulator is set up.

**Comment by olifolkerd** [comment]
Hey,

You need to call the ***redraw*** function when you make the table visible if you change any data or setup when it is hidden.

Tabulators column layouts and virtual DOM rely on making calculations based on the dimensions of the tables rows and cells, because DOM elements have no height or width until they are first visible it is unable to correctly lay elements out while they are hidden.

Calling the ***redraw*** function when the table is made visible reruns the calculations an makes the table display correctly:
```js
$("#example-table").tabulator("redraw");
```

Cheers

Oli
