### ISSUE TITLE
html tag (link, span, etc.. ) in existing html table

### ISSUE THREAD

**Issue by TORION84** [olifolkerd/tabulator#554]
Hi , first of all thank you for the great work.
I noticed a bug: if in the `<td>` tag is present html code (eg between `<a>` or `<span>`) in the tabulator it isn't "render".

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch and thanks for your kind words.

Are you referring to a td tag inside an anchor tag or span?
```html
<span>
    <td></td>
</span>
```

If so then im afraid the reason that isnt working is because that isn't technically valid HTML, some browsers support invalid syntax's to help give the best view possible regardless of circumstance, but Tabulator can only parse for valid HTML syntax when building a table.

If i have got the wrong end of the stick here, could you post a sample copy of the html you are trying to parse?

Cheers

Oli

**Comment by TORION84** [comment]
No like this `<table><thead><tr><th>link</th><th>data</th></tr></thead><tbody><tr><td><a>link 01</a></td><td><a>data 01</a></td></tr><tr><td><a>link 02</a></td><td><a>data 02</a></td></tr></tbody></table>` . 
In the first column it writes `<a>link 01</a>`

**Comment by olifolkerd** [comment]
Ahh i see what you mean, 

To prevent code injection into tables Tabulator automatically sanitized the data to plain text, if you want the text to display as HTML you should set the ***formatter*** for that column to ***html***

Let me know if that helps

Cheers

Oli

**Comment by TORION84** [comment]
Ok but I must write **_formatter_** for each column or can I write in the header of html table?

**Comment by olifolkerd** [comment]
it must be included in any column that contains html you want to show in the Tabulator, you can either include it in the column definition or in the header elements for each of the columns using the following tag property:
```html
<th tabulator-formatter="html">Column Name</th>
```

Cheers

Oli

**Comment by TORION84** [comment]
Thank you for your support :)
