### ISSUE TITLE
niceSelect inside tabulator not working 

### ISSUE THREAD

**Issue by mohanen** [olifolkerd/tabulator#591]
Hi oli, 

I been facing this issue for quite long time since 3.0.0, I usually use [niceSelect](http://hernansartorio.com/jquery-nice-select/) to style my select boxes . But its not working inside Tabulator.

What nice select does is hides the native select box and creates one with HTML   

I added nice Select call in the editor  - so every time a editor is called nice Select is called to style it .
But the HTML select of niceSelect is not working in the tabulator (The the native select box is hidden and HTML select box created but its not working on click  ).

Thanks & Regards,
Mohanen B

**Comment by olifolkerd** [comment]
could you post a copy of your table constructor and nice select editor so i can run some tests,

cheers

oli

**Comment by mohanen** [comment]
[tabulator-niceSelect.tar.gz](https://github.com/olifolkerd/tabulator/files/1336144/tabulator-niceSelect.tar.gz)

I included a example

**Comment by olifolkerd** [comment]
Thanks for the example, it was very helpful.

The issue you are having is because overflow in cells is set to ***hidden*** by default.

You can get round this with a CSS tweak:
```css
.tabulator .tabulator-row .tabulator-cell{
    overflow:visible !important;
}
```

Though depending on your other table options this may cause issues, give it a try and see if it helps you out.

Cheers

Oli

**Comment by mohanen** [comment]
Hi oli,

that css tweak doesn't seem to work in 3.2.

**Comment by olifolkerd** [comment]
does it have any effect?

**Comment by olifolkerd** [comment]
Just figured it out,

The issue is you are calling the `editor.niceSelect()` in the ***onRendered*** callback, by this point the row has already been resized, so it wont take account of the new selectbox's height. to get round this you need to call the ***normalizeHeight*** function on the row after you have initialised you niceSelect element:

```js
onRendered(function () {
        editor.niceSelect();
        cell.getRow().normalizeHeight();
 });
```

**Comment by mohanen** [comment]
the clicks aren't passing through - 

its like when you click on the html select box it toggles the class "open" in the "div" which allows the list to be visible.

But the click isn't passing through or not recognized.

when i add open class directly it the list shows up

**Comment by olifolkerd** [comment]
It looks like the niceSelect is getting corrupted during the cell reformatting, if you add a small set timeout function around it you should be sorted. You will need to add listeners to check when the value has changed and call the ***success*** function
```js
onRendered(function () {
    setTimeout(function(){
        //create nice select element
        editor.niceSelect();

        //resize row to fit element
        cell.getRow().normalizeHeight();
    }, 10);
});

editor.on("change", function(){
    success($(this).val());
})
```
you will probably need to check for a blur event to trigger the ***cancel*** function if the user aborts, and you may want to trigger the drop down to open on load for a better user experience.

Cheers

Oli
