### ISSUE TITLE
rowClick

### ISSUE THREAD

**Issue by vmontal** [olifolkerd/tabulator#595]
Hi Oli,
following your advice (#593) I upgraded tabular version to 3.2 (from 2.9), but something wrong in rowClick event;
 in the previsious version the callback function was:

`rowClick: function (e, id, data, row) { 
                    dataCliente.IDCliente = parseInt(data.ID_Cliente);
                    dataCliente.ragioneSociale = data.ragioneSociale;
},`

where "ID_Cliente" and "ragioneSociale" are fields name in the data table!

Now in 3.2 version I saw the callBack function is:

`rowClick: function (e, row) { 
    ?????
},`

I tried with e.ID_Cliente and row.ID_Cliente, but nothing to do!!!! What I get is  "NaN" and "undefined"

I looked at in the help documents, but I lost myself, sorry!

Thanks in advance!

**Comment by olifolkerd** [comment]
Hey @vmontal,

No problemo, there were a load of really cool changes in version 3 that require a few tweaks to version 2 code to get working.

Version 3 introduced the concept of [Component Objects](http://tabulator.info/docs/3.2#components). each callback is passed in a component object that allows access to all the functionality of the component, in your ***rowClick*** example this is the Row Component for the row that was clicked.

To get the data from the component you need to use the ***getData*** function:
```js
$("#example-table").tabulator({
        rowClick:function(e, row){
        //e - the click event object
        //row - row component

        var data = row.getData(); //get row data
    },
});
```

Have a look at the [Component Objects Documentation](http://tabulator.info/docs/3.2#components) for all the extra functionality it offers.

Cheers

Oli

**Comment by vmontal** [comment]
... a few tweaks? :-(

however... thanks a lot! :-)

**Comment by olifolkerd** [comment]
Hey @vmontal,

Version 3.0 was a complete rewrite of Tabulator from the ground up, it rebuilt the library into an extensible modular structure that could be easily expanded as the project grows. It added a Virtual DOM to allow rendering of any number of row without slowing down the browser and standardised the naming conventions of callbacks and variables to make the library more intuitive to use. Full details of which can be found [Here](http://tabulator.info/news).

It also added loads of console messages, so now Tabulator warns you when you are using invalid formatters, passing in incorrect data and much more.

In general a few of the configurations options changed names to make them uniform, but the biggest change in terms of updating code was the introduction of the component objects, the addition of these made using the system much simpler, because they mean there no longer has to be a massive and ever changing list of arguments passed into callbacks, new functionality can be added to the component objects without any change to the callback arguments.

I will only do a major version update once a year at most and will try where possible to not break previous changes, but it cant always be guaranteed, at the bottom of the documentation for each version there is a list of any deprecated features that will be removed at the next major version change, and Tabulator will now give console warnings when you are using a deprecated features, so it should give people more warning when things are going to change.

When the version 4.0 library is released in around May 2018, i will look at putting together a migration guide to help people out.

**Comment by vmontal** [comment]
Thanks, Oli.

I realize, but It's not a walk rearranging my application from 2.9 to 3.2, (sigh)

One more...
I'm facing some (big) trouble with angularJS and the Tabulator callBack functions: 
angularJS $scope, inside the callback function ( i. e.  rowClick) don't fire!!! and this is a big, big problem, really !!!

here an example:
`                rowClick: function (e, row) {
                    var data = row.getData();
                    dataCliente.IDCliente = parseInt(data.ID_Cliente);
                    dataCliente.ragioneSociale = data.ragioneSociale;
                    dataCliente.IDAzione = 0;
                    Auth.paginaStudio = parseInt($("#tabella").tabulator("getPage"));
                    $scope.tabMenu = 99;
                    $("#navCliente").html("<span class='glyphicon glyphicon-hand-right'></span> " + dataCliente.ragioneSociale);
                    $scope.anagrafeAttivo = data.Attivo == "true" ? true : false;
                    getAnagrafe(dataCliente.IDCliente);
                },`

**Comment by olifolkerd** [comment]
Hey @vmontal,

Sorry to hear you are having issues with the upgrade, if there are particular areas you feel could be improved I would love the feedback, it will help when the next major version comes out.

Im not an angular man myself (vue.js here) but does this [Stack Overflow Article](https://stackoverflow.com/questions/20318401/how-to-access-my-angular-scope-inside-my-custom-callback) help at all?

Cheers

Oli

**Comment by vmontal** [comment]
I already knew this angularJS feature and it's not working in this case!

I tried some other kind of workarounds

Sorry, I give up!

downgrade to 2.9, but now I have another problem and I'd like open a new different issue

Always, Thanks!!!

**Comment by olifolkerd** [comment]
Sorry to hear that,

I will have a play with angular at some point and put togeather a guide for working with tabulator. Though i cant see why the functionality in the callbacks would have changed between versions.

Cheers

Oli
