### ISSUE TITLE
Grouping Data And Column Calculation

### ISSUE THREAD

**Issue by dasio86** [olifolkerd/tabulator#604]
Hi,
first of all thanks for your great job.
I was wondering if it was possible to leave the calculated field visible when a group is grouped.

I would like to highlight this problem:
When I make a table change that sets a new value for the calculated column, the total is not updated
Thank you

**Comment by olifolkerd** [comment]
Hey @dasio86 

Thanks for getting in touch, it is always great to hear people are enjoying using Tabulator.

The good news is that in today's 3.3 release you can now choose whether to hide or show calculations in collapsed groups using the new ***groupClosedShowCalcs*** property:

```js
$("#example-table").tabulator({
    groupClosedShowCalcs:true, //show column calculations when a group is closed
});
```

There was a bug in version 3.2 where column calculations only updated when not in grouped mode, this should now be fixed in version 3.3

I hope that helps you out!

Cheers

Oli :)

**Comment by dasio86** [comment]
Thank you very much and sorry if i don't see it before :)

**Comment by olifolkerd** [comment]
No problem, you wouldn't have seen it before, i only released it yesterday :D
