### ISSUE TITLE
Disable row selection per column

### ISSUE THREAD

**Issue by DevilWarrior** [olifolkerd/tabulator#612]
Hi again,

First, thanks for the awesome work. Currently I'm integrating  [select2](https://select2.org/) with tabulator. It works great, but when I click on a row it also triggers the row selection/deselection. Any way of avoid this or to disable row selection/deselection per column?

Best

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch, i can certainly recommend a solution for you, i have a couple of questions so i can provide the best solution:

How are you using selectable rows at the moment, are you allowing the user to select any row they want, or to just to select one row at a time?

Would you prefer the row to be selected only when a specific column is clicked, or would it be all columns apart from the ones containing the select2 editor?

could you post a copy of your table constructor so i can see how your table is currently configured?

Cheers

Oli

**Comment by DevilWarrior** [comment]
Hey, right now the "selectable" option is set to "1". So only one row at the time. Ideally I would like to trigger the selection of the row on any column except the ones with select2 in it; otherwise anytime you change the option from the dropdown it selects/deselects the row. Most of the parameters do come from the server but here's the constructor:


``function table_setup(target, columns, tbl_data, index){
    $("#" + target).tabulator({
        height:'100%',
        fitColumns:true,
        persistentLayout: true,
        columns:columns,
        index: index,
        movableColumns: true,
        selectable:1,
    });

    $("#" + target).tabulator("setData", tbl_data);
}``

**Comment by olifolkerd** [comment]
It shouldn't trigger row selection when you click on an editor, it is set to prevent that, through it might be happening because of the custom editor

Your best option would be to add a `stopPropagation()` call to you ***cellClick*** callback:
```js
{title:"Name", field:"name", cellClick:function(e, cell){
        e.stopPropagation(); //prevent click event from reaching the row.
    },
}
```

You will probably also want to add that to a click event listener on your select2 editor element.

If you are still having trouble after that could you post a copy of your custom editor.

Cheers

Oli

**Comment by DevilWarrior** [comment]
Hey, thanks! It worked like charm...again. I tried adding the callback to select2 but I had no luck with that. Although I could see the event being triggered for some reason it was still propagated. I'm sending most of the column data from a flask server so I can't really set the cellClick event there, I ended up adding it right before initializing the table. I do not have an editor for select2, just a formatter. Thanks for the answer ;)

**Comment by fr0z3nfyr** [comment]
Hi Oli!

Sorry for reviving a closed issue. I have a similar issue, so I thought of checking if there is a better solution. 

I don't use editor, I have action buttons on the last column of table. The buttons are set using HTML `data-` attributes to toggle a bootstrap `modal`. 

If I use `.stopPropagation()` the modal will never show up (which is expected because no more `click` event handlers/listeners will get to know about this `click`). I know about manually triggering the modal but I do not want to use a `$('#mymodal').modal('show')` unless there is no other absolute solution.

**Comment by olifolkerd** [comment]
Hey @fr0z3nfyr 

Please ask questions like that on Stack Overflow.

It would be really helpful if you could post the relevent snippets of your code when asking for help as it is hard to give the appropriate advice without knowing how your table is configured in code.

Cheers

Oli :)
