### ISSUE TITLE
Existance of columnCalcs (bottom/top) causes error when grouping with "setGroupBy"

### ISSUE THREAD

**Issue by FancyUsername** [olifolkerd/tabulator#619]
# How to reproduce
1. activate `columnCal` (`tabulator.js:2796`), e.g. by defining column setting `bottomCalc:"avg"`
2. set grouping: `$("#example-table").tabulator("setGroupBy", "myfield");`
# Effect
Code `data.push(row.getData()); `(`tabulator.js:7289`) causes error: `Uncaught TypeError: row.getData is not a function`
# Reason
After grouping the `rows` parameter in `ColumnCalcs.prototype.rowsToData` does not only contain `Row` objects but also `Group`objects causing the error.

**Comment by olifolkerd** [comment]
Could you post a copy of your table constructor object so i can replicate your setup.

If you can get a chance to post it in the next day i can include a fix in this weekends patch release

Cheers

Oli

**Comment by olifolkerd** [comment]
Great Spot!

I have pushed a fix for this to the master branch, it will be included in this weekends patch release!

In case you are interested the error was caused because there are two render modes internally for column calculations, one for grouped rows and one for non-grouped rows. This mode was only being set when the table was first initialized, not when the the row grouping state was changed.

Let me know if you find anything else.

Cheeers

Oli
