### ISSUE TITLE
Trigger edit event: cell.trigger is not a function

### ISSUE THREAD

**Issue by notom** [olifolkerd/tabulator#622]
Hello,

I'm trying to trigger event like that:

`var tickToggle = function(e, cell){
        var newVal = !cell.getValue();
        cell.trigger('editval', newVal);
    }`

`{title:"Active",    field:"active",     align:"center", headerFilter:columnFilter, formatter:"tickCross", cellClick: tickToggle},`

But when I click on the cell I get: **cell.trigger is not a function**

What I'm doing wrong?

**Comment by olifolkerd** [comment]
The ***editval*** event was used back in Tabulator 2.12.

As of version 3 Tabulator introduces the concept of [Component Objects](http://tabulator.info/docs/3.3#components), instead of passing loads of different things into callbacks components are now passed int that allow access to loads of different functionality.

You can now set the value on the cell component using the ***setValue*** function:
```js
var tickToggle = function(e, cell){
    cell.getValue(!cell.getValue()); 
}
```
Let me know if that helps,

Cheers

Oli :)

**Comment by notom** [comment]
That should be setValue, right?

**Comment by olifolkerd** [comment]
yup, i have corrected the example
