### ISSUE TITLE
Sorting letters wrongly

### ISSUE THREAD

**Issue by Lazaroth** [olifolkerd/tabulator#635]
In Sweden we have 3 extra letters, å, ä, ö, which are placed after Z, so X-Y-Z-Å-Ä-Ö.

On my computer where I have a Swedish OS language, sorting by letters works correctly and places for example "Älska" at the bottom of a list, after Z.
However when the OS is English, it places it after the letter A, so we have A-Ä-B-C-D etc.

Setting locale: 'sv' doesn't change anything.

**Comment by olifolkerd** [comment]
Hey @Lazaroth 

Thanks for getting in touch, Tabulators string sorter uses the localeCompare function, so sorts according to the locale set in the browser. The ***locale*** property of the table is currently only used for setting the locale of the table text, and has no affect on sorting.

I like that as a suggestion though, i will add it in the next update so that you can specify the locale of the sort.

Cheers

Oli

**Comment by Lazaroth** [comment]
Nice, thanks!

**Comment by olifolkerd** [comment]
Hey @Lazaroth 

You will be happy to hear i have just pushed this to the 3.4 branch.

You will be able to use the ***locale*** sorterParam to specify the locale of the sort:
```js
{title:"Name", field:"name", sorter:"string", sorterParams:{locale:"en-gb"}}
```
You can also give it a value of ***true*** to use the current table locale:
```js
{title:"Name", field:"name", sorter:"string", sorterParams:{locale:true}}
```

Version 3.4 should be released in the next couple of weeks.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially released!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
