### ISSUE TITLE
Different colors for even/odd rows

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#69]
Hi @olifolkerd ,

Default theme is, there's no border for the cells inside, instead using white and grey colors for even/odd rows to make it looks nicer. 

So, when I use formatter to set background-color for a field/column, since no border inside the cells, it will look ugly as a block without any borders. 

Is there a way to set 2 different colors for odd/even rows in formatter?

**Comment by olifolkerd** [comment]
I would suggest you do this in css rather than in the formatter.

You could you use a formatter to assign a class to the cells and then use css to style cells in odd rows with that class one colour and cell in even rows with that class another colour.

let me know if you would like some example code to help you out.

**Comment by hohozhao** [comment]
It turns out that using css gradient is perfect for what I needs. e.g.
`cell.css({"background":"linear-gradient(#ccc 95%,#eee)"})`
