### ISSUE TITLE
Some smallchanges

### ISSUE THREAD

**Issue by Astalavista70** [olifolkerd/tabulator#7]
- With tabulator we can use ajax for update Data but we can't set Headers (after we can initialize Tabulator without any parameters and send it after / We can use the same "Tabulator" for multiple pages)
- The index can't be changed from Data updates so the data is the only element that knows the name of the index.

Excuse me for my bad English ...

**Comment by olifolkerd** [comment]
Changing the headers is actually on my to-do list for this weekend so there should be some more features for this soon.

Im not sure what you mean by the index cant be changed? The whole point of the index is it is unique to the row and identifies it, changing it would invalidate the data in the table. if you call ***setData*** you can load a new set of data with a new range of index values. Are you asking for a ***getIndex*** method so you can request the name of the index field?  Could you provide an example of what you are trying to achieve.

Cheers

**Comment by Astalavista70** [comment]
In my previous change, i use my row_id (index of SQLite database) as Index in row (and i've add unique options to data to use this column as index of rows).
Have you think about Flex-box to simplify the width of column and let's Html engine calculate widths ?

**Comment by olifolkerd** [comment]
If you are talking about updating the index after the table has been initialised then you can use the options function to change the index value, next time the data is set it will use the new index:

```js
 $("#example-table").tabulator("option", "index", "new_index_field");
```

if you wanted to do all of this as part of an ajax call then i would recommend something like the following:

```js
$.ajax({
	url: "path/to.data",
	type: "get",
	dataType:'json',
	success: function (response) {
		//Assuming that the response object has two properties
		//index - a sting containing the name of the index field;
		//data - an array containing the table data

		$("#example-table").tabulator("option", "index", response.index);
		$("#example-table").tabulator("setData", response.data);
	},
});
```
I have chosen not to use flexbox as there would be issues in synchronising the column widths between rows. 

Cheers

**Comment by Astalavista70** [comment]
But, in my opinion the index came from the Headers options.

With the flex, you can use flex only with Headers and use it width on table's column, no ?

**Comment by olifolkerd** [comment]
The index has never been defined in the header options. The reason being that the index does not always need to be displayed in the table, and in a lot of situations it would be very unwise to show it. Therefore it is set as a global option using the ***index*** options parameter. That way any field in data that is provided to the table, regardless of whether it has a defined column or not can be used as an index.

By allowing it to be set in the columns definition you allow the possibility of someone accidentally declaring two index's, which would not be possible.

You can still use the ajax method above to pull the index field from your headers data if you wanted to.

Due to the reasons outlined above, there will not be the option to define the index through the column definitions, but feel free to add this in your own branch if you feel you would prefer to do it that way.

With regards to flex, when the columns are set to fit to table width i can see where you are coming from. But when the columns are set to fit to data, then the columns resize to fit the largest data in each column if the header size is not defined, and there is no maximum width to the table rows, they can overflow the table. Therefore a flex box would not be useful in that case. Given that the system has to cope with both types of layout, i have built one layout system that copes with both options rather than trying to integrate flexible that would only work in one situation.

**Comment by Astalavista70** [comment]
Ok, i use this because i can change the displayed table without any other parameters just with the new Headers and Data.

I'v try to check the width fix with your example (and my pages) and i've make some changed.
If you want see, I post changed in a patch file. 

[Astalavista-patch.diff.txt](https://github.com/olifolkerd/tabulator/files/100614/Astalavista-patch.diff.txt)

**Comment by olifolkerd** [comment]
Thanks for sending over the example.

I will get a fix in for the width issue this evening, it should take long at all.

I will get the column data getters and setters in over the weekend.

Cheers

**Comment by Astalavista70** [comment]
And i create _renderHeader and _init to add the possibility to update headers, the_init always call the headers' render but we must call this method only if headers updated .

**Comment by olifolkerd** [comment]
The following functions have been added in the latest 1.8.0 release.

#### Set New Column Definitions
To update the current column definitions for a table use the ***setColumns*** function. this function takes two parameters. the first should be the new columns definition array. The second is a boolean value that determines the type of column update you wish to use. If you set this to ***false***, the current column definition array will be completely overwritten. Set it to ***true*** and only the column layout information (width, order, visibility) will be overwritten, perfect for loading user layout preferences from an external store.

```js
	//new column definition array
	var newColumns = [
		{title:"Name", field:"name", sortable:true, sorter:"string", width:200, editable:true},
		{title:"Age", field:"age", sortable:true, sorter:"number", align:"right", formatter:"progress"},
		{title:"Height", field:"height", sortable:true, formatter:"star", align:"center", width:100},
		{title:"Favourite Color", field:"col", sorter:"string", sortable:false},
		{title:"Date Of Birth", field:"dob", sortable:true, sorter:"date", align:"center"},
	],

	$("#example-table").tabulator("setColumns", newColumns , false) //completely overwrite existing columns with new columns definition array
```

#### Get Column Definitions
To get the current column definition array (including any changes made through user actions, such as resizing or re-ordering columns), call the ***getColumns*** function. this will return the current columns definition array.
```js
	var colDefs = $("#example-table").tabulator("getColumns") //get column definition array
```

#### Persistent Column Layout
This may also be of interest to you

Tabulator can store the layout of columns in a cookie so that each time a user comes back to the page, the table is laid out just as they left it. To enable this feature set the ***columnLayoutCookie*** options parameter to ***true***.


For detailed documentation on these functions [click here.](https://github.com/olifolkerd/tabulator/wiki/Column-Layout-Manipulation)

**Comment by olifolkerd** [comment]
Hi Guys,

I have just launched a new documentation site for tabulator, check it out:
http://olifolkerd.github.io/tabulator/

Oli
