### ISSUE TITLE
"Shift + Tab" can not go back (previous) cell focus

### ISSUE THREAD

**Issue by hohozhao** [olifolkerd/tabulator#70]
Hi @olifolkerd,

While "Tab" can move cursor to next cell and get focused, "Shift + Tab" can not move it back to previous cell.

**Comment by olifolkerd** [comment]
Good point,

i will have a look at that today

**Comment by olifolkerd** [comment]
looking into this, it is quite a complicated issue, it does work on some editors but not on others because of the way the browser handles interactions with different types of UI element.

I will look into fixing this in release 2.9, but for the mean time i would suggest you add ***keydown*** event bindings to the editors you wish to have this functionality.

**Comment by hohozhao** [comment]
I would rather wait for your update. Thx.

**Comment by hohozhao** [comment]
Btw, just updated my profile.

> I am not a professional programmer. I do program for what I want, and I program for my work, but may not for my job, so far.

**Comment by olifolkerd** [comment]
Thanks, and you are welcome.

Im always happy to help people out with their programming questions :)

**Comment by olifolkerd** [comment]
Hey,

I have some good news for you, with today's 3.1 release there is now a new set of cell navigation functions, documentation for which can be found in the [Navigation Documentation](http://olifolkerd.github.io/tabulator/docs/3.1/#navigation)

You can also customise all of the shortcut key bindings with the new [Keybindings Extension](http://olifolkerd.github.io/tabulator/docs/3.1/#keybindings)

Let me know how you get on.

Cheers

Oli :)
