### ISSUE TITLE
Moving cell to next column

### ISSUE THREAD

**Issue by robblock** [olifolkerd/tabulator#703]
I have a button in my cell which I would like to use to move the cell to the next column. Is there any way to do this?

For example, I have a cell with index 1.1 how would I move this cell to have index 1.2

**Comment by olifolkerd** [comment]
Hey @robblock ,

I am assuming you mean you want to move the data from that cell into the cell in the next column. in that case what would you like to happen to the data already in that columns cell?

Cheers

Oli

**Comment by robblock** [comment]
Oli I appreciate the response.. As of right now there would be nothing in the next cell over. I am attempting to create a table to track a person. For example: 

Column 1: Arrival
Column 2: Checkin
Column 3...

The person would start in column 1 and would then move to the next column as they move along in the process.

**Comment by robblock** [comment]
```javascript
var currentColumn = $( element ).parents()
 $(currentColumn[1]).attr( 'tabulator-field', 'pre-test' )
```
I have tried this and then calling refresh, although it does change the attribute the cell does not move.

**Comment by olifolkerd** [comment]
Hey @robblock,

because tabulator is rendered using a virtual DOM you should not try accessing any of the DOM elements directly as they can be created and destroyed at any point. Tabulator provides all the functionality you will need for most functions.

how you want this to be formatted will change the solution, in this example i am going to assume you are moving a text value (name for example) between the cells, but you could equally make each cell show a tick box as they are completed or have a dot that moves along, if you can be more specific i can give you a more tailored example.

in this case i have defined a table with three columns, clicking on a cell in that column will cause its value to shift to the next cell along, it assumes that you start with a value in the arrival field:

```js
//function to move data to next cell
function moveNext(cell, next){
	//find next cell
	var nextCell = cell.getRow().getCell(next);

	//set value of next cell to current cell
	nextCell.setValue(cell.getValue());

	//clear value in current cell
	cell.setValue(null);
}

//define table
$("#example-table").tabulator({
	columns:[
		{title"Arrival", field:"arrival", cellClick(e, cell){
			moveNext(cell, "checkin");
		}},
		{title"Checkin", field:"checkin", cellClick(e, cell){
			moveNext(cell, "boarding");
		}},
		{title"Boarding", field:"boarding"},
	]
})
```

Let me know if that helps,

Cheers

Oli :)

**Comment by robblock** [comment]
Your the man! That does exactly what I need it to do. I need to take this one step further though. I do not want this to happen when the cell is click, rather I have a button inside the cell which when click will do exactly this.

**Comment by robblock** [comment]
New challenge

```
var patientName = $( element ).parent().parent().find( 'h2' )[0].innerHTML
      firebase.database().ref( 'Patients/' + patientName).once( 'value' ).then(function(snapshot) {

      var row = $( '.test-table' ).tabulator( 'getRow', snapshot.val().tableIndex ),
      currentCell = row.getCell( 'checkin' ),
      nextCell = row.getCell( 'pre-test' );

      nextCell.setValue(currentCell.getValue())
      nextCell.getElement().append(currentCell.getElement().children())
```

I apologize if this is a bad thing to do but I am new to javascript!! 

When  I run this all the DOM elements are moved from the current cell to the next but nothing is visible. Appreciate any help

**Comment by robblock** [comment]
Thanks Oli! That did do the trick but I am still having an issue. Although the cell did move when I call
```
nextCell.getField() 
```
It is returning the field name of column 1 and not column 2, thus preventing me to move any futher along. Any help is appreciated!
