### ISSUE TITLE
Custom Filters on ajaxFiltering:true

### ISSUE THREAD

**Issue by cschnelting** [olifolkerd/tabulator#705]
I have set ajaxFiltering:true in my tabulator and would like to set a Filter with "setFilter"-Function. My FIlter is: 
`var filter = {field:"status", operator:"IN", value:["A", "B"]};`
But the Filter is not send to the Server in the ajaxRequest. Insted i get the following Error:

> Filter Error - No such filter type found, ignoring:  IN

How can  change it? I'm using tabulator v3.3.1

**Comment by olifolkerd** [comment]
The issue you are having is because there is no built in filter type of "in" so Tabulator cannot deal with that correctly.

Though as you are doing server side filtering this shouldn't matter, so i will look at correcting this in the next release.

in the mean time you could extend the filter system to add this functionality to prevent the error. include the following code before you define your table:

```js
Tabulator.extendExtension("filter", "filters", {
    "in":function(filterVal, rowVal){
        return filterVal.includes(rowVal);
    }
});
```

Cheers

Oli

**Comment by cschnelting** [comment]
Thanks!

**Comment by cschnelting** [comment]
I also use an "or"-Filter for server side filtering. This Filter has the format 
`{or: filterArray}`

But the Tabulator sends only field, type and value in the ajaxRequest to the server. So I've modified the Filter.prototype.getFilters function:

```
...
self.filterList.forEach(function (filter) {
        if(filter.or !== undefined) {
            output.push({ or: filter.or});
        } else {
            output.push({ field: filter.field, type: filter.type, value: filter.value });
        }
});
...
```

**Comment by olifolkerd** [comment]
there was an issue with the filtering system in the last patch release, i am releasing another patch release this evening that should fix that.

Cheers

Oli
