### ISSUE TITLE
IE11 Pagination -Clicking Last Not working

### ISSUE THREAD

**Issue by keithhobbs** [olifolkerd/tabulator#752]
Hi

I'm new to Tabulator and am currently evaluating it with a review to replacing a legacy list control in my ASP.NET webforms solution.

I have created a simple web page that calls into a Web API which queries a view to return data to my page. This seems to work perfectly in Firefox and Chrome but in IE11/Edge clicking the last button on the pagination momentarily shows the last page, but then just re-loads page 1. Clicking Next, or page n works fine in all browsers.

The web api just returns the entire view to the client as I am interested in how well Tabulator works with one biggish up front request and the user can then page and sort the list as desired without having to make another ajax request. Generally this seems to work and perform on my local machine pretty well.

Putting a debugging statement in my javascript it appears as if the page is re-loaded and then setData gets called twice. Am I doing something wrong? Or is there an event I should handle to stop IE processing the re-load?

One thing I noticed on your pagination example is that the setup has movableColumns= true set twice? I've tried removing one of these and it doesn'k make any discernible difference.

Hopefully I've done something/missed something straightforward. Really impressed with the list, it seems to do everything I want.
[Tabulator Example.zip](https://github.com/olifolkerd/tabulator/files/1528515/Tabulator.Example.zip)

**Comment by olifolkerd** [comment]
Hey @keithhobbs 

Thanks for getting in touch,

Thanks for pointing out the duplicate ***movableColumns*** property, i have now removed this from the documentation.

The reason that set data is being called twice is because if you dont set the ***data*** or ***ajaxURL*** paramters the table is initialzed with a blank array first, then the data is loaded with your ***setData*** function.

To avoid this, remove your ***setData*** function call and add the following to your table definition:
```js
ajaxURL:"/api/list/Get",
```

I hope that helps.

Cheers

Oli
