### ISSUE TITLE
columnResized event called every time jquery tabulator

### ISSUE THREAD

**Issue by deshpandeharshada** [olifolkerd/tabulator#760]
I have added a columnResize callback function. It is called repeateadly every time i click a row or cell.

**Comment by olifolkerd** [comment]
Hey @deshpandeharshada 

Thanks for getting in touch, in order to help you out i will need a bit more information:

- What version of Tabulator are you using
- Does this happen in all browsers
- Could you post a copy of your table constructor so i can see how your table is setup
- where in the cells are you clicking (in the center at the edges etc...)

Cheers

Oli
