### ISSUE TITLE
csv file money values mixed format

### ISSUE THREAD

**Issue by carterwe** [olifolkerd/tabulator#766]
I have repeating money values  in a csv file.  The first of a repeating value is formatted as currency and others are not.  My value is displayed with formatter:"money".  Please note first column in sample.  
"Receipt Amount","Application","Account","Department","Amount"
"$995.00","LUR - Minor Amendment","43356-001-4840","Land Use Review","480"
"995","Minor Amendment - CSFire","45786-001-2230","CSFire","248"
"995","Minor Amendment - CSUtilities","40381-702-9881","CSUtilities","111"

**Comment by olifolkerd** [comment]
Hey @carterwe,

Formatters are only used in the table because a  lot of output HTML which would be meaningless in CSV file.

At the moment the only way to achieve this would be to create a custom CSV file formatter to handle it, see the [Download Data Documentation](http://tabulator.info/docs/3.3#download) for more information. 

in a future release there will me more functionality to allow for formatting columns in downloads.

Cheers

Oli :)

**Comment by carterwe** [comment]
Hello Oli.  The issue is not formatting or lack of formatting but
inconsistent almost random looking formatting on different rows of fields
in the same column.  I’m guessing it is tied to grouping even though the
groups are not included in the export as the first row in a group has $
sign stuck in front of value.  My only goal is to have consistent
presentation. What do you think?

**Comment by olifolkerd** [comment]
Hey @carterwe 

The ***CSV*** downloaded doesn't manipulate the data in any way, it just dumps it to a file, that would suggest that the data being entered into Tabulator is possibly inconsistent.

Cheers

Oli
