### ISSUE TITLE
tabulator("destroy") not remove the old table and columns

### ISSUE THREAD

**Issue by rri195** [olifolkerd/tabulator#774]
I have 2 tables, after destroy the 1st table and initialize the 2nd table, the columns in 1st table shows in the 2nd table

please see example here.

https://jsfiddle.net/odmg2wnd/5/

**Comment by olifolkerd** [comment]
Hey @rri195 

It takes time to initialize a Tabulator instance when you call the constructor, functions immediately after this will likely be run  ***before*** the table has be built, which is why i would usually recommend the be placed inside one of Tabulators many callbacks to ensure they get executed after the table is built.

In this case it is likely that you are trying to destroy the first Tabulator while it is still being built, which is resulting in an inconsistent result.

Cheers

Oli

**Comment by rri195** [comment]
Thanks for the reply, but I tried to wait the 1st table is build then destroy it, still not work. see link below

https://jsfiddle.net/odmg2wnd/6/

**Comment by olifolkerd** [comment]
Looks like you may have found a bug there, i will look into it further this evening.

Cheers

Oli

**Comment by rri195** [comment]
Thank you so much, waiting for the fix.

Greg

**Comment by rri195** [comment]
also, if you could please take a look at this https://jsfiddle.net/odmg2wnd/12/

why the download doesn't download any data except header?

Thanks

Greg

**Comment by olifolkerd** [comment]
Hey @rri195 

Could you raise a second issue for help with your other problem, it should only be one issue per problem to make it easier to track.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @rri195 

Could you raise a second issue for help with your other problem, it should only be one issue per problem to make it easier to track.

Cheers

Oli

**Comment by olifolkerd** [comment]
I have just pushed a fix for this to the master branch, it will be included in this evenings patch release.

Cheers

Oli

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
