### ISSUE TITLE
Options Error - Tabulator does not allow options to be set after initialization unless there is a function defined for that purpose

### ISSUE THREAD

**Issue by azizur-rahman** [olifolkerd/tabulator#783]
Options Error - Tabulator does not allow options to be set after initialization unless there is a function defined for that purpose

What can I do now ? Plz reply with proper solutions.

Cheers

Azizur

**Comment by Rodbjartson** [comment]
What did you do to get this error?

**Comment by olifolkerd** [comment]
Hey @azizur-rahman 

This error suggest you are trying to use the jQuery ***options*** function to update the tables configuration after initialization, which Tabulator does not allow.

if you are trying to achieve anything specific with this, let me know and i can suggest the correct approach.

Cheers

Oli

**Comment by answerquest** [comment]
Hi, I want to define a `rowSelected:function(row){...}` action after initialization. There are some values to work with that aren't present at the stage of table initialization. Please suggest how to make the `unless there is a function defined for that purpose` part happen?

**Comment by olifolkerd** [comment]
Hey @answerquest 

There is no way to set this function after initialization, but you could reference variables outside the function which would fix this issue, you could then call the ***redraw*** function if those variables changed.

Cheers

Oli :)

**Comment by adnanganie** [comment]
Greetings,
There should be Filter option above  the tabulator  search  record on whole pages .

**Comment by answerquest** [comment]
Hi @adnanganie could you please file that as a separate feature request? I don't see it being directly connected to this issue which has already been closed long back. 

Besides, tabulator provides column-wise search filters and I am using it precisely because that is far more accurate than a generic single search box (which I found in pretty much all the other jquery-table implementations) searching all the columns and messing up my search.
