### ISSUE TITLE
Complex Column Grouping Formatting

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#853]
Oli, quite impressed with the complex grouping!

I have an application where I need 3-4 grouped headers and noodling with the enclosed test file.
Can you look into why the following is happening?
- Age and Birthday do not inherit "columnVertAlign"
- Vertical cell line is missing between "Age" and "Birthday"
- Have a really long name that I did the wrapping in CSS option, and some lines go missing - eg. between "Cheese" and "Color".  Once I expand out the column to like 120, it goes away.

Rename Test.txt to Test.html to get a jist of what's going on....
[Test.txt](https://github.com/olifolkerd/tabulator/files/1682329/Test.txt)

Thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

Thanks for your kind words.

Your first couple of points look like a bug in the header rendering engine, which looks like it is to do with the particular order of the grouping, i will make sure this is fixed in the 3.4 release in a couple of weeks.

Your third point, im not sure what you mean by "some lines go missing", you you are talking about some of the words in the title are missing this is because the text is truncated to fit the width of the column which you have set at 75px, If the width isnt defined the column will expand to fit the header.

Cheers

Oli

**Comment by YendorMc** [comment]
Thanks Oli!
Yeah, sorry, about that...

It may be related to #1 and #2...  so here's another example (rename .txt to .html)
[Test2.txt](https://github.com/olifolkerd/tabulator/files/1683626/Test2.txt)

I'm referring just to the lines... Note the lines between Color and Age and Age and Birthday are missing in the vertical span.  Note PNG pic, as well.
![msnglines](https://user-images.githubusercontent.com/10876357/35652543-119b2824-06b2-11e8-95e0-495f51ced78e.png)


If I increase the width of the first column then they look 'normal'.  This only happens when using  wrapping in CSS.

Many thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

Ahh yes i see your point, yeah that is cause by the same issue as your first two points, i will look at resolving that in the 3.4 release.

I will drop you a message on here when i push a fix.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @YendorMc 

You will be happy to hear i have just pushed a fix for this to the 3.4 branch. It will be included in tomorrows release.

Cheers

Oli :)

**Comment by YendorMc** [comment]
You’re awesome!  Thanks Oli!

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
