### ISSUE TITLE
mutators doesn't work as shown

### ISSUE THREAD

**Issue by E3V3A** [olifolkerd/tabulator#860]
I was trying to convert values from feet to meters using `mutators` according to [your documentation]( http://tabulator.info/docs/3.3#mutators), however it doesn't work, but the `formatters` does. 
What's going on?

```javascript
// This doesn't work
Tabulator.extendExtension("mutator", "mutators", {
    ft2met:function(value, data, type, mutatorParams){
        return (value * 0.3048);
    },
});

// But this does!
Tabulator.extendExtension("format", "formatters", {
    ft2mt:function(cell, formatterParams){              // Feet to Meters
        return  (0.3048*cell.getValue()).toFixed(0);
    },
});

...

{title:"Alt [m]", field:"altitude", sortable:true,  responsive:0, formatter:"ft2mt", align:"right", sorter:"number"},  // works!
{title:"Alt [m]", field:"altitude", sortable:true,  responsive:0, align:"right", sorter:"number", mutateType:"data", mutator:ft2met}, // does not

```

**Comment by E3V3A** [comment]
Found solution while posting issue.

**Documentation BUG:**
`The mutator name require double quotes!`

**Comment by E3V3A** [comment]
Any idea what is more efficient to use?

**Comment by olifolkerd** [comment]
Hey @E3V3A 

It requires quotes when it is a built in formatted or mutator (or one that has been added as an extension, it requires the function to be passed in when it is a custom mutator/formatter that has not been built into Tabulator.

Your example seems to be a mix of the two approaches which is why it isnt working.

Cheers

Oli :)

**Comment by E3V3A** [comment]
@olifolkerd 
> Your example seems to be a mix of the two approaches which is why it isnt working.

Thanks for your reply. It works now, and I was never using both at once, as shown. I just posted them for illustration. So, yes, we need double quotes. Since, I am very new to these types of tools, it is unfortunate that such simple errors (as those in the documentation of those) is throwing me off.  Anyway, if you decide to update the doc's you can just close this issue.

**Comment by olifolkerd** [comment]
Hey @E3V3A 

If you have found an error in the documentation could you let me know where it is and i will be happy to fix it.

That sort of thing is not included in the documentation because it is a fundamental precept of javascript development, im afraid the Tabulator site cannot offer tutorials how to use the language properly as that would be too wide a scope to cover. 

also i would be appreciative if you would use slightly more pleasant phrasing in your posts to this board, a lot of the posts you have made today have been written in a demanding an accusatory way instead of just asking a simple question in a plain and friendly way,

This is a free open source project with a friendly and helpful community and you will get a much better response from people if you try and be respectful rather than derogatory.

Thousands of people use this library every day with out issue, and i understand in this case you have had trouble, but a bit of patience goes a long way.

Cheers

Oli :)

**Comment by E3V3A** [comment]
@olifolkerd  

Hi Oli,
I'm very sorry about all that. I certainly have no intention in being demanding or accusatory. Perhaps its only a misalignment of cultural perception. However, I only arrived to this great project site about a day ago. So by trying to get stuff working I just happened to stumble across an unusual amount of confusing and sometimes misleading info, which is certainly much better than most and none. That is of course from the point of view of someone (like me) who have never used these tools before. Searching through both the issues and the documentation, I have come across some inconsistencies and inaccuracies. I merely try to address these to you and your team for further improvement on an otherwise great project and very informative site. So my main intention was actually trying to do some good. 

Best Regards,
E:V:A

**Comment by olifolkerd** [comment]
@E3V3A 

Thanks for letting me know, it is great to have issues pointed out, its how we make things better,  but as i say there is no need for the sarcastic/condescending tone that has come with most of the posts. 

If there are particular passages in the documentation that are causing you problems if you can include a link to the page and a copy of the passage of text then i would be happy to take a look at it.

With regards to the mutator documentation, i will have a look at rewording it to make it a bit clearer. Once you have used Tabulator you will find that all of the functionality follows the same API pattern to make it easier to use.

Cheers

Oli

**Comment by E3V3A** [comment]
@olifolkerd  
> but as i say there is no need for the sarcastic/condescending tone that has come with most of the posts.

You keep saying I'm sarcastic, but I simply do not see that and do not recognize that description of myself. 
* *So I think you need to look up the definition of `sarcasm`.*  ⬅️  That is Condescension! 

But then again those labels usually goes both ways. Telling a stranger they are being condescending and sarcastic is a passive aggressive and hidden type of condescension itself. So let's just stop telling everyone what they and try to remain open for some good faith. People are different.

Again. Thanks a lot for your help, but it's very unlikely I will file any further issues here again, given the attitude I receive along with it, here.
