### ISSUE TITLE
tabulator("redraw", true) not working on div/container resize

### ISSUE THREAD

**Issue by vladyslav-shyrkov** [olifolkerd/tabulator#868]
Hi! 
I encountered a problem when when changing the size of the container (the left navigation menu becomes smaller, making the container with the table larger), the redraw function does not work. When you resize the browser window, everything works fine.

![screenshot_1](https://user-images.githubusercontent.com/36258590/35962301-91240a22-0cb9-11e8-8a19-cdee58519581.jpg)
![screenshot_2](https://user-images.githubusercontent.com/36258590/35962302-9140eb4c-0cb9-11e8-8577-265904370a9e.jpg)

i noticed, if i turn off in css .tabulator width 100%  i get this result

![screenshot_3](https://user-images.githubusercontent.com/36258590/35962983-faf9289a-0cbb-11e8-904d-bd001181aff9.jpg)

**Comment by olifolkerd** [comment]
Hey @vladyslav-shyrkov 

Could you post a copy of your table constructor so i can see how it has been configured?

Cheers

Oli :)

**Comment by vladyslav-shyrkov** [comment]
Hi, here is cfg file. Thank you! 
[exmpl_cfg.txt](https://github.com/olifolkerd/tabulator/files/1711303/exmpl_cfg.txt)

**Comment by olifolkerd** [comment]
Hey @vladyslav-shyrkov 

This is because you can only detect when the window resizes not when a DOM element is resized, which is what happens when you change the visibility of a side bar.

In the latest ES* spec, there is now a ResizeObserver that lets you monitor just that, and the 3.4 release of Tabulator (released tomorrow) will use that to update when the element is resized, the downside is that this is a very new feature and currently only available in the latest release of chrome, it will be a good few months before all the browsers support it.

In the mean time i would suggest that you call the ***redraw*** function on the table whenever you show/hide your sidebar:
```js
$("#example-table").tabulator("redraw");
```

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)
