### ISSUE TITLE
Table Tidy Up - Format Empty Rows, Header Sort Initial Direction 

### ISSUE THREAD

**Issue by xXmrotsXx** [olifolkerd/tabulator#873]
Hey Oli,

Three last questions to finalize my test site that I've been playing with to learn about Tabulator. I'm really loving it BTW, and your support is the best!

1. When filtering the table and the table height is then greater than the filtered data, is there an in-built option to continue the row "even/odd" shading for the entire table height just to "pretty things up"? I guess if I just populate the last few rows of the virtual DOM with "" then the usual formatting will do it... just seems a bad way to do it.

2. Bar editing tabulator.min.js, is there a way to change the way a headersort sorts (asc/desc) on the first click? Most of the time I want a desc sort so I'm always doubling up on the clicks. Will I need to write my own onclick function?

3. Is there a bug in layout modes relating to column widths? More likely my error, but I've tried:
```
layout:"fitData",
layout:"fitDataFill",
layoutColumnsOnNewData:true,
```
I believe it is related to columns having rows that are outside the virtual DOM but once they are filtered the columns are not resizing. Ideally they would not need to resize rather be the right size from the start.

Thanks again for the time you take on here. I'm sure my stupid questions must be boring you by now.  :-)

**Comment by olifolkerd** [comment]
Hey @xXmrotsXx 

Thanks for getting in touch, in answer to your questions:

- There is no inbuilt way to fill the remaining space, though you could easily write a function to put in the data loaded callback that checks if the number of rows and fill the table and adds new empty rows to fill the remaining space (i would be happy to put a demo together of this)
- The header sorts dont have this as an option, but i like the idea and will stick it on the roadmap to add a option for this. if you sort a column to desc in the initial sort then the first click will sort it asc
- The column width issue is because it is impossible to calculate the width of cells in rows that have not been rendered yet as they do not have any elements and only visible elements have dimensions, it is a downside of using a virtual DOM, in time when browsers have new fuctionality that is in the specs this wont be a problem, but it is a bit of a waiting game on that front.

Cheers

Oli :)

**Comment by xXmrotsXx** [comment]
A demo of your suggestion would be great if you don't mind. I've since got something working but not using that method - I'm always interested in another point of view if it's not too much trouble.

I'm glad I could contribute, albeit in a very small way, to your project with my suggestion re header sorting. In the mean time I could just tweak the tabulator file, although I will look into initially sorting all columns.

As I thought about the widths... Thanks for confirming. I can just hard code a size for those particular columns in this case as I know the contents sizes.

Thanks again.

**Comment by olifolkerd** [comment]
Hey @xXmrotsXx  

I have just pushed an update to the 3.5 branch. you will now be able to use the ***headerSortStartingDir*** column definition property to set the starting sort direction on an unsorted column when you first click it:

```js
{title:"Name", field:"name", sorter:"string", headerSortStartingDir:"desc"} //start sorting column in descending order when user clicks on header of unsorted column
```

Version 3.5 has not been release yet as i will be working on it for the next couple of weeks, but i have published the documentation on the website and will be updating it as i add the features to the 3.5 branch.

Documentation for the sorter functionality can be found [Here](http://tabulator.info/docs/3.5#sorting);

Cheers

Oli :)
