### ISSUE TITLE
Issue with pagination when formatter=textarea

### ISSUE THREAD

**Issue by geekbleek** [olifolkerd/tabulator#875]
Hello - first off, amazing project!  Thanks for sharing with the community!!

I found an issue with the pagination that is specific to when the formatter is set to textarea.  The docs indicate that when height is defined, and paginationSize is not, but pagination is set to local, the number of items shown per page will be automatically calculated.  I believe this is done by the standard row height before taking into account the textarea formatter.  When I use:

```
$("#example-table").tabulator({
    height:"300px",
    pagination:"local", //enable local pagination.
});
```

And a column setup like this:

```
{title:'Description (Click For More)', formatter: 'textarea', headerFilter:true, headerFilterPlaceholder:'Search by description...', field:'details', align: 'left', responsive:0, width:500, minWidth:250}
```

I end up having to scroll the table (which isn't apparent) to see the bottom entries.  If I remove the formatter on the column, then pagination behaves normally.

It would be nice to be able to set the height to 100% and let pagination be automatic, but I found even without the formatter set to textarea, the pagination icons end up being pushed below the height of the surrounding div, or having the last row hang off the bottom requiring a small amount of scrolling.

Please let me know if I can provide further info or if you know of any good workarounds.  For now I just put a lightbox popup to show the full text for each cell when clicked, rather than using textarea as a formatting, knowing tables aren't ideal for larger bodies of text anyway, but thats my current requirement.

Thanks!!!

**Comment by olifolkerd** [comment]
Hey @geekbleek 

Thanks for getting in touch, and thanks for your kind words, it is always great to hear that Tabulator is appreciated :)

The text area formatter provides a unique challenge for pagination, because it varies in height between rows it is impossible to tabulator to know ahead of time the height of each row in the table (rows have no height till they are rendered), it therefore makes an educated guess from the first row of the table and calculates things from that. if the rows then vary in height it will cause a scroll bar to show, but that should only affect the rows in the table, if it is pushing the buttons off the bottom that sounds like a bug.

As is standard with pagination, it tries to show the same number of rows on each page, which can lead to this issue if the heights vary. In version 3.5 i will be taking a look at the pagination system so will see if i can add a render mode where the page size is varied to fit rows, although if text areas are in use this may result in a bit of whitespace in the table.

I hope that answers your question.

Cheers

Oli :)
