### ISSUE TITLE
Nice project

### ISSUE THREAD

**Issue by git265** [olifolkerd/tabulator#881]
hi ,

I am impressed with your project and thanks for sharing to the community . I started liking it for its simplicity and easily extendable.  I think you should probably have donate button on your website.

Thanks.

**Comment by olifolkerd** [comment]
Hey @git265 

Thanks for your kind words, it is always great to hear that Tabulator is appreciated :D 

I am working on some updates to the website in the next couple of months and will look at adding a donate button to the community page in case anyone want to help support the project with a donation.

Cheers

Oli :)

**Comment by roypardi** [comment]
I concur: awesome project and I'd like to thank @olifolkerd for staying engaged and being so responsive to questions and issues.

**Comment by olifolkerd** [comment]
Hey @git265 @roypardi @lgraziani2712 

Thanks for all your kind words, it really is awesome to hear that you are enjoying using the library.

A few people have kindly offered to donate to help support the cost of the website etc.

I have now setup a Patreon page for those generous souls if you want to make a donation. More information can be found on the [Community Page](http://www.tabulator.info/community)

Cheers

Oli :)

**Comment by mestaritonttu** [comment]
Have you considered an option for one-time donations? I was trying to find your email to propose it directly (bank transfer would have been one suggestion).

Btw., I think it would be fine to display a link to your Patreon page on the front page of Tabulator. Now it is sort of buried in the Community page.

**Comment by olifolkerd** [comment]
Hey @mestaritonttu 

Thanks for your kind words,

If you want to make a one time donation simply signup with patreon when the first payment comes out (which usually takes an hour or so) cancel the subscription.

Im looking into onetime payment options and will probably go with paypal.me link because leaving bank account details online is just asking for trouble.

There is a link to patreon on all the documentation pages at the bottom of the sidebar, but i will consider adding one to the home page too.

Cheers

Oli :)

**Comment by mestaritonttu** [comment]
I see you added PayPal now, cool :) I recently sent Tabulator to this list: https://github.com/uraimo/awesome-software-patreons/

**Comment by olifolkerd** [comment]
Hey @mestaritonttu  Thankyou! that is  very kind of you :)
