### ISSUE TITLE
height impacting jquery css updates

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#890]
So this may be a bit unconventional, but wanted to ask.

I have a summary table csv file that is is read in via papaparse, and is rendered in tabulator.  

I have rows with the word "Subtotal" in a column. Most of my CSV files have about 35 rows  and I use a tabulator height of 600.

```
	$("#example-table").tabulator({
		height:600, 
```
I wanted to highlight the row that has the word "Subtotal", so after tabulator renders the table, I cheat and use jquery...
```
$('.tabulator-row:contains("Subtotal")').css({
'background-color' : 'darkgray',
 'font-size' : '16px',
'font-weight' : 'bold'
});
```
The jquery update works great!

However this one particular table has 97 rows, and the jquery doesn't update everything at a height of 600, but it works great with a height of 2000...
```
	$("#example-table").tabulator({
		height:2000,
```
It seems that the entire table has to be seen in order for the jquery to update the CSS info.

Is this expected behavior? 
Is there a horizontal or row class I could apply in tablulator or maybe I need to do a custom formatter function that looks for Subtotal in the row?  

I'll work on a generic example over the weekend if needed, but wanted to query a question first to see if there's something I'm missing or could handle better.

Thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc 

You are running into trouble because Tabulator uses a virtual DOM which means that row elements are created and destroyed as you scroll the table (only the visible rows actually exist, they are destroyed when the scroll out of view), that means that you cant reliably access the DOM elements from outside of Tabulator as they will likely be destroyed shortly afterwards, or may not have been created yet.

The virtual DOM means tabulator can handle 100,000's of rows without issue because it only uses the resources needed to display a few of them at a time.

To achieve the effect you are after i would recommend using the ***rowFormatter*** function to apply a class to the rows you want to style and then using CSS to style that class:

***JS***
```js
$("#example-table").tabulato({
	columns:[...],
	rowFormatter:function(row, data){
		// row - row component for the row
		// data - data object for row

		//check on data object for the "Subtitle" word

		//add style
		row.getElement().addClass("subtitle");
	}
})
```

***CSS***
```css
.subtitle{
    background-color : darkgray,
    font-size : 16px,
    font-weight : bold
}
```

Let me know if that helps.

Cheers

Oli :)

**Comment by YendorMc** [comment]
This worked brilliantly, but then another issue came up, so will post another 'issue' .thank you!
