### ISSUE TITLE
Cell.SetValue fails 

### ISSUE THREAD

**Issue by GavinOG** [olifolkerd/tabulator#896]
I hook the rowUpdated function to recalcuate values in a table row when changes are made to that row. 

(e.g. one of my columns is a hidden field used to store a Set(). Another column is a visible field that displays the count of either the total set, or counts of types of entities in the set. I want to display the size of the Set() as it's modified, so when the row is updated, I change the values of the counts).  

For each cell that I wanted to update, I would use row.getCell() to get the cell, and then use cell.SetValue() to update the value. I did it this way so as to avoid using row.update() from within the rowUpdated function, and avoid recursive disaster. 

But it seems that cells are not created for rows that have not yet been displayed after the most recent updated, so the call to row.getCell() fails. Any suggestions for an alternative?

**Comment by olifolkerd** [comment]
Hey @GavinOG 

You are correct, because of the virtual DOM cells are only created once the row has been rendered for the first time.

There are two approaches you can take.

### Formatters
If this is just a display update and you want to keep the underlying data untouched then you could create a custom formatter for that cell, which will get called when the row is rendered or updated. a formatter function is passed the relevant cell component and you can use the `cell.getData()` function to retrieve the data for the whole row.

More information on this can be found in the [Formatter Documentation](http://tabulator.info/docs/3.4#formatting)

### Mutators
The other option which will affect the data, and is probably the right option for you is a mutator. mutators are used to alter data as it enters the table, either through the ***setData*** command or through user interaction of the table.

More information can be found in the [Mutator Documentation](http://tabulator.info/docs/3.4#get-set)

I would you have a read of the documentation for both options and pick the one that best suits your needs. if you need any pointers once you have chosen a route, give me a shout.

Cheers

Oli :)
