### ISSUE TITLE
renderComplete Question

### ISSUE THREAD

**Issue by jwb12345** [olifolkerd/tabulator#900]
Hi,

Thanks so much for sharing tabulator.  It is fantastic.

I am having an issue with being able to see all of the rows of the table in my renderComplete callback function.  Currently, the table has about 125 rows.  I am setting the first column to be a link in a formatter function.  I am trying to bind all of the links, but for some reason it seems to only bind the links for first 46 rows.  Is there a better way for me to be doing this?  Do you have any thoughts on how I can get all of the links to be seen?  Here is a snippet of my code:

   var cols = [];
   cols[cols.length] =
          {title:"Name", headerFilter: true, width:nameWidth, field:"name",
                                  formatter:function(cell, formatterParams) {
              var theID = cell.getData().id;
              entityDataArr[theID] = cell.getData();
              return "<a href=# id=row_" + theID + ">" + cell.getValue() + "</a>";
            },
          };
.. Add several more columns...
 $("#mainDiv").tabulator({
        layout:"fitColumns",
        height:"500px",
        columns: cols,
        renderComplete: function() {
          $("a[id*=row_]").bind('click', function() {
              Do some stuff (works for first 46 rows)
          });
        }
      });
      $("#mainDiv").tabulator("setHeight",$(window).height() - 250);
      $("#mainDiv").tabulator("setData", "../entity?entityTypeID=" + entityTypeID, {}, "POST");

I replaced the bind call with the following and can see that it is only processing 46 rows and not the full 125:

 $("a[id*=row_]").each(function() {
       var splitID = $(this).attr("id").split("_");
       var entityData = entityDataArr[splitID[1]];
       alert(entityData.name);
   });

**Comment by olifolkerd** [comment]
Hey @jwb12345 

Thanks for your kind words, it is great to hear you are enjoying using Tabulator

The issue you are having is because tabulator uses a virtual DOM, which means that none of the DOM elements actually exists when they are not visible, they are created and destroyed as you scroll through the table. This allows tabulator to handle 100,000's of rows because it is only trying to render a few at a time.

You should never try to bind directly to any elements in the table as most of them wont exist and those that do will disappear as soon at the user scrolls.

There are a number of ways to safely bind to click events.

**cellClick Callback**
you can use the ***cellClick*** callback in the column definition for that column, which will be passed a [Cell Component](http://tabulator.info/docs/3.4#component-cell) that you can then use in your actions 
```js
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", cellClick:function(e, cell){
                alert("The cell has a value of:" + cell.getValue()); //display the cells value
        } }
    ]
});
```

More information on the wide range of callbacks available can be found in the [Callbacks Documentation](http://tabulator.info/docs/3.4#callbacks)

**Custom Formatter**
If you only want to take action when the link is clicked rather than anywhere on the cell, you could create a custom formatter to do this:
```js
//create custom formatter
var linkFormatter = function(cell, formatterParams){
    var url = cell.getValue();
    var link = $("<a href='" + url  + "'>Click Me</a>");

    link.click(function(e){
        //do something when the link is clicked
    });

    return link;
}

//assign formatter to column
$("#example-table").tabulator({
    columns:[
        {title:"Name", field:"name", formatter:linkFormatter }
    ]
});
}
```

More information on formatters can be found in the [Formatting Documentation](http://tabulator.info/docs/3.4#formatting)

Let me know if that helps

Cheers

Oli :)

**Comment by jwb12345** [comment]
Awesome.  Thanks for the explanation.  Yes, everything is working great.  Thanks again.
