### ISSUE TITLE
count of unique column values

### ISSUE THREAD

**Issue by NidhiChandak** [olifolkerd/tabulator#902]
When I hover on a particular cell, i should be able to see the count of the number of entries with the same cell value in the particular column.
How should I do it?

**Comment by olifolkerd** [comment]
Hey @NidhiChandak 

If the data in your table doesn't change then you can pass a function to the ***tooltips*** property:

```js
$("#example-table").tabulator({
columns:[...],
    tooltips:function(cell){
        //cell - cell component

        var data = $("#example-table").tabulator("getData");
       	var field = cell.getColumn().getField();
       	var value = cell.getValue();
       	var count = 0;

       	data.forEach(function(item){
       		if(item[field] === value){
       			count ++;
       		}
       	})

        return count;
    },
});
```

The above example would work, but it is a bit simple and isnt very efficient because it runs that calculation for every single cell.


Instead i would recommend that you run the calculations on the data when you set it  and store that data in an array then use the ***tooltips*** function to retrieve the value from the array.

Cheers

Oli :)

**Comment by NidhiChandak** [comment]
Hey Oli,
It Worked. Thank You.
Is there any feature that on 'hovering' on the cell, i can display a popup or a message kind of thing.

**Comment by NidhiChandak** [comment]
Hey Oli,
Thank You so much. It Works.
