### ISSUE TITLE
Maintaining sort order of groups

### ISSUE THREAD

**Issue by seb303** [olifolkerd/tabulator#906]
Hi,

I'm loving using this great library, but am struggling with one thing: I have a table where I am grouping the data using groupBy, and I want the sort order of the groups to stay constant when sorting by other columns.

The initial sort is working fine - using initialSort and specifying both the other sort column and the group column.  However, as soon as I click on another column to sort, the order of the groups becomes randomised.

Am I missing a way to do this?  I've tried using the dataSorting callback to amend the sort parameters, but this ends up infinitely recursive.

Thanks,
Seb

**Comment by olifolkerd** [comment]
Hey Seb,

The reason this happens is because the data is sorted and then the groups are generated from the sorted data in the order it is in.

You can get round this by adding a function to the ***headerClick*** callback to trigger a second level of sorting when the header is clicked.

Adding this functionality to the table is covered in a fairly lengthy and detailed discussion on issue #483

Let me know if that works for you.

Cheers

Oli :)
