### ISSUE TITLE
Feature request: sort by result of formatter

### ISSUE THREAD

**Issue by seb303** [olifolkerd/tabulator#907]
It would be nice to have a sort option that sorted data by the result of the formatter used (i.e. by the displayed string).  In my current usage, this would eliminate the need for a lot of custom sort functions.

Still loving using the tabulator though :)

**Comment by olifolkerd** [comment]
Hey @seb303,

Formatters are purely for visual layout on the DOM, the data they generate is done so as the cell is being rendered. sorting happens on the raw data much earlier in the table generation process.

If you want to affect the underlying data, which is used in the sort, the you should look at using a [Mutator](http://tabulator.info/docs/3.4#get-set) instead of a formatter.

I hope that helps.

Cheers

Oli :)
