### ISSUE TITLE
Not able to setValue on the next page

### ISSUE THREAD

**Issue by ravieses** [olifolkerd/tabulator#912]
Hi Oli,
i have enabled the pagination, but when i am trying to set values on the next page using cell component it gives some error.
Here is my code:

rows[21].getCell("number").setValue(tempStepNo++);

here my current page size is 10 .. and i am presently on the first page so when i am trying to set values to the cell 'number ' of row number 21, it gives exception. It is working fine when i am setting the values on the active page.

following exception occurs:

**Cannot read property 'getComponent' of undefined**

please help me out of the issue.

**Comment by olifolkerd** [comment]
Hey @ravieses 

That is happening because you are trying to update the data directly on the cell component, which hasnt been created yet because the row has not yet been rendered.

In this case what you want to do is use the ***update*** function on the row component:

```js
rows[21].update({number:rempStepNo++});
```

Which will update that value on the row data object, which will trigger an update on the cell if it is visible.


Let me know if that helps

Cheers

Oli :)
