### ISSUE TITLE
Removing an "in" filter?

### ISSUE THREAD

**Issue by YendorMc** [olifolkerd/tabulator#928]
Hi Oli,

I'm able to add this filter using the new "in" keyword:
$("#example-table").tabulator("setFilter","values", "in", ["Subtotal",""]);

But I cannot remove it using the removeFilter context:
$("#example-table").tabulator("removeFilter","values", "in", ["Subtotal",""]);

Would it be because of the null?

And if I were to get fancy on the filtering using "OR" between two columns, I would need to use a custom filter, right?

Thanks!

**Comment by olifolkerd** [comment]
Hey @YendorMc,

The reason it is failing is because the array being passed into both functions is a literal and so has a different memory pointer for each one. if you want to remove this filter you will need to pass it in as a variable:

```js
var match = ["Subtotal",""];
$("#example-table").tabulator("setFilter","values", "in", match);
$("#example-table").tabulator("removeFilter","values", "in", match);
```

If you are only using one filter then i would recommend using the ***clearFilter*** function instead of ***removeFilter***

With regards to "OR" functionality, you would need to use a custom filter function at the moment, but it is on the roadmap to be added in the next release.

Cheers

Oli :)
