### ISSUE TITLE
Save CSV without dialogue

### ISSUE THREAD

**Issue by xXmrotsXx** [olifolkerd/tabulator#950]
Hi @olifolkerd,

Sorry if I've missed this here or in the documentation, but I was wondering if it was possible to export/save the table data to a CSV without the prompt and GUI - just force it to save? 

Thanks.

**Comment by olifolkerd** [comment]
Hey @xXmrotsXx 

There is no way to do this on a browser, it is an inbuilt safety mechanism to prevent websites maliciously saving data back to the users computer.

If you just want access to the raw blob data to the do something else with instead of triggering the save then this functionality will be coming in version 3.5 next month.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @xXmrotsXx 

Version 3.5 has now been released!
