### ISSUE TITLE
Using browser print function,and print tabulator table

### ISSUE THREAD

**Issue by ZinThiThiTun** [olifolkerd/tabulator#951]
Hi,Oli
I have to show data using tabulator and then print (using browser print function).
But,when i see with print preview ,tabulator table data can't show.
Title is showed,and then only blank space is show.
I think its size is changed, when adjust A4 size.
Pls tell me,there is a way to adjust.

Thank You.

**Comment by olifolkerd** [comment]
Hey @ZinThiThiTun 

Could you post a couple of screen prints of what it looks like before and during the print?

Cheers

Oli :)

**Comment by fbenedetti06** [comment]
Hi Oli
Congratulation for this amazing library! I can't stop using it!

Same issue here... And I really try all possible to avoid this problem.

Browser:
![image](https://user-images.githubusercontent.com/49648330/105019014-eb308180-5a45-11eb-9c67-04b0b31d3b9c.png)

Printer:
![image](https://user-images.githubusercontent.com/49648330/105018937-d94ede80-5a45-11eb-8395-5ccf806bbb43.png)

As you can see center table do not show data!

Tables have exactly same setup.

Data are present because they are showed if I use printAsHtml:true

Thanks for your support.
