### ISSUE TITLE
Run Actions Before Pagination

### ISSUE THREAD

**Issue by stack-its** [olifolkerd/tabulator#972]
Hi Oli,

I'm running v3.2 of Tabulator & I pull the display:none tabulator-cell & related tabulator-col into a display div that gets revealed.  It works great, but when I leave the display div open & use the pagination buttons, the tabulator-col (headers) are being lost & don't exist on the new page.

Is there a way I can run some cleanup stuff on clicking the tabulator-page buttons, but before tabulator takes over & brings up the next page?
I tried an on-click and even tableBuilding function, but couldn't get the dom cleaned up before tabulator does it's thing.

Thanks for the guidance,  Bill

**Comment by olifolkerd** [comment]
Hey Bill,

If you are creating your table on a hidden div you will need to call the ***redraw*** function once the table is visible to ensure that it renders correctly.

This is because hidden elements have no height/width until they are first visible so Tabulator cannot correctly size the column and cell elements.

Cheers

Oli

**Comment by stack-its** [comment]
I'm not creating the table on a hidden div.  I need a way to cleanup before tabulator does the pagination.

**Comment by olifolkerd** [comment]
Hey,

Im afraid i don't follow you, what do you mean you are pulling the tabulator-cell and tabulator-col into another div.

Could you explain in more detail what your custom modifications are and what you are trying to achieve?

Cheers

Oli :)

**Comment by stack-its** [comment]
Hi,

I have a display div that shows tabulator's hidden fields.  When you click the far left icon cell, it causes that div to slideDown.  Just before it's revealed, I literally move the hidden .tabulator-cell & the related (title) .tabulator-col into the display div.

If you leave the display div open & click the pagination buttons, then these moved cells are lost.  And when you reveal a record on the next page, the headers will be missing !

SO, **I need to find a way to prevent the default pagination action from occurring until I have had a chance to move the cells back** to where tabulator expects them to be.

Try it on this test page:  http://partiproductions.com/design/easydb_test/textgrid/

I tried the following (simplified sudo code for readability), w/o success & not even getting logs for header & cell:

    `$('#wrapperdiv button.tabulator-page').on('click', function(e) {
        var rrvlck = $('#wrapperdiv').attr('data-rnum');  // row id of revealed record
        if (rrvlck != '#') {
            $('#wrapperdiv #selectshow .show').each(function() {
                var mythis = $(this);
                var chdr = mythis.find('.tabulator-col');
                console.log('Header: ' , chdr);
                var ccell = mythis.find('.tabulator-cell');
                console.log('Cell: ' , ccell);
                var crow = $('#wrapperdiv .tabulator-selected');  // current row
                $('#wrapperdiv .tabulator-headers').append(chdr);
                $(crow).append(ccell);
                mythis.remove();
            });
           $('#wrapperdiv #selectshow').remove();
           $('#tableid').tabulator("redraw");
           //$('#wrapperdiv button.tabulator-page').delay(400).trigger('click');
           e.preventDefault();
        }  
     });`

**Comment by olifolkerd** [comment]
Hey @stack-its 

I take it you mean from you example that you are trying to show the cells hidden by the responsive layout in the revealed div.

You cant bind to elements inside of the table, because of the way tabulator works it will regenerate DOM elements and event bindings from outside tabulator will stop working.

Im afraid at the moment there is no "pre-pageing" callback, but as you are making an ajax request you could use the ***ajaxRequesting*** callback which might do what you are after.

Im afraid im still not sure what you are trying to do with your code there. you should never try and manipulate elements inside the table from outside at it can have unexpected effects. you should instead look at using the ***rowFormatter*** function to do this for you.

Cheers

Oli :)

**Comment by stack-its** [comment]
Thanks @olifolkerd 
I thought about what I was doing & I got it working now w/o trying to mess w/ Tabulator dom stuff.
Appreciate the feedback.

Bill
