### ISSUE TITLE
hide columns group

### ISSUE THREAD

**Issue by iceman60** [olifolkerd/tabulator#980]
# Column Grouping did not support hiding like this:

$("#example-table-column-grouping").tabulator({
    columnVertAlign:"bottom", 
    columns:[
        {title:"Name", field:"name", width:160},
        {
            title:"Work Info", field:"work"
            columns:[
                {title:"Progress", field:"progress", align:"right", sorter:"number", width:100},
                {title:"Rating", field:"rating", align:"center", width:80},
                {title:"Driver", field:"car", align:"center", width:80},
            ],
        },
        {
            title:"Personal Info",
            columns:[
                {title:"Gender", field:"gender", width:90},
                {title:"Favourite Color", field:"col", width:140},
                {title:"Date Of Birth", field:"dob", align:"center", sorter:"date", width:130},
            ],
        },
    ],
});

### $("#example-table-column-grouping").tabulator("hideColumn","work")

**Comment by olifolkerd** [comment]
Hey @iceman60 

Im afraid that is not a valid column grouping, column groups cannot be assigned fields (as they do not process data, they are just simple wrappers for columns) which is why that isn't working.

You would need to hide each of the columns under the group for the group to be hidden.

Cheers

Oli :)
