### ISSUE TITLE
pagination and vertical scrollbar

### ISSUE THREAD

**Issue by pointware** [olifolkerd/tabulator#984]
hi, I think tabulator is well-made product.

but, I wonder body scrolling when using pagination

why can't I use vertical scroll bar when using pagination?

I need that feature, so update setRenderMode of RowManager.
(even if use pagination, render mode is virtual mode)

Does this change affect other function?

**Comment by olifolkerd** [comment]
Hey Pointware,

This is done so that the tabulator height conforms to the height of the rows, which most people requiring pagination opt for.

Although I can see where your coming from and in the next release i will make it so the vitrual DOM is still enabled if height is set on the table,  even in pagination mode

Thanks for the feedback

Cheers

Oli :)
