### ISSUE TITLE
jQuery, jQuery UI independence

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#986]
Hi Oli
do You have plans with regard to this topic, and if yes, what are they. We in our group of developers have started to be as jQuery independent as possible. And even if we often use Bootstrap 4, we use only its styling and replace the modal with a jQuery free alternative.

Also on Your roadmap there is an item "jQuery UI CSS Theme". Does this have a relation to the topic raised here by me?

(To be clear: the issue is NOT stop using tabulator because of that)

Pleas let me know Your take on that subject.
Cheers, Michael

**Comment by olifolkerd** [comment]
Hey @michaelongithub 

I couldn't agree with you more, i am also moving over to a pure JavaScript development methodology.  With Tabulators expanded functionality jQuery is simply not responsive enough to cope.

I have in-fact been slowly stripping out the jQuery since version 3. Version 3 was actually created to act as a stepping stone to a jQuery free Tabulator, removing almost all jQuery UI dependencies (currently only the widget part of jQuery UI is used) with the aim of being completely free of any jQuery by version 4, which is on the roadmap for around July this year,

Though just for any other developers that do use jQuery, i will be including a jQuery wrapper for Tabulator to allow the continued use of it as a jQuery plugin if needed.

As for the theme, im not sure where exactly that one was requested, but it fits along with the bootstrap and semantic-ui themes so it seemed like a logical addition.

Cheers

Oli :)

**Comment by michaelongithub** [comment]
Great to hear and thanks for replying so quickly
