### ISSUE TITLE
Mutator not working with topCalc and grouping.

### ISSUE THREAD

**Issue by MusinAmir** [olifolkerd/tabulator#991]
Last column compute sum of columns 1-12. After cell edit topCalc updated, but field below not.
![image](https://user-images.githubusercontent.com/14330661/37912196-5d208700-312b-11e8-884f-209e52118615.png)

Column:
```
{title: 'Всего', field:'total', width:100, headerSort:false, topCalc:"sum", mutateType:"all", mutator: totalForRow}
```
Mutator
```
    function totalForRow(value, data, type, mutatorParams, cell){
        var total = 0;
        var i;
        for (i = 1; i < 13; i++) { 
            total += data[i];
        }
        return total;
    };
```

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

A mutator will only be triggered data is first loaded into a row or when the cell in the column it is attached to is updated, therefore if you make a change to any of the other columns in that row it will not trigger the mutator, which is why the cell content is not being updated.

Column calculations work differently and are all updated if a row is updated.

A way round this would be to use the ***cellEdited*** callback to track when any changes are made to any cell on a row and then force an update of the totals cell:

```js
$("#example-table").tabulator({
    columns:[...], //column definitions
    cellEdited:function(cell){
        //cell - cell component
        cell.getRow().update({total:false}); //force total column mutator to run if any cell in the row is edited
    },
});
```

Let me know if that helps,

Cheers

Oli :)

**Comment by MusinAmir** [comment]
Hello @olifolkerd
Thank you for your response. Unfortunately this doesn't force mutator to run, it's just update total with empty string. 
I did this:
```
var row = cell.getRow();
row.update({total: totalForRow(row.getData())});
```

**Comment by philipsouthwell** [comment]
Hi Oli,
Tabulator is amazing and I've wanted to tell you since I started using it about 6 months ago. Thanks so much for your hard work - it's certainly much appreciated.

I have a similar issue to that in this thread. On cellEdited this won't work:

    row.update({total:false});

So I try to use MusinAmir's solution:

    row.update({total: totalForRow(row.getData())});

This updates the row data for the mutator. Using console.log() I've verified that the new data is now passed to the mutator to that's all fine. However in my case there are mutatorParams and his solution doesn't reload these parameters but only the table data. I'm hoping you'll have some pointers for a way forward.

**Comment by olifolkerd** [comment]
Hey @philipsouthwell 

Thanks for your kind words, it is always great to hear that Tabulator is appreciated :)

Would you mind rasing this as a new issue as thing have moved on quite a bit since this post and the suggested solutions would no longer work as the mutator column definition properties have changed since this was posted

When you do could you post a copy of your constructor object so we can tell what your table setup is like and let us know what version of Tabulator you are using?

Cheers

Oli :)

**Comment by philipsouthwell** [comment]
I think this thread is still valid. In MusinAmir's last comment he had to force the current data of the table through to the mutator upon an edit in a way which is not currently possible with the new code.

My problem is similar. The row data is being passed to the mutator function correctly upon setData. The row data is not being passed to the same mutator function correctly when the cell is edited.

**Comment by olifolkerd** [comment]
Hey @philipsouthwell 

There are two main reason that i do not want to continue on this thread:

The code that is references has been deprecated for about 5 months, the mutatorType property no longer exists and i do not want to confuse users with threads that span different versions of code.

The second reason is that as of version 4 i have asked users to use Stack Overflow for questions and only use Git for bug and issue tracking, so it is important that more questions are raised on their to help users out.

We seem to have a meaning full dialog going on stack overflow so i would ask that it continue there.

Cheers

Oli :)

**Comment by philipsouthwell** [comment]
No worries at all - I'm all for getting tabulator more into the public sphere. It's a great app!
