### ISSUE TITLE
Row height with several custom formatted elements

### ISSUE THREAD

**Issue by iagoswi** [olifolkerd/tabulator#996]
Hi,

This is probably a question, not a bug...

Thanks to this great little plug-in, I have built a table for my hiking webpage containing links, images and texts. The images are added using custom formatters, e.g. if a cell contains the value -4, then the formatter returns the image tag using concatenation for the filename.

Here is the result: https://www.noth.ch/en/randos/liste-des-randos.html

My only problem is that when the page loads, the line height does not fit the image height:
![1 - after page loaded](https://user-images.githubusercontent.com/29518242/38007368-6a44a596-3249-11e8-8027-a9b96f25a790.jpg)

Only after a click on *any* column header, the line height adapts and becomes correct:
![2 - after click on any header](https://user-images.githubusercontent.com/29518242/38007369-6a662676-3249-11e8-9c5d-61f783f00624.jpg)

I have tried many things to make it work better, e.g. adding "variableHeight:true" with no succes. Can someone give me a hint. The JS file is below:
[liste-des-randos.js.pdf](https://github.com/olifolkerd/tabulator/files/1854495/liste-des-randos.js.pdf)

**Comment by olifolkerd** [comment]
Hey @iagoswi 

Thanks for getting in touch.

The reason this is happening is because it can take a while for the image to load, and Tabulator has already set the row height before the image has loaded.

But you are in luck, the inbuilt image formatter has a way round this, so you can incorporate it into your formatter:
```js
var imageFormatter = function(cell, formatterParams){
	var value = this.sanitizeHTML(cell.getValue());

	var el = $("<img src='" + value + "'/>");

	el.on("load", function(){
		cell.getRow().normalizeHeight();
	});

	return el;
}
```

As you can see in the code above, the image formatter binds to the ***load*** event on the image, when the image has loaded it triggers the rows ***normalizeHeight*** function, which adjusts the rows height to fit the image.

Let me know if that helps.

Cheers

Oli :)

**Comment by iagoswi** [comment]
It did help. Thanks a lot!

Philippe
